### ISSUE TITLE
Implement remaining syscalls

### ISSUE THREAD

**Issue by joneschrisg** [mozilla/rr#1053]
We're probably at about the point where it makes more sense to audit and implement the remaining linux x86 syscalls instead of waiting for user programs to hit them in the field.  Of course, some syscalls like ptrace will remaining NYI.

**Comment by garrison** [comment]
I don't believe ``shmget`` is implemented by rr, and it is also missing from the above list of unsupported syscalls compiled by @cgjones.  I'm guessing there are a few others that might be missing as well.  (I noticed ``shmget`` is missing while attempting to use rr with julialang.  When I disabled OpenBLAS threading, julialang instead failed when calling ``mincore``.)

I think it would be incredibly useful if there existed a python script that could import ``syscalls.py`` and take output from an `strace` run and list all syscalls made that are currently unsupported by `rr`.  This seems relatively easy to implement (assuming it does not already exist), and could help get a handle on what syscalls are necessary for supporting various programs/environments.

**Comment by rocallahan** [comment]
> I don't believe shmget is implemented by rr, and it is also missing from the above list of unsupported syscalls compiled by @cgjones.

Right. `shmget` and a few other syscalls exist on x86-64 but not x86 (where they're subfunctions of the `ipc` syscall), so they never got added to `syscalls.py`. I'll push a commit to fix that.

`shmget` is a little bit tricky to support since we need to avoid rr tracees sharing memory with the outside world, and we also need to identify when tracees are sharing memory so we can set everything up correctly during replay (and during checkpointing). But it's definitely doable.

`mincore` would be trivial to support.

> I think it would be incredibly useful if there existed a python script that could import syscalls.py and take output from an strace run and list all syscalls made that are currently unsupported by rr.

That's a good idea. I'll give it a go.

**Comment by rocallahan** [comment]
> I'll push a commit to fix that.
83f7b216bfe19ed14cd0180f336c9a8063355963

**Comment by rocallahan** [comment]
Added `mincore` support in 8404fdb98558e02257209b52d1e0f42a8a8abb74.

**Comment by rocallahan** [comment]
I've pushed support for SysV shmem in a461eaec24f4dca1cd4819ec37640a0d88c29396.

**Comment by rocallahan** [comment]
At this point I think we should at least add support for all syscalls that are obviously 'trivial", i.e. only require switching from `UnsupportedSyscall` to `EmulatedSyscall` in `syscalls.py` because they have no relevant side-effects (including memory writes).

**Comment by ordian** [comment]
@rocallahan, Are you going to support mount/umount syscalls in the near future? I'm highly interested in using rr in a project with this syscalls.

` ->  Assertion 't->regs().syscall_result_signed() == -syscall_state.expect_errno' failed to hold. Expected ENOSYS for 'mount' but got result 0; execution of syscall unsupported by rr`

**Comment by rocallahan** [comment]
Those are trivial to support; they have no memory side-effects You could probably add them yourself :-).

The main difficulty would be adding a test. Probably should add something to unshare.c to do mount/unmount in a user/fs namespace so the test works when not run as root.

**Comment by rocallahan** [comment]
OK, I added support for mount: https://github.com/mozilla/rr/commit/408b516935e6bedd5f7f95d9a72097cb3d4dd73e

**Comment by ordian** [comment]
Thanks :-)

**Comment by rocallahan** [comment]
This issue isn't very useful. We aren't going to systematically go through remaining unsupported syscalls, we're just going to keep doing what we're doing --- adding support new syscalls as needed. So I'm closing this.
