### ISSUE TITLE
WINE failing near startup

### ISSUE THREAD

**Issue by cgjones** [mozilla/rr#1078]
#158. It's trying to read the ELF header of /usr/bin/wine, but for some reason is attempting to read into an invalid pointer.  It's not clear whether this is an rr bug.

**Comment by cgjones** [comment]
Would be interesting to re-check this and see how broken rr is or isn't with WINE.

**Comment by luser** [comment]
Seems to still be busted:
```
luser@eye7:/build/rr/rr$ ../obj/bin/rr record wine /build/test.exe
rr: Saving the execution of `wine' to trace directory `/home/luser/.rr/wine-0'.
/usr/bin/wine: failed to read ELF header

luser@eye7:/build/rr/rr$ file /usr/bin/wine
/usr/bin/wine: ELF 32-bit LSB  executable, Intel 80386, version 1 (SYSV), dynamically linked (uses shared libs), for GNU/Linux 2.6.24, BuildID[sha1]=30d6a41db3c4cf4bbe45c809ba355fc10d20499f, stripped
```

**Comment by luser** [comment]
That error is from here:
https://github.com/wine-mirror/wine/blob/wine-1.6.2/loader/preloader.c#L695

Wine apparently has its own syscall wrappers, I assume something in there is going wrong:
https://github.com/wine-mirror/wine/blob/wine-1.6.2/loader/preloader.c#L269

**Comment by luser** [comment]
For reference, I tested with this incredibly minimal Windows exe that I had built for another purpose:
http://people.mozilla.com/~tmielczarek/test.exe.gz

It doesn't link to any external libraries.

**Comment by rocallahan** [comment]
> Wine apparently has its own syscall wrappers, I assume something in there is going wrong:
https://github.com/wine-mirror/wine/blob/wine-1.6.2/loader/preloader.c#L269

Those wrappers alone shouldn't cause problems for rr. Something else is going on.

Ted, do you need rr for WINE for some reason?

**Comment by rocallahan** [comment]
We're dying because WINE's `read` call is recorded as failing with `EFAULT` for no apparent reason. rr would have redirected the `read` to a scratch buffer, so I guess that got screwed up somehow.

I'm not inclined to dig further myself until/unless Mozilla needs WINE support ... though I'd love someone else to pick this up as a project! :-)

**Comment by luser** [comment]
Nope, I just happened to have installed it for something else recently and saw this while browsing through the issue list.

**Comment by luser** [comment]
I don't know if Wine support would be useful for Mozilla, although it's probably easier than native Win32 RR support.

**Comment by rocallahan** [comment]
Yeah, it's vastly vastly easier than native Win32 rr support (which is probably orders of magnitude more effort than all the work we've put into rr to date).

The question is whether it would be useful...

**Comment by jrmuizel** [comment]
The recording seems to work at least a little bit. However, the replay doesn't seem to include the actual wine program being run. Instead it just records the wine loader bringing things up.

**Comment by fracting** [comment]
@jrmuizel 

What did you get if you run `rr ps` to get the process list, and then select the specific wine process to replay?

I remember RR works for me few months ago, but it seems I did some hack on Wine loader, but I heard somebody else say RR should work with Wine without hack, I can check again later today.

**Comment by jrmuizel** [comment]
2061	--	wine ./test.exe.so
2063	2061	/usr/bin/wineserver
2064	2063	(forked without exec)
2065	2061	(forked without exec)
2066	2065	/usr/bin/wine-preloader /usr/bin/wine C:\windows\system32\wineboot.exe --init
2067	2066	(forked without exec)
2068	2067	/usr/bin/wine-preloader /usr/bin/wine C:\windows\system32\winemenubuilder.exe -a -r
2069	2066	(forked without exec)
2070	2069	/usr/bin/wine-preloader /usr/bin/wine C:\windows\system32\services.exe
2073	2070	(forked without exec)
2074	2073	/usr/bin/wine-preloader /usr/bin/wine C:\windows\Microsoft.NET\Framework\v4.0.30319\mscorsvw.exe
2075	2068	(forked without exec)
2076	2075	/usr/bin/wine-preloader /usr/bin/wine C:\windows\system32\explorer.exe /desktop
2083	2070	(forked without exec)
2084	2083	/usr/bin/wine-preloader /usr/bin/wine C:\windows\system32\winedevice.exe MountMgr
2089	2070	(forked without exec)
2090	2089	/usr/bin/wine-preloader /usr/bin/wine C:\windows\system32\plugplay.exe

If I run rr replay -a the test.exe.so does not seem to be run.

**Comment by fracting** [comment]
This is the hack I used last time to make Wine work with RR:
https://gist.github.com/fracting/d3e193242fd5f41d2f91

Reference: https://github.com/mozilla/rr/issues/1560
(I forgot to create an issue for it, sorry)

However, with today's latest Wine Staging + RR, I got an error:
```
[FATAL /home/fracting/src/rr/rr/src/ReplaySession.cc:870:check_ticks_consistency() errno: 0 'Success'] 
 (task 24749 (rec:24265) at time 1615)
 ->  Assertion `llabs(ticks_now - trace_ticks) <= ticks_slack' failed to hold. ticks mismatch for 'SYSCALL: mmap2'; expected 218211, got 218207
```

I haven't tested "Wine Regular" yet.

What Wine version are you testing?

**Comment by rocallahan** [comment]
For me, Wine doesn't work in rr because the preloader does
````
if (wld_prctl( 15 /* PR_SET_NAME */, (long)name ) == -1)
````
Unfortunately the prototype for `wld_prctl` is
````
int wld_prctl( int code, int arg );
````
So the upper 32 bits of `name` get chopped off. `name` is on the stack after the preloader is execed, so there's nothing ensuring it's in the first 4GB as far as I can tell. This seems to be just a Wine bug. I need to make rr handle EFAULT here.

**Comment by rocallahan** [comment]
Pushed 3e014072a75c8a7ec5eb05325bbd1e42e74de67e to fix that.

> If I run rr replay -a the test.exe.so does not seem to be run.

When I record notepad.exe, it does seem to run; at least notepad.exe.so gets mapped and the replay runs to completion.

**Comment by rocallahan** [comment]
Running the Firefox installer works under rr...

**Comment by rocallahan** [comment]
Firefox doesn't work very well under Wine for me. Doesn't seem to be able to load anything.

**Comment by rocallahan** [comment]
(Nightly, so it could be e10s related or even a bad nightly.)

**Comment by rocallahan** [comment]
But, recording and replaying Firefox seems to work perfectly for me.

**Comment by rocallahan** [comment]
If I disable e10s then Firefox nightly works under Wine for me. Not perfect, but pretty close! Amazing :-).

**Comment by rocallahan** [comment]
And all that runs under rr for me. You can't really debug anything because gdb has no idea what's going on when you attach. I guess that's fixable somehow; not a priority for me, but someone with deep Wine knowledge could probably set something up.

**Comment by rocallahan** [comment]
http://robert.ocallahan.org/2016/03/running-firefox-for-windows-with-rr.html

**Comment by fracting** [comment]
Thanks @rocallahan, I sent a patch to Wine fixing the wld_prctl problem.

http://source.winehq.org/git/wine.git/?a=commit;h=33765285c535ea521961a6ee812db08c79abda6e

**Comment by rocallahan** [comment]
Excellent, thanks!

**Comment by rocallahan** [comment]
I'm closing this on the assumption that it's been fixed.
