### ISSUE TITLE
Does rr work with servo?

### ISSUE THREAD

**Issue by cgjones** [mozilla/rr#1081]
I had originally intended to use servo as my rust test case for #992, but hit a snag.  Servo doesn't much care about 32-bit support, and rr doesn't have 64-bit support (#606).  So we're going to have to delay this project until someone "gives".

**Comment by doublec** [comment]
I tested with servo on Ubuntu 64 bit:

    ./mach rr-record http://cd.pn/x.txt
    rr: Saving the execution of `components/servo/target/servo' to trace directory `/home/chris/.rr/servo-5'.
    [glutin] x error code=11 major=-101 minor=34!

I get the glutin error if I use 'rr' outside of 'mach' too. Is this a known 'rr' issue? Anything I can provide to help track it down?

**Comment by rocallahan** [comment]
rr disables access to DRI by blocking access to `/dev/dri/card0`. Maybe that's the cause of the error? You could try disabling DRI some other way to see.

**Comment by doublec** [comment]
My previous report was using the NVIDIA graphics. I switched to Intel to compare and get the following instead:

    [glutin] x error code=-78 major=-101 minor=34!
    thread '<main>' panicked at 'Failed to compile shader: ', .cargo/git/checkouts/rust-layers-3d9d5f0b4e4d9002/master/src/rendergl.rs:121
    thread 'PaintTask' panicked at 'called `Result::unwrap()` on an `Err` value: "SendError(..)"', rust/src/libcore/result.rs:743

I'll have a look at the DRI settings when I next try.

**Comment by cgjones** [comment]
Yeah, if servo can't downgrade to no-GL or mesa-backed GL, it's not going to work.  We've observed that Firefox seems to fall back on mesa GL.

**Comment by Manishearth** [comment]
It works now, when servo is built with `SERVO_HEADLESS=1`.

**Comment by jdm** [comment]
!!!

**Comment by luser** [comment]
Can you write up a description on how to make that work somewhere?

**Comment by Manishearth** [comment]
There's not much to do in terms of steps. Setup rr, clone Servo, build with `SERVO_HEADLESS=1 ./mach build`, and then `./mach rr-record` and `./mach rr-replay`
