### ISSUE TITLE
Remove constraint on srcdir/objdir layout for running tests

### ISSUE THREAD

**Issue by cgjones** [mozilla/rr#1153]
Currently, $srcdir must be a sibling of $objdir and must be named "src".   ([Documented here](https://github.com/mozilla/rr/wiki/Installation).)  I think just about everyone who's tried to run the rr unit tests has been tripped up by that.

IIRC we require this because I didn't know how to reference the $srcdir from within CMakefiles.txt.  (The test scripts are run directly from the srcdir.)

So one fix is for someone with more cmake-fu than me to find a $srcdir referent.  Another fix is to copy the test scripts into the $objdir.

**Comment by rocallahan** [comment]
Fixed by #1465
