### ISSUE TITLE
monkeypatching vdso entry points for fun and profit

### ISSUE THREAD

**Issue by froydnj** [mozilla/rr#1216]
The wiki page for porting to x86-64 lists several options for what to do about x86-64's VDSO.  I was looking into this today and thought of a fifth option that's not listed there: simply monkeypatch each vdso function to execute the appropriate syscall.  That way we don't have to worry about doing much fancy handling on the rr side (as opposed to, e.g. monkeypatching them to jump back into rr code or `mprotect`'ing the appropriate pages); everything just looks like a normal syscall.

The only way this would fail would be if symbols in the VDSO didn't have enough space to insert the required instructions (`mov $num, eax / int $80 / ret`), but I'm guessing there would be enough space--the kernel folks want performance, and they'd align the entry points pretty aggressively, so there ought to be 16 bytes minimum per-function.

I don't know what the performance hit of this would be, versus the other monkeypatching options suggested.  My guess is about even.

This would require some fairly elaborate code to parse the in-memory VDSO image to discover entry points (though I don't know that it'd be any worse than other monkeypatching options, and parsing ELF is more straightforward than rr tricks), but that strikes me as not entirely a bad thing:

1. We can suddenly handle `__kernel_vsyscall` moving around automagically.
2. We can fail fast if VDSOs add things that we're not prepared to handle.

WDYT?

**Comment by cgjones** [comment]
Anything left to do here?

**Comment by rocallahan** [comment]
No, we fixed this.
