### ISSUE TITLE
Use hardlinks to make traces more robust to underlying file changes

### ISSUE THREAD

**Issue by rocallahan** [mozilla/rr#1381]
Karl Tomlinson made an excellent suggestion during the rr meeting in Portland: we can make rr traces a lot more robust to filesystem changes by storing hardlinks to mmapped files in the trace directory and mapping those during replay. Creating a hardlink is practically free and if the original files are moved, deleted, or replaced the trace will still work. (If a file is written without being deleted first then the trace will still diverge.) And of course this will work on almost all filesystem types, though will break down if the trace directory and the mapped files are on different filesystems. I have this mostly implemented for all explicit mmaps and it works great with a very simple implementation, and I'll land that soon. When we can't make a hardlink we just fall back to the current setup.

The major remaining issue is the memory mappings created by `execve`; these are not easy to handle. `execve` creates mappings for the executable itself, its interpreter (usually ld.so), the esoteric VDSO-related areas, and the initial stack with auxvs and other data. Obviously handling changes in the executable would be the highest priority, but handling changes in ld.so and possibly the setup of other areas would be important for making traces portable across OS releases.

I'd like to try an approach where after exec we unmap everything that was mapped by the kernel and install new mappings of saved files from the trace. If that works, it will give us maximum trace portability.

**Comment by pm215** [comment]
Would fixing this issue make rr recorded sessions robust to system library upgrades? I just lost a recorded session I was trying to debug ("doing 'run 100000' in the debugger caused it to complain a lot about "Metadata of /usr/lib/x86_64-linux-gnu/libpulse.so.0.19.0 changed: replay divergence likely, but continuing anyway" etc and then fail with "Assertion `ticks_now == trace_ticks' failed to hold. ticks mismatch for 'SYSCALL: close'; expected 17610, got 17538"), which I'm pretty sure is because of a badly-timed 'apt-get upgrade' that updated various libraries including libc so they were newer than at time of session recording...

**Comment by rocallahan** [comment]
You want `rr pack`. http://robert.ocallahan.org/2017/06/new-rr-pack-command.html

**Comment by pm215** [comment]
'rr pack' doesn't really help, because it requires you to do something in advance, whereas by the time I realized my recorded session was toast the ill-timed upgrade had already happened...

**Comment by rocallahan** [comment]
Another option is to configure your system so that all relevant files (system files, application files, and your rr trace) are on the same filesystem, and have that filesystem be something like btrfs that supports reflink copies. Then rr will make reflink copies of all files and you'll be protected.

Another option is to set `RR_COPY_ALL_FILES=1` in your environment to force copies at all times. Note however that (if reflinks aren't possible in your configuration) this will be slow and bloat traces, which is why we don't do it by default.
