### ISSUE TITLE
rr/src/AddressSpace.h:184: void Mapping::assert_valid() const: Assertion `num_bytes() % page_size() == 0' failed

### ISSUE THREAD

**Issue by heycam** [mozilla/rr#1413]
I get this assertion failure with current HEAD on 32-bit Linux Mint 17.1 (based on Ubuntu 14.04) running in a VM.

**Comment by heycam** [comment]
$ gdb --args /home/cam/rr/obj/bin/rr record -M ./mach mochitest-plain layout/style/test/test_value_computation.html
    ...
    (gdb) r
    ...
    rr: Saving the execution of `./mach' to trace directory `/home/cam/.rr/mach-5'.
    rr: /home/cam/rr/rr/src/AddressSpace.h:184: void Mapping::assert_valid() const: Assertion `num_bytes() % page_size() == 0' failed.

    Program received signal SIGABRT, Aborted.
    0xb7fdd424 in __kernel_vsyscall ()
    (gdb) bt
    #0  0xb7fdd424 in __kernel_vsyscall ()
    #1  0xb7d01577 in raise () from /lib/i386-linux-gnu/libc.so.6
    #2  0xb7d049a3 in abort () from /lib/i386-linux-gnu/libc.so.6
    #3  0xb7cfa6c7 in ?? () from /lib/i386-linux-gnu/libc.so.6
    #4  0xb7cfa777 in __assert_fail () from /lib/i386-linux-gnu/libc.so.6
    #5  0x080fb1c4 in Mapping::assert_valid (this=0xbfffead8) at /home/cam/rr/rr/src/AddressSpace.h:184
    #6  0x080fb09a in Mapping::Mapping (this=0xbfffead8, start=..., end=..., prot=3, flags=34, offset=0)
        at /home/cam/rr/rr/src/AddressSpace.h:165
    #7  0x080fbb69 in AddressSpace::update_heap (this=0x8238dc8, start=..., end=...) at /home/cam/rr/rr/src/AddressSpace.h:677
    #8  0x080f5cee in AddressSpace::brk (this=0x8238dc8, addr=...) at /home/cam/rr/rr/src/AddressSpace.cc:519
    #9  0x081a7154 in Task::maybe_update_vm_arch<rr::X86Arch> (this=0x8236f48, syscallno=45, state=SYSCALL_EXIT)
        at /home/cam/rr/rr/src/task.cc:624
    #10 0x0819cbaf in Task::maybe_update_vm (this=0x8236f48, syscallno=45, state=SYSCALL_EXIT) at /home/cam/rr/rr/src/task.cc:655
    #11 0x08161d0a in before_syscall_exit<rr::X86Arch> (t=0x8236f48, syscallno=45) at /home/cam/rr/rr/src/record_syscall.cc:2420
    #12 0x081579a6 in rec_process_syscall_arch<rr::X86Arch> (t=0x8236f48) at /home/cam/rr/rr/src/record_syscall.cc:2529
    #13 0x08152c85 in rec_process_syscall (t=0x8236f48) at /home/cam/rr/rr/src/record_syscall.cc:3108
    #14 0x08149ed1 in syscall_state_changed (t=0x8236f48, by_waitpid=false) at /home/cam/rr/rr/src/RecordSession.cc:523
    #15 0x0814bf3d in RecordSession::record_step (this=0x82205f8) at /home/cam/rr/rr/src/RecordSession.cc:955
    #16 0x081462f3 in record (args=..., flags=...) at /home/cam/rr/rr/src/RecordCommand.cc:187
    #17 0x0814654c in RecordCommand::run (this=0x821d7b0 <RecordCommand::singleton>, args=...)
        at /home/cam/rr/rr/src/RecordCommand.cc:233
    #18 0x0813a702 in main (argc=6, argv=0xbffff224) at /home/cam/rr/rr/src/main.cc:241
    (gdb) frame 5
    #5  0x080fb1c4 in Mapping::assert_valid (this=0xbfffead8) at /home/cam/rr/rr/src/AddressSpace.h:184
    184	    assert(num_bytes() % page_size() == 0);
    (gdb) p num_bytes()
    $1 = 3392
    (gdb) p page_size()
    $2 = 4096

**Comment by rocallahan** [comment]
Hey, I can reproduce this!

**Comment by heycam** [comment]
Thanks! \o/
