### ISSUE TITLE
Unhandled ptrace event PTRACE_EVENT_VFORK(2)

### ISSUE THREAD

**Issue by heycam** [mozilla/rr#1414]
After the #1413 fix, I'm getting this:

```
$ rr record -M ./mach mochitest-plain layout/style/test/test_value_computation.html 
rr: Saving the execution of `./mach' to trace directory `/home/cam/.rr/mach-9'.
[rr 10460 2045][rr 10460 2047][rr 10460 2049][rr 10460 2051][rr 10460 2060][rr 10460 2062][rr 10460 2064][rr 10460 2066][rr 10460 2068][rr 10460 2070][rr 10460 2076][rr 10460 2078][rr 10460 2080][rr 10460 2082][rr 10460 2084][rr 10460 2086][rr 10460 2097][rr 10460 2099][rr 10460 2101][rr 10460 2103][rr 10460 2109][FATAL /home/cam/rr/rr/src/RecordSession.cc:196:handle_ptrace_event() errno: 0 'Success'] 
 -> Unhandled ptrace event PTRACE_EVENT_VFORK(2)
Aborted
```

**Comment by rocallahan** [comment]
Yeah, I proceeded with your testcase and found this myself. We need to implement vfork(); I'm working on it.

**Comment by heycam** [comment]
:thumbsup:

**Comment by rocallahan** [comment]
Fixed by commit a5fd1a7faa1dcf4fd6da16345999abd620d3f783

**Comment by rocallahan** [comment]
Now I get pretty far through the mochitest, but I get a layout assertion 
````
###!!! ASSERTION: bad inline size: 'metrics.ISize(lineWM) >= 0'
````
and then rr aborts with `Unknown ioctl(0x80045430)`...

**Comment by rocallahan** [comment]
That's `TIOCGPTN` being called by some python process-management stuff.

**Comment by rocallahan** [comment]
Fixed that with commit eab35b1c2ca6a9d3b49ceb57be526f017e2b33a8.

**Comment by rocallahan** [comment]
Now it gets through the whole test, but rr dies at the end with
````
Assertion `!has_stashed_sig()' failed to hold. Tried to stash SIGCONT when SIGHUP was already stashed.
````
That looks tricky, and I'll just ignore it for now.

**Comment by rocallahan** [comment]
Ah, but replay doesn't work :-(.

**Comment by rocallahan** [comment]
Found and fixed one bug, but there's at least one more...

In the meantime, you can run `./mach --debugger rr ...` to avoid recording all of mach and the test harness.

**Comment by heycam** [comment]
Thanks, `./mach --debugger rr` is working for me.

**Comment by rocallahan** [comment]
I pushed some more commits to master, but still had a divergence during replay. Then I updated my tree and the divergence went away, so now I can record and replay the harness reliably (except for the stashed_sig error at the end). So I'm going to shelve this for now.
