### ISSUE TITLE
Replay fails with "Remote 'g' packet reply is too long"

### ISSUE THREAD

**Issue by bgirard** [mozilla/rr#1421]
I'm trying to replay firefox nightly (start+close) and get the following error. This is on bgirard@hawkman.corp.tor1.mozilla.com, send me your public key if you have access to the mozilla VPN to debug this.

Remote 'g' packet reply is too long: 9ac8888c0000000070eaffffff7f000000000000000000002b3d1c0000000000000000000000000070eaffffff7f000060eaffffff7f0000d0e9ffffff7f00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000086faaaaaaa2a000002020100330000002b0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000007f0300000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000801f0000ffffffffffffffff

**Comment by bgirard** [comment]
Linux hawkman 3.13.0-32-generic #57-Ubuntu SMP Tue Jul 15 03:51:08 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux
Intel(R) Core(TM) i7-4770 CPU @ 3.40GHz

**Comment by froydnj** [comment]
What does:

```
$ gdb
(gdb) target exec /bin/ls # or some other 64-bit executable
(gdb) maint print registers
```

say?

**Comment by bgirard** [comment]
bgirard@hawkman:~/ben/firefoxnightly$ gdb
GNU gdb (Ubuntu 7.7.1-0ubuntu5~14.04.2) 7.7.1
Copyright (C) 2014 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word".
(gdb) target exec /bin/ls
(gdb) maint print registers
 Name         Nr  Rel Offset    Size  Type            
 rax           0    0      0       8 int64_t         
 rbx           1    1      8       8 int64_t         
 rcx           2    2     16       8 int64_t         
 rdx           3    3     24       8 int64_t         
 rsi           4    4     32       8 int64_t         
 rdi           5    5     40       8 int64_t         
 rbp           6    6     48       8 *1              
 rsp           7    7     56       8 *1              
 r8            8    8     64       8 int64_t         
 r9            9    9     72       8 int64_t         
 r10          10   10     80       8 int64_t         
 r11          11   11     88       8 int64_t         
 r12          12   12     96       8 int64_t         
 r13          13   13    104       8 int64_t         
 r14          14   14    112       8 int64_t         
 r15          15   15    120       8 int64_t         
 rip          16   16    128       8 *1              
 eflags       17   17    136       4 i386_eflags     
 cs           18   18    140       4 int32_t         
 ss           19   19    144       4 int32_t         
 ds           20   20    148       4 int32_t         
 es           21   21    152       4 int32_t         
 fs           22   22    156       4 int32_t         
 gs           23   23    160       4 int32_t         
 st0          24   24    164      10 _i387_ext       
 st1          25   25    174      10 _i387_ext       
 st2          26   26    184      10 _i387_ext       
 st3          27   27    194      10 _i387_ext       
 st4          28   28    204      10 _i387_ext       
 st5          29   29    214      10 _i387_ext       
 st6          30   30    224      10 _i387_ext       
 st7          31   31    234      10 _i387_ext       
 fctrl        32   32    244       4 int             
 fstat        33   33    248       4 int             
 ftag         34   34    252       4 int             
 fiseg        35   35    256       4 int             
 fioff        36   36    260       4 int             
 foseg        37   37    264       4 int             
 fooff        38   38    268       4 int             
 fop          39   39    272       4 int             
 xmm0         40   40    276      16 vec128          
 xmm1         41   41    292      16 vec128          
 xmm2         42   42    308      16 vec128          
 xmm3         43   43    324      16 vec128          
 xmm4         44   44    340      16 vec128          
 xmm5         45   45    356      16 vec128          
 xmm6         46   46    372      16 vec128          
 xmm7         47   47    388      16 vec128          
 xmm8         48   48    404      16 vec128          
 xmm9         49   49    420      16 vec128          
 xmm10        50   50    436      16 vec128          
 xmm11        51   51    452      16 vec128          
 xmm12        52   52    468      16 vec128          
 xmm13        53   53    484      16 vec128          
 xmm14        54   54    500      16 vec128          
 xmm15        55   55    516      16 vec128          
 mxcsr        56   56    532       4 i386_mxcsr      
 ''           57   57    536       0 int0_t          
 ''           58   58    536       0 int0_t          
 ''           59   59    536       0 int0_t          
 ''           60   60    536       0 int0_t          
 ''           61   61    536       0 int0_t          
 ''           62   62    536       0 int0_t          
 ''           63   63    536       0 int0_t          
 ''           64   64    536       0 int0_t          
 ''           65   65    536       0 int0_t          
 ''           66   66    536       0 int0_t          
 ''           67   67    536       0 int0_t          
 ''           68   68    536       0 int0_t          
 ''           69   69    536       0 int0_t          
 ''           70   70    536       0 int0_t          
 ''           71   71    536       0 int0_t          
 ''           72   72    536       0 int0_t          
 ''           73   73    536       0 int0_t          
 ''           74   74    536       0 int0_t          
 ''           75   75    536       0 int0_t          
 ''           76   76    536       0 int0_t          
 ''           77   77    536       0 int0_t          
 ''           78   78    536       0 int0_t          
 orig_rax     79   79    536       8 long            
 al           80    0    544       1 int8_t          
 bl           81    1    545       1 int8_t          
 cl           82    2    546       1 int8_t          
 dl           83    3    547       1 int8_t          
 sil          84    4    548       1 int8_t          
 dil          85    5    549       1 int8_t          
 bpl          86    6    550       1 int8_t          
 spl          87    7    551       1 int8_t          
 r8l          88    8    552       1 int8_t          
 r9l          89    9    553       1 int8_t          
 r10l         90   10    554       1 int8_t          
 r11l         91   11    555       1 int8_t          
 r12l         92   12    556       1 int8_t          
 r13l         93   13    557       1 int8_t          
 r14l         94   14    558       1 int8_t          
 r15l         95   15    559       1 int8_t          
 ah           96   16    560       1 int8_t          
 bh           97   17    561       1 int8_t          
 ch           98   18    562       1 int8_t          
 dh           99   19    563       1 int8_t          
 ax          100   20    564       2 int16_t         
 bx          101   21    566       2 int16_t         
 cx          102   22    568       2 int16_t         
 dx          103   23    570       2 int16_t         
 si          104   24    572       2 int16_t         
 di          105   25    574       2 int16_t         
 bp          106   26    576       2 int16_t         
 ''          107   27    578       2 int16_t         
 r8w         108   28    580       2 int16_t         
 r9w         109   29    582       2 int16_t         
 r10w        110   30    584       2 int16_t         
 r11w        111   31    586       2 int16_t         
 r12w        112   32    588       2 int16_t         
 r13w        113   33    590       2 int16_t         
 r14w        114   34    592       2 int16_t         
 r15w        115   35    594       2 int16_t         
 eax         116   36    596       4 int32_t         
 ebx         117   37    600       4 int32_t         
 ecx         118   38    604       4 int32_t         
 edx         119   39    608       4 int32_t         
 esi         120   40    612       4 int32_t         
 edi         121   41    616       4 int32_t         
 ebp         122   42    620       4 int32_t         
 esp         123   43    624       4 int32_t         
 r8d         124   44    628       4 int32_t         
 r9d         125   45    632       4 int32_t         
 r10d        126   46    636       4 int32_t         
 r11d        127   47    640       4 int32_t         
 r12d        128   48    644       4 int32_t         
 r13d        129   49    648       4 int32_t         
 r14d        130   50    652       4 int32_t         
 r15d        131   51    656       4 int32_t         
*1: Register type's name NULL.

**Comment by rocallahan** [comment]
The problem seems to be that gdb thinks the remote arch is x86-32.

**Comment by rocallahan** [comment]
The *real* problem is that the recording (`~/.rr/firefox-2`) started by recording the wrapper script, and when you `rr replay` we're trying to launch gdb on the Firefox wrapper shell script:
````
gdb -l -1 /usr/lib/firefox/firefox.sh -l -1 -x /proc/24019/fd/4 -ex target extended-remote 127.0.0.1:24020
````
gdb helpfully warns us `"/usr/lib/firefox/firefox.sh": not in executable format: File format not recognized` but of course none of us noticed that :-). gdb can't guess the architecture so defaults to i386, but rr gives it 64-bit registers, so things go wrong.

**Comment by rocallahan** [comment]
The question then is, what *should* rr do in this situation?

**Comment by rocallahan** [comment]
One option: by default, wait for the initial process to exec something that's not a script, and debug that. That'd give you the results you wanted in this case, and for wrapper scripts in general. Maybe it's too DWIM though.

Whether we do that or not, when launching gdb rr should provide the filename of the interpreter binary here, not the script. So I'll fix that first.
