### ISSUE TITLE
Assertion `t->regs().syscall_result_signed() == -syscall_state.expect_errno' failed to hold. Expected EINVAL for 'prctl' but got result 0

### ISSUE THREAD

**Issue by heycam** [mozilla/rr#1429]
```
[FATAL /z/rr/rr/src/record_syscall.cc:2562:rec_process_syscall_arch() errno: 0 'Success']
 (task 16068 (rec:16068) at time 396521)
 ->  Assertion `t->regs().syscall_result_signed() == -syscall_state.expect_errno' failed to hold. Expected EINVAL for 'prctl' but got result 0
```

I get this assertion when trying to record running a gaia-ui-test using a desktop B2G build. I think that the assertion is occurring at the point Gecko is crashing (the thing I'm trying to debug), but I'm not sure.

Let me know if you need STR and I'll work some out.

**Comment by rocallahan** [comment]
We probably need the emergency-debug data. If you get the emergency-debug message (instructing you to attach gdb with `target remote ...`), follow those instructions. If not, make sure rr runs with the `-F` option (you may need to write a trivial wrapper script that supplies `-F` and specify that as the debugger).

**Comment by rocallahan** [comment]
I've just pushed an update to master that makes those emergency-debug instructions easier to follow.

If you can attach to the emergency-debug session, then we'll want a stack trace. This looks like an unsupported `prctl` is being called, and the stack trace should show us which one it is. `info registers` in the bottom-most stack frame would be helpful too.

**Comment by rocallahan** [comment]
Actually, you can ignore all that for now ... I just pushed to master a change that will report the unsuported `prctl` value directly if you just rerun recording.

**Comment by heycam** [comment]
`unknown prctl(0x4)` it tells me now.

**Comment by heycam** [comment]
Based on that value I'm guessing it's because I have the crashreporter enabled and it's trying to generate the minidump.

**Comment by rocallahan** [comment]
I actually had that working at one point. Maybe the crashreporter code changed.
