### ISSUE TITLE
"Assertion `pending_events.back().type() == expected_type' failed to hold." while rr record mach

### ISSUE THREAD

**Issue by staktrace** [mozilla/rr#1434]
Using trunk rr (commit 380526db7d65ffc) I was attempting to record a FF mochitest crash, seems like rr didn't like something mach was doing:

kats@kgupta-pc gecko$ ~/zspace/rr/obj/bin/rr record mach mochitest dom/imptests/editing/conformancetest/test_runtest.html
rr: Saving the execution of `mach' to trace directory `/home/kats/.rr/mach-3'.
[FATAL /home/kats/zspace/rr/rr/src/task.cc:1021:pop_event() errno: 0 'Success']
 (task 27960 (rec:27960) at time 33134)
 ->  Assertion `pending_events.back().type() == expected_type' failed to hold.
Launch gdb with
  gdb /bin/dash
and attach to the rr debug server with:
  target remote :27960

Presumably the gecko version doesn't matter here since rr was failing on mach itself. uname -a shows:

Linux kgupta-pc 3.13.0-46-generic #75-Ubuntu SMP Tue Feb 10 15:24:04 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

**Comment by cgjones** [comment]
Most likely the same problem as #1424, but this is a slightly different invocation.

**Comment by rocallahan** [comment]
Note that you can work around this using `mach mochitest --debugger rr`.

**Comment by khuey** [comment]
This is probably fixed by #1461.

I suspect the workaround works because the part that's failing here is inside the shell, and the workaround doesn't record mach's shell bits in rr.
