### ISSUE TITLE
watch point doesn't seem to work with reverse exection

### ISSUE THREAD

**Issue by jrmuizel** [mozilla/rr#1435]
Here's the recording
http://people.mozilla.org/~jmuizelaar/rr/firefox-3.tar.xz

Set a breakpoint on testing::internal::EqFailure.
When it is hit go up to the frame RegionBitmap::compare
Set a watchpoint on bitmap[x+y*width]
Running reverse-cont goes to the beginning of the program

**Comment by jrmuizel** [comment]
I tried reproducing this with a simple test case and the watch point did work. I'm not sure what the difference is yet.

**Comment by rocallahan** [comment]
Did you use `watch -l`? I haven't really tested what happens if you don't use `-l`.

Uncommenting `#define DEBUGTAG "ReplayTimeline"` and `#define DEBUGTAG `GdbConnection`" and pasting the results here would be helpful.

**Comment by rocallahan** [comment]
BTW porting traces between machines doesn't work currently, sorry!

**Comment by jrmuizel** [comment]
Yeah, I was using 'watch -l'. I'll post the debug info when I get a chance.

**Comment by jrmuizel** [comment]
(gdb) print res.bitmap[20*600+20]
[GdbConnection] raw request m(7ffffff4ca20,8)
[GdbConnection] gdb requests memory (addr=0x7ffffff4ca20, len=8)
[GdbConnection] write_flush: '$7048faffff7f0000#8f'
[GdbConnection] raw request m(7ffffffa7764,1)
[GdbConnection] gdb requests memory (addr=0x7ffffffa7764, len=1)
[GdbConnection] write_flush: '$ff#cc'
$5 = 255 '\377'
(gdb) watch -location res.bitmap[20*600+20]
[GdbConnection] raw request m(7ffffff4ca20,8)
[GdbConnection] gdb requests memory (addr=0x7ffffff4ca20, len=8)
[GdbConnection] write_flush: '$7048faffff7f0000#8f'
[GdbConnection] raw request m(7ffffffa7764,1)
[GdbConnection] gdb requests memory (addr=0x7ffffffa7764, len=1)
[GdbConnection] write_flush: '$ff#cc'
[GdbConnection] raw request m(7ffffffa7764,1)
[GdbConnection] gdb requests memory (addr=0x7ffffffa7764, len=1)
[GdbConnection] write_flush: '$ff#cc'
Hardware watchpoint 3: -location res.bitmap[20*600+20]
(gdb) reverse-continue
Continuing.
[GdbConnection] raw request m(7ffffffa7764,1)
[GdbConnection] gdb requests memory (addr=0x7ffffffa7764, len=1)
[GdbConnection] write_flush: '$ff#cc'
[GdbConnection] raw request Z(0,2aaaaaaae92d,1)
[GdbConnection] gdb requests setbreakpoint (addr=0x2aaaaaaae92d, len=1)
[GdbConnection] write_flush: '$OK#9a'
[GdbConnection] raw request Z(0,2aaaaaabfc5a,1)
[GdbConnection] gdb requests setbreakpoint (addr=0x2aaaaaabfc5a, len=1)
[GdbConnection] write_flush: '$OK#9a'
[GdbConnection] raw request Z(0,2aaaaaac0d8c,1)
[GdbConnection] gdb requests setbreakpoint (addr=0x2aaaaaac0d8c, len=1)
[GdbConnection] write_flush: '$OK#9a'
[GdbConnection] raw request Z(0,2aaaaf147974,1)
[GdbConnection] gdb requests setbreakpoint (addr=0x2aaaaf147974, len=1)
[GdbConnection] write_flush: '$OK#9a'
[GdbConnection] raw request Z(2,7ffffffa7764,1)
[GdbConnection] gdb requests setbreakpoint (addr=0x7ffffffa7764, len=1)
[GdbConnection] write_flush: '$OK#9a'
[GdbConnection] raw request H(cp442e.0)
[GdbConnection] gdb selecting 17454.0
[GdbConnection] write_flush: '$OK#9a'
[GdbConnection] raw request b(c)
[ReplayTimeline] ReplayTimeline::reverse_continue from {time:5368,ticks:55838656,st:4,regs_ip:0x2aaaaf147974}
[ReplayTimeline] Seeked backward from {time:5368,ticks:55838656,st:4,regs_ip:0x2aaaaf147974} to {time:18,ticks:135,st:0,regs_ip:0x2aaaaaaafeaa}
[ReplayTimeline] Found breakpoint break at {time:224,ticks:238145,st:1,regs_ip:0x2aaaaaaae92d}
[ReplayTimeline] Found breakpoint break at {time:363,ticks:275887,st:1,regs_ip:0x2aaaaaabfc5a}
[ReplayTimeline] Found breakpoint break at {time:387,ticks:282930,st:6,regs_ip:0x2aaaaaabfc5a}
[ReplayTimeline] Found breakpoint break at {time:409,ticks:289952,st:6,regs_ip:0x2aaaaaabfc5a}
[ReplayTimeline] Found breakpoint break at {time:431,ticks:310657,st:6,regs_ip:0x2aaaaaabfc5a}
[ReplayTimeline] Found breakpoint break at {time:455,ticks:350599,st:6,regs_ip:0x2aaaaaabfc5a}
[ReplayTimeline] Found breakpoint break at {time:477,ticks:377663,st:6,regs_ip:0x2aaaaaabfc5a}
[ReplayTimeline] Found breakpoint break at {time:501,ticks:399448,st:6,regs_ip:0x2aaaaaabfc5a}
[ReplayTimeline] Found breakpoint break at {time:523,ticks:449902,st:6,regs_ip:0x2aaaaaabfc5a}
[ReplayTimeline] Found breakpoint break at {time:543,ticks:457112,st:6,regs_ip:0x2aaaaaabfc5a}
[ReplayTimeline] Found breakpoint break at {time:1529,ticks:2985043,st:7,regs_ip:0x2aaaaaabfc5a}
[ReplayTimeline] Found breakpoint break at {time:1717,ticks:3785097,st:1,regs_ip:0x2aaaaaabfc5a}
[ReplayTimeline] Found watch/signal break at {time:2394,ticks:6360919,st:5,regs_ip:0x2aaaab0e1250}
[ReplayTimeline] Found breakpoint break at {time:2831,ticks:8012917,st:1,regs_ip:0x2aaaaaabfc5a}
[ReplayTimeline] Found breakpoint break at {time:2847,ticks:8246278,st:1,regs_ip:0x2aaaaaabfc5a}
[ReplayTimeline] Found breakpoint break at {time:2861,ticks:8472162,st:6,regs_ip:0x2aaaaaabfc5a}
[ReplayTimeline] Found breakpoint break at {time:5368,ticks:47464911,st:4,regs_ip:0x2aaaaf147974}
[ReplayTimeline] Found breakpoint break at {time:5368,ticks:51651790,st:4,regs_ip:0x2aaaaf147974}
[ReplayTimeline] Seeking to final destination {time:5368,ticks:51651790,st:4,regs_ip:0x2aaaaf147974}
[GdbConnection] forcing query/resume thread to 17454.17454
[GdbConnection] write_flush: '$T05thread:p442e.442e;#42'
[GdbConnection] raw request g()
[GdbConnection] gdb requests registers
[GdbConnection] write_flush: '$f0c6ffffff7f0000000000000000000020e32eabaa2a000020caf4ffff7f000071360aaeaa2a0000f0c6ffffff7f0000f0c9f4ffff7f000090c9f4ffff7f00006400000000000000140000000000000080c7f4ffff7f0000f1390daeaa2a000010d905aeaa2a0000000000000000000021000000000000000000000000000000747914afaa2a000006020000330000002b0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000007f03000000000000000000000000000000000000000000000000000000000000ff000000000000000000000000000000252525252525252525252525252525254553545f53484152445f494e4445580000000000000000000000000000000000ff0000000000000000000000000000005a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a20202020202020202020202020202020000000ffffffff00ffffffff00ffffff526567696f6e56697369744564676573000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000ffffffffff0000000000000000000000000000283c000000000000000086bd86a630e03c3c0000000000000000c07b3357245431400000000000000000a11f0000ffffffffffffffff#38'
[GdbConnection] raw request z(0,2aaaaaaae92d,1)
[GdbConnection] gdb requests removebreakpoint (addr=0x2aaaaaaae92d, len=1)
[GdbConnection] write_flush: '$OK#9a'
[GdbConnection] raw request z(0,2aaaaaabfc5a,1)
[GdbConnection] gdb requests removebreakpoint (addr=0x2aaaaaabfc5a, len=1)
[GdbConnection] write_flush: '$OK#9a'
[GdbConnection] raw request z(0,2aaaaaac0d8c,1)
[GdbConnection] gdb requests removebreakpoint (addr=0x2aaaaaac0d8c, len=1)
[GdbConnection] write_flush: '$OK#9a'
[GdbConnection] raw request z(0,2aaaaf147974,1)
[GdbConnection] gdb requests removebreakpoint (addr=0x2aaaaf147974, len=1)
[GdbConnection] write_flush: '$OK#9a'
[GdbConnection] raw request z(2,7ffffffa7764,1)
[GdbConnection] gdb requests removebreakpoint (addr=0x7ffffffa7764, len=1)
[GdbConnection] write_flush: '$OK#9a'

[GdbConnection] raw request m(7ffffff4c9f8,8)
[GdbConnection] gdb requests memory (addr=0x7ffffff4c9f8, len=8)
[GdbConnection] write_flush: '$24390aaeaa2a0000#3e'
[GdbConnection] raw request m(7ffffff4c9f8,8)
[GdbConnection] gdb requests memory (addr=0x7ffffff4c9f8, len=8)
[GdbConnection] write_flush: '$24390aaeaa2a0000#3e'
[GdbConnection] raw request m(7ffffff4c9f0,8)
[GdbConnection] gdb requests memory (addr=0x7ffffff4c9f0, len=8)
[GdbConnection] write_flush: '$c0c6ffffff7f0000#ed'
[GdbConnection] raw request m(7ffffff4c9a8,8)
[GdbConnection] gdb requests memory (addr=0x7ffffff4c9a8, len=8)
[GdbConnection] write_flush: '$f0c6ffffff7f0000#f0'
[GdbConnection] raw request m(7ffffff4c9a0,8)
[GdbConnection] gdb requests memory (addr=0x7ffffff4c9a0, len=8)
[GdbConnection] write_flush: '$71360aaeaa2a0000#3d'
Breakpoint 2, nsRegion::VisitEdges (this=0x7fffffffc6f0, visit=0x2aaaae0a3671 <VisitEdge(void*, VisitSide, int, int, int, int)>, 
[GdbConnection] raw request m(7ffffff4c998,8)
[GdbConnection] gdb requests memory (addr=0x7ffffff4c998, len=8)
[GdbConnection] write_flush: '$20caf4ffff7f0000#b5'
    closure=0x7ffffff4ca20) at /home/jrmuizel/src/mozilla-central/gfx/src/nsRegion.cpp:486
486	{

**Comment by jrmuizel** [comment]
Or https://pastebin.mozilla.org/8826114 for less github

**Comment by jrmuizel** [comment]
It might be worth noting that the memory that I'm watching is on the stack

**Comment by jrmuizel** [comment]
The watchpoint doesn't work when going forward either

**Comment by jrmuizel** [comment]
When I turn on AddressSpace logging I get the following message:
[AddressSpace]   mapping at 0x7ffffffde000 out of range, done.

My naïve guess is that rr is not observing stack growth and thinks that the watchpoint is out of range

**Comment by rocallahan** [comment]
I think that's exactly right! I've reproduced this in a small testcase. Thanks!!!

**Comment by rocallahan** [comment]
Resolved by https://github.com/mozilla/rr/commit/ab9230231046eb64b50ea8d2d7689a94ee47e081.

There's some more work to do to clean up how we handle stack growth, but this should work for now.

**Comment by jrmuizel** [comment]
Yep, that commit fixes the problem that I was seeing in Firefox
