### ISSUE TITLE
'restart N' fails after checkpointing

### ISSUE THREAD

**Issue by benturner** [mozilla/rr#1449]
I can't get 'restart N' to work any more. Any info I can provide to help fix this? Here's my basic workflow:

(gdb) checkpoint
$4 = 1
(gdb) c
Continuing.
...
(gdb) restart 1
Running the default executable on the remote target failed; try "set remote exec-file"?
(gdb) set remote exec-file
(gdb) restart 1
Running the default executable on the remote target failed; try "set remote exec-file"?

**Comment by rocallahan** [comment]
WFM. What version of gdb? Can you reproduce it on a trivial program like `obj/bin/simple`?

**Comment by rocallahan** [comment]
FWIW I can't reproduce this with gdb 7.7.1 or 7.9 on `simple`.

**Comment by hotsphink** [comment]
I'm not sure if this is related, but if I do 'restart 0' then I get the same error message.

Which is distinct from the error message I get from 'restart tasty-taters', which aborts execution. (Not a big deal, but slightly annoying if you typo.)

**Comment by rocallahan** [comment]
This isn't perhaps fully resolved, but I checked in a fix to not crash when given an unparseable checkpoint number, and to print more informative messages when you pass an invalid checkpoint number. You can resume the program using `run` or `restart` with a valid checkpoint number. If Ben still has an issue we'll need to reopen with more info.
