### ISSUE TITLE
can't rr QEMU due to unsupported prctl(PR_MCE_KILL and PR_SET_TIMERSLACK)

### ISSUE THREAD

**Issue by pm215** [mozilla/rr#1452]
Trying to run QEMU under rr fails:

rr: Saving the execution of `./build/all-debug/aarch64-softmmu/qemu-system-aarch64' to trace directory `/home/petmay01/.rr/qemu-system-aarch64-41'.
[FATAL /home/petmay01/src/rr/src/record_syscall.cc:2638:rec_process_syscall_arch() errno: 0 'Success'] 
 (task 7033 (rec:7033) at time 2720)
 ->  Assertion `t->regs().syscall_result_signed() == -syscall_state.expect_errno' failed to hold. Expected EINVAL for 'prctl' but got result 0; unknown prctl(0x21)
Launch gdb with
  gdb /home/petmay01/linaro/qemu-from-laptop/qemu/build/all-debug/aarch64-softmmu/qemu-system-aarch64
and attach to the rr debug server with:
  target remote :7033

0x21 is PR_MCE_KILL. (QEMU has used this prctl for a long time, and running QEMU under rr used to work, so maybe something's changed in rr?)

**Comment by pm215** [comment]
If you comment out that prctl it then fails on prctl(0x1d) which is PR_SET_TIMERSLACK. That seems to be the only other thing preventing it working.

**Comment by rocallahan** [comment]
Yeah, I tightened up the handling of unknown prctls so we didn't just blindly execute them. I'll add support for these.
