### ISSUE TITLE
Using WINE with RR: get error "wine: failed to read ELF header"

### ISSUE THREAD

**Issue by synlestidae** [mozilla/rr#1453]
Hi,

So I am working on a project to get WINE working with RR to trace program execution. When I run the command "rr record wine helloworld.exe" I get the error: "/usr/bin/wine: failed to read ELF header". 

Some system details:

rr version 3.0.0
wine version 1.7.31

Thoughts?

I have been told that the issue may be that I'm using 32bit WINE. I am currently compiling it for
my 64 bit machine so if it turns out that that is the problem, I'll close the issue.

Cheers

**Comment by rocallahan** [comment]
32bit WINE isn't the problem. You'll need to debug this in rr. I partially debugged this earlier and discovered that under rr a `read` system call is returning `EFAULT`, which it shouldn't.  It's probably something to do with scratch memory. You'll want to use `rr dump` to identify the `read` call which is returning `-EFAULT` in $rax, and debug rr itself to figure out what address it's actually passing in $rcx when we perform that `read` call. It's probably a bug related to how rr redirects `read` output buffers to scratch memory.

**Comment by synlestidae** [comment]
Okay I will investigate this, should be interesting. Before I read your reply, Wine successfully compiled and the error on the same program is 

    [FATAL /u/students/mate/rr/rr/src/record_syscall.cc:2638:rec_process_syscall_arch() errno: 0 'Success'] 
 (task 9859 (rec:9859) at time 5500)
    ->  Assertion `t->regs().syscall_result_signed() == -syscall_state.expect_errno' failed to hold. Expected EINVAL for 'ioctl' but got result -25; Unknown ioctl(0x82307201): type:0x72 nr:0x1 dir:0x2 size:560 addr:0x122000

Just put that here for your info. I'll focus on debugging what you have outlined. should a good starting point to get familiar with the debugging work I'll be doing for my project.

**Comment by rocallahan** [comment]
Looks like we'll need to add support for that ioctl too. I have no idea what it is; running `strace -f` on the program and then grepping for 'ioctl' might show you ... or searching the Internet ...
