### ISSUE TITLE
Consider supporting XDG Base Directory or allowing for a definable directory.

### ISSUE THREAD

**Issue by Earnestly** [mozilla/rr#1455]
In the struggle against dotfiles, a UNIXv2  [bug](https://plus.google.com/+RobPikeTheHuman/posts/R58WgWwN9jp), there have been a few efforts involving creating `LD_PRELOAD` hacks such as [libetc](http://ordiluc.net/fs/libetc/) and even FUSE filesystems such as [rewritefs](https://github.com/sloonz/rewritefs) to combat the increasing complexity of `HOME`.

The [XDG Base Directory Specification](http://standards.freedesktop.org/basedir-spec/basedir-spec-latest.html) was created by Waldo Bastian to address these issues on the Linux desktop much like OSX and Windows have their own schemes such as `Application Data` and `Local Application Data` which has existed since Windows 98.  OSX provides `HOME/Library` (barring `/Library` and `/System/Library` which are OSX-only).

Although some people think that only a few support XDG Basedir or that only desktop applications are meant to make use of it, many low level projects such as `git`, `util-linux` and `jack` have since migrated to it along with most major software from `blender` to `chromium`.

Other older software also provides mechanisms which allows one to specify an alternative directory such as `gdb -nh -x "${XDG_CONFIG_HOME:-$HOME/.config}"/gdb/init` or environment variables such as `ELINKS_CONFDIR`, `SLRNHOME`, `GNUPGHOME`, etc.

It would then be very nice if `rr` could support XDG Basedir (along with keeping legacy `HOME/.rr` behaviour) or allowing users to specify alternative directories.

Thanks

**Comment by rocallahan** [comment]
I'm not really sure how to apply that specification to rr.

**Comment by rocallahan** [comment]
You can override the base directory by setting `_RR_TRACE_DIR`.

**Comment by Earnestly** [comment]
Yes, `_RR_TRACE_DIR` is perfectly fine too.  The ultimate result of this specification is really to give users control over where configuration and data is stored in their `HOME` on Linux systems.

Environment variables which expose this kind of control is fine as well, so long as they're documented somewhere.

This is another issue, but I can't seen to find any documentation for this setting, the `doc/rr.html` doesn't appear to work on my system.  The only other place which mentions it seems to be in `src/test/util.sh` and `src/TraceStream.cc`.

Thanks anyway, this environment will do well for my purposes. :-)

**Comment by Yamakaky** [comment]
A default directory following XDG specification would be better!

**Comment by rocallahan** [comment]
I'd accept a PR for that as long as the default directory for most users remains `$HOME/.rr`.

**Comment by nickolay** [comment]
There was a followup https://github.com/mozilla/rr/commit/02e7d41e96e2203eff2ea126b3875d35846510b9 , but even after that the default changed from `~/.rr` to `$XDG_DATA_HOME/rr`, so I updated the wiki: https://github.com/mozilla/rr/wiki/Usage/_compare/dd3b33ffa9db21b3313a2edf9cfa159cbff75cb9...96f9297ebb16ef3d14d855698d3630a1294c3e82
