### ISSUE TITLE
rr fails when trying to debug Mozilla web-platform-tests test suite

### ISSUE THREAD

**Issue by bzbarsky** [mozilla/rr#1458]
STEPS TO REPRODUCE:
1. git clone rr revision 069833f22a58e792742429f3cf5a64b2621f009b
2. Compile it, per the instructions at https://github.com/mozilla/rr/wiki/Building-And-Installing (on a 64-bit Ubuntu desktop system, in case that matters)
3. hg clone -r 6f35b7d9755a http://hg.mozilla.org/integration/mozilla-inbound
4. Build Firefox.
5. In the Firefox tree, execute:

    mach web-platform-tests --debugger=/path/to/rr html/browsers/history/the-history-interface

EXPECTED RESULTS: Tasty debugging

ACTUAL RESULTS: 

    [FATAL /home/bzbarsky/mozilla/rr/rr/src/record_syscall.cc:2655:rec_process_syscall_arch() errno: 0 'Success']
     (task 30925 (rec:30925) at time 1523)
     ->  Assertion `t->regs().syscall_result_signed() == -syscall_state.expect_errno' failed to hold. Expected ENOSYS for 'unshare' but got result 0; execution of syscall unsupported by rr
    [FATAL /home/bzbarsky/mozilla/rr/rr/src/log.cc:16:emergency_debug() errno: 0 'Success']
     -> (session doesn't look interactive, aborting emergency debugging)

Before that I also got:

    rr: Warning: Your CPU frequency governor is 'ondemand'.  rr strongly
        recommends that you use the 'performance' governor.  Not using the
        'performance' governor can cause rr to be at least 2x slower
        on laptops.
    
        On Fedora-based systems, you can enable the 'performance' governor
        by running the following commands:
    
        $ sudo yum install kernel-tools
        $ sudo cpupower frequency-set -g performance

but I'm not sure whether it's relevant here.

**Comment by cgjones** [comment]
> ``` ->  Assertion `t->regs().syscall_result_signed() == -syscall_state.expect_errno' failed to hold. Expected ENOSYS for 'unshare' but got result 0; execution of syscall unsupported by rr```

D'oh, the `unshare()` syscall isn't implemented.  Looks like gecko sandboxing code uses it.  Disabling sandboxing might be a temporary workaround, if that's possible.

>  ```rr: Warning: Your CPU frequency governor is 'ondemand'.  rr strongly```
> but I'm not sure whether it's relevant here.

It's not relevant to the `unshare()` bug you hit here, but if you get into serious rr'ing you'll want to change your CPU governor.  Can make a 2x difference in performance.

**Comment by rocallahan** [comment]
Yeah, we need to support the sandbox. I'm not sure how hard that's going to be. Maybe not too hard, maybe really hard.

**Comment by rocallahan** [comment]
I'll look into it shortly...

**Comment by benturner** [comment]
I rebuilt with this:

ac_add_options --disable-sandbox
ac_add_options --disable-content-sandbox

That seems to have been enough to get rr working again.
