### ISSUE TITLE
Assertion `false' failed to hold. Unhandled syscall <unknown-syscall-317>(317) returned -14

### ISSUE THREAD

**Issue by MatsPalmgren** [mozilla/rr#1459]
rr "/OBJDIR/$PWD/dist/bin"/firefox  -profile /tmp/qasfdfds 
rr: Saving the execution of `/OBJDIR//md1/src/opt2/dist/bin/firefox' to trace directory `/home/mats/.rr/firefox-0'.
Printing register file:
rax:fffffffffffffff2
rbx:2aaaaab013a0
rcx:ffffffffffffffff
rdx:0
rsi:1
rdi:1
rbp:1
rsp:7fffffffa6d8
r8:3
r9:2aaab1bb1768
r10:0
r11:206
r12:7fffffffe0b8
r13:7fffffffe0d8
r14:2aaab1c99e14
r15:0
rip:2aaaabe0b859
eflags:206
cs:33
ss:2b
ds:0
es:0
fs:0
gs:0
orig_rax:13d

[FATAL /home/roc/rr/rr/src/record_syscall.cc:2420:check_syscall_rejected() errno: 0 'Success'] 
 (task 9360 (rec:9360) at time 1474)
 ->  Assertion `false' failed to hold. Unhandled syscall <unknown-syscall-317>(317) returned -14
Attach to the rr debug server with this command:
  target remote :9360
^C^C[FATAL /home/roc/rr/rr/src/RecordCommand.cc:143:handle_termsig() errno: 4 'Interrupted system call'] 
 -> Received termsig while an earlier one was pending.  We're probably wedged.
Aborted
#

I installed the prebuilt .deb package from here:
http://rr-project.org/releases/rr-3.0.0-Linux-$(uname -m).deb

**Comment by khuey** [comment]
This is fixed in trunk.

**Comment by MatsPalmgren** [comment]
I tried to build from source but it failed:
> make -j8
[  0%] [  0%] Scanning dependencies of target test_lib
Scanning dependencies of target Generated
[  0%] [  0%] Scanning dependencies of target cpuid
Generating 32/cpuid_loop.S
Generating 32/rrutil.h
Scanning dependencies of target rrpreload
cp: cannot create regular file ‘/mnt2/rr/obj/32/cpuid_loop.S’: No such file or directory
make[2]: *** [32/cpuid_loop.S] Error 1

**Comment by rocallahan** [comment]
Sorry, that's a race in the build system. Just retry.

**Comment by MatsPalmgren** [comment]
That worked, thanks!
And it seems to be able to replay my Firefox crash as well.  Nice!
