### ISSUE TITLE
Implement gdb query "qGetTLSAddr"

### ISSUE THREAD

**Issue by cgjones** [mozilla/rr#146]
I'm debugging an issue right now where that query is needed to resolve a symbol.  (Why, I dunno, since the symbol isn't TLS, but oh well.)  Unfortunately this looks quite tricky to implement.  It appears that valgrind punted it.

**Comment by tromey** [comment]
FWIW I'm debugging an implementation of this.

**Comment by rocallahan** [comment]
Excellent!

**Comment by tromey** [comment]
I  have it working, but I'm having some trouble getting the test suite to work properly.  I'll ask on irc tomorrow or so.

There's one issue I want to raise as well.  This work relies on the `proc_service.h` header.  However, glibc doesn't install this header.  (You can follow the [glibc bug](https://sourceware.org/bugzilla/show_bug.cgi?id=20311) I filed.)

On my current branch I've just copied this header into the rr source tree.  This is what gdb does as well (with extra hacks, haha.)  But, maybe that's not really what you want, considering that the file has the LGPL on it.

Another option might be to duplicate the needed stuff.  There are a few function types and an enum.

**Comment by rocallahan** [comment]
What does it mean to honor the LGPL for this file, if (say) someone wanted to ship rr without honoring the LGPL terms for all of rr?

**Comment by rocallahan** [comment]
If we're just using this file as the interface to a dynamically linked glibc library, that we're not shipping, then they wouldn't have to do anything to comply with the LGPL? Except they'd have to make available the source for that one file, I suppose.

**Comment by tromey** [comment]
It seems like a reasonable interpretation to me.
