### ISSUE TITLE
reverse-continue after resizing terminal crashes rr with Assertion `t->regs().ip() - callregs.ip() == syscall_instruction_length(t->arch())' failed to hold. Should have advanced ip by one syscall_insn

### ISSUE THREAD

**Issue by dbaron** [mozilla/rr#1472]
I hit a fatal assertion while debugging in rr, and @khuey helped me debug it.  It turns out to be trivially reproducable:
1. rr replay
2. cont
3. Press Ctrl+C to break
4. resize the containing terminal (I'm using gnome-terminal)
5. reverse-continue

(I hadn't even realized I'd resized the terminal before hitting it, but @khuey found that it was handling a SIGWINCH.)

Possibly the same as #1450, but @khuey says I should file as a separate issue.

**Comment by dbaron** [comment]
(And I have the output of both the rr session and the gdb-of-rr session if you need them, but I suspect not.  @khuey observed that advance_syscall doesn't skip SIGWINCH.)

**Comment by dbaron** [comment]
Oh, and I'm using 3c6f87c6.

**Comment by rocallahan** [comment]
Pretty easy fix. However, when a `SIGCHLD` or `SIGWINCH` arrives in AutoRemoteSyscalls during recording, we actually have a (existing) problem: these signals should be eventually delivered to the tracee, not just thrown away.
