### ISSUE TITLE
Changing syscalls.py rebuilds everything, including the tests

### ISSUE THREAD

**Issue by khuey** [mozilla/rr#1478]
Haven't investigated yet but that seems unnecessary.  Filing so I don't forget.

**Comment by froydnj** [comment]
Ah, probably a side effect of @luser's changes in #1469.  The tests likely don't need to depend on the generated files.

**Comment by rocallahan** [comment]
We do build from syscalls.py #defines for all the syscall numbers (`RR_`) that can be used by tests. This is to deal with the problem that tests for new-ish syscalls sometimes need to call syscalls whose numbers aren't defined in glibc headers.

**Comment by khuey** [comment]
Ok, this is invalid then.
