### ISSUE TITLE
http-only download for deb files

### ISSUE THREAD

**Issue by dturner-tw** [mozilla/rr#1487]
http://rr-project.org/ suggests 
cd /tmp
wget http://rr-project.org/releases/rr-3.2.0-Linux-$(uname -m).deb
sudo dpkg -i rr-3.2.0-Linux-$(uname -m).deb

This should be a https url, to prevent modification of the packages during download.

**Comment by rocallahan** [comment]
Thanks, you're quite right. Fixed.

I suppose we need to figure out how to make rr-project.org use TLS, but that's apparently not possible while it's hosted on Github Pages :-(.
