### ISSUE TITLE
unsupported syscall mknod

### ISSUE THREAD

**Issue by dturner-tw** [mozilla/rr#1488]
[FATAL /home/roc/rr/rr/src/record_syscall.cc:2879:rec_process_syscall_arch() errno: 0 'Success'] 
 (task 27298 (rec:27298) at time 7020)
 ->  Assertion `t->regs().syscall_result_signed() == -syscall_state.expect_errno' failed to hold. Expected ENOSYS for 'mknod' but got result 0; execution of syscall unsupported by rr
[FATAL /home/roc/rr/rr/src/log.cc:16:emergency_debug() errno: 0 'Success'] 
 -> (session doesn't look interactive, aborting emergency debugging)
Aborted (core dumped)

(attempting to run rr record on a very, very hacked version of git that is totally broken, fwiw).

Ubuntu, rr-3.2.0-Linux-x86_64.

**Comment by rocallahan** [comment]
Trivial to add; writing the test would be the hardest part. Feel like sending a PR? :-)

**Comment by dturner-tw** [comment]
https://github.com/mozilla/rr/pull/1489

**Comment by rocallahan** [comment]
Thanks. Merged that.
