### ISSUE TITLE
ctrl-c doesn't interrupt a reverse-continue in replay

### ISSUE THREAD

**Issue by pm215** [mozilla/rr#1491]
Consider this little test program:
```
#include <stdio.h>

void foo(void) {
}

void bar(void) {
}

void busyloop(void) {
    int i;
    for (i = 0; i < 100000000000ULL; i++) {
    }
}

int main(void) {
    printf("In main\n");
    foo();
    busyloop();
    bar();
    printf("Out of main\n");
    return 0;
}
```

If you record it, and then in the replay do:
```
break foo
break bar
cont      # will stop in foo
cont
```
and then immediately hit ^C, execution will be interrupted somewhere in busyloop().
If you then do
```
cont    # will stop in bar
rc
```
and then immediately hit ^C again, execution will not terminate until you get back to foo(), indicating that we aren't allowing ^C to interrupt a reverse-execute.

This is particularly unfortunate if you did a reverse-continue with a conditional breakpoint or watchpoint that gets hit-but-fails-condition a lot, because the reverse-continue might take an extremely long time to complete, and you basically have no choice but to abandon the whole debug session...

**Comment by hotsphink** [comment]
Yep, I just hit this too, in a similar scenario as that described in the last sentence. I had a hardware watchpoint set, which seemed to make reverse-continue very very slow, and I ended up having to abandon several debug sessions. (Which is far less of a big deal than it is without rr, of course, but still.)
