### ISSUE TITLE
unable to recover when calling a function via gdb that crashes

### ISSUE THREAD

**Issue by hotsphink** [mozilla/rr#1496]
I replayed a recording under gdb, stopped at a breakpoint, and called an inferior function. It crashed with a SIGSEGV. Continuing just repeated the crash. Attempting to start over by re-running failed with:

rr: /home/sfink/src/rr/src/GdbServer.cc:657: GdbRequest GdbServer::divert(ReplaySession&, pid_t): Assertion `diversion_refcount == 0' failed.
Remote connection closed

**Comment by hotsphink** [comment]
(gdb) run
 Starting program: /home/sfink/src/MI-GC/obj-spider/js/src/shell/js 
 
 Breakpoint 3, js::WeakMapBase::trace (this=0x2aaaaaf04380, tracer=0x2aaaaaf48230)
 at /home/sfink/src/MI-GC/js/src/jsweakmap.cpp:51
 (gdb) p key
 $5 = {<js::BarrieredBase<JSObject*>> = {<js::BarrieredBaseMixins<JSObject*>> = {<No data fields>}, value = 0x7fffffffc530}, <No data fields>}
 (gdb) p key.value
 $6 = (JSObject *) 0x7fffffffc530
 (gdb) p key.value->dump()
 
 Program received signal SIGSEGV, Segmentation fault.
 JSObject::dump (this=0x7fffffffc530) at /home/sfink/src/MI-GC/js/src/jsobj.h:121
 The program being debugged was signaled while in a function called from GDB.
 GDB remains in the frame where the signal was received.
 To change this behavior use "set unwindonsignal on".
 Evaluation of the expression containing the function
 (JSObject::dump()) will be abandoned.
 When the function is done executing, GDB will silently stop.
 (gdb) rn
 (gdb) rn
 (gdb) rn
 (gdb) rn
 (gdb) rn
 (gdb) up
 #1  <function called from gdb>
 (gdb) 
 #2  js::WeakMap<js::PreBarriered<JSObject*>, js::RelocatablePtr<JS::Value>, js::DefaultHasher<js::PreBarriered<JSObject*> > >::markEphemeronEntries (
 this=0x2aaaaaf04380, trc=0x2aaaaaf48230)
 at /home/sfink/src/MI-GC/js/src/jsweakmap.h:188
 (gdb) c
 Continuing.
 
 Program received signal SIGSEGV, Segmentation fault.
 JSObject::dump (this=0x7fffffffc530) at /home/sfink/src/MI-GC/js/src/jsobj.h:121
 (gdb) rn
 (gdb) rn
 (gdb) c
 Continuing.
 
 Program received signal SIGSEGV, Segmentation fault.
 JSObject::dump (this=0x7fffffffc530) at /home/sfink/src/MI-GC/js/src/jsobj.h:121
 (gdb) c
 Continuing.
 
 Program received signal SIGSEGV, Segmentation fault.
 JSObject::dump (this=0x7fffffffc530) at /home/sfink/src/MI-GC/js/src/jsobj.h:121
 (gdb) run
 The program being debugged has been started already.
 Start it from the beginning? (y or n) y
 
 Starting program: /home/sfink/src/MI-GC/obj-spider/js/src/shell/js 
 rr: /home/sfink/src/rr/src/GdbServer.cc:657: GdbRequest GdbServer::divert(ReplaySession&, pid_t): Assertion `diversion_refcount == 0' failed.
 Remote connection closed
 (gdb)

**Comment by rocallahan** [comment]
I think the best thing here is to use `set unwindonsignal on` --- perhaps in the default gdb commands provided by rr. When that's off, we can try to do something non-crashy.
