### ISSUE TITLE
Build fails on aarch64

### ISSUE THREAD

**Issue by ikitayama** [mozilla/rr#1498]
Tried to build rr at HEAD on aarch64 Fedora 22 \:

[itaru.kitayama@localhost rr]$ make
[  0%] Generating AssemblyTemplates.generated
[  0%] Generating CheckSyscallNumbers.generated
[  0%] Generating IsAlwaysEmulatedSyscall.generated
[  0%] Generating SyscallDefsTable.generated
[  0%] Generating SyscallEnumsX64.generated
[  0%] Generating SyscallEnumsX86.generated
[  1%] Generating SyscallEnumsForTestsX64.generated
[  1%] Generating SyscallEnumsForTestsX86.generated
[  1%] Generating SyscallHelperFunctions.generated
[  1%] Generating SyscallnameArch.generated
[  1%] Generating SyscallRecordCase.generated
[  1%] Built target Generated
Scanning dependencies of target 64bit_child
[  1%] Building C object CMakeFiles/64bit_child.dir/src/test/64bit_child.c.o
In file included from /home/itaru.kitayama/rr/src/test/64bit_child.c:3:0:
/home/itaru.kitayama/rr/src/test/rrutil.h:75:23: fatal error: x86intrin.h: No such file or directory
compilation terminated.
CMakeFiles/64bit_child.dir/build.make:54: recipe for target 'CMakeFiles/64bit_child.dir/src/test/64bit_child.c.o' failed
make[2]: *** [CMakeFiles/64bit_child.dir/src/test/64bit_child.c.o] Error 1
CMakeFiles/Makefile2:60: recipe for target 'CMakeFiles/64bit_child.dir/all' failed
make[1]: *** [CMakeFiles/64bit_child.dir/all] Error 2
Makefile:146: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by khuey** [comment]
rr is not yet supported on ARM architecture machines. issue #1373 covers 32 bit ARM support

**Comment by ikitayama** [comment]
Thank you @khuey.
