### ISSUE TITLE
Finer granularity 'when'

### ISSUE THREAD

**Issue by hotsphink** [mozilla/rr#1499]
Warning: I don't really understand what rr is doing internally. But I've noticed that whatever counter 'when' is using, it's pretty coarse granularity. I'd like to have a fine-grained version of it that would allow returning to an arbitrary point in the execution -- like checkpoint does, but I want a linear sequence that I can probe at arbitrary points where I didn't have control previously.

Perhaps this is just a workaround for the current slowness of reverse-continue, and perhaps if that were magically fixed then I wouldn't need this. But here's what I'm thinking:

Say I am looking for the last time a particular memory location was changed, or perhaps the condition is something complex that requires running inferior commands. With a fine-granularity 'when', I could do my own binary search through the execution timeline, re-evaluating my condition to test each point. If I could additionally map checkpoints to this fine-granularity timer, I could use those to speed up the replay up to a probe point. (Unless something like that is already happening internally?)

**Comment by rocallahan** [comment]
Are you using `watch -l`? I think I'd rather fix whatever issues you're having with reverse-continue if at all possible. How about we focus on that?

**Comment by hotsphink** [comment]
The basic thing here is done, in the form of when-ticks. I use it heavily for charting out sequences of interesting states. There's certainly more to do in terms of running until a particular tick or setting conditional breakpoints using the tick count, but for the purposes of this bug, I'd say it's done.
