### ISSUE TITLE
Assertion failure: current->trace_reader().time() == mark.ptr->key.trace_time

### ISSUE THREAD

**Issue by hotsphink** [mozilla/rr#1503]
I have an rr recording of a mochitest-1 run. I run it with rr replay -p and it goes to a segmentation fault. Then when I try to 'rc', I end up getting the error message below. 'rsi' does the same thing.

[FATAL /home/sfink/src/rr/src/ReplayTimeline.cc:408:replay_step_to_mark() errno: 5 'Input/output error'] 
 (task 23375 (rec:13018) at time 2024204)
 ->  Assertion `current->trace_reader().time() == mark.ptr->key.trace_time' failed to hold. 
Launch gdb with
  gdb /home/sfink/src/mozilla/obj-x86_64-unknown-linux-gnu/dist/bin/firefox
and attach to the rr debug server with:
  target remote :23375

**Comment by hotsphink** [comment]
Full log of my replay session is at http://people.mozilla.org/~sfink/data/replay-issue1503.log

**Comment by hotsphink** [comment]
This was using 245925ce3934fcd76b04dea9a365c1abdffbd4ba for both record and replay.

**Comment by rocallahan** [comment]
I'll probably need access to the session to debug this. Find me in Whistler?

**Comment by hotsphink** [comment]
Sadly, I'm not at Whistler. Independent of this particular bug, I have a
great bug for rr (as in, rr would be really helpful), and it's not quite up
to the task. But this particular bug has not resurfaced. Most of my
problems are related to either rr not stopping at the event number I
request (eg issue 1504) or rr taking forever to do backwards execution
(mentioned in issue 1499, where I am guilty of not giving any additional
data, but it should really be a separate bug). I should be doing a better
job of recording the issues I am encountering, but I'm never entirely sure
what is *supposed* to work with respect to the 'run', 'checkpoint', and
'restart' commands. Can the gdb server supply help strings?

**Comment by rocallahan** [comment]
I think you have found some simple bugs here that I just need to fix --- I just haven't had time this week. Next week I should have time, and hopefully I'll fix them, and then we'll see where we're at.

**Comment by hotsphink** [comment]
Sorry, I didn't mean to imply otherwise. Everything is basically working,
it's just enough small things broken at the moment to mostly block me on
the current path. I could try different versions or something, but I have
enough clues at this point to make progress on my actual bug, even without
using rr.

**Comment by rocallahan** [comment]
If you still have working traces for the original issue you reported here, or you can reproduce it afresh, I'd like to remotely debug the issue. Otherwise I think we should probably close this.

**Comment by hotsphink** [comment]
rr has been working great for me for a long time now. Will file issues for anything new.
