### ISSUE TITLE
run NNNNN does not stop

### ISSUE THREAD

**Issue by hotsphink** [mozilla/rr#1504]
Again using the session recorded at http://people.mozilla.org/~sfink/data/replay-issue1503.log you can see that I tried to run up to a particular event. rr saw the event number, printed out a message saying it had reached it, but then continued running up until an eventual segmentation fault. In this example, I did 'run 2009035', and when I did 'when' at the seg fault it said 2024202.

This is with 245925ce3934fcd76b04dea9a365c1abdffbd4ba on a mochitest-1 run.

**Comment by hotsphink** [comment]
As a workaround, I can run to the seg fault, set a breakpoint that I know will fire at about the right  point (in fact, it was from a command list associated with that breakpoint that I got the 2009035 event number in the first place), then subtract a bit from the event number:

run
b js::gc::GCRuntime::beginMarkPhase
run 2009000

**Comment by hotsphink** [comment]
That doesn't always work either. I have a case now where neither run NNNN nor restart NNNN will stop the execution. I will record my current problems here, since it seems related; let me know if it would be better as a separate bug.

I ran with rr record -M. One output line is:

[rr 23315 1263182]*************************

I somewhat arbitrarily decided that I wanted to "break" at that event (it seemed far enough before the interesting badness). First I did rr replay -p <pid> and it stopped at dl_start. When I tried |run 1263182|, it first said that the script was already running and would I like to restart it. Now, I didn't actually care, but I would like to note that my mental model at this point is that I'd either like to continue to the given event, or just jump ahead to that event. I don't care about what's happened so far, and I don't care about the interval between now and my event number. Perhaps that's what 'restart' is for? I'm not sure.

Anyway, it ran to my event and printed out Ctrl-G followed by:

--------------------------------------------------
 ---> Reached target process 24015 at event 1263210.
--------------------------------------------------

and then did some gdb symbol loading goop, which seemed good. But it did not return control to me; it just continued running until it eventually hit the seg fault at the end of the trace.

So I said 'restart 1263182', and it told me «Running the default executable on the remote target failed; try "set remote exec-file"?»

I ran 'when', and it said «Cannot access memory at address 0x7276».

Oh! Also, when I do |run 1263182|, it says

Starting program: /home/sfink/src/mozilla/obj-x86_64-unknown-linux-gnu/dist/bin/firefox 1263182

which makes it look like it's interpreting my event number as a command-line argument. Which would explain the problem, except that it clearly *does* know that I am requesting an event because it tells me when it reaches it.

**Comment by hotsphink** [comment]
After the above "Cannot access memory at address 0x7276", if I do |run 1263182|, it successful reruns and hits the seg fault again, at which point I can do 'when', and it says 1319158.

Hm... I see debug logging stuff in the rr code. Might be nice to have a command to turn that on dynamically from the gdb shell.

I really should start digging into rr myself instead of just whining here, but I am trying hard not to be distracted from the actual problem I'm debugging right now.

Another thing I keep trying is to set a breakpoint on a function of interest, and setting up a command list for that breakpoint that prints out 'when' and creating a checkpoint. Then I try to run to the last checkpoint before the seg fault with |run c9|. That gives: 

    Starting program: /home/sfink/src/mozilla/obj-x86_64-unknown-linux-gnu/dist/bin/firefox c9
    Running the default executable on the remote target failed; try "set remote exec-file"?

'restart 9' at that point says the same thing. I tried doing a 'run 1' to kick things back live so I could try 'restart c9' (just to try!), and it of course started rerunning the whole trace again, and when I hit ctrl-c I got:

    C-c C-c
    
    [Thread 24015.24015] #1 stopped.
    [FATAL /home/sfink/src/rr/src/ReplayTimeline.cc:603:remove_breakpoint() errno: 0 'Success'] 
     (task 771 (rec:24015) at time 1120093)
     ->  Assertion `it != breakpoints.end()' failed to hold. 
    Launch gdb with
      gdb /home/sfink/src/mozilla/obj-x86_64-unknown-linux-gnu/dist/bin/firefox
    and attach to the rr debug server with:
      target remote :1024

**Comment by hotsphink** [comment]
For the record, my workaround right now is to attach gdb to the rr gdbserver process, set a breakpoint on the line that prints out the "Reached target process..." line, remember the task pointer, step into GdbServer::replay_one_step, and do

     p break_status.task = $65 # the task pointer saved previously
     p break_status.singlestep_complete = true

That'll interrupt a random thread, but that's ok. I go to a somewhat earlier event, set a breakpoint on the place I really wanted to stop, and continue.

**Comment by rocallahan** [comment]
This sounds like an interesting bug, but I haven't seen it myself. Can you reproduce it in a simpler way using one of the rr tests (for example)?

The change I just checked in to print more useful information when an invalid checkpoint number is requested might clarify things a bit.

**Comment by hotsphink** [comment]
I always get this behavior. I've gotten a little better at workarounds. I just updated to a2678cdc185e, and it's the same. And it's not just with checkpoints; normally I'm trying to go to a particular 'when' or -M output event number.

gdb 7.7.1-21.fc20

Anything I can do to help debug?

On a side note, I just tried running rr replay -p 5331  -g 7391064, and it ran the whole trace without stopping at all (even at the segfault at the end). Sadly, I was not capturing the output, so I'm not sure if it tried to stop as described above. If I scroll back as far as I can, I see a strange large stack dump, so maybe it did something?

**Comment by rocallahan** [comment]
If you're still having problems, I think it would be easiest if you can just give me ssh access to do some debugging.

**Comment by rocallahan** [comment]
OK, the "run NNNN" not stopping issue is the same as the "restart N" not stopping issue: they both use gdb's "run" command internally which always continues execution after restarting the program. I don't see any way to get gdb to tell the remote target to restart but *not* continue execution.
