### ISSUE TITLE
rr record -M output not usable for rr replay -p (ppid instead of pid?)

### ISSUE THREAD

**Issue by hotsphink** [mozilla/rr#1508]
I tried running with rr record -M, and I get some lines like:

    [rr 23315 1520198]Stopping ssltunnel
    [rr.1520208] Warning: task 23960 (process 23960) dying from fatal signal SIGTERM.
    [rr 23315 1520254]TEST-INFO | leakcheck | default process: leak threshold set at 0 bytes
    [rr 23315 1520258]TEST-INFO | leakcheck | plugin process: leak threshold set at 0 bytes

According to the help output:

    -M, --mark-stdio           mark stdio writes with [rr.<EVENT-NO>],
                               where EVENT-NO is the global trace time at
                               which the write occures.

which matches the 2nd line pasted above, but not the rest. But the rest seem to have a pid, so I tried replaying with «rr replay -p 23315», which failed. Perhaps 23315 is a tid, not a pid? No, rr ps shows that 23315 is the ppid of the process I care about:

    % rr ps | fgrep firefox
    24015	23315	/home/sfink/src/mozilla/obj-x86_64-unknown-linux-gnu/dist/bin/firefox http://mochi.test:8888/tests?autorun=1&closeWhenDone=1&consoleLevel=INFO&manifestFile=tests.json&dumpOutputDirectory=%2Ftmp -foreground -profile /tmp/tmpG6TdrV.mozrunner

So it seems like those [rr MMMMM NNNNNN] lines are giving the ppid instead of the pid?

**Comment by hotsphink** [comment]
Oh, hm. I misremembered what «rr replay -p 23315» did. Probably because it showed me that it was running /bin/bash instead of firefox. It appears that it *does* replay the whole process group, and it notices when it's passing by the requested event number (as above). But when it finally drops to gdb it's for the bash shell. So I really do want the pid, not the tgid.

**Comment by rocallahan** [comment]
I fixed the help text in d1f61357344e81307410526aba912ffbd00c6ca8 but I don't understand the rest of this issue.

> So I really do want the pid, not the tgid.

I don't understand this, since AFAIK "pid" means the same thing as "tgid", per `man 2 clone`:
> Since Linux 2.4, calls to getpid(2) return the TGID of the caller.

**Comment by hotsphink** [comment]
Hm, looks like I lost the comment I had been writing here.

I was wrong about tgid. I saw a "g" in there and assumed it was related to the process group. So ignore that.

My issue is that when recording a mach test run, I get lines like:

[rr 4163 1011058]++DOMWINDOW == 1 (0x2aaacc2a7c00) [pid = 4338] [serial = 1] [outer = (nil)]

Notice that the pid of the process producing that output is 4338, but the -M output is showing 4163. Pid 4163 is the main process being recorded. The first line of output is

[rr 4163 246077]/usr/bin/gmake -j1 -s install-tests

% rr ps | fgrep firefox
4338	4163	/home/sfink/src/mozilla/obj-x86_64-unknown-linux-gnu/dist/bin/firefox about:blank -foreground -profile /tmp/tmpfd9hXI.mozrunner
5331	4338	/home/sfink/src/mozilla/obj-x86_64-unknown-linux-gnu/dist/bin/firefox -no-remote -foreground -profile /tmp/tmpfd9hXI.mozrunner/chrome_debugger_profile -chrome chrome://browser/content/devtools/framework/toolbox-process-window.xul -purgecaches

If I blindly use the -M output and do rr replay -p 4163, then I end up in gdb replaying /bin/bash.

I *do* get one non-4163 line output:

% fgrep -v '[rr 4163' tests-4-4.log | fgrep '[rr'
[rr 4257 798464]From _tests: Kept 39072 existing; Added/updated 0; Removed 0 files and 0 directories.
[sfink@thinkfink]~/src/mozilla% rr ps | fgrep 4257
4257	4254	/home/sfink/src/mozilla/obj-x86_64-unknown-linux-gnu/_virtualenv/bin/python -m mozbuild.action.process_install_manifest --no-remove _tests _build_manifests/install/tests

and when I test this with a simple example (running a shell that runs a shell that echoes something), it does the right thing -- the pid reported is that of the inner process, not the outer. But when run rr record ./mach test ..., I always see the funky behavior.

**Comment by khuey** [comment]
Yeah, I've seen that too.  I'm not sure if mach is redirecting all of the I/O through itself or if rr is screwing up here somehow.

**Comment by hotsphink** [comment]
Oh! You're totally right. I bet mach grabs all of the output and relays it for paging and timestamps and stuff.

**Comment by khuey** [comment]
I suspect it does.  Rather unfortunate ... we could make mach display the real pid somewhere (perhaps only under rr).

**Comment by rocallahan** [comment]
I usually record by passing the `--debugger rr` option to mach, which avoids this problem.

We could extend rr to disable syscall buffering on stdout/stderr for any process, and then extend it with an option to echo the output from some specified process during replay, which would avoid this issue. The former would slow down recordings where the main process creates a pipe filter chain of child processes, since writes that the user never sees would still have syscall buffering disabled. So this might have to be enabled during recording via an option, which would make the feature less useful.

**Comment by hotsphink** [comment]
Ooh, that's a good idea, especially since it avoids recording dozens of processes I don't care about. Hopefully, it'll only launch one process under rr, so I can use the latest recording as usual.

mach probably ought to have something to just pass its output through. --log-no-times is related, but it probably shouldn't disable buffering entirely.

I'm fine with closing this issue now that I understand what's going on. Though it'd be nice if mach magically noticed it was being run under rr and spat out a helpful message or something.
