### ISSUE TITLE
replay fails mochitest on digitalocean at replay_syscall.cc:544:finish_anonymous_mmap() errno: 0 'Success'

### ISSUE THREAD

**Issue by bgirard** [mozilla/rr#1510]
STR:
1) Setup a digitalocean instance.
2) Clone https://github.com/bgirard/RROrangeHunter
3) Run ./bootstrap && ./run.sh

which will setup firefox and run the canvas mochitest under RR.

The machine can be accessed using 'ssh mozilla@45.55.146.114' but it only has binaries. Email me for the password. I have the replay save under ~/mozilla/rr-trace.

Sometimes when I re-run it I get a different error, others the replay works fine.

mozilla@mozgfx-rr-orange-hunter-1:~/mozilla$ cat /proc/cpuinfo
processor	: 0
vendor_id	: GenuineIntel
cpu family	: 6
model		: 62
model name	: Intel(R) Xeon(R) CPU E5-2630L v2 @ 2.40GHz
stepping	: 4
microcode	: 0x1
cpu MHz		: 2399.998
cache size	: 15360 KB
physical id	: 0
siblings	: 1
core id		: 0
cpu cores	: 1
apicid		: 0
initial apicid	: 0
fpu		: yes
fpu_exception	: yes
cpuid level	: 13
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon rep_good nopl eagerfpu pni pclmulqdq vmx ssse3 cx16 pcid sse4_1 sse4_2 x2apic popcnt tsc_deadline_timer aes xsave avx f16c rdrand hypervisor lahf_lm xsaveopt vnmi ept fsgsbase tsc_adjust smep erms
bogomips	: 4799.99
clflush size	: 64
cache_alignment	: 64
address sizes	: 40 bits physical, 48 bits virtual
power management:

**Comment by bgirard** [comment]
I resized the instance to a 2GB instance and now everything works fine with that replay. RR seems to no longer be incredibly flaky on digitaloceans.

I'm going to close this bug as invalid. We may want to re-open or file a new bug to better report when RR ran out of memory instead of having it hang/abort. I'd be useful for us to not have to provision massive and costly VPS so that we don't hit these silent error but it might not be worth looking at ATM.

**Comment by rocallahan** [comment]
We need plenty of memory because when debugging a replay we'll make a lot of checkpoints. Since this is done by fork()ing, the memory is mostly consumed gradually as the tracee dirties more pages, so there's no realistic way to handle OOM.

**Comment by rocallahan** [comment]
If we used separate VMs for recording vs replay, we could probably use lower-memory VMs for recording and port the traces to a high-memory VM for debugging. Once we have adequate trace portability implemented, of course.

**Comment by rocallahan** [comment]
To be a bit clearer: `rr record` and `rr replay -a` should have reasonably low overhead: 3MB per thread for syscallbuf and scratch, mainly, plus some fixed costs. `rr replay` is where things start getting expensive.

**Comment by bgirard** [comment]
We could get away with a much stricter definition of portability. The resized instance reports the same CPU info as above. It seems to just add a core, 1GB more of ram and more space.

But I imagine for these costs it's more efficient to just provision more instances. With chaos mode I bet just 1-3 instance would be enough to produce replays faster than we can fix them.
