### ISSUE TITLE
 Assertion `!bail_error || match' failed to hold. Fatal register mismatch (ticks/rec:7002682811/7002677459)

### ISSUE THREAD

**Issue by dholbert** [mozilla/rr#1513]
While trying to replay a trace, I hit this fatal rr assertion:

    [ERROR /home/roc/rr/rr/src/Registers.cc:292:maybe_print_reg_mismatch() errno: 0 'Success'] 
     -> rbx 0xffffffffffffffe0 != 0x2aaaac086d00 (replaying vs. recorded)
    [ERROR /home/roc/rr/rr/src/Registers.cc:292:maybe_print_reg_mismatch() errno: 0 'Success'] 
     -> rdx 0 != 0x2aab020de320 (replaying vs. recorded)
    [ERROR /home/roc/rr/rr/src/Registers.cc:292:maybe_print_reg_mismatch() errno: 0 'Success'] 
     -> rsi 0x2400 != 0x7424 (replaying vs. recorded)
    [ERROR /home/roc/rr/rr/src/Registers.cc:292:maybe_print_reg_mismatch() errno: 0 'Success'] 
     -> rdi 0x3 != 0x2aaad5ff8000 (replaying vs. recorded)
    [ERROR /home/roc/rr/rr/src/Registers.cc:292:maybe_print_reg_mismatch() errno: 0 'Success'] 
     -> rbp 0x2aaaaab04018 != 0xb (replaying vs. recorded)
    [ERROR /home/roc/rr/rr/src/Registers.cc:292:maybe_print_reg_mismatch() errno: 0 'Success'] 
     -> r9 0 != 0xfe800000 (replaying vs. recorded)
    [ERROR /home/roc/rr/rr/src/Registers.cc:292:maybe_print_reg_mismatch() errno: 0 'Success'] 
     -> r10 0 != 0x54b (replaying vs. recorded)
    [ERROR /home/roc/rr/rr/src/Registers.cc:292:maybe_print_reg_mismatch() errno: 0 'Success'] 
     -> r11 0x246 != 0x206 (replaying vs. recorded)
    [ERROR /home/roc/rr/rr/src/Registers.cc:292:maybe_print_reg_mismatch() errno: 0 'Success'] 
     -> r12 0x7ffffffcee87 != 0 (replaying vs. recorded)
    [ERROR /home/roc/rr/rr/src/Registers.cc:292:maybe_print_reg_mismatch() errno: 0 'Success'] 
     -> r13 0x1 != 0x2aaacbd1bbf0 (replaying vs. recorded)
    [ERROR /home/roc/rr/rr/src/Registers.cc:292:maybe_print_reg_mismatch() errno: 0 'Success'] 
     -> r14 0x2aaaf9c98c90 != 0 (replaying vs. recorded)
    [ERROR /home/roc/rr/rr/src/Registers.cc:292:maybe_print_reg_mismatch() errno: 0 'Success'] 
     -> r15 0x7ffffffcee18 != 0x7ffffffcea80 (replaying vs. recorded)
    [ERROR /home/roc/rr/rr/src/Registers.cc:292:maybe_print_reg_mismatch() errno: 0 'Success'] 
     -> rip 0x70000004 != 0x70000018 (replaying vs. recorded)
    [ERROR /home/roc/rr/rr/src/Registers.cc:292:maybe_print_reg_mismatch() errno: 0 'Success'] 
     -> eflags 0x244 != 0x204 (replaying vs. recorded)
    [ERROR /home/roc/rr/rr/src/Registers.cc:292:maybe_print_reg_mismatch() errno: 0 'Success'] 
     -> orig_rax 0x10 != 0xb (replaying vs. recorded)
    [FATAL /home/roc/rr/rr/src/Registers.cc:412:compare_register_files() errno: 0 'Success'] 
     (task 13406 (rec:4691) at time 249976)
     ->  Assertion `!bail_error || match' failed to hold. Fatal register mismatch (ticks/rec:7002682811/7002677459)
    Launch gdb with
      gdb /scratch/work/builds/mozilla-central/mozilla-central.11-08-17.14-31/obj/dist/bin/firefox
    and attach to the rr debug server with:
      target remote :13406

**Comment by dholbert** [comment]
I ran the `gdb` / `target remote` commands suggested at the end of the assertion-output, and I got this info out:

    (gdb) up
    #1  0x00002aaaaacd3a1a in ?? () from /usr/bin/../lib/librrpreload.so
    (gdb) down
    #0  0x0000000070000004 in ?? ()
    (gdb) info locals
    No symbol table info available.
    (gdb) list
    400     #endif
    401     #ifdef XP_WIN
    402       rv = NS_NewLocalFile(NS_ConvertUTF8toUTF16(exePath), false,
    403                            xreDirectory);
    404     #else
    405       rv = NS_NewNativeLocalFile(nsDependentCString(exePath), false,
    406                                  xreDirectory);
    407     #endif
    408
    409       return rv;
    (gdb)

I'm not sure if any of that is useful (particularly the source; I don't think (?) gdb is actually targeting execution in that file, though maybe that's where rr was currently replaying when things broke.

**Comment by khuey** [comment]
That assertion indicates a divergence during replay.  Is it reproducible on this trace?

**Comment by dholbert** [comment]
Yes. At least, I've hit it twice in a row (on the two times I've tried replaying this trace, which I recorded ~30min ago).

**Comment by dholbert** [comment]
(For my own reference, this trace is ~/.rr/firefox-15)

**Comment by khuey** [comment]
roc will likely be interested in looking at it.  But IIRC to preserve the trace, you need to not rebuild the copy of firefox you traced.

**Comment by dholbert** [comment]
Cool, I'll ping @rocallahan when he wakes up, and I'll make sure not to rebuild in the meantime.

**Comment by dholbert** [comment]
(I made a new recording and hit the same issue when trying to replay it, BTW. In both recordings, this happens within ~20 seconds of starting the replay. In this case, the assertion was:

    ->  Assertion `!bail_error || match' failed to hold. Fatal register mismatch (ticks/rec:2416089096/2416076522)

**Comment by dholbert** [comment]
This is on a Dell Precision T1600, with a 4-core "Intel(R) Xeon(R) CPU E31280 @ 3.50GHz".  OS is Ubuntu 15.04.  I'm using the rr .deb from rr-project.org. `rr --version` reports "rr version 3.2.0".

I have successfully used rr on this machine before, a few months back. (for remote debugging with tbsaunde, in bug 1128751; though in that case I think I may have been using a locally-built trunk version of rr.)

**Comment by dholbert** [comment]
(BTW: I did end up rebuilding (to hack around a startup crash so I can proceed with debugging something else), but I saved a copy of my objdir before rebuilding in case it's useful, and I made a new recording & still hit this same bug after the rebuild.  My new recording plays for a lot longer before it hits this, but it does still hit this.)

**Comment by dholbert** [comment]
(I ended up invalidating my recording here, so I'm going to close this at this point. If I hit this again, I'll reopen.)
