### ISSUE TITLE
Provide some way to "fence" reverse-continue operations

### ISSUE THREAD

**Issue by khuey** [mozilla/rr#1516]
Maybe have them stop at the previous checkpoint?

In general, if I have a long recording, and I break and reverse continue to see if my breakpoint is hit, I may not want to back up indefinitely.

**Comment by rocallahan** [comment]
You can press ctrl-C at any time to interrupt the reverse execution. Is that sufficient?

**Comment by khuey** [comment]
Maybe ... I've had enough bad experiences in the past interrupting gdb that I'm afraid to do that, but I will try.

**Comment by rocallahan** [comment]
I'd rather fix bugs in ctrl-C interruptions than address this another way.

**Comment by khuey** [comment]
Alright, fair enough.
