### ISSUE TITLE
add a reverse-until command

### ISSUE THREAD

**Issue by heycam** [mozilla/rr#1519]
It'd be nice to have a reverse-until command. Obviously I can add a breakpoint on the given line, reverse-continue, then delete the breakpoint, but it would be handy to have that wrapped up in a single command. (Maybe this should be filed on gdb instead?)

**Comment by rocallahan** [comment]
You can use
````
set exec-direction reverse
until ...
````
You might be able to wrap that up into a `reverse-until` command using a gdb macro.

**Comment by rocallahan** [comment]
If you come up with a good macro we can add it to `gdb_rr_macros`.
