### ISSUE TITLE
Fatal assertion in rr when a SIGPIPE received after rr -f <pid>

### ISSUE THREAD

**Issue by khuey** [mozilla/rr#1522]
Using -f starts gdb before the exec, so the internal breakpoint that gdb sets (which I believe is to catch dlopen() so it can load symbols) is destroyed when we exec.  Later when we trap into gdb for the SIGPIPE it tries to remove that breakpoint, and rr asserts in ReplayTimeline::remove_breakpoint because it doesn't exist (not in that iteration of the task's address space, anyways).

It's not clear to me how to fix this other than removing that assertion.

**Comment by khuey** [comment]
Actually, we could probably just relax the assertion in this case to ignore the exec count on the AddressSpace.

**Comment by rocallahan** [comment]
We could explicitly migrate breakpoints and watchpoints from one address space to the next.

Alternatively we could just prevent execution from moving forward past an exec once the debugger has attached. I don't think that works very well anyway. I recently added code to prevent moving backwards past an exec for similar reasons.

**Comment by khuey** [comment]
Migrating doesn't seem like a good idea.  What if stuff doesn't get loaded at the same place?

Preventing execution from moving forwards past exec sounds like the way to go.  It isn't particularly useful to cross that boundary.

**Comment by rocallahan** [comment]
Fixing #1518 would make this easier. The tricky thing is that we need to replay right up to the execve() but not actually do the real execve() call.
