### ISSUE TITLE
When interrupting reverse-continue with ctrl-c, fatal assertion in rr at AutoRemoteSyscalls.cc:122

### ISSUE THREAD

**Issue by khuey** [mozilla/rr#1523]
At https://github.com/mozilla/rr/blame/41c9529bb3d60a65b5e0abaff8a43d1736afac09/src/AutoRemoteSyscalls.cc#L122

the syscall hasn't been executed when we return to rr, so the assert fires.  Stack is 

    #0  0x00007f6bb123bac7 in accept4 (fd=44, addr=..., addr_len=0x7fff6cce889c, flags=-1)
        at ../sysdeps/unix/sysv/linux/accept4.c:33
    #1  0x000000000056cf26 in GdbConnection::await_debugger (this=0x25c0380, listen_fd=...)
        at /home/khuey/dev/rr-pristine/src/GdbConnection.cc:111
    #2  0x000000000056d1b0 in GdbConnection::await_client_connection (desired_port=7437, probe=GdbConnection::PROBE_PORT,
        tgid=21227, exe_image=..., features=..., client_params_fd=0x0) at /home/khuey/dev/rr-pristine/src/GdbConnection.cc:146
    #3  0x0000000000585b6d in GdbServer::emergency_debug (t=0x70c3660) at /home/khuey/dev/rr-pristine/src/GdbServer.cc:1117
    #4  0x00000000005a069f in emergency_debug (t=0x70c3660) at /home/khuey/dev/rr-pristine/src/log.cc:27
    #5  0x00000000005a0762 in EmergencyDebugOstream::~EmergencyDebugOstream (this=0x7fff6cce9dd0, __in_chrg=<optimized out>)
        at /home/khuey/dev/rr-pristine/src/log.cc:34
    #6  0x000000000054b63a in AutoRemoteSyscalls::syscall_helper (this=0x7fff6ccea000, wait=AutoRemoteSyscalls::WAIT,
        syscallno=273, callregs=...) at /home/khuey/dev/rr-pristine/src/AutoRemoteSyscalls.cc:122
    #7  0x0000000000546f1d in AutoRemoteSyscalls::syscall_helper<3> (this=0x7fff6ccea000, syscallno=273, callregs=...)
        at /home/khuey/dev/rr-pristine/src/AutoRemoteSyscalls.h:204
    #8  0x00000000005442c5 in AutoRemoteSyscalls::syscall_helper<2, unsigned long> (this=0x7fff6ccea000, syscallno=273,
        callregs=..., arg=24) at /home/khuey/dev/rr-pristine/src/AutoRemoteSyscalls.h:197
    #9  0x0000000000540445 in AutoRemoteSyscalls::syscall_helper<1, remote_ptr<void>, unsigned long> (this=0x7fff6ccea000,
        syscallno=273, callregs=..., arg=...) at /home/khuey/dev/rr-pristine/src/AutoRemoteSyscalls.h:197
    #10 0x000000000053bca4 in AutoRemoteSyscalls::syscall<remote_ptr<void>, unsigned long> (this=0x7fff6ccea000, syscallno=273)
        at /home/khuey/dev/rr-pristine/src/AutoRemoteSyscalls.h:141
    #11 0x0000000000635605 in Task::copy_state (this=0x70c3660, state=...) at /home/khuey/dev/rr-pristine/src/task.cc:2420
    #12 0x000000000061e813 in Session::finish_initializing (this=0x47e79f0) at /home/khuey/dev/rr-pristine/src/Session.cc:329
    #13 0x00000000005e9c6c in ReplaySession::clone (this=0x47e79f0) at /home/khuey/dev/rr-pristine/src/ReplaySession.cc:88
    #14 0x0000000000601f2a in ReplayTimeline::seek_to_before_key (this=0x7fff6cceb278, key=...)
        at /home/khuey/dev/rr-pristine/src/ReplayTimeline.cc:315
    #15 0x0000000000605aa4 in ReplayTimeline::reverse_continue(std::function<bool ()>) (this=0x7fff6cceb278,
        interrupt_check=...) at /home/khuey/dev/rr-pristine/src/ReplayTimeline.cc:845
    #16 0x00000000006085fb in ReplayTimeline::replay_step(RunCommand, RunDirection, unsigned int, std::function<bool ()>) (
        this=0x7fff6cceb278, command=RUN_CONTINUE, direction=RUN_BACKWARD, stop_at_time=0, interrupt_check=...)
        at /home/khuey/dev/rr-pristine/src/ReplayTimeline.cc:1227
    #17 0x0000000000584646 in GdbServer::debug_one_step (this=0x7fff6cceb250, last_direction=0x7fff6cceb014)
        at /home/khuey/dev/rr-pristine/src/GdbServer.cc:857
    #18 0x00000000005858ca in GdbServer::serve_replay (this=0x7fff6cceb250, flags=...)
        at /home/khuey/dev/rr-pristine/src/GdbServer.cc:1085
    #19 0x00000000005e83f8 in replay (trace_dir=..., flags=...) at /home/khuey/dev/rr-pristine/src/ReplayCommand.cc:369
    #20 0x00000000005e8b9d in ReplayCommand::run (this=0x8f46d0 <ReplayCommand::singleton>, args=...)
        at /home/khuey/dev/rr-pristine/src/ReplayCommand.cc:457
    #21 0x00000000005a22d2 in main (argc=6, argv=0x7fff6cceb888) at /home/khuey/dev/rr-pristine/src/main.cc:258

**Comment by rocallahan** [comment]
Do you have any steps to reproduce?

**Comment by khuey** [comment]
Hit Ctrl-C at exactly the wrong time during a replay?  Not very helpful, I know.

**Comment by rocallahan** [comment]
I've tried that :-)

**Comment by rocallahan** [comment]
I might have fixed this with https://github.com/mozilla/rr/commit/d352b499ec399b35d668569def44923c15ca09d6.
