### ISSUE TITLE
Process exhaustion

### ISSUE THREAD

**Issue by hotsphink** [mozilla/rr#1524]
Sometimes while replaying, it hangs and everything on my system starts failing to fork any new processes. It was hard to debug what was happening when I wasn't allowed to fork. I finally had the brilliant idea to log in as root (duh!). It's a simple case of nprocs exhaustion -- my nproc limit is 1024, and I just had too many threads.

(Helpful note to anyone who runs across this same issue: I un-wedged myself without killing off the replay by running as root: «ps aux  | egrep '^sfink' | perl -lane 'print [1]' | xargs -n 1 prlimit -u4096 -p». That will bump the limit for all process owned by 'sfink' to 4096.)

I wonder if part of the problem is that rr is leaving behind processes? When I run with rr replay -V, I get a *lot* of messages like:

[WARN ~Task() errno: 3 'No such process'] 10860 is unstable; not blocking on its termination

Then again, I don't see any zombie processes in my ps output. You can see the output of ps ax -L at http://people.mozilla.org/~sfink/data/psax-L.txt or to better see what was started by rr, there's ps axf output at http://people.mozilla.org/~sfink/data/fullpsf.txt . Oddly, it seems to show a whole bunch of "python2.7 ./mach test ..." processes parented to pid 1 instead of rr or whatever? Those *are* from rr; lsof shows /home/sfink/.rr/mach-34/mmap_26_hardlink_librrpreload.so loaded in, as well as lots of other rr goop.

**Comment by rocallahan** [comment]
It's certainly possible to have processes that are under rr's control and not leaked but owned by pid 1. This happens whenever a tracee process exits while it has children that should not exit. And that can happen without any explicit tracee activity, e.g. when we fork process A1 to create a checkpoint in process A2, and then decide to drop A1 and resume A2, A1 will exit and A2 will be owned by pid 1. rr is still its ptracer parent of course.

I think maybe your limit of 1024 is just too low. In Fedora 21 and up it's set to 4096 (I'm on Fedora 22). See https://bugzilla.redhat.com/show_bug.cgi?id=432903#c25. I'd suggest just changing your limit to 4096 and see if you still have problems.

**Comment by hotsphink** [comment]
Yeah, the thing about unowned processes was really just a side observation. But you're right, from reading that bug it seems like 1024 is too slow for browsers these days. I bumped it to 4k and will reopen if I run into problems again.
