### ISSUE TITLE
-V output contains crazy amount of "<pid> is unstable; not blocking on its termination" messages when reverse-continuing

### ISSUE THREAD

**Issue by hotsphink** [mozilla/rr#1525]
It's basically taking forever, spitting out an endless repeat of

[WARN ~Task() errno: 3 'No such process'] 23694 still has pending events.  From top down:
[INFO log()] SYSCALL_INTERRUPTION: read
[INFO log()] (none)
[WARN ~Task() errno: 3 'No such process'] 23694 is unstable; not blocking on its termination
[WARN ~Task() errno: 3 'No such process'] 23704 is unstable; not blocking on its termination
<71 more of the preceding line, with different pids>

The task thing with pending events is always different.

**Comment by rocallahan** [comment]
I don't think this is necessarily a bug. If you turn off or filter out those messages, does reverse-continue work OK?

**Comment by hotsphink** [comment]
Yes, it works, just with at least a 10x slowdown. (Which is fine for a verbose option, though I was hoping that -V would spit out output telling me why my reverse execution is so slow. I do have a hw watchpoint set, but it doesn't fire very often.) So it's certainly not a serious bug, per se, but it does mean that -V output is not useful for tracking things down since I can't afford to run with it. (And it may be the wrong tool in the first place, in which case there's nothing at all to be done here.)

**Comment by hotsphink** [comment]
Oh. I just reran without the -V. Make that at least a 100x slowdown. I didn't realize the watchpoint hit I was looking for was so close.

**Comment by rocallahan** [comment]
Are you on master?

Do you have a simple testcase I can use to reproduce?

**Comment by hotsphink** [comment]
I'm on rr master, yes: a2678cdc185ec

What is a good form of test case? Everything I do tends to run into lots of problems, but clearly my experience is far from universal, so I don't know what aspects of my environment need to be recreated. The specific thing I'm doing here is running firefox with some GC-related patches. My command line is

rr record -M ./mach test browser/devtools/debugger/test/browser_dbg_breakpoints-button-02.js browser/devtools/debugger/test/browser_dbg_breakpoints-condition-thrown-message.js browser/devtools/debugger/test/browser_dbg_breakpoints-contextmenu-add.js browser/devtools/debugger/test/browser_dbg_breakpoints-contextmenu.js browser/devtools/debugger/test/browser_dbg_breakpoints-disabled-reload.js browser/devtools/debugger/test/browser_dbg_breakpoints-editor.js browser/devtools/debugger/test/browser_dbg_breakpoints-eval.js browser/devtools/debugger/test/browser_dbg_breakpoints-highlight.js browser/devtools/debugger/test/browser_dbg_breakpoints-new-script.js browser/devtools/debugger/test/browser_dbg_breakpoints-other-tabs.js browser/devtools/debugger/test/browser_dbg_breakpoints-pane.js browser/devtools/debugger/test/browser_dbg_breakpoints-reload.js browser/devtools/debugger/test/browser_dbg_bug-896139.js browser/devtools/debugger/test/browser_dbg_chrome-create.js browser/devtools/debugger/test/browser_dbg_chrome-debugging.js

and then rr replay -V -p 4338

But of course, I get a seg fault as a result of my patches, and I'm reverse-continuing out of there. Maybe the best way to get a good test case would be for me to run a stock build pulled down from treeherder and find some random place to set a breakpoint? If that reproduces the slowdown, then maybe you would have some hope of seeing the same thing.

**Comment by rocallahan** [comment]
If you're still seeing this issue of reverse-continue being very slow, turn off -V and enabled logging in ReplayTimeline.cc instead.

**Comment by hotsphink** [comment]
Haven't seen this in ages.
