### ISSUE TITLE
rr replay -K fails when rr is in /tmp

### ISSUE THREAD

**Issue by glandium** [mozilla/rr#1529]
I had rr in `/tmp/rr`.

Reproduced with:
```
$ /tmp/rr/bin/rr record -K /tmp/rr/bin/simple
$ /tmp/rr/bin/rr replay -a -K
```

Which led to the following error message:
```
rr: /tmp/rr/src/AddressSpace.cc:1146: static void AddressSpace::check_segment_iterator(void*, Task*, const map_iterator_data*): Assertion `kr == vas->r || string::npos != kr.fsname.find("/dev/shm" "/rr-emufs") || string::npos != kr.fsname.find("/run/shm" "/rr-emufs")' failed.
```

The file this is happening with is `/tmp/rr/bin/librrpreload.so` (in `vas->r`), while `kr` points to `/tmp/rr-emptyfile-L4G0B6`.

It looks like the internal mmap tracker somehow doesn't handle very well the dynamic linker mappings when they are made to be backed by SOURCE_TRACE instead of SOURCE_FILE, which having the file in /tmp forces.

If I re-record the trace with rr in a non-`/tmp` directory, it works.

**Comment by rocallahan** [comment]
Fixed on master by some commit related to the refactoring I did of AddressSpace memory tracking.
