### ISSUE TITLE
fast_forward.cc:352:fast_forward_through_instruction() errno: 0 'Success'

### ISSUE THREAD

**Issue by glandium** [mozilla/rr#1530]
When reverse-continuing with a watchpoint, I get:

```
[FATAL /home/glandium/rr/src/fast_forward.cc:352:fast_forward_through_instruction() errno: 0 'Success'] 
 (task 20944 (rec:11298) at time 218405)
 ->  Assertion `!(debug_status & DS_WATCHPOINT_ANY)' failed to hold. 
```

The value of debug_status when that happens is `0x4001`.

**Comment by glandium** [comment]
With FastForward logging enabled:
```
(gdb) watch *(uint16*)0x60c32cbd
Hardware watchpoint 1: *(uint16*)0x60c32cbd
(gdb) reverse-continue 
Continuing.
[FastForward] x86-string fast-forward: 111 iterations required (ip==0x577c273c)
[FastForward] Set x86-string fast-forward watchpoint at 0x60c329b4
[FastForward] x86-string fast-forward: 30 iterations to go
[FastForward] x86-string fast-forward done; ip()==0x577c273c
[FastForward] x86-string fast-forward: 54 iterations required (ip==0x577c2797)
[FastForward] x86-string fast-forward: 54 iterations to go
[FastForward] x86-string fast-forward done; ip()==0x577c2797
[FastForward] x86-string fast-forward: 214 iterations required (ip==0x577c2815)
[FastForward] Set x86-string fast-forward watchpoint at 0x60c32ada
[FastForward] x86-string fast-forward: 118 iterations to go
[FastForward] x86-string fast-forward done; ip()==0x577c2815
[FastForward] x86-string fast-forward: 86 iterations required (ip==0x577c283b)
[FastForward] x86-string fast-forward: 86 iterations to go
[FastForward] x86-string fast-forward done; ip()==0x577c283b
[FastForward] x86-string fast-forward: 38 iterations required (ip==0x577c2891)
[FastForward] Set x86-string fast-forward watchpoint at 0x60c32bcc
[FastForward] x86-string fast-forward: 32 iterations to go
[FastForward] x86-string fast-forward done; ip()==0x577c2891
[FastForward] x86-string fast-forward: 18 iterations required (ip==0x577c28eb)
[FastForward] x86-string fast-forward: 18 iterations to go
[FastForward] x86-string fast-forward done; ip()==0x577c28eb
[FastForward] x86-string fast-forward: 84 iterations required (ip==0x577c2776)
[FastForward] x86-string fast-forward: 84 iterations to go
[FATAL /home/glandium/rr/src/fast_forward.cc:352:fast_forward_through_instruction() errno: 0 'Success'] 
 (task 31179 (rec:11298) at time 218405)
 ->  Assertion `!(debug_status & DS_WATCHPOINT_ANY)' failed to hold. 
```

So it looks like it's trying to do fast-forward to catch the watch point for an execution. The watch point is triggered, but for data write, not for an execution, but the code that fail is assuming the watchpoint is for execution.

**Comment by glandium** [comment]
The interesting thing is that the behavior is different depending on how the watchpoint is set. If I set it like this:
```
(gdb) print (uint16*)(safepoint.stream_.buffer_-2)
$1 = (js::ion::uint16 *) 0x60c32cbd
(gdb) watch *$1
```
Then the same thing doesn't happen.

**Comment by rocallahan** [comment]
Is this still a problem? Any chance of getting a reduced testcase or just STR?

**Comment by glandium** [comment]
Here is what I can say: it doesn't happen with current master, but I can't tell whether it's because I'm failing to reproduce it anymore, or whether it's actually fixed somehow, because running older versions of rr (especially the one that I do know failed) doesn't work anymore for some reason (stuck sucking 100% CPU when running rr replay before even showing the gdb prompt)

**Comment by glandium** [comment]
I was, in fact, able to reproduce with current master. Here are my STR:
- Download and unpack `https://ftp.mozilla.org/pub/mozilla.org/firefox/nightly/2012/11/2012-11-14-04-20-11-mozilla-aurora/firefox-18.0a2.en-US.linux-i686.tar.bz2`
- Create an empty profile in e.g `/tmp/f`
- Run the following command: `MOZ_CRASHREPORTER_DISABLE=1 rr record firefox/firefox -profile /tmp/f https://v8.googlecode.com/svn/data/benchmarks/v7/run.html`
- Reload that v8 page until you get a crash. Usually, it happens on the first try.
- `rr replay`
- On the gdb prompt: `continue`, you should hit the crash in `js::gc::MarkKind`.
- Then `print *(uint16_t**)($esp+0xd0) - 1`. The returned value should have the last bits set to `0xd`.
- Take that literal value and set a watchpoint to follow the content at that address. So, for instance, if the `print` above shows:
`$1 = (uint16_t *) 0xd06654bd`
, then create the watchpoint with:
`watch *(uint16_t *) 0xd06654bd`
(*not* `watch *$1`, and *not* `watch *(*(uint16_t**)($esp+0xd0) - 1)`)
- Finally, `reverse-continue`.

On my machine, this reliably ends up with
`[FATAL /home/glandium/rr/src/fast_forward.cc:352:fast_forward_through_instruction() errno: 0 'Success']`

**Comment by rocallahan** [comment]
Great, I can reproduce with these steps!
