### ISSUE TITLE
Setting PR_SET_NO_NEW_PRIVS in syscall buffer changes semantics

### ISSUE THREAD

**Issue by joneschrisg** [mozilla/rr#155]
For example, if a program being recorded by rr forks then execs `ping`, then recording and replay will fail.  Without the prctl, it (should) succeed.

I'm guessing we're setting this to prevent programs from mucking with the seccomp filter.  Programs that try to use a seccomp filter will also be broken no matter what with the syscall buffer, so maybe we should remove the NO_NEW_PRIVS to get more programs working.

Another way to prevent programs from fiddling with the seccomp filter is to use the filter to block that particular prctl.

**Comment by Keno** [comment]
Didn't realize there was an issue for this, but this is fixed using the `setuid-sudo` feature in #1926. @rocallahan
