### ISSUE TITLE
FATAL [.../PerfCounters.cc:191:start_counter() errno: 2 'No such file or directory'] 

### ISSUE THREAD

**Issue by facontidavide** [mozilla/rr#1554]
Just compiled rr on my system. I always get this message.

```
[FATAL /home/icarus/Software/rr/src/PerfCounters.cc:191:start_counter() errno: 2 'No such file or directory'] 
 -> Failed to initialize counter
```

My system:

* Ubuntu 14.08 64 bits, running on VirtualBox
* gcc 4.8.4
* Linux kernel 4.3.0-rc3

**Comment by froydnj** [comment]
[According to the wiki](https://github.com/mozilla/rr/wiki/Building-And-Installing#hardwaresoftware-requirements), VirtualBox doesn't support virtualization of performance counters.  But it's possible the wiki is out of date...What does running `dmesg|grep PMU` output?

**Comment by facontidavide** [comment]
It prints 
```
[    3.774795] Performance Events: unsupported p6 CPU model 60 no PMU driver, software events only.
[    4.410892] RAPL PMU detected, API unit is 2^-32 Joules, 4 fixed counters 10737418240 ms ovfl timer
```
I guess there is no solution then :(

**Comment by froydnj** [comment]
Looks that way.  :(  I poked around on www.virtualbox.org, but all I found relating to hardware performance counters were [issues requesting that such support be added](https://www.virtualbox.org/ticket/12495).

**Comment by rocallahan** [comment]
VirtualBox is open source so it should be possible for someone to add PMU virtualization to it. Fun project.
