### ISSUE TITLE
Fails to build because `-Werror` is set and several variables are unused

### ISSUE THREAD

**Issue by crossroads1112** [mozilla/rr#1556]
Followed the instructions on the wiki and this was the output of `make -j8`

    [  0%] Built target exec_stub
    [  0%] Building C object CMakeFiles/rrpreload.dir/src/preload/preload.c.o
    [  0%] Building C object CMakeFiles/rrpreload_32.dir/32/preload.c.o
    [  0%] Built target Generated
    [  0%] Generating rr_page_32
    [  1%] Generating rr_page_64
    [  1%] Built target exec_stub_32
    [  1%] Building C object CMakeFiles/64bit_child_32.dir/32/64bit_child.c.o
    In file included from /home/chad/Public/rr/obj/32/preload.c:11:0:
    /home/chad/Public/rr/obj/32/preload_interface.h:178:11: error: ISO C forbids zero-size array ‘extra_data’ [-Werror=pedantic]
       uint8_t extra_data[0];
               ^
    /home/chad/Public/rr/obj/32/preload_interface.h:207:28: error: ISO C forbids zero-size array ‘recs’ [-Werror=pedantic]
       struct syscallbuf_record recs[0];
                                ^
    [  1%] Building C object CMakeFiles/abort_nonmain_32.dir/32/abort_nonmain.c.o
    [  1%] Building C object CMakeFiles/abort_nonmain.dir/src/test/abort_nonmain.c.o
    [  1%] Building C object CMakeFiles/64bit_child.dir/src/test/64bit_child.c.o
    In file included from /home/chad/Public/rr/rr/src/preload/preload.c:11:0:
    /home/chad/Public/rr/rr/src/preload/preload_interface.h:178:11: error: ISO C forbids zero-size array ‘extra_data’ [-Werror=pedantic]
       uint8_t extra_data[0];
               ^
    /home/chad/Public/rr/rr/src/preload/preload_interface.h:207:28: error: ISO C forbids zero-size array ‘recs’ [-Werror=pedantic]
       struct syscallbuf_record recs[0];
                                ^
    /home/chad/Public/rr/obj/32/preload.c: In function ‘local_memcpy’:
    /home/chad/Public/rr/obj/32/preload.c:219:24: error: pointer of type ‘void *’ used in arithmetic [-Werror=pointer-arith]
       char* dst_end = dest + n;
                            ^
    /home/chad/Public/rr/obj/32/preload.c: In function ‘open_desched_event_counter’:
    /home/chad/Public/rr/obj/32/preload.c:540:37: error: ISO C99 requires at least one argument for the "..." in a variadic macro [-Werror]
         fatal("Failed to dup desched fd");
                                         ^
    /home/chad/Public/rr/obj/32/preload.c:543:35: error: ISO C99 requires at least one argument for the "..." in a variadic macro [-Werror]
         fatal("Failed to close tmp_fd");
                                       ^
    /home/chad/Public/rr/obj/32/preload.c:546:57: error: ISO C99 requires at least one argument for the "..." in a variadic macro [-Werror]
         fatal("Failed to fcntl(O_ASYNC) the desched counter");
                                                             ^
    /home/chad/Public/rr/obj/32/preload.c:551:67: error: ISO C99 requires at least one argument for the "..." in a variadic macro [-Werror]
         fatal("Failed to fcntl(SETOWN_EX) the desched counter to this");
                                                                       ^
    /home/chad/Public/rr/obj/32/preload.c: In function ‘init_process’:
    /home/chad/Public/rr/obj/32/preload.c:640:23: error: ISO C forbids assignment between function pointer and ‘void *’ [-Werror=pedantic]
       real_pthread_create = dlvsym(RTLD_NEXT, "pthread_create", "GLIBC_2.1");
                           ^
    /home/chad/Public/rr/obj/32/preload.c:685:36: error: ISO C forbids conversion of function pointer to object pointer type [-Werror=pedantic]
       params.syscall_hook_trampoline = (void*)_syscall_hook_trampoline;
                                        ^
    /home/chad/Public/rr/obj/32/preload.c:686:37: error: ISO C forbids conversion of function pointer to object pointer type [-Werror=pedantic]
       params.syscall_hook_stub_buffer = (void*)_stub_buffer;
                                         ^
    /home/chad/Public/rr/obj/32/preload.c:687:41: error: ISO C forbids conversion of function pointer to object pointer type [-Werror=pedantic]
       params.syscall_hook_stub_buffer_end = (void*)_stub_buffer_end;
                                             ^
    /home/chad/Public/rr/obj/32/preload.c: In function ‘pthread_mutex_timedlock’:
    /home/chad/Public/rr/obj/32/preload.c:787:34: error: ISO C forbids assignment between function pointer and ‘void *’ [-Werror=pedantic]
         real_pthread_mutex_timedlock = dlsym(RTLD_NEXT, "pthread_mutex_timedlock");
                                      ^
    /home/chad/Public/rr/obj/32/preload.c: In function ‘start_commit_buffered_syscall’:
    /home/chad/Public/rr/obj/32/preload.c:940:61: error: pointer of type ‘void *’ used in subtraction [-Werror=pointer-arith]
       stored_end = record_start + stored_record_size(record_end - record_start);
                                                                 ^
    /home/chad/Public/rr/obj/32/preload.c:940:29: error: pointer of type ‘void *’ used in arithmetic [-Werror=pointer-arith]
       stored_end = record_start + stored_record_size(record_end - record_start);
                                 ^
    /home/chad/Public/rr/obj/32/preload.c:943:33: error: pointer of type ‘void *’ used in arithmetic [-Werror=pointer-arith]
       if (stored_end < record_start + sizeof(struct syscallbuf_record)) {
                                     ^
    /home/chad/Public/rr/obj/32/preload.c:948:40: error: pointer of type ‘void *’ used in arithmetic [-Werror=pointer-arith]
       if (stored_end > (void*)buffer_end() - sizeof(struct syscallbuf_record)) {
                                            ^
    /home/chad/Public/rr/obj/32/preload.c:965:26: error: pointer of type ‘void *’ used in subtraction [-Werror=pointer-arith]
       rec->size = record_end - record_start;
                              ^
    /home/chad/Public/rr/obj/32/preload.c: In function ‘commit_raw_syscall’:
    /home/chad/Public/rr/obj/32/preload.c:1008:26: error: pointer of type ‘void *’ used in subtraction [-Werror=pointer-arith]
       rec->size = record_end - record_start;
                              ^
    /home/chad/Public/rr/obj/32/preload.c: In function ‘sys_clock_gettime’:
    /home/chad/Public/rr/obj/32/preload.c:1094:9: error: pointer of type ‘void *’ used in arithmetic [-Werror=pointer-arith]
         ptr += sizeof(*tp2);
             ^
    /home/chad/Public/rr/obj/32/preload.c: In function ‘sys_fcntl64_own_ex’:
    /home/chad/Public/rr/obj/32/preload.c:1171:9: error: pointer of type ‘void *’ used in arithmetic [-Werror=pointer-arith]
         ptr += sizeof(*owner2);
             ^
    /home/chad/Public/rr/obj/32/preload.c: In function ‘sys_fcntl64_xlk64’:
    /home/chad/Public/rr/obj/32/preload.c:1200:9: error: pointer of type ‘void *’ used in arithmetic [-Werror=pointer-arith]
         ptr += sizeof(*lock2);
             ^
    /home/chad/Public/rr/obj/32/preload.c: In function ‘sys_futex’:
    /home/chad/Public/rr/obj/32/preload.c:1312:7: error: pointer of type ‘void *’ used in arithmetic [-Werror=pointer-arith]
       ptr += sizeof(*saved_uaddr);
           ^
    /home/chad/Public/rr/obj/32/preload.c:1315:9: error: pointer of type ‘void *’ used in arithmetic [-Werror=pointer-arith]
         ptr += sizeof(*saved_uaddr2);
             ^
    /home/chad/Public/rr/obj/32/preload.c: In function ‘sys_gettimeofday’:
    /home/chad/Public/rr/obj/32/preload.c:1359:9: error: pointer of type ‘void *’ used in arithmetic [-Werror=pointer-arith]
         ptr += sizeof(*tp2);
             ^
    /home/chad/Public/rr/obj/32/preload.c:1363:9: error: pointer of type ‘void *’ used in arithmetic [-Werror=pointer-arith]
         ptr += sizeof(*tzp2);
             ^
    /home/chad/Public/rr/obj/32/preload.c: In function ‘sys__llseek’:
    /home/chad/Public/rr/obj/32/preload.c:1395:9: error: pointer of type ‘void *’ used in arithmetic [-Werror=pointer-arith]
         ptr += sizeof(*result2);
             ^
    /home/chad/Public/rr/obj/32/preload.c: In function ‘sys_poll’:
    /home/chad/Public/rr/obj/32/preload.c:1510:9: error: pointer of type ‘void *’ used in arithmetic [-Werror=pointer-arith]
         ptr += nfds * sizeof(*fds2);
             ^
    /home/chad/Public/rr/obj/32/preload.c: In function ‘copy_output_buffer’:
    /home/chad/Public/rr/obj/32/preload.c:1548:15: error: pointer of type ‘void *’ used in arithmetic [-Werror=pointer-arith]
       return buf2 + ret_size;
                   ^
    /home/chad/Public/rr/obj/32/preload.c: In function ‘sys_read’:
    /home/chad/Public/rr/obj/32/preload.c:1565:9: error: pointer of type ‘void *’ used in arithmetic [-Werror=pointer-arith]
         ptr += count;
             ^
    /home/chad/Public/rr/obj/32/preload.c: In function ‘sys_readlink’:
    /home/chad/Public/rr/obj/32/preload.c:1590:9: error: pointer of type ‘void *’ used in arithmetic [-Werror=pointer-arith]
         ptr += bufsiz;
             ^
    /home/chad/Public/rr/obj/32/preload.c: In function ‘sys_socketcall_recv’:
    /home/chad/Public/rr/obj/32/preload.c:1619:9: error: pointer of type ‘void *’ used in arithmetic [-Werror=pointer-arith]
         ptr += len;
             ^
    /home/chad/Public/rr/obj/32/preload.c: In function ‘sys_xstat64’:
    /home/chad/Public/rr/obj/32/preload.c:1804:9: error: pointer of type ‘void *’ used in arithmetic [-Werror=pointer-arith]
         ptr += sizeof(*buf2);
             ^
    [  1%] Built target Pages
    /home/chad/Public/rr/obj/32/preload.c: In function ‘sys_getrusage’:
    /home/chad/Public/rr/obj/32/preload.c:1896:9: error: pointer of type ‘void *’ used in arithmetic [-Werror=pointer-arith]
         ptr += sizeof(struct rusage);
             ^
    /home/chad/Public/rr/obj/32/preload.c: In function ‘XShmQueryExtension’:
    /home/chad/Public/rr/obj/32/preload.c:2044:30: error: unused parameter ‘dpy’ [-Werror=unused-parameter]
     int XShmQueryExtension(void* dpy) { return 0; }
                                  ^
    /home/chad/Public/rr/obj/32/preload.c: In function ‘XShmCreateImage’:
    /home/chad/Public/rr/obj/32/preload.c:2048:38: error: unused parameter ‘dpy’ [-Werror=unused-parameter]
     void* XShmCreateImage(register void* dpy, register void* visual,
                                          ^
    /home/chad/Public/rr/obj/32/preload.c:2048:58: error: unused parameter ‘visual’ [-Werror=unused-parameter]
     void* XShmCreateImage(register void* dpy, register void* visual,
                                                              ^
    /home/chad/Public/rr/obj/32/preload.c:2049:36: error: unused parameter ‘depth’ [-Werror=unused-parameter]
                           unsigned int depth, int format, char* data, void* shminfo,
                                        ^
    /home/chad/Public/rr/obj/32/preload.c:2049:47: error: unused parameter ‘format’ [-Werror=unused-parameter]
                           unsigned int depth, int format, char* data, void* shminfo,
                                                   ^
    /home/chad/Public/rr/obj/32/preload.c:2049:61: error: unused parameter ‘data’ [-Werror=unused-parameter]
                           unsigned int depth, int format, char* data, void* shminfo,
                                                                 ^
    /home/chad/Public/rr/obj/32/preload.c:2049:73: error: unused parameter ‘shminfo’ [-Werror=unused-parameter]
                           unsigned int depth, int format, char* data, void* shminfo,
                                                                             ^
    /home/chad/Public/rr/obj/32/preload.c:2050:36: error: unused parameter ‘width’ [-Werror=unused-parameter]
                           unsigned int width, unsigned int height) {
                                        ^
    /home/chad/Public/rr/obj/32/preload.c:2050:56: error: unused parameter ‘height’ [-Werror=unused-parameter]
                           unsigned int width, unsigned int height) {
                                                            ^
    [  1%] Building C object CMakeFiles/accept.dir/src/test/accept.c.o
    /home/chad/Public/rr/rr/src/preload/preload.c: In function ‘local_memcpy’:
    /home/chad/Public/rr/rr/src/preload/preload.c:219:24: error: pointer of type ‘void *’ used in arithmetic [-Werror=pointer-arith]
       char* dst_end = dest + n;
                            ^
    /home/chad/Public/rr/rr/src/preload/preload.c: In function ‘open_desched_event_counter’:
    /home/chad/Public/rr/rr/src/preload/preload.c:540:37: error: ISO C99 requires at least one argument for the "..." in a variadic macro [-Werror]
         fatal("Failed to dup desched fd");
                                         ^
    /home/chad/Public/rr/rr/src/preload/preload.c:543:35: error: ISO C99 requires at least one argument for the "..." in a variadic macro [-Werror]
         fatal("Failed to close tmp_fd");
                                       ^
    /home/chad/Public/rr/rr/src/preload/preload.c:546:57: error: ISO C99 requires at least one argument for the "..." in a variadic macro [-Werror]
         fatal("Failed to fcntl(O_ASYNC) the desched counter");
                                                             ^
    /home/chad/Public/rr/rr/src/preload/preload.c:551:67: error: ISO C99 requires at least one argument for the "..." in a variadic macro [-Werror]
         fatal("Failed to fcntl(SETOWN_EX) the desched counter to this");
                                                                       ^
    /home/chad/Public/rr/rr/src/preload/preload.c: In function ‘init_process’:
    /home/chad/Public/rr/rr/src/preload/preload.c:670:23: error: ISO C forbids assignment between function pointer and ‘void *’ [-Werror=pedantic]
       real_pthread_create = dlsym(RTLD_NEXT, "pthread_create");
                           ^
    /home/chad/Public/rr/rr/src/preload/preload.c:685:36: error: ISO C forbids conversion of function pointer to object pointer type [-Werror=pedantic]
       params.syscall_hook_trampoline = (void*)_syscall_hook_trampoline;
                                        ^
    /home/chad/Public/rr/rr/src/preload/preload.c:686:37: error: ISO C forbids conversion of function pointer to object pointer type [-Werror=pedantic]
       params.syscall_hook_stub_buffer = (void*)_stub_buffer;
                                         ^
    /home/chad/Public/rr/rr/src/preload/preload.c:687:41: error: ISO C forbids conversion of function pointer to object pointer type [-Werror=pedantic]
       params.syscall_hook_stub_buffer_end = (void*)_stub_buffer_end;
                                             ^
    /home/chad/Public/rr/rr/src/preload/preload.c: In function ‘pthread_mutex_timedlock’:
    /home/chad/Public/rr/rr/src/preload/preload.c:787:34: error: ISO C forbids assignment between function pointer and ‘void *’ [-Werror=pedantic]
         real_pthread_mutex_timedlock = dlsym(RTLD_NEXT, "pthread_mutex_timedlock");
                                      ^
    /home/chad/Public/rr/rr/src/preload/preload.c: In function ‘syscall_buffer_valid’:
    /home/chad/Public/rr/rr/src/preload/preload.c:908:61: error: pointer of type ‘void *’ used in subtraction [-Werror=pointer-arith]
       stored_end = record_start + stored_record_size(record_end - record_start);
                                                                 ^
    /home/chad/Public/rr/rr/src/preload/preload.c:908:29: error: pointer of type ‘void *’ used in arithmetic [-Werror=pointer-arith]
       stored_end = record_start + stored_record_size(record_end - record_start);
                                 ^
    /home/chad/Public/rr/rr/src/preload/preload.c:909:33: error: pointer of type ‘void *’ used in arithmetic [-Werror=pointer-arith]
       if (stored_end < record_start + sizeof(struct syscallbuf_record)) {
                                     ^
    /home/chad/Public/rr/rr/src/preload/preload.c:914:40: error: pointer of type ‘void *’ used in arithmetic [-Werror=pointer-arith]
       if (stored_end > (void*)buffer_end() - sizeof(struct syscallbuf_record)) {
                                            ^
    /home/chad/Public/rr/rr/src/preload/preload.c: In function ‘start_commit_buffered_syscall’:
    /home/chad/Public/rr/rr/src/preload/preload.c:940:61: error: pointer of type ‘void *’ used in subtraction [-Werror=pointer-arith]
       stored_end = record_start + stored_record_size(record_end - record_start);
                                                                 ^
    /home/chad/Public/rr/rr/src/preload/preload.c:940:29: error: pointer of type ‘void *’ used in arithmetic [-Werror=pointer-arith]
       stored_end = record_start + stored_record_size(record_end - record_start);
                                 ^
    /home/chad/Public/rr/rr/src/preload/preload.c:943:33: error: pointer of type ‘void *’ used in arithmetic [-Werror=pointer-arith]
       if (stored_end < record_start + sizeof(struct syscallbuf_record)) {
                                     ^
    /home/chad/Public/rr/rr/src/preload/preload.c:948:40: error: pointer of type ‘void *’ used in arithmetic [-Werror=pointer-arith]
       if (stored_end > (void*)buffer_end() - sizeof(struct syscallbuf_record)) {
                                            ^
    /home/chad/Public/rr/rr/src/preload/preload.c:965:26: error: pointer of type ‘void *’ used in subtraction [-Werror=pointer-arith]
       rec->size = record_end - record_start;
                              ^
    /home/chad/Public/rr/rr/src/preload/preload.c: In function ‘commit_raw_syscall’:
    /home/chad/Public/rr/rr/src/preload/preload.c:1008:26: error: pointer of type ‘void *’ used in subtraction [-Werror=pointer-arith]
       rec->size = record_end - record_start;
                              ^
    /home/chad/Public/rr/rr/src/preload/preload.c: In function ‘sys_clock_gettime’:
    /home/chad/Public/rr/rr/src/preload/preload.c:1094:9: error: pointer of type ‘void *’ used in arithmetic [-Werror=pointer-arith]
         ptr += sizeof(*tp2);
             ^
    /home/chad/Public/rr/rr/src/preload/preload.c: In function ‘sys_fcntl64_own_ex’:
    /home/chad/Public/rr/rr/src/preload/preload.c:1171:9: error: pointer of type ‘void *’ used in arithmetic [-Werror=pointer-arith]
         ptr += sizeof(*owner2);
             ^
    /home/chad/Public/rr/rr/src/preload/preload.c: In function ‘sys_fcntl64_xlk64’:
    /home/chad/Public/rr/rr/src/preload/preload.c:1200:9: error: pointer of type ‘void *’ used in arithmetic [-Werror=pointer-arith]
         ptr += sizeof(*lock2);
             ^
    /home/chad/Public/rr/rr/src/preload/preload.c: In function ‘sys_futex’:
    /home/chad/Public/rr/rr/src/preload/preload.c:1312:7: error: pointer of type ‘void *’ used in arithmetic [-Werror=pointer-arith]
       ptr += sizeof(*saved_uaddr);
           ^
    /home/chad/Public/rr/rr/src/preload/preload.c:1315:9: error: pointer of type ‘void *’ used in arithmetic [-Werror=pointer-arith]
         ptr += sizeof(*saved_uaddr2);
             ^
    /home/chad/Public/rr/rr/src/preload/preload.c: In function ‘sys_gettimeofday’:
    /home/chad/Public/rr/rr/src/preload/preload.c:1359:9: error: pointer of type ‘void *’ used in arithmetic [-Werror=pointer-arith]
         ptr += sizeof(*tp2);
             ^
    /home/chad/Public/rr/rr/src/preload/preload.c:1363:9: error: pointer of type ‘void *’ used in arithmetic [-Werror=pointer-arith]
         ptr += sizeof(*tzp2);
             ^
    /home/chad/Public/rr/rr/src/preload/preload.c: In function ‘sys_poll’:
    /home/chad/Public/rr/rr/src/preload/preload.c:1510:9: error: pointer of type ‘void *’ used in arithmetic [-Werror=pointer-arith]
         ptr += nfds * sizeof(*fds2);
             ^
    /home/chad/Public/rr/rr/src/preload/preload.c: In function ‘copy_output_buffer’:
    /home/chad/Public/rr/rr/src/preload/preload.c:1548:15: error: pointer of type ‘void *’ used in arithmetic [-Werror=pointer-arith]
       return buf2 + ret_size;
                   ^
    /home/chad/Public/rr/rr/src/preload/preload.c: In function ‘sys_read’:
    /home/chad/Public/rr/rr/src/preload/preload.c:1565:9: error: pointer of type ‘void *’ used in arithmetic [-Werror=pointer-arith]
         ptr += count;
             ^
    /home/chad/Public/rr/rr/src/preload/preload.c: In function ‘sys_readlink’:
    /home/chad/Public/rr/rr/src/preload/preload.c:1590:9: error: pointer of type ‘void *’ used in arithmetic [-Werror=pointer-arith]
         ptr += bufsiz;
             ^
    /home/chad/Public/rr/rr/src/preload/preload.c: In function ‘sys_recvfrom’:
    /home/chad/Public/rr/rr/src/preload/preload.c:1664:9: error: pointer of type ‘void *’ used in arithmetic [-Werror=pointer-arith]
         ptr += sizeof(*src_addr);
             ^
    /home/chad/Public/rr/rr/src/preload/preload.c:1669:9: error: pointer of type ‘void *’ used in arithmetic [-Werror=pointer-arith]
         ptr += sizeof(*addrlen);
             ^
    /home/chad/Public/rr/rr/src/preload/preload.c:1673:9: error: pointer of type ‘void *’ used in arithmetic [-Werror=pointer-arith]
         ptr += len;
             ^
    /home/chad/Public/rr/rr/src/preload/preload.c: In function ‘sys_recvmsg’:
    /home/chad/Public/rr/rr/src/preload/preload.c:1715:7: error: pointer of type ‘void *’ used in arithmetic [-Werror=pointer-arith]
       ptr += sizeof(struct msghdr);
           ^
    /home/chad/Public/rr/rr/src/preload/preload.c:1719:7: error: pointer of type ‘void *’ used in arithmetic [-Werror=pointer-arith]
       ptr += sizeof(struct iovec) * msg->msg_iovlen;
           ^
    /home/chad/Public/rr/rr/src/preload/preload.c:1724:27: error: pointer of type ‘void *’ used in arithmetic [-Werror=pointer-arith]
           ptr = align_ptr(ptr + msg->msg_iov[i].iov_len);
                               ^
    /home/chad/Public/rr/rr/src/preload/preload.c:1731:25: error: pointer of type ‘void *’ used in arithmetic [-Werror=pointer-arith]
         ptr = align_ptr(ptr + msg->msg_namelen);
                             ^
    /home/chad/Public/rr/rr/src/preload/preload.c:1735:25: error: pointer of type ‘void *’ used in arithmetic [-Werror=pointer-arith]
         ptr = align_ptr(ptr + msg->msg_controllen);
                             ^
    /home/chad/Public/rr/rr/src/preload/preload.c:1749:17: error: comparison between signed and unsigned integer expressions [-Werror=sign-compare]
               bytes < msg->msg_iov[i].iov_len ? bytes : msg->msg_iov[i].iov_len;
                     ^
    /home/chad/Public/rr/rr/src/preload/preload.c:1749:51: error: signed and unsigned type in conditional expression [-Werror=sign-compare]
               bytes < msg->msg_iov[i].iov_len ? bytes : msg->msg_iov[i].iov_len;
                                                       ^
    /home/chad/Public/rr/rr/src/preload/preload.c: In function ‘sys_xstat64’:
    /home/chad/Public/rr/rr/src/preload/preload.c:1804:9: error: pointer of type ‘void *’ used in arithmetic [-Werror=pointer-arith]
         ptr += sizeof(*buf2);
             ^
    /home/chad/Public/rr/rr/src/preload/preload.c: In function ‘sys_getrusage’:
    /home/chad/Public/rr/rr/src/preload/preload.c:1896:9: error: pointer of type ‘void *’ used in arithmetic [-Werror=pointer-arith]
         ptr += sizeof(struct rusage);
             ^
    /home/chad/Public/rr/rr/src/preload/preload.c: In function ‘XShmQueryExtension’:
    /home/chad/Public/rr/rr/src/preload/preload.c:2044:30: error: unused parameter ‘dpy’ [-Werror=unused-parameter]
     int XShmQueryExtension(void* dpy) { return 0; }
                                  ^
    /home/chad/Public/rr/rr/src/preload/preload.c: In function ‘XShmCreateImage’:
    /home/chad/Public/rr/rr/src/preload/preload.c:2048:38: error: unused parameter ‘dpy’ [-Werror=unused-parameter]
     void* XShmCreateImage(register void* dpy, register void* visual,
                                          ^
    /home/chad/Public/rr/rr/src/preload/preload.c:2048:58: error: unused parameter ‘visual’ [-Werror=unused-parameter]
     void* XShmCreateImage(register void* dpy, register void* visual,
                                                              ^
    /home/chad/Public/rr/rr/src/preload/preload.c:2049:36: error: unused parameter ‘depth’ [-Werror=unused-parameter]
                           unsigned int depth, int format, char* data, void* shminfo,
                                        ^
    /home/chad/Public/rr/rr/src/preload/preload.c:2049:47: error: unused parameter ‘format’ [-Werror=unused-parameter]
                           unsigned int depth, int format, char* data, void* shminfo,
                                                   ^
    /home/chad/Public/rr/rr/src/preload/preload.c:2049:61: error: unused parameter ‘data’ [-Werror=unused-parameter]
                           unsigned int depth, int format, char* data, void* shminfo,
                                                                 ^
    /home/chad/Public/rr/rr/src/preload/preload.c:2049:73: error: unused parameter ‘shminfo’ [-Werror=unused-parameter]
                           unsigned int depth, int format, char* data, void* shminfo,
                                                                             ^
    /home/chad/Public/rr/rr/src/preload/preload.c:2050:36: error: unused parameter ‘width’ [-Werror=unused-parameter]
                           unsigned int width, unsigned int height) {
                                        ^
    /home/chad/Public/rr/rr/src/preload/preload.c:2050:56: error: unused parameter ‘height’ [-Werror=unused-parameter]
                           unsigned int width, unsigned int height) {
                                                            ^
    [  1%] Building C object CMakeFiles/accept_32.dir/32/accept.c.o
    /home/chad/Public/rr/rr/src/test/abort_nonmain.c: In function ‘kill_thread’:
    /home/chad/Public/rr/rr/src/test/abort_nonmain.c:5:32: error: unused parameter ‘dontcare’ [-Werror=unused-parameter]
     static void* kill_thread(void* dontcare) {
                                    ^
    /home/chad/Public/rr/rr/src/test/abort_nonmain.c: In function ‘main’:
    /home/chad/Public/rr/rr/src/test/abort_nonmain.c:12:14: error: unused parameter ‘argc’ [-Werror=unused-parameter]
     int main(int argc, char* argv[]) {
                  ^
    /home/chad/Public/rr/rr/src/test/abort_nonmain.c:12:26: error: unused parameter ‘argv’ [-Werror=unused-parameter]
     int main(int argc, char* argv[]) {
                              ^
    cc1: all warnings being treated as errors
    CMakeFiles/abort_nonmain.dir/build.make:62: recipe for target 'CMakeFiles/abort_nonmain.dir/src/test/abort_nonmain.c.o' failed
    make[2]: *** [CMakeFiles/abort_nonmain.dir/src/test/abort_nonmain.c.o] Error 1
    CMakeFiles/Makefile2:205: recipe for target 'CMakeFiles/abort_nonmain.dir/all' failed
    make[1]: *** [CMakeFiles/abort_nonmain.dir/all] Error 2
    make[1]: *** Waiting for unfinished jobs....
    /home/chad/Public/rr/obj/32/abort_nonmain.c: In function ‘kill_thread’:
    /home/chad/Public/rr/obj/32/abort_nonmain.c:5:32: error: unused parameter ‘dontcare’ [-Werror=unused-parameter]
     static void* kill_thread(void* dontcare) {
                                    ^
    /home/chad/Public/rr/obj/32/abort_nonmain.c: In function ‘main’:
    /home/chad/Public/rr/obj/32/abort_nonmain.c:12:14: error: unused parameter ‘argc’ [-Werror=unused-parameter]
     int main(int argc, char* argv[]) {
                  ^
    /home/chad/Public/rr/obj/32/abort_nonmain.c:12:26: error: unused parameter ‘argv’ [-Werror=unused-parameter]
     int main(int argc, char* argv[]) {
                              ^
    /home/chad/Public/rr/rr/src/test/64bit_child.c: In function ‘main’:
    /home/chad/Public/rr/obj/32/64bit_child.c: In function ‘main’:
    /home/chad/Public/rr/rr/src/test/64bit_child.c:5:14: error: unused parameter ‘argc’ [-Werror=unused-parameter]
     int main(int argc, char* argv[]) {
                  ^
    /home/chad/Public/rr/rr/src/test/64bit_child.c:5:26: error: unused parameter ‘argv’ [-Werror=unused-parameter]
     int main(int argc, char* argv[]) {
                              ^
    /home/chad/Public/rr/obj/32/64bit_child.c:5:14: error: unused parameter ‘argc’ [-Werror=unused-parameter]
     int main(int argc, char* argv[]) {
                  ^
    /home/chad/Public/rr/obj/32/64bit_child.c:5:26: error: unused parameter ‘argv’ [-Werror=unused-parameter]
     int main(int argc, char* argv[]) {
                              ^
    /home/chad/Public/rr/obj/32/accept.c: In function ‘main’:
    /home/chad/Public/rr/obj/32/accept.c:71:14: error: unused parameter ‘argc’ [-Werror=unused-parameter]
     int main(int argc, char* argv[]) {
                  ^
    /home/chad/Public/rr/obj/32/accept.c:71:26: error: unused parameter ‘argv’ [-Werror=unused-parameter]
     int main(int argc, char* argv[]) {
                              ^
    cc1: all warnings being treated as errors
    cc1: all warnings being treated as errors
    cc1: all warnings being treated as errors
    CMakeFiles/abort_nonmain_32.dir/build.make:71: recipe for target 'CMakeFiles/abort_nonmain_32.dir/32/abort_nonmain.c.o' failed
    make[2]: *** [CMakeFiles/abort_nonmain_32.dir/32/abort_nonmain.c.o] Error 1
    CMakeFiles/Makefile2:242: recipe for target 'CMakeFiles/abort_nonmain_32.dir/all' failed
    make[1]: *** [CMakeFiles/abort_nonmain_32.dir/all] Error 2
    /home/chad/Public/rr/rr/src/test/accept.c: In function ‘main’:
    /home/chad/Public/rr/rr/src/test/accept.c:71:14: error: unused parameter ‘argc’ [-Werror=unused-parameter]
     int main(int argc, char* argv[]) {
                  ^
    /home/chad/Public/rr/rr/src/test/accept.c:71:26: error: unused parameter ‘argv’ [-Werror=unused-parameter]
     int main(int argc, char* argv[]) {
                              ^
    CMakeFiles/64bit_child.dir/build.make:62: recipe for target 'CMakeFiles/64bit_child.dir/src/test/64bit_child.c.o' failed
    make[2]: *** [CMakeFiles/64bit_child.dir/src/test/64bit_child.c.o] Error 1
    CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/64bit_child.dir/all' failed
    make[1]: *** [CMakeFiles/64bit_child.dir/all] Error 2
    CMakeFiles/64bit_child_32.dir/build.make:71: recipe for target 'CMakeFiles/64bit_child_32.dir/32/64bit_child.c.o' failed
    make[2]: *** [CMakeFiles/64bit_child_32.dir/32/64bit_child.c.o] Error 1
    CMakeFiles/Makefile2:104: recipe for target 'CMakeFiles/64bit_child_32.dir/all' failed
    make[1]: *** [CMakeFiles/64bit_child_32.dir/all] Error 2
    cc1: all warnings being treated as errors
    cc1: all warnings being treated as errors
    CMakeFiles/rrpreload.dir/build.make:62: recipe for target 'CMakeFiles/rrpreload.dir/src/preload/preload.c.o' failed
    make[2]: *** [CMakeFiles/rrpreload.dir/src/preload/preload.c.o] Error 1
    CMakeFiles/Makefile2:12667: recipe for target 'CMakeFiles/rrpreload.dir/all' failed
    make[1]: *** [CMakeFiles/rrpreload.dir/all] Error 2
    CMakeFiles/accept_32.dir/build.make:71: recipe for target 'CMakeFiles/accept_32.dir/32/accept.c.o' failed
    make[2]: *** [CMakeFiles/accept_32.dir/32/accept.c.o] Error 1
    CMakeFiles/Makefile2:316: recipe for target 'CMakeFiles/accept_32.dir/all' failed
    make[1]: *** [CMakeFiles/accept_32.dir/all] Error 2
    cc1: all warnings being treated as errors
    CMakeFiles/accept.dir/build.make:62: recipe for target 'CMakeFiles/accept.dir/src/test/accept.c.o' failed
    make[2]: *** [CMakeFiles/accept.dir/src/test/accept.c.o] Error 1
    CMakeFiles/Makefile2:279: recipe for target 'CMakeFiles/accept.dir/all' failed
    make[1]: *** [CMakeFiles/accept.dir/all] Error 2
    cc1: all warnings being treated as errors
    CMakeFiles/rrpreload_32.dir/build.make:94: recipe for target 'CMakeFiles/rrpreload_32.dir/32/preload.c.o' failed
    make[2]: *** [CMakeFiles/rrpreload_32.dir/32/preload.c.o] Error 1
    CMakeFiles/Makefile2:12704: recipe for target 'CMakeFiles/rrpreload_32.dir/all' failed
    make[1]: *** [CMakeFiles/rrpreload_32.dir/all] Error 2
    Makefile:160: recipe for target 'all' failed
    make: *** [all] Error 2

**Comment by rocallahan** [comment]
Seems like you're building with -pedantic or -ansi or something like that? You should stop doing that.

**Comment by crossroads1112** [comment]
I simply ran the cmake command as specified in the wiki. I did not add any additional flags.

**Comment by rocallahan** [comment]
Run `cmake -LAH` in your objdir and see what it says for `CMAKE_C_FLAGS`. Also see what it says for `CMAKE_C_COMPILER` and see if that's a script or a wrapper that adds `-pedantic`.

**Comment by crossroads1112** [comment]
CMAKE_C_FLAGS definitely includes `-pedantic` but CMAKE_C_COMPILER is
simply `/usr/bin/gcc`. How can I remove `-pedantic

**Comment by rocallahan** [comment]
I don't know. I'm not enough of a cmake expert to know how `CMAKE_C_FLAGS ` gets set.

**Comment by crossroads1112** [comment]
Well at least I've found the problem. Not a problem with `rr`
