### ISSUE TITLE
clone_interruption.c inconsistent operand constraints in an 'asm'

### ISSUE THREAD

**Issue by mikedilger** [mozilla/rr#1559]
````
[ 13%] Building C object CMakeFiles/clone_interruption_32.dir/32/clone_interruption.c.o
/usr/local/src/rr/obj/32/clone_interruption.c: In function ‘futex’:
/usr/local/src/rr/obj/32/clone_interruption.c:13:3: error: inconsistent operand constraints in an ‘asm’
   __asm__("int $0x80\n\t" ::"a"(SYS_futex), "b"(uaddr), "c"(op), "d"(val),
   ^
CMakeFiles/clone_interruption_32.dir/build.make:71: recipe for target 'CMakeFiles/clone_interruption_32.dir/32/clone_interruption.c.o' failed
make[2]: *** [CMakeFiles/clone_interruption_32.dir/32/clone_interruption.c.o] Error 1
CMakeFiles/Makefile2:3086: recipe for target 'CMakeFiles/clone_interruption_32.dir/all' failed
````

**Comment by rocallahan** [comment]
I have no idea how to fix that. What version of gcc?

**Comment by mikedilger** [comment]
mike@gentoo ~ $ gcc --version
gcc (Gentoo Hardened 4.9.3 p1.0, pie-0.6.2) 4.9.3

**Comment by rocallahan** [comment]
Try changing `"S"(NULL)` to `"S"(0)`?

**Comment by mikedilger** [comment]
no diff.

**Comment by mikedilger** [comment]
Sorry, I think my toolchain was built when this system supported 64 and 32 bit ABIs, and now it's strictly 64bit... because it's complaining about code in the __i386__ guard.   I'll rebuild my toolchain and check back.

**Comment by froydnj** [comment]
Ah, that would make some amount of sense, though the register constraints ought to be the same for 64-bit and 32-bit.

Anyway, for posterity, that error message is gcc's register allocator giving up on the `__asm__`.

Not sure what the alternative would be.  We might try putting all the arguments in a stack array, then passing the address of that array into the asm and letting the asm load the syscall arguments into the correct registers?  Then the registers would just be declared as clobbers, and gcc wouldn't have to worry about register allocation...

**Comment by rocallahan** [comment]
Try this:
````
-  __asm__("int $0x80\n\t" ::"a"(SYS_futex), "b"(uaddr), "c"(op), "d"(val),
-          "S"(NULL));
+  __asm__("xchg %%ebx,%%edi\n\t"
+          "int $0x80\n\t"
+          "xchg %%ebx,%%edi\n\t" ::"a"(SYS_futex), "c"(op), "d"(val),
+          "S"(NULL), "D"(uaddr));
````

**Comment by froydnj** [comment]
Ah, yes, the `%ebx` as PIC register problem...

**Comment by mikedilger** [comment]
that works!

**Comment by mikedilger** [comment]
Another one:
````
/usr/local/src/rr/obj/32/reverse_step_threads_break.c:19:3: error: inconsistent operand constraints in an ‘asm’
   __asm__("int $0x80\n\t"
   ^
````

**Comment by rocallahan** [comment]
OK, I fixed (hopefully) the last two on master.

**Comment by mikedilger** [comment]
```
/usr/local/src/rr/obj/32/sigrt.c:25:3: error: inconsistent operand constraints in an ‘asm’
   __asm__ __volatile__("int $0x80\n\t"
   ^
```
Last one.  After fixing that one, it compiled to 100%.
