### ISSUE TITLE
Is PTRACE_POKEDATA supported?

### ISSUE THREAD

**Issue by fracting** [mozilla/rr#1561]
Dear rr developers,

After workaround bug #1560 , Wine runs further. However, when WriteProcessMemory is called, Wine needs ptrace( PTRACE_POKEDATA , ... ), which introduce the below error:

[FATAL /home/fracting/src/rr/rr/src/record_syscall.cc:3014:rec_process_syscall_arch() errno: 0 'Success'] 
 (task 32182 (rec:32182) at time 1030949)
 ->  Assertion `t->regs().syscall_result_signed() == -syscall_state.expect_errno' failed to hold. Expected EIO for 'ptrace' but got result -3; unsupported ptrace(0x5 [PTRACE_POKEDATA])

source code: https://github.com/wine-compholio/wine-patched/blob/81667786de2e23faae28f4f0f1d4a08209b92e1b/server/ptrace.c#L313

I have no idea how to do a quick hack for PTRACE_POKEDATA, looking forward to rr developer's voice ;-)

Thanks!

**Comment by rocallahan** [comment]
This is probably not very hard. I'll explain how it should work and maybe you can write the code and send a pull request?

This needs to be added to `prepare_ptrace` in `RecordSyscall.cc`. I guess it'll be like `PTRACE_PEEKDATA` except that you write the data to tracee memory using `Task::write_mem` and --- very important --- you have to record the modified data using `Task::record_local`.

You'd also need to add test code to `ptrace.c`. Do a POKEDATA and then a PEEKDATA to ensure that it actually got written OK.

**Comment by fracting** [comment]
Thanks for the hints, I'm glad to work on it. The usage of Task::record_local isn't very clear to me yet, I'll come back this evening.

**Comment by rocallahan** [comment]
Actually this isn't so easy because unlike anything else in rr, this requires writing to the address space of a different task to the one performing the system call :-(.

**Comment by rocallahan** [comment]
... which means when `ReplaySession::exit_syscall` calls `t->apply_all_data_records_from_trace()`, it will write to the wrong address space.

**Comment by fracting** [comment]
Ah, thanks for let me know, then I'll leave it for experienced rr developers ;-)

**Comment by fracting** [comment]
Confirming works for me, thank you!
