### ISSUE TITLE
Test suite OOMs unsupported architecture machines

### ISSUE THREAD

**Issue by wthrowe** [mozilla/rr#1563]
`rr` forks and [the child stops itself](https://github.com/mozilla/rr/blob/master/src/task.cc#L3017) waiting for the parent to ptrace and restart it.  After the fork, [the parent creates a `Task`](https://github.com/mozilla/rr/blob/master/src/task.cc#L3053), which has the side effect of checking that the CPU architecture is supported and [aborting if it isn't](https://github.com/mozilla/rr/blob/master/src/PerfCounters.cc#L163).  In that case, the child is left stopped and reparented to init.  As the child uses roughly 50 MB of RAM and there are 1340 tests, the test suite quickly tries to consume roughly 67 GB of memory.  That will have very unfortunate effects on many machines.

**Comment by rocallahan** [comment]
Oops! In fact, I guess any abnormal exit between `fork()` and `PTRACE_SEIZE` will cause a process to be leaked.
