### ISSUE TITLE
removexattr needs by Wine Staging 1.7.53

### ISSUE THREAD

**Issue by fracting** [mozilla/rr#1564]
Wine Staging use setxattr/removexattr to emulate extended file attributes.

Reference: https://github.com/wine-compholio/wine-patched/blob/3f15cb2e9119584ab8a6b7dc0269699b74b23b3f/libs/port/xattr.c#L119

Assertion `t->regs().syscall_result_signed() == -syscall_state.expect_errno' failed to hold. Expected ENOSYS for 'removexattr' but got result -61; execution of syscall unsupported by rr

**Comment by rocallahan** [comment]
Should be easy to add. Check the git log for patches adding support for other system calls.

**Comment by fracting** [comment]
Forgot to close issue, sorry.
