### ISSUE TITLE
memfd_create needed by Wine Staging 1.7.53

### ISSUE THREAD

**Issue by fracting** [mozilla/rr#1565]
Reference: https://github.com/wine-compholio/wine-patched/blob/master/server/mapping.c#L44

205:     shm_fd = syscall( __NR_memfd_create, "wineserver_shm", MFD_ALLOW_SEALING );

**Comment by rocallahan** [comment]
Should be easy to add. Check the git log for patches adding support for other system calls. Looks like this syscall is new enough that its syscall numbers will need to be added to `syscalls.py`.

**Comment by fracting** [comment]
Thank you! I created https://github.com/mozilla/rr/pull/1567 for your review.
A comment like "this is easy" or "this is hard" is really helpful for new contributors like me ;-)

**Comment by rocallahan** [comment]
Thanks! Merged.
