### ISSUE TITLE
What would it take to run deterministically *without* a recording?

### ISSUE THREAD

**Issue by rrnewton** [mozilla/rr#1566]
Apologies, this definitely gets the "Question" label, rather than a bug report.

Both [NixOS](https://nixos.org/) and [Debian Reproducible Builds](https://wiki.debian.org/ReproducibleBuilds) try to isolate build jobs in a reproducible way, but neither actually fully *enforces* determinism.  For enforcing determinism, right now there are compiler approaches (CoreDet) and intra-process approaches ([DThreads](http://emeryberger.com/research/dthreads/)) and system-wide approaches that require a modified kernel (dOS, Determinator).  But none of these seems to be appropriate for enforcing determinism of a build job on a normal linux kernel, i.e. a process tree resulting from `./configure && make -j`.

But if `rr` could run a process *without* a recording, substituting certain default values and restricting functionality, perhaps it could become a good tool for this?

  * `rdtsc` would just reflect the instructions executed (deterministically)
  * Any IO except for normal file IO would result in an error.  (Presenting a deterministic file system to the process would be the job of other software -- like running in a Docker container.)

From what I understand `rr` already selectively traps syscalls, does sycall buffering, etc.  It sounds like all the core functionality is there such that the trace-free execution would only require a few tweaks.  Or maybe there's something I completely missing here?  Any feedback appreciated.

**Comment by rocallahan** [comment]
Interesting idea. Parts of rr would be usable as the basis for this, though you'd have to throw out or disable most of it. Some issues:
* Processes migrating between CPUs cause `cpuid` to return different values (since some `cpuid` calls include the processor core number). rr avoids this by pinning the tracees to a randomly chosen core; your tool would want to do that too. I guess for real determinism you'd have to pin to core 0.
* You can't use instructions executed for `rdtsc` since that isn't deterministic (page faults). You'd want to use the same counter (retired conditional branches) that rr uses.
* Various syscalls would need to be emulated to behave deterministically --- e.g. `getrandom`.
* Scheduling would be hard. I don't know how you'd solve that. rr records the order in which blocked processes wake up, but doesn't control that order.
* rr doesn't suppress ASLR. That's easy to do though via `personality()`.
* rr's syscall buffering is quite tricky because of the need to preserve performance counter values (and register/memory values) between recording and replay. You don't need that so you can just use a preload library that intercepts system calls and does whatever. rr's syscall patching infrastructure would still be useful though.

Altogether it seems to me that this problem is well outside rr's scope, but if you wanted to build such a tool, you could definitely reuse some rr code or at least ideas.

**Comment by rrnewton** [comment]
I was hoping this would be architecturally simply -- just catching all places that rr refers to the trace file and fabricating answers -- but of course it's complicated.  And this list of concrete issues is extremely valuable, so thank you!

Regarding the specifics, it sounds like `cpuid` can't be intercepted the way `rdtsc` is -- that's a shame.  (Full static or dynamic binary instrumentation to change those instructions to traps (0xCC) would be expensive, hmm...)  But how does rr get away with pinning to a random core?  It must pin at trace recording time, and pin again to the same core at at replay time, right?  

It sounds like your judgement is that this functionality could not easily coexist in the same repo.  Thus it would be more likely be a fork of rr leading to a different project.  That's good to know.  I don't have any manpower for this project atm, but I'm going to pitch it to future PhD students as a possible topic.

**Comment by rrnewton** [comment]
I would like to dig into the scheduling issue a bit further, if you could unpack that one a little bit, please.  The task scheduler during the rr record phase already takes into account blocking syscalls like `waitpid`.  And it seems like some of the same logic would apply for trace-free "replay".  So maybe this would end up looking like a blend of the record and replay modes.

Conceptually at least, it's a matter of implementing a deterministic round-robin scheduler which at each point can:

 * Track live (ready to run) tasks
 * Track tasks that are blocked on other (known) tasks
 * Track tasks that are blocked waiting for unknown conditions?  (Do those exist?)

The symmetry-breaking action of picking a task deterministically from any of the above sets (to run or poll) should be able to use some kind of deterministic task ID?  But rr already faking recorded process IDs/thread IDs as part of replay, right?  So would it just be a matter of having a simple algorithm for creating those IDs in the first place?  (For instance by using the concept of "pedigree" in the parallel task graph..)

**Comment by rocallahan** [comment]
> Regarding the specifics, it sounds like cpuid can't be intercepted the way rdtsc is -- that's a shame. 

That's potentially fixable. At least some Intel hardware has MSRs that allow trapping `cpuid`. Someone just needs to write the Linux kernel API for it.

> But how does rr get away with pinning to a random core? It must pin at trace recording time, and pin again to the same core at at replay time, right?

Correct.

Regarding scheduling, I was worried about the case where you have two processes that both enter blocking syscalls. In rr we do a `waitpid(-1)`, (at least) one of them completes in the kernel, the kernel schedules one, wakes it up and tells us which one it woke up. I'm not sure how you make that deterministic. You can't just force-wait for one selected process, because it might be waiting for the other process to make more progress.

**Comment by rrnewton** [comment]
Ah, ok, I read through some of `Scheduler.cc/.h` trying to understand this scheduling situation, and I see this business about tasks becoming "unstable".  If I'm understanding what you said above, in record mode, rr just says "let em race", and then it records the order they land in, which is then a known-good order for the replay mode to use -- but how to derive such a known-not-to-deadlock order in general?

(Actually, interestingly, if the replay processes are kind of solipsistic and only care about their own internal state, I guess it doesn't matter what order racing syscalls linearize in the kernel as long as the order effects hit the process state is observably the same on record and replay.)

If we had a task graph where blocked tasks identify their dependencies, then deterministic scheduling is feasible.  But the problem here is that the processes block on system calls with unknowable dependencies?  For someone who doesn't have all the Linux syscalls memorized -- is there a quick reference for what syscalls do that?

Finally, I think maybe an acceptable partial solution would be to support something less than the full concurrent semantics of thread and process forks.  For example, I think many shell scripts and build jobs would run to completion even with sequential semantics (where each forked task or process runs sequentially to completion before the parent resumes).  Other jobs would deadlock, but it would be deterministic!

**Comment by rocallahan** [comment]
>  I see this business about tasks becoming "unstable".

Ignore the "unstable" stuff. It's only relevant to task exits.

> If I'm understanding what you said above, in record mode, rr just says "let em race", and then it records the order two racing syscalls land in, which is then a known-good order for the replay mode to use -- but how to derive such a known-not-to-deadlock order in general?

That's correct.

> If we had a task graph where blocked tasks identify their dependencies, then deterministic scheduling is feasible. But the problem here is that the processes block on system calls with unknowable dependencies? For someone who doesn't have all the Linux syscalls memorized -- is there a quick reference for what syscalls do that?

One way it can happen is when you have a pipe or socket, one process does a blocking read on it, and another process must write. Another way is when one process does a FUTEX_WAIT until another does a FUTEX_WAKE.

One problem with trying to compute dependencies is that it depends on future information. For example if process A reads from pipe X and process B reads from pipe Y, whether A depends on B depends on whether B will write to X after reading from Y.

**Comment by rrnewton** [comment]
Got it!

I think this suggests that banning inter-process communication for deterministic execution one way to go?  It may be hard to separate "allowed" IO, from interprocess comm, but maybe this would look something like a dynamic data-race detector.  If process A touches a file, pipe, or whatever, and another process B touches it while logically in parallel (i.e. no "happens before" relation), it immediately throws an error and exits the whole process tree.  We'd track metadata for any resources that can potentially be hit concurrently.
   The happens-before relation would need to be formed purely based on the fork-join structure of the process graph, *not* including data-flow dependencies like pipe communication (which would be disallowed).

This formulation would be slightly looser than fully sequentializing processes, but it would amount to much the same thing.  My goal is really to change certain process trees into "pure functions" from a set of files on disk to another set of files on disk, with no other observable effects.  (Which I *think* is all we need for build jobs like `gcc`.)

A truly concurrent deterministic semantics would probably require some notion of synchronous rounds [(like in Blelloch et al PPoPP'12)](https://www.cs.cmu.edu/~guyb/papers/BFGS12.pdf).  So in your pipe example, if B completes its write to X in round R, then A depends on B if it reads X at round R+1 or later, otherwise not.  Racing uses of shared resources in the same round then need a deterministic resolution of who "wins", with only one winner accessing the resource that round.

**Comment by rrnewton** [comment]
To clarify, in that PPoPP paper each round is split into two phases that involve dependence discovery and then real execution.  This would need to be something similar, where during each round R each process P is entitled to:

 * A slice of time up to a fixed number of cycles, 
 * up to one system call that represents potential IPC, 
 * an unlimited number of system calls that are non-IPC and/or buffered

So all processes would get a slice in the first phase of the round, up to hitting one of the above bounds, and then the second phase of the round would involve picking winners for the potential-IPC syscalls and committing the ones that won.  The losers would slide into the next round (and would not get to execute in the next round, essentially making only the syscall as their first and only action).

**Comment by rocallahan** [comment]
Yes, it seems like that would work. Sounds like an interesting project to try.

I think we've gone well beyond the scope of rr here so I'm going to close this issue. Send me an email if you have any more questions.
