### ISSUE TITLE
Assertion failure in AddressSpace::coalesce_around on Ubuntu 14.04 VM

### ISSUE THREAD

**Issue by evincarofautumn** [mozilla/rr#1576]
I am trying to run `rr record` on an Ubuntu 14.04 VM with two processors running under VMWare Fusion 6.06. Whether using a binary release or building from `master`, I get the following output:

```
rr: /home/jonathanpurdy/rr/src/AddressSpace.cc:1278: void AddressSpace::coalesce_around(std::map<MemoryRange, AddressSpace::Mapping, MappingComparator>::iterator): Assertion `last_kv != mem.end()' failed.
```

Based on a cursory reading of `coalesce_around`, it seems this assertion is correct, and has been present in the code for a long while. What should I try next? I can provide any information necessary.

Output of `uname -a`:

```
Linux ubuntu 3.13.0-49-generic #83-Ubuntu SMP Fri Apr 10 20:11:33 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
```

I don’t know if this is relevant, but the process I am attempting to debug with `rr` does not crash—it exhibits wrong behaviour but exits successfully.

**Comment by evincarofautumn** [comment]
Also fails on a real machine, not just a VM. I am debugging the Mono runtime, and it appears this assertion does not fail when debugging other programs. The GC does make extensive use of virtual memory operations. Any suggestions for how to debug this would be welcome.

**Comment by rocallahan** [comment]
Is `prev == mem.end()`? I assume so.
Is `it == mem.end()`? I assume so.
Are we calling `coalesce_around` from `protect`? I assume so.
Can you dump the parameters to `protect` from the call stack, dump `/proc/.../maps` for the tracee process, and also the output of `this->dump()`?

**Comment by rocallahan** [comment]
Also, in `protect`, what's `last_overlap`?
I have a feeling this could be because someone's doing an `mprotect` and no mapping intersects the `mprotect`ed region. I can write a test for that and fix it shortly, but I'm in the middle of something else right this minute.

**Comment by evincarofautumn** [comment]
`prev == mem.end()` and `it == mem.end()`. `coalesce_around` is being called from `protect`:

```
rr(AddressSpace::coalesce_around(std::_Rb_tree_iterator<std::pair<MemoryRange const, AddressSpace::Mapping> >)+0x2a3) [0x57d6c9]
rr(AddressSpace::protect(remote_ptr<void>, unsigned long, int)+0x1d5) [0x57869b]
rr(void Task::on_syscall_exit_arch<rr::X64Arch>(int, Registers const&)+0x2b4) [0x6920fc]
rr(Task::on_syscall_exit(int, Registers const&)+0x6d) [0x682d1d]
rr() [0x61d028]
rr() [0x61339d]
rr(rec_process_syscall(Task*)+0x34) [0x6133d3]
rr(RecordSession::syscall_state_changed(Task*, RecordSession::StepState*)+0x91d) [0x603e25]
rr(RecordSession::record_step()+0x33d) [0x606bf1]
rr() [0x5ff40d]
rr(RecordCommand::run(std::vector<std::string, std::allocator<std::string> >&)+0xe7) [0x5ff625]
rr(main+0x18a) [0x5eafff]
/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf5) [0x7f186a904ec5]
```

`last_overlap` is `0-0`, so I would be inclined to agree with your hunch. [Here](https://gist.github.com/evincarofautumn/14e585eb227227187caa) is the output of `this->dump()` just before the assertion failure.

Could this not also indicate a bug in Mono?

**Comment by rocallahan** [comment]
> Could this not also indicate a bug in Mono?

Maybe, maybe not. rr should handle it in any case.

**Comment by evincarofautumn** [comment]
For the record, this solved our particular issue—thanks!

For future reference, the kernel that ships with Ubuntu 14.04 is too old for `rr` (missing `PTRACE_INTERRUPT` or something), so `rr record` would hang. That’s why I didn’t submit a PR with my changes, which were nearly identical—I thought they didn’t work! Simply upgrading to Ubuntu 15.10 was enough.

**Comment by rocallahan** [comment]
That's odd. I regularly test rr on 32-bit Ubuntu 14.04 in a VMWare VM (that's where I make the 32-bit rr release builds).
````
roc@ubuntu:~$ uname -a
Linux ubuntu 3.13.0-34-generic #60-Ubuntu SMP Wed Aug 13 15:49:09 UTC 2014 i686 i686 i686 GNU/Linux
````
So I have no idea why it wouldn't work for you. If you care, open an issue and we can investigate further.

**Comment by evincarofautumn** [comment]
Huh, guess I was mistaken. Maybe it’s the fact that I was running a 64-bit Ubuntu, but my 15.10 is also 64-bit with no issue. (Well, except for the fact that instruction counts aren’t correct in a VMWare guest, but that’s unrelated.)
