### ISSUE TITLE
wiki "Building and installing -> Tests" directory hierarchy confusion

### ISSUE THREAD

**Issue by nickolay** [mozilla/rr#1584]
https://github.com/mozilla/rr/wiki/Building-And-Installing#tests seems to be outdated, as it says:

> rr has a suite of tests in $rr/src/test. The test harness expects that your rr disk environment is layed out like the following
>
>     $rr/     # toplevel
>       rr/    # srcdir
>       $obj/  # objdir
>
> The actual names of the $rr toplevel and $obj directories don't actually matter. However, the rr srcdir actually has to be named "rr" for the tests to run correctly. 

This seemingly contradicts itself ($rr/src/test or $rr/rr/src/test?) and hard to map to the directory hierarchy I get after following https://github.com/mozilla/rr/wiki/Building-And-Installing#tldr (though `make check` passed). My directory hierarchy looks like this:

    ~/
      rr/        # manually created (step 1 of tl&dr instructions)
        rr/      # git checkout
          .git/
          obj/   # objdir
          src/   # https://github.com/mozilla/rr/tree/master/src
            test/  # and so on.
          ...

Not sure if this section should just be removed or if you wanted to warn users that the git working directory root folder (the one containing `src` and `obj`)  should be named `rr`?

**Comment by rocallahan** [comment]
It's out of date; that got fixed a while back. Thanks for pointing it out; I updated the wiki.
