### ISSUE TITLE
thread_stress test wastes CPU compressing gigabytes of threads' stack memory

### ISSUE THREAD

**Issue by nickolay** [mozilla/rr#1591]
Currently (after 6915ac068e6433b6e738e59dde9cde2dca0b36cd I guess), `rr record obj/bin/thread_stress` runs for about 30 seconds here, using almost all the 4 cores of a VM at 100% to compress the 12GB trace down to a few MB:

    $ rr dump -s
    ...
    // Uncompressed bytes 12566470122, compressed bytes 13183031, ratio 953.23x

This is mainly due to rr saving the memory `madvise(MADV_DONTNEED)`-ed for stack - https://github.com/mozilla/rr/blob/89374abf483c8cb48d05d497e70ee9697e879bc8/src/record_syscall.cc#L3318 - for 1500 threads * 8MB/thread:

    $ strace -f -o trace.txt bin/thread_stress
    ...
    33639 clone(...) = 33642
    33639 mmap(NULL, 8392704, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS|MAP_STACK, -1, 0) = 0x7f7486b92000
    33639 mprotect(0x7f7486b92000, 4096, PROT_NONE <unfinished ...>
    33642 madvise(0x7f7487393000, 8368128, MADV_DONTNEED
    ...

Reducing `ulimit -s` reduces the overhead significantly.

If saving of MADV_DONTNEED memory is intentional, perhaps the test could be run with reduced stack memory?

(Related: #528)

**Comment by rocallahan** [comment]
Perhaps better would be to extend the trace-data record format to specially represent all-zeroes without compressing them, and make MADV_DONTNEED/MADV_REMOVE use that.

**Comment by rocallahan** [comment]
I ended up taking a different approach where we just don't record anything and actually perform the `MADV_DONTNEED` during replay. We were actually already doing that for syscall-buffered `madvise`, but that wasn't working for thread-stack cleanup, so I fixed that as well.
