### ISSUE TITLE
Assertion triggered in patch_after_exec_arch

### ISSUE THREAD

**Issue by dannas** [mozilla/rr#1598]
I'm hitting an assertion when recording the QtCreator IDE using rr built against https://github.com/mozilla/rr/commit/d1f962607d50dfbc69db884903d82f23f3c83ca9

rr: /home/dannas/code/external/rr/src/Monkeypatcher.cc:776: void patch_after_exec_arch(Task*, Monkeypatcher&) [with Arch = rr::X64Arch]: Assertion `(sym_address & ~vdso_max_size) == vdso_static_base || (sym_address & ~vdso_max_size) == 0' failed.

I've reproduced it twice after about five minutes of recording (but unfortunately dumping core was disabled).

I have a saved trace dir (note to self: qtcreator-15). 

I'll try to investigate and reproduce with core enabled when I get home from office (and if time permits :)

**Comment by dannas** [comment]
Managed to reproduce. A [full backtrace](https://gist.githubusercontent.com/dannas/d6f11fd3e11b8b121cda/raw/7f8fc5a157e41b50bb691b9ed478d58717dfdf04/gistfile1.txt)

The symbol address is outside the range of allowed addresses.

    (gdb) p/x sym_address
    $14 = 0x1a2dd20

Theories: Either (1) the assertion is too strong or (2) there's a bug in VdsoReader or (3) we've read the wrong part of memory or (4) something else.

I'm trying to access the location of vdso, in order to compare the content against what VdsoReader sees, but I'm having trouble accessing the AddressSpace through Task::vm() - it returns a shared_pointer and I can't call functions (include operator*) to access the underlying AdressSpace.

Will keep trying tomorrow.

**Comment by rocallahan** [comment]
You can extract the vdso data from any process and dump it to a file. Then `objdump` will dump it. I don't really know enough about ELF details to know whether the assertion is valid.

**Comment by dannas** [comment]
Created [fork_exec.c](https://gist.github.com/dannas/4b718fee6293257ec6cb) that calls `execve` in a tight loop 1000 times. Ran the program 15 times under rr, but could not reproduce. So it takes something more than that, to trigger the assertion.

@rocallahan Ok. Too bad I can't dump the vdso after the crash (the vdso belongs to the tracee and I only have access to the core file for rr). I've changed the assert to ASSERT(t, cond) and will try to trigger it once again.

**Comment by dannas** [comment]
Added the following lines to `patch_after_exec_arch`

    for (size_t i = 0; i < syms.size(); ++i) {
      uintptr_t off = syms.symbols[i].file_offset;
      size_t name_index = syms.symbols[i].name_index;
      printf("off=%lx, name_index=%lu\n", off, name_index);
    }

It prints...
>off=0, name_index=0
off=418, name_index=0
off=8e0, name_index=8
off=73752f3a6e69622f, name_index=3417213296966381426
off=dc0, name_index=22
off=1060, name_index=54
off=dc0, name_index=29
off=1040, name_index=49
off=1060, name_index=61
off=8e0, name_index=1
off=1040, name_index=42

..Whenever I run rr against [vdso.c](https://gist.github.com/dannas/45cffc338cf3691f4519)



Running objdump on the dumped vdso, does not display the fourth entry with the long offset from above (objdump listes them in a different order, but they can be matched on their offset) 
>$ objdump -T foo.vdso
0000000000000418 l    d  .rodata        0000000000000000              .rodata
00000000000008e0  w   DF .text  00000000000004d3  LINUX_2.6   clock_gettime
0000000000000000 g    DO *ABS*  0000000000000000  LINUX_2.6   LINUX_2.6
0000000000000dc0 g    DF .text  0000000000000271  LINUX_2.6   __vdso_gettimeofday
0000000000001060 g    DF .text  0000000000000029  LINUX_2.6   __vdso_getcpu
0000000000000dc0  w   DF .text  0000000000000271  LINUX_2.6   gettimeofday
0000000000001040  w   DF .text  0000000000000015  LINUX_2.6   time
0000000000001060  w   DF .text  0000000000000029  LINUX_2.6   getcpu
00000000000008e0 g    DF .text  00000000000004d3  LINUX_2.6   __vdso_clock_gettime
0000000000001040 g    DF .text  0000000000000015  LINUX_2.6   __vdso_time

In the backtrace for the corefile I get for the four first entries in `syms`:

>{file_offset = 0, name_index = 0}, 
{file_offset = 1048,   name_index = 0}, 
{file_offset = 2272, name_index = 8}, 
{file_offset = 27450656, name_index = 42},

Here the `name_index` happens to fall within the range of strtab. `SymbolTable::is_name` filters out entries whose `name_index` doesn't point inside strtab, but this one sneaked through and caused the assert.

Guess I'll just have to figure out what that third entry in the dynsym table is used for, and make sure it will always be ignored when patching. 

I wonder why the dynsym table from the core file differs from what I see when I dump the vdso? I thought that the vdso would identical for all processes and that only the mapping address differed.

**Comment by dannas** [comment]
Added this line to `patch_after_exec_arch`

    printf("off=%ld, name_index=%lu\n", syms.symbols[3].file_offset, 
                syms.symbols[3].name_index);

Ran qtcreator under rr. A sample of values logged...

>off=7091318038165598062, name_index=8246216753318292527
off=140553248178176, name_index=140553248182272
off=6492160, name_index=6500352
off=0, name_index=0
off=20129408, name_index=20129488
off=19978672, name_index=289
off=139724317220864, name_index=139724317237248
off=3905530384309120620, name_index=8086829064643964218
off=140553246859264, name_index=140553247924224
off=140283419131904, name_index=140283420196864
off=20116896, name_index=20137184
off=0, name_index=0

.. Looks like the fourth entry in the symbol table, varies from run to run. 

I'm reading the [elf spec](https://refspecs.linuxbase.org/elf/elf.pdf), trying to figure out how  a symbol table is constructed.

**Comment by dannas** [comment]
Tried...

>--- a/src/Monkeypatcher.cc
+++ b/src/Monkeypatcher.cc
@@ -546,7 +546,7 @@ SymbolTable ElfReader::read_symbols_arch(const char* symtab,
   result.symbols.resize(symbol_list.size());
   for (size_t i = 0; i < symbol_list.size(); ++i) {
     auto& s = symbol_list[i];
-    if (s.st_shndx >= sections.size()) {
+    if ((s.st_info & 0x0f) != STT_FUNC || s.st_shndx >= sections.size()) {
       continue;
     }
     auto& section = sections[s.st_shndx];

.. But I  get 68 test failures. Investigating.

**Comment by dannas** [comment]
Closing this issue as I can no longer reproduce it.

For future reference:  #1627 mentions another problem (unsure if related but an indication that the format of the vdso is not set in stone) with monkeypatching the vdso and was fixed by https://github.com/mozilla/rr/commit/4ad2055d6b4cd5729c99724e6dc4ac6dee90315b
