### ISSUE TITLE
'make check' fails if .local doesn't already exist and XDG_DATA_HOME not set

### ISSUE THREAD

**Issue by kapiliitr** [mozilla/rr#1599]
I compiled rr from source on a Debian machine in a VirtualBox. When I ran 'make check', all the tests fail and make check hangs after some time. Below is the error for the first test, although its the same for the other tests as well.

    test 1
            Start   1: 64bit_child

    1: Test command: /bin/bash "/home/debian/rr/src/test/basic_test.run" "-b" "/home/debian/rr" "/home/debian/rr/obj" "64bit_child"
    1: Test timeout computed to be: 9.99988e+06
    1: /home/debian/rr/src/test/util.sh: line 190:  6476 Aborted                 _RR_TRACE_DIR="$workdir" rr $GLOBAL_OPTIONS record $LIB_ARG $RECORD_ARGS $exe $exeargs > record.out 2> record.err
    1: Test '64bit_child' FAILED: : error during recording:
    1: --------------------------------------------------
    1: [FATAL /home/debian/rr/src/TraceStream.cc:124:ensure_default_rr_trace_dir() errno: 2 'No such file or directory']
    1:  -> Failed to create directory `/home/debian/.local/share/rr'
    1: --------------------------------------------------
    1: record.out:
    1: --------------------------------------------------
    1: --------------------------------------------------
    1: Test 64bit_child failed, leaving behind /tmp/rr-test-64bit_child-xWHfTO09Y
    1: To replay the failed test, run
    1:   _RR_TRACE_DIR=/tmp/rr-test-64bit_child-xWHfTO09Y rr replay
      1/1408 Test   #1: 64bit_child ...............................................***Failed  Error regular expression found in output. Regex=[FAILED]  0.01 sec

**Comment by froydnj** [comment]
Does `/home/debian/.local/` exist already?  Does `/home/debian/.local/share/`?  What are the permissions on those directories if they do exist?

In general, running rr under VirtualBox isn't going to work, because VirtualBox doesn't support the necessary performance counters (see #1554, for instance).  The wiki [has some details](https://github.com/mozilla/rr/wiki/Building-And-Installing#hardwaresoftware-requirements) about what virtual machines are known to work.

**Comment by kapiliitr** [comment]
Nope, `.local` does't exist. Oh, I am having the same problem as #1554.

Regards,
Kapil Agarwal

**Comment by froydnj** [comment]
Well, once we fix the directory creation bits to create `~/.local` if necessary, you will be having the same problems as #1554. :)
