### ISSUE TITLE
'make check' fail in Debian VM

### ISSUE THREAD

**Issue by kapiliitr** [mozilla/rr#1600]
I am getting errors during 'make check'. I am running debian sid-unstable in a KVM. I added `<cpu mode='host-passthrough'/>` to the libvirt XML file and below is the output for 'dmesg|grep PMU'
    [    0.024868] Performance Events: 16-deep LBR, IvyBridge events, Intel PMU driver.
    [    0.026318] perf_event_intel: PMU erratum BJ122, BV98, HSD29 workaround disabled, HT off

Below is an error that I am getting-
    Test command: /bin/bash "/home/debian/rr/rr/src/test/basic_test.run" "-n" "/home/debian/rr/rr" "/home/debian/rr/rr/obj" "fadvise"
    Test timeout computed to be: 9.99988e+06
    /home/debian/rr/rr/src/test/util.sh: line 190:  8402 Aborted                 _RR_TRACE_DIR="$workdir" rr $GLOBAL_OPTIONS record $LIB_ARG $RECORD_ARGS $exe $exeargs > record.out 2> record.err
    /home/debian/rr/rr/src/test/util.sh: line 216:  8428 Aborted                 _RR_TRACE_DIR="$workdir" rr $GLOBAL_OPTIONS replay -a $replayflags > replay.out 2> replay.err
    Test 'fadvise' FAILED: : error during recording:
    --------------------------------------------------
    [FATAL /home/debian/rr/rr/src/PerfCounters.cc:188:start_counter() errno: 13 'Permission denied'] 
     -> Permission denied to use 'perf_event_open'; are perf events enabled? Try 'perf record'.
    --------------------------------------------------
    record.out:
    --------------------------------------------------
    --------------------------------------------------
    Test fadvise failed, leaving behind /tmp/rr-test-fadvise-uA8lGejEN
    To replay the failed test, run
      _RR_TRACE_DIR=/tmp/rr-test-fadvise-uA8lGejEN rr replay
     64/704 Test  #64: fadvise-no-syscallbuf ..................................***Failed  Error regular expression found in output. Regex=     [FAILED]  
    0.16 sec

**Comment by rocallahan** [comment]
Does `perf record` work for you? It sounds like your system might be configured so perf events are only usable by root.

**Comment by kapiliitr** [comment]
Yes, perf record worked for me but it wasn't installed.
Also, make check did run for root user, but now I am getting a new error.
Maybe I should create a new issue for that ?

Here is the log anyways-
35: Test command: /bin/bash "/home/debian/rr/rr/src/test/basic_test.run"
"-b" "/home/debian/rr/rr" "/home/debian/rr/rr/obj" "capget"
35: Test timeout computed to be: 9.99988e+06
35: Test 'capget' FAILED: : error during recording:
35: --------------------------------------------------
35: capget-LZNK4ugda: /home/debian/rr/rr/src/test/capget.c:26: main:
Assertion `"FAILED: !" && check_cond(0 == data[0].effective)' failed.
35: --------------------------------------------------
35: record.out:
35: --------------------------------------------------
35: FAILED: errno=0 (Success)
35: --------------------------------------------------
35: Test capget failed, leaving behind /tmp/rr-test-capget-LZNK4ugda
35: To replay the failed test, run
35:   _RR_TRACE_DIR=/tmp/rr-test-capget-LZNK4ugda rr replay
 35/704 Test  #35: capget
.................................................***Failed  Error regular
expression found in output. Regex=[FAILED]
0.17 sec


ᐧ

Regards,
Kapil Agarwal

**Comment by rocallahan** [comment]
OK, I just pushed a fix for the capget test.

You probably should configure your system to allow perf events to be used by non-privileged users, instead of running everything as root.
