### ISSUE TITLE
Replay fails with "FATAL ReplaySession.cc:521:guard_overshoot()" after "Replay diverged"

### ISSUE THREAD

**Issue by theres-waldo** [mozilla/rr#1602]
I'm running into an issue replaying a recording of Firefox. I'm using the trunk version of rr (for both capturing the recording and replaying), and gdb 7.10, on Debian Jessie.

Here's the error output:

    [ERROR /home/botond/builds/rr/src/ReplaySession.cc:505:guard_overshoot() errno: 0 'Success'] 
     -> Replay diverged.  Dumping register comparison.
    [FATAL /home/botond/builds/rr/src/ReplaySession.cc:521:guard_overshoot() errno: 0 'Success'] 
     (task 9129 (rec:9018) at time 14540)
     ->  Assertion `false' failed to hold. overshot target ticks=3664691 by 7489
    Launch gdb with
      gdb /home/botond/.local/share/rr/firefox-2/mmap_493_hardlink_plugin-container
    and attach to the rr debug server with:
      target remote :9129
    [FATAL /home/botond/builds/rr/src/log.cc:28:emergency_debug() errno: 0 'Success'] 
     -> Can't resume execution from invalid state

**Comment by khuey** [comment]
Likely the same is #1603, which also has a regression range.

**Comment by theres-waldo** [comment]
Indeed, I tried with a revision prior to the one identified in #1603 and the problem did not occur; closing.
