### ISSUE TITLE
Intel Skylake support

### ISSUE THREAD

**Issue by Noctune** [mozilla/rr#1607]
Trying to run rr on a Skylake CPU currently throws this error:

    [FATAL /home/roc/rr/rr/src/PerfCounters.cc:129:get_cpu_microarch() errno: 0 'Success'] 
    -> CPU 0x506e0 unknown.

I'm guessing it just need to be added to get_cpu_microarch in PerfCounters.cc, but I have no idea what the correct flags for Skylake is.

**Comment by khuey** [comment]
The value 0x506e0 is the cpu_type that goes in the switch statement in get_cpu_microarch.  The values in pmu_configs come from the relevant Intel manuals.  http://www.intel.com/content/dam/www/public/us/en/documents/manuals/64-ia-32-architectures-software-developers-manual.pdf has a section on performance counters for Skylake.  Comparing that to the existing table for Broadwell in the Intel manual, it looks like those values are unchanged between the two architectures, so you ought to just be able to copy Broadwell's values and verify that it works.
