### ISSUE TITLE
File name too long error in create_shmem_segment() during replay

### ISSUE THREAD

**Issue by jrmuizel** [mozilla/rr#1611]
Here's the path:
/dev/shm/rr-emufs-13012-dev-2049-inode-20089069-\home\jrmuizel\.mozilla\firefox\w7b0wgy1.default\storage\default\file++++home+jrmuizel+Downloads+emunit+2015-09-29-emunittest_0.4-Teleporter-u5.2.1p1_hg-e.1.34.11-release-prof+index.html\idb\2083995541%s2fFbid.sqlite-shm

Perhaps we can just hash the paths instead of using the whole thing?

**Comment by rocallahan** [comment]
The first part should be unique enough, the rest is just for informational purposes. I'll just truncate it to 255 bytes.
