### ISSUE TITLE
Documenting required kernel settings

### ISSUE THREAD

**Issue by fmarier** [mozilla/rr#1616]
rr requires these kernel settings in order to run:

    kernel.kptr_restrict=0
    kernel.perf_event_paranoid=1

Should I add this to the [install instructions](https://github.com/mozilla/rr/wiki/Building-And-Installing) or is there a better place for this?

**Comment by rocallahan** [comment]
Why does rr require `kptr_restrict`, do you know?

rr should check these settings and prompt if it detects that these settings need to be changed. The install instructions should mention them, though they're the defaults in Fedora.

**Comment by fmarier** [comment]
> Why does rr require kptr_restrict, do you know?

Sorry, I didn't actually see an rr error related to this one. I did however run `perf record` at rr's suggestion and got this warning message until I disabled `kptr_restrict`:

```
$ perf record ls
WARNING: Kernel address maps (/proc/{kallsyms,modules}) are restricted,
check /proc/sys/kernel/kptr_restrict.

Samples in kernel functions may not be resolved if a suitable vmlinux
file is not found in the buildid cache or in the vmlinux path.

Samples in kernel modules won't be resolved at all.

If some relocation was applied (e.g. kexec) symbols may be misresolved
even with a suitable vmlinux or kallsyms file.

Cannot read kernel map
Couldn't record kernel reference relocation symbol
Symbol resolution may be skewed if relocation was used (e.g. kexec).
Check /proc/kallsyms permission or run as root.
```

`kernel.perf_event_paranoid=3` appears to be the default in Debian.

**Comment by rocallahan** [comment]
OK. AFAIK rr does not care about `kptr_restrict`. `perf` does because it wants to profile what's going on in the kernel.

**Comment by rocallahan** [comment]
OK, now 6966e1258b222cdce1a2e384cf01d28b6877c441 produces a helpful error message when `perf_event_paranoid` has the wrong value. It's still possible to run rr with a higher value by disabling syscall buffering, it'll just be a lot slower.

**Comment by rocallahan** [comment]
And I've updated the wiki. Thanks!
