### ISSUE TITLE
Assertion `i + 1 < mark_vector.size() && mark_vector[i + 1] == m.ptr' failed

### ISSUE THREAD

**Issue by jrmuizel** [mozilla/rr#1618]
I got this when reverse-finishing. I haven't tried reproducing it, but will if I run into it again.

Here's what happened in the gdb session:

0x00007f20fcc83fc9 in traced_raw_syscall (call=call@entry=0x7fff2a027110) at /home/jrmuizel/src/rr/src/preload/preload.c:308
308	  return _raw_syscall(call->no, call->args[0], call->args[1], call->args[2],
(rr) 
Run back to call of #0  0x00007f20fcc83fc9 in traced_raw_syscall (call=call@entry=0x7fff2a027110)
    at /home/jrmuizel/src/rr/src/preload/preload.c:308
0x00007f20fcc84d43 in syscall_hook_internal (call=0x7fff2a027110) at /home/jrmuizel/src/rr/src/preload/preload.c:2071
2071	      return traced_raw_syscall(call);
(rr) 
Run till exit from #0  0x00007f20fcc84d43 in syscall_hook_internal (call=0x7fff2a027110)
    at /home/jrmuizel/src/rr/src/preload/preload.c:2071
syscall_hook (call=0x7fff2a027110) at /home/jrmuizel/src/rr/src/preload/preload.c:2079
2079	  long result = syscall_hook_internal(call);
(rr) 
Run back to call of #0  syscall_hook (call=0x7fff2a027110) at /home/jrmuizel/src/rr/src/preload/preload.c:2079

_syscall_hook_trampoline () at /home/jrmuizel/src/rr/src/preload/syscall_hook.S:190
190	        callq syscall_hook
(rr) 
Run back to call of #0  _syscall_hook_trampoline () at /home/jrmuizel/src/rr/src/preload/syscall_hook.S:190
_syscall_hook_trampoline_48_3d_01_f0_ff_ff () at /home/jrmuizel/src/rr/src/preload/syscall_hook.S:232
232	        callq _syscall_hook_trampoline
(rr) 
Run back to call of #0  _syscall_hook_trampoline_48_3d_01_f0_ff_ff () at /home/jrmuizel/src/rr/src/preload/syscall_hook.S:232
0x00007f20fcc8688f in _stub_buffer () at /home/jrmuizel/src/rr/src/preload/syscall_hook.S:342
342	        .endr
(rr) 
Run back to call of #0  0x00007f20fcc8688f in _stub_buffer () at /home/jrmuizel/src/rr/src/preload/syscall_hook.S:342
bt 9
rr: /home/jrmuizel/src/rr/src/ReplayTimeline.cc:219: void ReplayTimeline::mark_after_singlestep(const ReplayTimeline::Mark&, const ReplayResult&): Assertion `i + 1 < mark_vector.size() && mark_vector[i + 1] == m.ptr' failed.

**Comment by rocallahan** [comment]
130129129f399573dc6be1fddafb7788714b93bb fixed a bug that could have caused this. I'll close this bug now; reopen if it recurs with that commit.
