### ISSUE TITLE
rr tests require gdb but build instructions don't list it as a prerequisite

### ISSUE THREAD

**Issue by pm215** [mozilla/rr#1631]
Some of the rr tests run gdb, but the build instructions (https://github.com/mozilla/rr/wiki/Building-And-Installing) don't list it as a prerequisite package that needs to be installed.

If you don't have gdb then some of the tests fail with 'Failed to exec gdb' and similar errors (but not until quite a way through the very slow 'make check' process). It would be nice if rr's test suite failed faster in this situation.

**Comment by rocallahan** [comment]
> Some of the rr tests run gdb, but the build instructions (https://github.com/mozilla/rr/wiki/Building-And-Installing) don't list it as a prerequisite package that needs to be installed.

OK, I fixed the wiki page.

It would be useful to have a small set of tests which have to pass before we run the rest under `make check`. I have no idea how to do that though...

**Comment by rocallahan** [comment]
I added a build-time check for gdb being present: https://github.com/mozilla/rr/commit/0e3a9c9c72a65cd30aac13b65d60d0b65f135e96
