### ISSUE TITLE
rr doesn't terminate after shutting down firefox

### ISSUE THREAD

**Issue by staktrace** [mozilla/rr#1635]
STR:
- Build master version of rr (currently 11e67a66a2218effb9381b9ac86a2085b0f5d5d1)
- Build gecko (my mozconfig is at https://github.com/staktrace/moz-scripts/blob/6c2e1f4fc4cdc1694078c3dfc6378d5181b31bf0/mozconfig.Linux-host-debug)
- Run ./mach run --debugger=rr
- Firefox will start to the about:home page. Move the mouse around a little bit, I usually hover over the icons near the bottom of the screen, and then ctrl-q to quit
- After this there's some more console output from firefox shutting down, but rr hangs and doesn't terminate. Hitting ctrl-c also doesn't kill it. Expected result here is that rr terminates and gives me back the command line.

In another console, if I run 'ps' I can see that the mach python script is still running, as is rr. Killing rr will terminate the process successfully and everything seems ok.

**Comment by staktrace** [comment]
If I attach to the rr process with gdb and get thread backtraces it seems pretty idle. https://gist.github.com/staktrace/ce020847aff5c4af86bc

**Comment by staktrace** [comment]
Also just to be clear, while firefox is running I can see the firefox and plugin-container processes in 'ps' output, but after I quit firefox, those processes go away and it's just the rr that's left.

**Comment by staktrace** [comment]
I said previously (in https://github.com/mozilla/rr/issues/1614#issuecomment-175739184) that i had a regression range in which this started happening, but now I'm seeing it happen even at the start changeset of that range, which I had thought was good. So it might be intermittent. I'll try to pin down a regression window.

**Comment by bgirard** [comment]
Based on your stack it looks fairly similar to issue 1532.

**Comment by staktrace** [comment]
It might be something like that. I tried bisecting but it seems to happen pretty much as far back as I can go. If I go too far back (like early 2015) in rr history, my firefox build fails to start up under rr.

**Comment by rocallahan** [comment]
I don't see this. I built mozilla-central 2b73b0a4d52b debug, tried following your STR, and everything exits normally. Try a fresh profile maybe?

**Comment by rocallahan** [comment]
Probably same as issue #1655. Closing.
