### ISSUE TITLE
Version of libstdc++.so.6 to be used with rr?

### ISSUE THREAD

**Issue by mijoharas** [mozilla/rr#1637]
In switching from rr version 4.0.3 to 4.1.0 I now experience this error message:

```
rr: relocation error: rr: symbol _ZNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEC1Ev, version GLIBCXX_3.4.21 not defined in file libstdc++.so.6 with link time reference
```

has anything changed about how the binary is built? do I need new libraries?

**Comment by rocallahan** [comment]
I updated my distro to Fedora 23 in the meantime. I guess that has caused this error.

**Comment by rocallahan** [comment]
OK, I've updated the release packages. Please try them again.

**Comment by mijoharas** [comment]
Thanks, works for me again.
