### ISSUE TITLE
"building and installing" tldr should suggest 'make test' rather than 'make check'

### ISSUE THREAD

**Issue by pm215** [mozilla/rr#1647]
The "building and installing" wiki page https://github.com/mozilla/rr/wiki/Building-And-Installing starts with a tldr section. I think the tldr instructions should use "make test" rather than "make check" -- for people who don't know much about rr internals (exactly the people following a wiki tldr instruction list) the 'make test' output provides a more comprehensible view of the test suite and its progress.

**Comment by rocallahan** [comment]
Done
