### ISSUE TITLE
DumpJSStack during replay causes SIGILL, blows up replay

### ISSUE THREAD

**Issue by khuey** [mozilla/rr#1648]
I have a recording that explodes when I try to get the JS stack at a point.

`    (rr) b nsGlobalWindow::PostMessageMoz
    Breakpoint 1 at 0x715f333474b0: nsGlobalWindow::PostMessageMoz. (2 locations)
    (rr) rc
    Continuing.
     
    Breakpoint 1, nsGlobalWindow::PostMessageMoz (this=0x68e328548800, aCx=0x759c02119c00, aMessage=..., aTargetOrigin=...,
        aTransfer=..., aError=...) at /home/khuey/dev/gecko-dev/dom/base/nsGlobalWindow.cpp:8031
    8031      FORWARD_TO_OUTER_OR_THROW(PostMessageMozOuter,
    (rr) js
    0 navigationStatus(child = [object HTMLIFrameElement]) ["http://example.com/tests/dom/security/test/mixedcontentblocker/file_frameNavigation_grandchild.html":48]
        this = [object Window]
     
     
    Program received signal SIGILL, Illegal instruction.
    0x00007fff1ff37782 in ?? ()
    The program being debugged was signaled while in a function called from GDB.
    GDB remains in the frame where the signal was received.
    To change this behavior use "set unwindonsignal on".
    Evaluation of the expression containing the function
    (DumpJSStack()) will be abandoned.
    When the function is done executing, GDB will silently stop.
    (rr) rc
    Continuing.
     
    [Thread 22686.22686] #1 stopped.
    0x00007fff1ff37782 in ?? ()
    (rr) c
    Continuing.
     
    Program received signal SIGILL, Illegal instruction.
    0x00007fff1ff37782 in ?? ()
    (rr) `

**Comment by rocallahan** [comment]
Interesting. Can you print $rsp before you call DumpJSStack? and dump the contents of the memory around 0x00007fff1ff37782 before and after the DumpJSStack? And do a `where` after the SIGILL?

**Comment by khuey** [comment]
`(rr) b nsGlobalWindow::PostMessageMoz
Breakpoint 1 at 0x715f333474b0: nsGlobalWindow::PostMessageMoz. (2 locations)
(rr) rc
Continuing.

Breakpoint 1, nsGlobalWindow::PostMessageMoz (this=0x68e328548800, aCx=0x759c02119c00, aMessage=..., aTargetOrigin=..., 
    aTransfer=..., aError=...) at /home/khuey/dev/gecko-dev/dom/base/nsGlobalWindow.cpp:8031
8031	  FORWARD_TO_OUTER_OR_THROW(PostMessageMozOuter,
(rr) p $rsp
$1 = (void *) 0x7fff1ff37800
(rr) x/i 0x7fff1ff37782
   0x7fff1ff37782:	repz (bad) 
(rr) x/4i 0x7fff1ff37780
   0x7fff1ff37780:	mov    $0x77,%al
   0x7fff1ff37782:	repz (bad) 
   0x7fff1ff37784:	(bad)  
   0x7fff1ff37785:	jg     0x7fff1ff37787
(rr) js
0 navigationStatus(child = [object HTMLIFrameElement]) ["http://example.com/tests/dom/security/test/mixedcontentblocker/file_frameNavigation_grandchild.html":48]
    this = [object Window]


Program received signal SIGILL, Illegal instruction.
0x00007fff1ff37782 in ?? ()
The program being debugged was signaled while in a function called from GDB.
GDB remains in the frame where the signal was received.
To change this behavior use "set unwindonsignal on".
Evaluation of the expression containing the function
(DumpJSStack()) will be abandoned.
When the function is done executing, GDB will silently stop.
(rr) x/4i 0x7fff1ff37780
   0x7fff1ff37780:	mov    $0x77,%al
=> 0x7fff1ff37782:	repz (bad) 
   0x7fff1ff37784:	(bad)  
   0x7fff1ff37785:	jg     0x7fff1ff37787
(rr) info share
From                To                  Syms Read   Shared Object Library
0x00004ce039f3ac20  0x00004ce039f6e477  Yes         /home/khuey/dev/obj-rr/bin/../lib/librrpreload.so
0x00007fff1ffe2a90  0x00007fff1ffefc41  Yes         /lib/x86_64-linux-gnu/libpthread.so.0
0x000000006fdfce60  0x000000006fdfda5e  Yes         /lib/x86_64-linux-gnu/libdl.so.2
0x0000471877973020  0x0000471877a1f279  Yes (*)     /usr/lib/x86_64-linux-gnu/libstdc++.so.6
0x0000189f102675a0  0x0000189f102d8c61  Yes         /lib/x86_64-linux-gnu/libm.so.6
0x0000471877c6daf0  0x0000471877c7d845  Yes (*)     /lib/x86_64-linux-gnu/libgcc_s.so.1
0x00007f925e21a4f0  0x00007f925e36d304  Yes         /lib/x86_64-linux-gnu/libc.so.6
0x00007f925e5c5aa0  0x00007f925e5e15e0  Yes         /lib64/ld-linux-x86-64.so.2
0x000058543da12d70  0x000058543da43b4f  Yes         /home/khuey/dev/gecko-dev/obj-x86_64-unknown-linux-gnu/dist/bin/libnspr4.so
0x0000748d2d3ed5a0  0x0000748d2d3ef555  Yes         /home/khuey/dev/gecko-dev/obj-x86_64-unknown-linux-gnu/dist/bin/libplc4.so
0x00007f925e7ec0b0  0x00007f925e7ed7ff  Yes         /home/khuey/dev/gecko-dev/obj-x86_64-unknown-linux-gnu/dist/bin/libplds4.so
0x00003bdd2add5140  0x00003bdd2adebc10  Yes         /home/khuey/dev/gecko-dev/obj-x86_64-unknown-linux-gnu/dist/bin/libnssutil3.so
0x00004f343a4ad610  0x00004f343a5c1743  Yes         /home/khuey/dev/gecko-dev/obj-x86_64-unknown-linux-gnu/dist/bin/libnss3.so
0x00007532302b72e0  0x00007532302d513d  Yes         /home/khuey/dev/gecko-dev/obj-x86_64-unknown-linux-gnu/dist/bin/libsmime3.so
0x000058543d7a1de0  0x000058543d7eb632  Yes         /home/khuey/dev/gecko-dev/obj-x86_64-unknown-linux-gnu/dist/bin/libssl3.so
0x000031424f242bf0  0x000031424f337faf  Yes         /home/khuey/dev/gecko-dev/obj-x86_64-unknown-linux-gnu/dist/bin/libmozsqlite3.so
0x0000435373c15190  0x0000435373c3161f  Yes         /home/khuey/dev/gecko-dev/obj-x86_64-unknown-linux-gnu/dist/bin/liblgpllibs.so
0x000058543da589b0  0x000058543da58cf8  Yes         /home/khuey/dev/gecko-dev/obj-x86_64-unknown-linux-gnu/dist/bin/libmozgtk.so
0x00007f925d98d430  0x00007f925dc983d9  Yes (*)     /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
0x0000471877ea6d30  0x0000471877f0b3e9  Yes (*)     /usr/lib/x86_64-linux-gnu/libgdk-3.so.0
0x00007f925d7081b0  0x00007f925d7090b5  Yes (*)     /usr/lib/x86_64-linux-gnu/libgmodule-2.0.so.0
0x00004cf81d8b0920  0x00004cf81d8b5616  Yes (*)     /usr/lib/x86_64-linux-gnu/libpangocairo-1.0.so.0
0x00003d547a4dc870  0x00003d547a5642e4  Yes (*)     /usr/lib/x86_64-linux-gnu/libX11.so.6
0x00007f925e7f31e0  0x00007f925e7fd112  Yes (*)     /usr/lib/x86_64-linux-gnu/libXi.so.6
0x00004353739e5530  0x00004353739e7756  Yes (*)     /usr/lib/x86_64-linux-gnu/libXfixes.so.3
0x000030b71f303410  0x000030b71f3043a9  Yes (*)     /usr/lib/x86_64-linux-gnu/libcairo-gobject.so.2
0x000066fb332c9ca0  0x000066fb3338afc7  Yes (*)     /usr/lib/x86_64-linux-gnu/libcairo.so.2
0x000024ed36c41190  0x000024ed36c53969  Yes (*)     /usr/lib/x86_64-linux-gnu/libgdk_pixbuf-2.0.so.0
0x000000006820b800  0x0000000068217c43  Yes (*)     /usr/lib/x86_64-linux-gnu/libatk-1.0.so.0
0x0000471878160490  0x00004718781744a9  Yes (*)     /usr/lib/x86_64-linux-gnu/libatk-bridge-2.0.so.0
0x00003e663fbbb870  0x00003e663fbf7b11  Yes (*)     /usr/lib/x86_64-linux-gnu/libepoxy.so.0
0x00007f925d4f83d0  0x00007f925d5008db  Yes (*)     /usr/lib/x86_64-linux-gnu/libpangoft2-1.0.so.0
0x000058543d555e80  0x000058543d575e76  Yes (*)     /usr/lib/x86_64-linux-gnu/libpango-1.0.so.0
0x0000270710c39ca0  0x0000270710c57c5d  Yes (*)     /usr/lib/x86_64-linux-gnu/libfontconfig.so.1
0x000025ed3acb1f30  0x000025ed3ad818ab  Yes (*)     /usr/lib/x86_64-linux-gnu/libgio-2.0.so.0
0x0000435373ce7f80  0x0000435373d18996  Yes (*)     /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
0x00007fff1f449800  0x00007fff1f4c05a9  Yes (*)     /lib/x86_64-linux-gnu/libglib-2.0.so.0
0x0000000000441af0  0x00000000004423ec  Yes (*)     /usr/lib/x86_64-linux-gnu/libXinerama.so.1
0x0000565a1594ec70  0x0000565a15954a82  Yes (*)     /usr/lib/x86_64-linux-gnu/libXrandr.so.2
0x00007f925ea03420  0x00007f925ea07e20  Yes (*)     /usr/lib/x86_64-linux-gnu/libXcursor.so.1
0x00005975348ebc40  0x00005975348ec618  Yes (*)     /usr/lib/x86_64-linux-gnu/libXcomposite.so.1
0x00007f1d008cab90  0x00007f1d008cb49b  Yes (*)     /usr/lib/x86_64-linux-gnu/libXdamage.so.1
0x000061444a81de70  0x000061444a838895  Yes (*)     /usr/lib/x86_64-linux-gnu/libxkbcommon.so.0
0x00000594075d8240  0x00000594075d9dd9  Yes (*)     /usr/lib/x86_64-linux-gnu/libwayland-cursor.so.0
0x00004cf81dab96e0  0x00004cf81dab98b6  Yes (*)     /usr/lib/x86_64-linux-gnu/libwayland-egl.so.1
0x0000000070005c00  0x000000007000a18f  Yes (*)     /usr/lib/x86_64-linux-gnu/libwayland-client.so.0
0x000066fb33049210  0x000066fb33092afa  Yes (*)     /usr/lib/x86_64-linux-gnu/libmirclient.so.9
0x00001ee54f513590  0x00001ee54f51d39f  Yes (*)     /usr/lib/x86_64-linux-gnu/libXext.so.6
0x000003d9701e1190  0x000003d9701e4167  Yes         /lib/x86_64-linux-gnu/librt.so.1
0x0000000067d64b90  0x0000000067dd3bd2  Yes (*)     /usr/lib/x86_64-linux-gnu/libfreetype.so.6
0x000064124465d620  0x000064124466be35  Yes (*)     /usr/lib/x86_64-linux-gnu/libxcb.so.1
0x000024ed369979e0  0x000024ed36a21ba0  Yes (*)     /usr/lib/x86_64-linux-gnu/libpixman-1.so.0
0x00004353737c1b00  0x00004353737db0f3  Yes (*)     /lib/x86_64-linux-gnu/libpng12.so.0
0x000045b21512cdf0  0x000045b21512d903  Yes (*)     /usr/lib/x86_64-linux-gnu/libxcb-shm.so.0
0x00007f925ec0e4a0  0x00007f925ec1191a  Yes (*)     /usr/lib/x86_64-linux-gnu/libxcb-render.so.0
0x00007f925d2e8ad0  0x00007f925d2ee9e5  Yes (*)     /usr/lib/x86_64-linux-gnu/libXrender.so.1
0x000056d31f2d7df0  0x000056d31f2e8870  Yes (*)     /lib/x86_64-linux-gnu/libz.so.1
0x000078864079c5a0  0x00007886407addd8  Yes (*)     /usr/lib/x86_64-linux-gnu/libatspi.so.0
0x000058543da66810  0x000058543da91594  Yes (*)     /lib/x86_64-linux-gnu/libdbus-1.so.3
0x0000081d7703a6a0  0x0000081d77075639  Yes (*)     /usr/lib/x86_64-linux-gnu/libharfbuzz.so.0
0x000020d920f05bd0  0x000020d920f0912c  Yes (*)     /usr/lib/x86_64-linux-gnu/libthai.so.0
0x0000000067b33b90  0x0000000067b4be39  Yes (*)     /lib/x86_64-linux-gnu/libexpat.so.1
0x00007f925ee1abc0  0x00007f925ee2d7bb  Yes (*)     /lib/x86_64-linux-gnu/libselinux.so.1
0x00007886405769d0  0x0000788640585f51  Yes         /lib/x86_64-linux-gnu/libresolv.so.2
0x000069e46d8c77e0  0x000069e46d8cbfec  Yes (*)     /usr/lib/x86_64-linux-gnu/libffi.so.6
0x000058543d2dc600  0x000058543d32afc6  Yes (*)     /lib/x86_64-linux-gnu/libpcre.so.3
0x00004a2a1bf273a0  0x00004a2a1bf47527  Yes (*)     /usr/lib/x86_64-linux-gnu/libmircommon.so.5
0x00003bdd2b01d260  0x00003bdd2b0468ab  Yes (*)     /usr/lib/x86_64-linux-gnu/libmirprotobuf.so.3
0x0000748d2d1e9030  0x0000748d2d1e9cd6  Yes (*)     /usr/lib/x86_64-linux-gnu/libboost_system.so.1.58.0
0x00006ca577020460  0x00006ca5770389e6  Yes (*)     /usr/lib/x86_64-linux-gnu/libprotobuf-lite.so.9
0x00000594073d3e50  0x00000594073d4acc  Yes (*)     /usr/lib/x86_64-linux-gnu/libXau.so.6
0x000030ef23a05210  0x000030ef23a06bf6  Yes (*)     /usr/lib/x86_64-linux-gnu/libXdmcp.so.6
0x000045517a144300  0x000045517a19601a  Yes (*)     /lib/x86_64-linux-gnu/libsystemd.so.0
0x00004f85559e43b0  0x00004f85559f59f5  Yes (*)     /usr/lib/x86_64-linux-gnu/libgraphite2.so.3
0x00006b971dd1e170  0x00006b971dd21455  Yes (*)     /usr/lib/x86_64-linux-gnu/libdatrie.so.1
0x00001e944d7399c0  0x00001e944d7466cf  Yes (*)     /usr/lib/x86_64-linux-gnu/libboost_filesystem.so.1.58.0
0x00004f343a2740d0  0x00004f343a28824d  Yes (*)     /lib/x86_64-linux-gnu/liblzma.so.5
0x000025ed3b006e00  0x000025ed3b0a8448  Yes (*)     /lib/x86_64-linux-gnu/libgcrypt.so.20
0x00007f925d0d66d0  0x00007f925d0df299  Yes (*)     /lib/x86_64-linux-gnu/libgpg-error.so.0
0x0000715f31bd1c40  0x0000715f37cc1e60  Yes         /home/khuey/dev/gecko-dev/obj-x86_64-unknown-linux-gnu/dist/bin/libxul.so
0x00007f925ce09190  0x00007f925ce91052  Yes (*)     /usr/lib/x86_64-linux-gnu/libasound.so.2
0x000000000064dcc0  0x000000000065fce1  Yes (*)     /usr/lib/x86_64-linux-gnu/libdbus-glib-1.so.2
0x000031424efde1b0  0x000031424f01a0a9  Yes (*)     /usr/lib/x86_64-linux-gnu/libXt.so.6
0x000025e10f91dbc0  0x000025e10f921ade  Yes (*)     /usr/lib/x86_64-linux-gnu/libSM.so.6
0x000027dd410316b0  0x000027dd4103e71a  Yes (*)     /usr/lib/x86_64-linux-gnu/libICE.so.6
0x00007f925cbdb550  0x00007f925cbdcbc1  Yes (*)     /lib/x86_64-linux-gnu/libuuid.so.1
0x000047c75ac93740  0x000047c75ac94e4e  Yes         /usr/lib/x86_64-linux-gnu/gconv/UTF-16.so
0x000002ae24778340  0x000002ae24779edc  Yes (*)     /usr/lib/x86_64-linux-gnu/gtk-3.0/modules/libunity-gtk-module.so
0x000041945a389ef0  0x000041945a391ecc  Yes (*)     /usr/lib/x86_64-linux-gnu/libunity-gtk3-parser.so.0
0x00006a5b398e7be0  0x00006a5b398ec8ce  Yes (*)     /usr/lib/x86_64-linux-gnu/gio/modules/libdconfsettings.so
0x00004718776c1b80  0x00004718776dbc46  Yes (*)     /usr/lib/x86_64-linux-gnu/gio/modules/libgvfsdbus.so
0x00002e3e36980400  0x00002e3e36996d06  Yes (*)     /usr/lib/x86_64-linux-gnu/gvfs/libgvfscommon.so
---Type <return> to continue, or q <return> to quit---
0x00006af626f03750  0x00006af626f14190  Yes (*)     /lib/x86_64-linux-gnu/libudev.so.1
0x00007fff202010e0  0x00007fff20203190  Yes (*)     /usr/lib/x86_64-linux-gnu/gtk-3.0/modules/libcanberra-gtk-module.so
0x000045b215331c50  0x000045b21533321e  Yes (*)     /usr/lib/x86_64-linux-gnu/libcanberra-gtk3.so.0
0x00003ab94ca01be0  0x00003ab94ca0b20a  Yes (*)     /usr/lib/x86_64-linux-gnu/libcanberra.so.0
0x00004f343a7fbda0  0x00004f343a80016c  Yes (*)     /usr/lib/x86_64-linux-gnu/libvorbisfile.so.3
0x000071a57d1aaa40  0x000071a57d1b5b53  Yes (*)     /usr/lib/x86_64-linux-gnu/libtdb.so.1
0x00007f925f83bf60  0x00007f925f840452  Yes (*)     /usr/lib/x86_64-linux-gnu/libltdl.so.7
0x000032a15ffc0dd0  0x000032a15ffd745d  Yes (*)     /usr/lib/x86_64-linux-gnu/libvorbis.so.0
0x00002cf2658dfa70  0x00002cf2658e3c05  Yes (*)     /usr/lib/x86_64-linux-gnu/libogg.so.0
0x0000083e62990230  0x0000083e62997393  Yes         /lib/x86_64-linux-gnu/libnss_files.so.2
0x0000748d2d3f8830  0x0000748d2d42379f  Yes         /home/khuey/dev/gecko-dev/obj-x86_64-unknown-linux-gnu/dist/bin/browser/components/libbrowsercomps.so
0x0000705b40f51e80  0x0000705b40f53cf9  Yes (*)     /usr/lib/x86_64-linux-gnu/gdk-pixbuf-2.0/2.10.0/loaders/libpixbufloader-png.so
0x00004f343a02ea60  0x00004f343a05b649  Yes (*)     /usr/lib/x86_64-linux-gnu/libpulse.so.0
0x000066fb32e2a800  0x000066fb32e2f612  Yes (*)     /lib/x86_64-linux-gnu/libjson-c.so.2
0x000041b433767d30  0x000041b4337a8cf9  Yes (*)     /usr/lib/x86_64-linux-gnu/pulseaudio/libpulsecommon-6.0.so
0x0000471878397d70  0x000047187839b798  Yes (*)     /lib/x86_64-linux-gnu/libwrap.so.0
0x00000594077e50b0  0x000005940782739c  Yes (*)     /usr/lib/x86_64-linux-gnu/libsndfile.so.1
0x000068e3282d0300  0x000068e3282d2988  Yes (*)     /usr/lib/x86_64-linux-gnu/libasyncns.so.0
0x00001f592a9710f0  0x00001f592a97dee1  Yes         /lib/x86_64-linux-gnu/libnsl.so.1
0x000058f51c11d420  0x000058f51c17ecfd  Yes (*)     /usr/lib/x86_64-linux-gnu/libFLAC.so.8
0x00001f592ab9aaa0  0x00001f592ab9d0e7  Yes (*)     /usr/lib/x86_64-linux-gnu/libvorbisenc.so.2
0x000047187746c320  0x00004718774a6d90  Yes         /home/khuey/dev/gecko-dev/obj-x86_64-unknown-linux-gnu/dist/bin/libsoftokn3.so
0x00004f343aa061d0  0x00004f343aa288b0  Yes         /home/khuey/dev/gecko-dev/obj-x86_64-unknown-linux-gnu/dist/bin/libnssdbm3.so
0x0000211d70372080  0x0000211d7040b3c0  Yes         /home/khuey/dev/gecko-dev/obj-x86_64-unknown-linux-gnu/dist/bin/libfreebl3.so
0x00000000678aa310  0x00000000678be310  Yes         /home/khuey/dev/gecko-dev/obj-x86_64-unknown-linux-gnu/dist/bin/libnssckbi.so
0x00006ee66327c240  0x00006ee6632946b5  Yes (*)     /usr/lib/x86_64-linux-gnu/libgconf-2.so.4
0x000024ed36e6fee0  0x000024ed36e71ff6  Yes (*)     /usr/lib/x86_64-linux-gnu/gtk-3.0/3.0.0/immodules/im-ibus.so
0x000033ae6500db60  0x000033ae6502f29b  Yes (*)     /usr/lib/x86_64-linux-gnu/libibus-1.0.so.5
                                        No          /tmp/tmpTS_ZaM.mozrunner/plugins/libnptest.so
0x00004f3439a41270  0x00004f3439c9a3ce  Yes (*)     /usr/lib/x86_64-linux-gnu/libgtk-x11-2.0.so.0
0x000076306b59f9d0  0x000076306b5f659b  Yes (*)     /usr/lib/x86_64-linux-gnu/libgdk-x11-2.0.so.0
                                        No          /tmp/tmpTS_ZaM.mozrunner/plugins/libnpswftest.so
                                        No          /tmp/tmpTS_ZaM.mozrunner/plugins/libnpthirdtest.so
                                        No          /tmp/tmpTS_ZaM.mozrunner/plugins/libnpctrltest.so
                                        No          /tmp/tmpTS_ZaM.mozrunner/plugins/libnpsecondtest.so
                                        No          /tmp/tmpTS_ZaM.mozrunner/plugins/libnptestjava.so
0x00006b971c963cb0  0x00006b971d6a3ea8  Yes (*)     /usr/lib/flashplugin-installer/libflashplayer.so
0x00001fcb3ef0b6c0  0x00001fcb3ef0b83a  Yes (*)     /usr/lib/x86_64-linux-gnu/libgthread-2.0.so.0
0x000043193fd67730  0x000043193fd68e2d  Yes (*)     /usr/lib/mozilla/plugins/libgnome-shell-browser-plugin.so
0x000000006843edd0  0x000000006845126d  Yes (*)     /usr/lib/x86_64-linux-gnu/libjson-glib-1.0.so.0
0x00007f92522fdbb0  0x00007f92522fdfa9  Yes (*)     /usr/lib/x86_64-linux-gnu/gdk-pixbuf-2.0/2.10.0/loaders/libpixbufloader-svg.so
0x00004b866b10fc40  0x00004b866b133b0f  Yes (*)     /usr/lib/x86_64-linux-gnu/librsvg-2.so.2
0x00006c7c18f4ccd0  0x00006c7c18f6ab95  Yes (*)     /usr/lib/x86_64-linux-gnu/libcroco-0.6.so.3
0x0000592a54ff2950  0x0000592a5511f167  Yes (*)     /usr/lib/x86_64-linux-gnu/libxml2.so.2
0x00001dac5ae346d0  0x00001dac5aeeefd3  Yes (*)     /usr/lib/x86_64-linux-gnu/libicuuc.so.55
0x000030b71d749570  0x000030b71d749670  Yes (*)     /usr/lib/x86_64-linux-gnu/libicudata.so.55
0x0000128e1f266cd0  0x0000128e1f267a8c  Yes (*)     /usr/lib/x86_64-linux-gnu/libXss.so.1
0x000040f03457b880  0x000040f034598bab  Yes         /home/khuey/dev/gecko-dev/obj-x86_64-unknown-linux-gnu/dist/bin/libmozavutil.so
0x0000291b606717f0  0x0000291b609261ad  Yes         /home/khuey/dev/gecko-dev/obj-x86_64-unknown-linux-gnu/dist/bin/libmozavcodec.so
0x00003c95448ba4a0  0x00003c954508bfa5  Yes (*)     /usr/lib/x86_64-linux-gnu/libavcodec-ffmpeg.so.56
0x00001dac5abc5b40  0x00001dac5abd7e11  Yes (*)     /usr/lib/x86_64-linux-gnu/libswresample-ffmpeg.so.1
0x000030593999ca10  0x00003059399d46b3  Yes (*)     /usr/lib/x86_64-linux-gnu/libavutil-ffmpeg.so.54
0x000066fb33702090  0x000066fb3370dfff  Yes (*)     /usr/lib/x86_64-linux-gnu/libva.so.1
0x000048e67f481b00  0x000048e67f4c7418  Yes (*)     /usr/lib/x86_64-linux-gnu/libzvbi.so.0
0x000078864005fb20  0x00007886400c8b40  Yes (*)     /usr/lib/x86_64-linux-gnu/libxvidcore.so.4
0x00007f926263c560  0x00007f926289058c  Yes (*)     /usr/lib/x86_64-linux-gnu/libx265.so.59
0x00000a667124aac0  0x00000a667133de82  Yes (*)     /usr/lib/x86_64-linux-gnu/libx264.so.146
0x0000638d04280c00  0x0000638d042bd985  Yes (*)     /usr/lib/x86_64-linux-gnu/libwebp.so.5
0x000068e328601a00  0x000068e32861ff92  Yes (*)     /usr/lib/x86_64-linux-gnu/libwavpack.so.1
0x00002bf25da54840  0x00002bf25dc135cb  Yes (*)     /usr/lib/x86_64-linux-gnu/libvpx.so.2
0x0000641244433530  0x000064124443fbf5  Yes (*)     /usr/lib/x86_64-linux-gnu/libtwolame.so.0
0x000037823b947400  0x000037823b971eea  Yes (*)     /usr/lib/x86_64-linux-gnu/libtheoraenc.so.1
0x0000597917401290  0x0000597917416a28  Yes (*)     /usr/lib/x86_64-linux-gnu/libtheoradec.so.1
0x000030ed632ea780  0x000030ed632f9745  Yes (*)     /usr/lib/x86_64-linux-gnu/libspeex.so.1
0x00005d8f03dee0c0  0x00005d8f03df52fc  Yes (*)     /usr/lib/x86_64-linux-gnu/libshine.so.3
0x00007f9251b3a1d0  0x00007f9251bb1e72  Yes (*)     /usr/lib/x86_64-linux-gnu/libschroedinger-1.0.so.0
0x000048285a0b7f40  0x000048285a0f248d  Yes (*)     /usr/lib/x86_64-linux-gnu/libopus.so.0
0x0000482859e96d60  0x0000482859eaf534  Yes (*)     /usr/lib/x86_64-linux-gnu/libopenjpeg.so.5
0x00006c7c19186d40  0x00006c7c191b486f  Yes (*)     /usr/lib/x86_64-linux-gnu/libmp3lame.so.0
0x00000000705012a0  0x000000007050b164  Yes (*)     /usr/lib/x86_64-linux-gnu/libgsm.so.1
0x00000a66715ec5a0  0x00000a66715fa8ae  Yes (*)     /usr/lib/x86_64-linux-gnu/libcrystalhd.so.3
0x00003a2029264c50  0x00003a20292911ac  Yes (*)     /usr/lib/x86_64-linux-gnu/libsoxr.so.0
0x000024ed36785eb0  0x000024ed3678a8b5  Yes (*)     /usr/lib/x86_64-linux-gnu/libnuma.so.1
0x00002b39005e4410  0x00002b39006368df  Yes (*)     /usr/lib/x86_64-linux-gnu/liborc-0.4.so.0
0x000009501c6ba1f0  0x000009501c6ce04e  Yes (*)     /usr/lib/x86_64-linux-gnu/libgomp.so.1
0x000030f114b2d320  0x000030f114cb24dc  Yes (*)     /usr/lib/x86_64-linux-gnu/x265-10bit/libx265.so.59
(*): Shared library is missing debugging information.
(rr) when
Traceback (most recent call last):
  File "<string>", line 51, in invoke
  File "<string>", line 60, in rr_cmd
gdb.error: Remote connection closed
Error occurred in Python command: Remote connection closed
(rr)`

**Comment by rocallahan** [comment]
OK, how about enabling #define DEBUGTAG in GdbConnection and putting those results somewhere?

**Comment by khuey** [comment]
http://people.mozilla.org/~khuey/rr-1648.txt

**Comment by rocallahan** [comment]
OK, please update to master (added more logging) and do that again, with DiversionSession DEBUGTAG enabled, and dump the memory from 0x7fff1ff37760 to 0x7fff1ff37790 as bytes please.

**Comment by khuey** [comment]
http://people.mozilla.org/~khuey/rr-1648-2.txt

**Comment by khuey** [comment]
I updated that file based on our IRC conversation.

**Comment by rocallahan** [comment]
This is probably a regression since ac4bb9d8bdb12f8432596c1fd2d11385875c0329 but I'm not sure exactly what the bug is.

**Comment by khuey** [comment]
Verified.
