### ISSUE TITLE
Assertion `t->regs().syscall_result_signed() == -syscall_state.expect_errno' failed to hold. Expected ENOSYS for 'getcpu' but got result 0; execution of syscall unsupported by rr

### ISSUE THREAD

**Issue by guilhem-bichot** [mozilla/rr#1650]
Hello. After reading an enthusiastic blog post about rr, I tried it with the MySQL server. It crashed at MySQL's startup with this:

[FATAL /home/roc/rr/rr/src/record_syscall.cc:3134:rec_process_syscall_arch() errno: 0 'Success'] 
 (task 3740 (rec:3740) at time 11883)
 ->  Assertion `t->regs().syscall_result_signed() == -syscall_state.expect_errno' failed to hold. Expected ENOSYS for 'getcpu' but got result 0; execution of syscall unsupported by rr
Launch gdb with
  gdb /home/mysql_src/git/cte/build_debug/sql/mysqld
and attach to the rr debug server with:
  target remote :3740

As it is recommended to file such issue, I am doing it.
I have rr-4.1.0-Linux-x86_64.deb on
4.2.0-27-generic #32-Ubuntu SMP Fri Jan 22 04:49:08 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

**Comment by rocallahan** [comment]
If an application uses `getcpu` heavily, it will be slow in rr but we could speed it up by implementing syscall buffering for `getcpu`. I'd rather not do that unless we need to.
