### ISSUE TITLE
rr immediately fails to build if your compiler is clang, with "clang: error: argument unused during compilation: '-pthread'"

### ISSUE THREAD

**Issue by dholbert** [mozilla/rr#1659]
STR:
 1. Have these environmental variables set:
CC=clang
CXX=clang++

 2. Run the rr build instructions -- in particular:
>     mkdir obj
>     cd obj
>     cmake ..
>     make -j8

ACTUAL RESULTS:
cmake implies that all will be well:
> -- The C compiler identification is Clang 3.8.0
> -- The CXX compiler identification is Clang 3.8.0
> [...]
> -- Check for working CXX compiler: /usr/bin/clang++-3.8
> -- Check for working CXX compiler: /usr/bin/clang++-3.8 -- works

...but you end up failing quickly with:
> [  2%] Generating SyscallEnumsX86.generated
> Building C object CMakeFiles/rrpreload_32.dir/32/preload.c.o
> [  2%] Built target Pages
> clang: error: argument unused during compilation: '-pthread'

EXPECTED RESULTS:
No such build error. I'm guessing we're treating warnings as errors, but we shouldn't be making clang treat this "argument unused during compilation" warning as an error.

**Comment by dholbert** [comment]
I'm on 64-bit Ubuntu Linux 15.10, if it matters, and I'm using clang 3.8 installed via the repository information at http://llvm.org/apt/.  (I suspect this affects earlier clang versions as well.)

**Comment by rocallahan** [comment]
https://github.com/mozilla/rr/commit/9d54c080005762ed3be9d010a99d88507e7d1a1c makes rr work with clang for me (passing tests).

**Comment by dholbert** [comment]
Works for me now, too.  (Builds & passes tests. I happen to be using clang 3.7 [not 3.8] now because I'm on a different machine, but I doubt that matters.)

Thanks!
