### ISSUE TITLE
several tests failed

### ISSUE THREAD

**Issue by portnoy** [mozilla/rr#1669]
I compiled rr on CentOS 7.2 running kernel 3.10.0-327.4.5.el7.x86_64 on Intel(R) Core(TM) i7-3770 CPU
'make test' failures are below. What are the implications if any?

The following tests FAILED:
	 83 - fcntl_seals (Failed)
	 84 - fcntl_seals-no-syscallbuf (Failed)
	157 - memfd_create (Failed)
	158 - memfd_create-no-syscallbuf (Failed)
	439 - vm_readv_writev (Failed)
	440 - vm_readv_writev-no-syscallbuf (Failed)
	593 - thread_exit_signal (Failed)
	594 - thread_exit_signal-no-syscallbuf (Failed)

**Comment by rocallahan** [comment]
Probably innocuous. Need the full output of 'make check'...

**Comment by portnoy** [comment]
Sure, attaching. [rr-make-check.txt.gz](https://github.com/mozilla/rr/files/164350/rr-make-check.txt.gz)

**Comment by rocallahan** [comment]
Thanks.

`fcntl_seals` and `memfd_create` are failing because `syscall(RR_memfd_create, TEST_MEMFD, MFD_ALLOW_SEALING)` is failing with `EINVAL`. I have no idea why that would happen. Is it possible that your kernel supports `memfd_create(2)` but not `MFD_ALLOW_SEALING`? Could you look into that?

The `vm_readv_writev` test failed at the line
````
test_assert(4 == process_vm_writev(getpid(), in_iov, 2, out_iov, 2, 0));
````
Probably need to debug that and find out what `process_vm_writev` actually returned.

**Comment by rocallahan** [comment]
> fcntl_seals and memfd_create are failing because syscall(RR_memfd_create, TEST_MEMFD, MFD_ALLOW_SEALING) is failing with EINVAL. I have no idea why that would happen. Is it possible that your kernel supports memfd_create(2) but not MFD_ALLOW_SEALING? Could you look into that?

Well, I assume that's the problem, so I pushed a fix for that.

**Comment by rocallahan** [comment]
`thread_exit_signal` looks like an actual bug. `ls -l /tmp/rr-test-thread_exit_signal-rqXC1ZnCK/latest-trace` would be useful.

**Comment by rocallahan** [comment]
None of these issues are likely to affect real rr usage, but I do like to have tests passing everywhere.

**Comment by portnoy** [comment]
```
ls -l /tmp/rr-test-thread_exit_signal-rqXC1ZnCK/latest-trace/
total 160
-rw-rw-r-- 1 eugene eugene   2773 Mar  8 18:15 args_env
-r-------- 1 eugene eugene  37855 Mar  8 18:15 data
-r-------- 1 eugene eugene   3012 Mar  8 18:15 data_header
-r-------- 1 eugene eugene 100702 Mar  8 18:15 events
-r-------- 1 eugene eugene   1472 Mar  8 18:15 mmaps
-r-------- 1 eugene eugene   1258 Mar  8 18:15 tasks
-rw-rw-r-- 1 eugene eugene      3 Mar  8 18:15 version
```
would you like me to attach the contents as well?

**Comment by rocallahan** [comment]
Add `-F` to `DEFAULT_FLAGS` in util.sh, then in $RR/src/test run `bash thread_exit_signal.run -b $RR $RR_OBJ thread_exit_signal`. The test should run and during recording rr should hang; I expect we get an assertion failure in `check_signals_while_exiting`, which you should be able to see if you connect gdb to the rr process.

**Comment by portnoy** [comment]
It was actually simpler, than that:
thread_exit_signal.run had
`wait -n %1 || ( failed "rr died" && exit 1 )`

which was leading to
```
thread_exit_signal.run: line 17: wait: -n: invalid option
wait: usage: wait [id]
Test 'thread_exit_signal' FAILED: rr died
``` 
I removed the offending option:
`wait %1 || ( failed "rr died" && exit 1 )`

and after this fix, the threat_exit_signal failures I reported earlier are gone:
```
99% tests passed, 6 tests failed out of 766

The following tests FAILED:
	 83 - fcntl_seals (Failed)
	 84 - fcntl_seals-no-syscallbuf (Failed)
	157 - memfd_create (Failed)
	158 - memfd_create-no-syscallbuf (Failed)
	439 - vm_readv_writev (Failed)
	440 - vm_readv_writev-no-syscallbuf (Failed)
```

**Comment by rocallahan** [comment]
Thanks!

>      83 - fcntl_seals (Failed)
>      84 - fcntl_seals-no-syscallbuf (Failed)
>     157 - memfd_create (Failed)
>     158 - memfd_create-no-syscallbuf (Failed)

These should be fixed on master.

`vm_readv_writev` needs debugging.

**Comment by portnoy** [comment]
100% tests passed, 0 tests failed out of 826

Thank you!
