### ISSUE TITLE
rr tip crashes while trying to record Firefox (at browser startup)

### ISSUE THREAD

**Issue by bzbarsky** [mozilla/rr#1672]
Steps to reproduce, on Ubuntu:

1. Check out revision 0068f44 of rr.  Compile it.
2. Check out revision d0fa0d383880 of Firefox, compile it (debug build).
3. rr firefox

I get a segmentation fault on a null-deref.  gdb output:

>Program received signal SIGSEGV, Segmentation fault.
0x00000000005a19dc in Task::session (this=0x0) at /home/bzbarsky/mozilla/rr/rr/src/task.h:845
845       Session& session() const { return *session_; }
(gdb) bt
#0  0x00000000005a19dc in Task::session (this=0x0) at /home/bzbarsky/mozilla/rr/rr/src/task.h:845
#1  0x00000000006aa652 in Task::replay_session (this=0x0) at /home/bzbarsky/mozilla/rr/rr/src/task.cc:663
#2  0x00000000006adb5a in Task::current_trace_frame (this=0x0) at /home/bzbarsky/mozilla/rr/rr/src/task.cc:1519
#3  0x000000000065e916 in Registers::compare_register_files (t=0x0, name1=0x0, reg1=..., name2=0x0, reg2=..., 
    mismatch_behavior=EXPECT_MISMATCHES) at /home/bzbarsky/mozilla/rr/rr/src/Registers.cc:423
#4  0x00000000005cd51c in Registers::matches (this=0x97b750, other=...) at /home/bzbarsky/mozilla/rr/rr/src/Registers.h:323
#5  0x00000000006b0a35 in Task::maybe_in_spinlock (this=0x97b5d0) at /home/bzbarsky/mozilla/rr/rr/src/task.cc:2196
#6  0x000000000062e5a7 in RecordSession::prepare_to_inject_signal (this=0x979ea0, t=0x97b5d0, step_state=0x7fffffffe370)
    at /home/bzbarsky/mozilla/rr/rr/src/RecordSession.cc:1248
#7  0x000000000062f5f1 in RecordSession::record_step (this=0x979ea0)
    at /home/bzbarsky/mozilla/rr/rr/src/RecordSession.cc:1459
#8  0x0000000000628549 in record (args=..., flags=...) at /home/bzbarsky/mozilla/rr/rr/src/RecordCommand.cc:200
#9  0x00000000006287b5 in RecordCommand::run (this=0x976400 <RecordCommand::singleton>, args=...)
    at /home/bzbarsky/mozilla/rr/rr/src/RecordCommand.cc:244
#10 0x000000000061557a in main (argc=2, argv=0x7fffffffe608) at /home/bzbarsky/mozilla/rr/rr/src/main.cc:262

**Comment by rocallahan** [comment]
https://github.com/mozilla/rr/commit/d9587be4790adb9310a034fdc85d0d0c2485687d
