### ISSUE TITLE
Fatal error in gdb connection

### ISSUE THREAD

**Issue by yuyichao** [mozilla/rr#1677]
When `rr replay`ing julia script with debugger attached, I repeatedly get the following error if I accidentally pressed enter,

```
yuyichao% rr julia -e 'for i in 1:100 gc(true) end'
rr: Saving the execution of `julia' to trace directory `/home/yuyichao/.local/share/rr/julia-60'.
office:~
yuyichao% rr replay
GNU gdb (GDB) 7.11
Copyright (C) 2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-pc-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from /usr/bin/julia...done.
Really redefine built-in command "restart"? (y or n) [answered Y; input not from terminal]
Remote debugging using 127.0.0.1:19034
warning: remote target does not support file transfer, attempting to access files from local filesystem.
Reading symbols from /lib64/ld-linux-x86-64.so.2...(no debugging symbols found)...done.
0x00007fb05a6add90 in _start () from /lib64/ld-linux-x86-64.so.2
(rr) c
Continuing.
warning: Could not load shared library symbols for linux-vdso.so.1.
Do you need "set solib-search-path" or "set sysroot"?

readline: readline_callback_read_char() called with no handler!
[FATAL /build/rr-git/src/rr/src/GdbConnection.cc:268:read_data_once() errno: 104 'Connection reset by peer'] Error reading from gdb
[1]    19033 abort (core dumped)  rr replay
```

I can't really reproduce this with some other programs (`find`, `dd`, `python`) so it might be something julia is doing to the IO that causes this. Please suggest how I can find out what is causing this to happen.

rr version d6babd0

**Comment by rocallahan** [comment]
Running with `RR_LOG=GdbConnection` would be useful.

**Comment by yuyichao** [comment]
https://gist.github.com/yuyichao/71cc158a2443efbb1c9e

The few blank lines after

```
[GdbConnection] gdb requests memory (addr=0x7f88df0280e0, len=4)
[GdbConnection] raw request qSymbol::
[GdbConnection] gdb is ready for symbol lookups
```

is when I pressed enter a few times.

**Comment by rocallahan** [comment]
This looks like it's just a gdb bug. `rl_callback_read_char` triggers `readline: readline_callback_read_char() called with no handler!` and immediately aborts the gdb process. I don't know why that's being triggered in your case but I can't see how rr would have anything to do with it. There have been bugs in this area before:
https://sourceware.org/bugzilla/show_bug.cgi?id=17546
though 7.11 should have all the fixes mentioned in that bug.

You could attach gdb to the gdb instance and try to debug gdb I guess...

**Comment by yuyichao** [comment]
Reproted to gdb as https://sourceware.org/bugzilla/show_bug.cgi?id=19855. Closing here for now (unless it turns out to be a rr issue....)

**Comment by yuyichao** [comment]
It seems that this happens because [rr triggers some path that is less and less tested](https://sourceware.org/bugzilla/show_bug.cgi?id=19855#c10). While this should probably be fixed in gdb, the gdb maintainer this may not be necessary anymore if it is to workaround old gdb bugs.

**Comment by rocallahan** [comment]
Thanks very much! I explained in the gdb bug why we use target-async 0.

**Comment by sorokin** [comment]
The referred gdb bug (19855) is closed as fixed in gdb 7.11.1, but I still experience (probably) the same bug.

When I repeatedly do step command (by pressing and holding the enter key). After a few seconds gdb aborts with an error message. The last lines in a log are:

```
[GdbConnection] raw request vCont;s:p7974.7974;c:p7974.-1
[GdbConnection] forcing query/resume thread to ANY
[GdbConnection] raw request g
[GdbConnection] gdb requests registers
[GdbConnection] raw request vCont;s:p7974.7974;c:p7974.-1
[GdbConnection] forcing query/resume thread to ANY
[GdbConnection] raw request g
[GdbConnection] gdb requests registers
[GdbConnection] raw request vCont;s:p7974.7974;c:p7974.-1
[GdbConnection] forcing query/resume thread to ANY

[GdbConnection] raw request g
[GdbConnection] gdb requests registers
[GdbConnection] raw request vCont;s:p7974.7974;c:p7974.-1
readline: readline_callback_read_char() called with no handler!
[GdbConnection] forcing query/resume thread to ANY
[FATAL /tmp/nix-build-rr-4.2.0.drv-0/rr-4.2.0-src/src/GdbConnection.cc:268:read_data_once() errno: 104 'Connection reset by peer'] Error reading from gdb
Aborted
```

Should the gdb bug be reopened? Or is this a different bug? I use rr version 4.2.0.

**Comment by rocallahan** [comment]
Update to 4.3.0. In that version we don't set target-async 0 for gdb 7.11.1, so you shouldn't see this issue.

**Comment by sorokin** [comment]
4.3.0 works flawlessly. Thank you.
