### ISSUE TITLE
Checksumming is broken due to in_replay

### ISSUE THREAD

**Issue by dreiss** [mozilla/rr#1679]
e6f2ed16ca05a8a1604941d1aef79ece7cbfc176 causes checksumming to fail because in_replay is different during record and replay.  Easy to reproduce with

```
rr --checksum=on-all-events record /bin/true
rr --checksum=on-all-events replay --autopilot
```

I can take a shot at fixing this with a little guidance.  The checksum code at https://github.com/mozilla/rr/blob/0f30c4740f6095d952c1bd2c55d204bc5baa0ea8/src/util.cc#L299 operates four bytes at a time, but in_replay is just one byte: https://github.com/mozilla/rr/blob/0f30c4740f6095d952c1bd2c55d204bc5baa0ea8/src/preload/preload.c#L113

One option is to make in_replay an unsigned, and have the checksum code skip over it by comparing the address of buf[i] to the address of in_replay.  The check should be fast because it will (almost) always be correctly branch-predicted.

Another option would be to store in_replay in a section of the syscall buffer, which is already skipped during checksumming.  That would not work when the syscall buffer is disabled, though.

Another option would be to create a separate always-on memory mapping for data expected to diverge between record and replay, and store in_replay there.

**Comment by rocallahan** [comment]
Another option would be to temporarily set in_replay to 0 when checksumming during replay. That's probably the simplest.

**Comment by dreiss** [comment]
Actually, I rebased and there is now another problem with checksumming, caused by e7a7229d008c6e2a6248c47e4f964716c187e2d4 .  You should be able to reproduce it with just `rr --checksum=on-all-events record /bin/true`.  It looks like it's trying to generate a memory checksum after the process has exited, but I'm not totally sure.

I have a fix for the original error I was reporting: https://github.com/mozilla/rr/commit/71f169069fedf2a3621d63532b84b824f43da883 .  It adds a basic checksum test that passes, but if you rebase onto master, it fails due to the new error.

**Comment by rocallahan** [comment]
Thanks ... I'll look into it.

**Comment by rocallahan** [comment]
Yeah, when we record that final event and trigger checksumming, we've detached from the task so it will have finished exiting and we can't look at its memory. No problem, we just have to avoid checksumming in that case.

**Comment by rocallahan** [comment]
FWIW your test needed a `check` call, so I added that.

The `explicit operator bool` is C++11 theoretically, so it might not work with older compilers, but I don't know that's a real problem so we'll see what happens.

Thanks!!!

**Comment by dreiss** [comment]
Ah, yes.  I'll be sure to add the check next time.  Even without the check, it was failing on trunk with

```
/home/dreiss/stuff/build/rr/src/test/util.sh: line 219:  4049 Aborted
_RR_TRACE_DIR="$workdir" rr $GLOBAL_OPTIONS replay -a $replayflags > replay.out 2> replay.err
```
