### ISSUE TITLE
Does rr support parallels hypervisor?

### ISSUE THREAD

**Issue by sidkshatriya** [mozilla/rr#1686]
The parallels hypervisor seems to support PMU virtualization...

See: http://download.parallels.com/desktop/v9/ga/docs/en_US/Parallels%20Desktop%20User's%20Guide/33236.htm
(Search for the term PMU)

Has this been tested to work with `rr`? I'm looking to use `rr` on a Mac. 

(Qemu is very slow. VMWare is windows only and Virtualbox has not implemented PMU virtualization as was mentioned on the the installation instructions)

**Comment by rocallahan** [comment]
AFAIK no-one's tested Parallels with rr yet.

VMWare Fusion for Mac supports PMU virtualization. It's worked with rr for some people and not others.

**Comment by sidkshatriya** [comment]
Thanks for the tip! 

I'll try VMWare fusion for Mac...

**Comment by sidkshatriya** [comment]
@rocallahan Related query: will I need VMWare Fusion 8 or VMWare Fusion Pro 8 ? i.e. does the professional version make a difference to PMU Virtualization?)

(At first glance it doesn't: http://www.vmware.com/in/products/fusion/compare )

**Comment by rocallahan** [comment]
I don't know, but I guess it doesn't.

**Comment by sidkshatriya** [comment]
I'm using the non pro version of fusion. Things seem to be working fine so far
