### ISSUE TITLE
Avoid defining global preprocessor symbols in headers if possible

### ISSUE THREAD

**Issue by Keno** [mozilla/rr#1720]
It would be nice if we could avoid including so many of the system headers in rr's headers and
include them in the source files instead. The reason for this is that some other libraries and projects really don't like those symbols defined, which is a problem when using rr as a library (e.g. you can't currently include both rr and LLVM because LLVM has enum values which conflict with `#define`s in the elf header). Of course that's really a bug in those libraries, but to play along nicely, it would be good to avoid pulling those headers in in rr's headers. It looks like the primary problem here is `kernel_abi.h`. However, it seems like it already redefines most of the structures and then just verifies they are correct. As such may it make sense to split the definition and verification and only require the system headers for the latter?

**Comment by rocallahan** [comment]
Yes, that's a great idea.
