### ISSUE TITLE
unhandled ioctl running curses

### ISSUE THREAD

**Issue by hotsphink** [mozilla/rr#1730]
rr record python -c 'import curses; curses.wrapper(lambda x: x)'

crashes with

[FATAL /home/sfink/src/rr/src/record_syscall.cc:3795:rec_process_syscall_arch() errno: SUCCESS] 
 (task 3361 (rec:3361) at time 1026)
 -> Assertion `t->regs().syscall_result_signed() == -syscall_state.expect_errno' failed to hold. Expected EINVAL for 'ioctl' but got result 0 (errno SUCCESS); Unknown ioctl(0x5403): type:0x54 nr:0x3 dir:0 size:0 addr:0x7ffc020900d0

**Comment by rocallahan** [comment]
Are you on master?

**Comment by hotsphink** [comment]
Doh! Sorry, git is still not fitting in my brain. Yes, I was on master -- master on my fork, which was well behind upstream master.
