### ISSUE TITLE
Writing to pts doesn't show up in replay

### ISSUE THREAD

**Issue by yuyichao** [mozilla/rr#1731]
libuv reopens the current tty file and use that as output. However, the write to this file does not show up in the replay.

**Comment by rocallahan** [comment]
Hmm, e101a4f7880d5fd24427adbd574bf9a088a9ecdf should have fixed this. Does the `dev_tty` test pass on your system? If so, any idea what libuv is doing differently?

**Comment by yuyichao** [comment]
iirc the test is about writing to `/dev/tty`? The file libuv opens is the value returned by `ttyname` (more precisely [`ttyname_r`](https://github.com/libuv/libuv/blob/96b37293a9a6a4f100e117b9760aaac3e39f94ee/src/unix/tty.c#L90)) i.e. `/dev/tty*` or `/dev/pts/*` instead of `/dev/tty`.

**Comment by yuyichao** [comment]
FYI https://github.com/libuv/libuv/commit/387102b2475776e5e40a3f6da5041eb674ad4abf
