### ISSUE TITLE
Check if reads and writes with files are handled properly

### ISSUE THREAD

**Issue by neon12345** [mozilla/rr#1732]
if (ssize_t(buf.data.size()) !=
      pwrite64(emufile->fd(), buf.data.data(), buf.data.size(), offset_bytes)) 
{
//ERROR
}

From the Linux man page:
"pwrite() writes **up to** count bytes from the buffer starting at buf to the file descriptor fd at offset offset. The file offset is not changed."

**Comment by rocallahan** [comment]
I haven't seen this being a problem in practice... I'd accept a PR to fix it :-)

**Comment by neon12345** [comment]
When mmaping large areas say 4gb this will most probably hit you. I'm looking forward to see rr as a general tool to fix bugs. But your comment doesn't make me feel very confident. ;-)

**Comment by rocallahan** [comment]
I suspect you mean well, but pressuring developers with that kind of comment rubs me the wrong way. Please don't do it.
