### ISSUE TITLE
"Allow" recursive recording?

### ISSUE THREAD

**Issue by yuyichao** [mozilla/rr#1737]
I can understand allowing recursive recording is hard but I think it might be useful to allow running `rr record` in a record session as a no-op.

The use case is that I want to record only the worker processes (so that they can run in parallel) by modifying the worker lauching command. However, each worker might use the same command to launch a few other helper processes. Ideally, I'd like those workers to be recorded independently (since race condition in IPC isn't usually what I want to debug) but it would be good enough to just run those workers in the same rr session as if they are started without rr.

If any of these are possible to implement but is too problematic as default mode, a command line switch would also be good.

**Comment by rocallahan** [comment]
rr sets `RUNNING_UNDER_RR=1` in the environment so it would be easy to have an option that lets `rr record` simply spawn the child without recording it, if `RUNNING_UNDER_RR` is already set.
