### ISSUE TITLE
Option to expose more than one CPU

### ISSUE THREAD

**Issue by yuyichao** [mozilla/rr#1738]
Currently rr seems to be overwriting the number of CPU cores as 1. This means the libraries that use the CPU core number to determine the number of threads to use will only start one thread, making it harder to debug race conditions. It would be nice to have an option to overwrite the number of CPU cores seen by the process being recorded.

**Comment by rocallahan** [comment]
rr chaos mode randomizes the number of cores reported. See `pretend_num_cores`. You could add an option to control that directly, or just use chaos mode. If you're trying to track down races I recommend chaos mode.

**Comment by hotsphink** [comment]
This issue can be closed. (I'm not sure if I could have done something in the PR to make that happen automatically?)

**Comment by khuey** [comment]
You can write "fixes #1738" in the commit message to make it automatically close this when merged.
