### ISSUE TITLE
Scheduling issue when opening fifo

### ISSUE THREAD

**Issue by yuyichao** [mozilla/rr#1742]
The following program can execute successfully outside `rr` but blocks on either the parent or child `open` under `rr`.

```c
#include <unistd.h>
#include <sys/types.h>
#include <sys/stat.h>
#include <stdio.h>
#include <fcntl.h>

int main()
{
    char *fn = tmpnam(NULL);
    int ret = mkfifo(fn, 0644);
    printf("%s %d\n", fn, ret);
    if (fork() == 0) {
        printf("Child\n");
        int fd = open(fn, O_WRONLY);
        printf("fd = %d\n", fd);
        close(fd);
        printf("Child done\n");
    }
    else {
        printf("Parent\n");
        int fd = open(fn, O_RDONLY);
        printf("fd = %d\n", fd);
        close(fd);
        printf("Parent done\n");
        unlink(fn);
    }
    return 0;
}
```

IIUC the issue is that the two `open` has to happen at the same time for this to success, is it at all possible to schedule another process when one is blocked on a syscall? (I imagine things like this should be necessary to get mutex working when one process is blocked on `futex`?)

Reduced from https://github.com/JuliaLang/julia/blob/913b24de9c68b6c79a767bc2f6caacea249b3198/test/file.jl#L1093-L1109 which is AFAIK the last test failure when running the julia tests under `rr` other than https://github.com/mozilla/rr/issues/1741

**Comment by rocallahan** [comment]
This is relatively easy to fix. Just need to change `WONT_BLOCK` to `MAY_BLOCK` in `sys_open` and `PREVENT_SWITCH` to `ALLOW_SWITCH` for `Arch::open` in `rec_prepare_syscall_arch`. It's a little less efficient but not a problem.

**Comment by yuyichao** [comment]
Confirmed that the julia test is also fixed. Thanks.
