### ISSUE TITLE
Replay got unrecorded signal 11 (SIGSEGV)

### ISSUE THREAD

**Issue by CervantesYu** [mozilla/rr#1744]
This happens during replay firefox content process:
[FATAL /home/cervantes/git/rr/rr/src/ReplaySession.cc:323:cont_syscall_boundary() errno: SUCCESS] 
 (task 30185 (rec:25212) at time 1508291)
 -> Assertion `!t->stop_sig()' failed to hold. Replay got unrecorded signal 11 (SIGSEGV)
Launch gdb with 
  gdb '-l' '-1' '-ex' 'target extended-remote :30185' /home/cervantes/.rr/firefox-2/mmap_hardlink_2_firefox

rr revision: 1041217864ae149cc0d05acbd65b22b067d3e5be
gdb revision: 8b302db80cb07f5f3264b50e1b51fdb8ecb29183
kernel version: 4.4.0-22-generic

**Comment by CervantesYu** [comment]
[Running gdb '-l' '-1' '-ex' 'target extended-remote :30185' /home/cervantes/.rr/firefox-2/mmap_hardlink_2_firefox](https://github.com/mozilla/rr/files/331691/gdb_output.txt)

**Comment by rocallahan** [comment]
Somewhere in the rr error output is the "time". Dig that out and run `rr dump -b -m -p <trace>` and look for the `global_time:<time>`, and please paste somewhere the events around that time.

This looks like a general divergence problem. Can you record and replay any Firefox runs at all? Or does every single Firefox run fail to replay?

**Comment by rocallahan** [comment]
@CervantesYu I'd like to push out a new rr release but I'd like to resolve this bug before I do that, so please get back to me :-). Thanks!

**Comment by CervantesYu** [comment]
This problem happened twice out of 5 of my recordings so it's not always reproducible. The problematic recording is already purged, but the problem is not that hard to reproduce. I'll try to get a dump today.

**Comment by CervantesYu** [comment]
[FATAL /home/cervantes/git/rr/rr/src/ReplaySession.cc:323:cont_syscall_boundary() errno: SUCCESS]
 (task 10277 (rec:9031) at time 589105)
 -> Assertion `!t->stop_sig()' failed to hold. Replay got unrecorded signal 11 (SIGSEGV)
Launch gdb with
  gdb '-l' '-1' '-ex' 'target extended-remote :10277' /home/cervantes/.rr/latest-trace/mmap_hardlink_2_firefox

[rr dump excerpt around the failure](https://github.com/mozilla/rr/files/334109/file1.txt)

**Comment by rocallahan** [comment]
What is the failing event number?

Also, if you follow the instructions "Launch gdb with..." and get a backtrace (`where`), can you paste that backtrace here?

**Comment by CervantesYu** [comment]
The closest event is
[rr 9031 109236]  Message: TypeError: window.getSelection is not a function

The backtrace is similar to https://github.com/mozilla/rr/issues/1744#issuecomment-228326912 where mozilla-central/js/src/vm/Time.h:153 performs rdtsc instruction.

**Comment by CervantesYu** [comment]
[gdb backtracce](https://github.com/mozilla/rr/files/334192/gdb_backtrace.txt) for reference.

**Comment by rocallahan** [comment]
There's supposed to be a line that looks like
````
 (task 23680 (rec:28732) at time 17)
````
just before `-> Assertion `!t->stop_sig()' failed to hold. `. But for some reason you didn't copy it?

**Comment by CervantesYu** [comment]
It's
(task 17597 (rec:9031) at time 589105)

**Comment by rocallahan** [comment]
OK. Looks like a general divergence bug :-(.

I think the next step would be to re-record with the `-n` option to `rr record`. That may help us narrow down the divergence.

Also, how are you triggering this? Can you give me instructions that I can use to try to reproduce it here?

**Comment by rocallahan** [comment]
To be clear, re-record with -n until replay fails and then dump the failure error with its event number and also the output of `rr dump -b -m -p` around that event. Unfortunately using -n is slower. It's possible that the bug may go away when you use -n (but that's useful information).

**Comment by CervantesYu** [comment]
I don't know the condition to trigger this bug, but just start firefox with my profile, which contains 100+ tabs and about 30 addons installed.

**Comment by rocallahan** [comment]
OK. Then it's worth checking whether this error occurs on your system with a clean profile. I suspect it won't.

You could also try rr 4.2.0 or 4.1.0 to see if it's an rr regression.

Thanks!!!

**Comment by CervantesYu** [comment]
A clean profile doesn't trigger this bug. I also checked 4.2.0 and rr even gets stuck in starting my profile:

% rr record ./firefox 
rr: Saving the execution of `./firefox' to trace directory `/home/cervantes/.rr/firefox-4'.
libGL error: failed to open drm device: No such file or directory
libGL error: failed to load driver: nouveau
ATTENTION: default value of option force_s3tc_enable overridden by environment.

^C^C^C^C^C^Czsh: killed     rr record ./firefox
(ctrl+c didn't stop the record session and I finally killed it).

I'll try to reproduce on master branch.

**Comment by rocallahan** [comment]
Alright, then this is the next step:
> re-record with -n until replay fails and then dump the failure error with its event number and also the output of rr dump -b -m -p around that event.

Thanks!

**Comment by CervantesYu** [comment]
I can't reproduce the same error with -n, but another error shows up and is tracked in issue #1745

**Comment by rocallahan** [comment]
I checked in a fix for #1562 which I hope will fix this and #1745. Please pull master and retry!

**Comment by CervantesYu** [comment]
I am almost sure dconf triggered this failure. Switching between input methods produces the following:

/org/gnome/desktop/input-sources/current
  uint32 1
/desktop/ibus/general/engines-order
  ['chewing', 'xkb:us::eng']
/org/gnome/desktop/input-sources/current
  uint32 0
/desktop/ibus/general/engines-order
  ['xkb:us::eng', 'chewing']

and triggers various assertions during replay. The latest master doesn't exhibit this failure. Thanks.!
