### ISSUE TITLE
Assertion `!syscall_bp_vm' failed to hold. during replay

### ISSUE THREAD

**Issue by CervantesYu** [mozilla/rr#1745]
This is found in reproducing issue #1744 with -n.

[FATAL /home/cervantes/git/rr/rr/src/ReplaySession.cc:414:enter_syscall() errno: SUCCESS] 
 (task 12523 (rec:21773) at time 2736484)
 -> Assertion `!syscall_bp_vm' failed to hold. 
Launch gdb with 
  gdb '-l' '-1' '-ex' 'target extended-remote :12523' /home/cervantes/.rr/firefox-3/mmap_hardlink_2_firefox

**Comment by CervantesYu** [comment]
(task 12523 (rec:21773) at time 2736484)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ I don't know why github always eats this line of output during copy/paste.

[gdb backtrace](https://github.com/mozilla/rr/files/334609/gdb_bt.txt)
[dump around 2736484](https://github.com/mozilla/rr/files/334616/dump.txt)

**Comment by rocallahan** [comment]
After attaching gdb to the emergency debug session, can you try `disassemble` or if that doesn't work `disassemble $rip-0x80,$rip+0x80`?

**Comment by rocallahan** [comment]
Also, if you attach gdb to rr itself, then go up to the frame `ReplaySession::enter_syscall`, and dump `t->wait_status`.

**Comment by rocallahan** [comment]
And in `enter_syscall` dump `syscall_bp_addr`.

**Comment by rocallahan** [comment]
And in the emergency debug session, dump the current registers (`info registers`).

Thanks!!!

**Comment by rocallahan** [comment]
It looks like divergence is happening during GC. Interestingly the two recordings you showed me are both quite similar in that we're replaying towards an `munmap` when we take a different path and hit a RDTSC (in #1744) and what I guess is `gettimeofday` here.

**Comment by rocallahan** [comment]
Oh, also in `enter_syscall` print `t->tick_count()`.

**Comment by CervantesYu** [comment]
In the emergency debug session:
Dump of assembler code from 0x7ffef5c7ecb7 to 0x7ffef5c7edb7:
   0x00007ffef5c7ecb7:  adc    $0xffffd3dc,%eax
   0x00007ffef5c7ecbc:  and    -0x2c33(%rip),%rax        # 0x7ffef5c7c090
   0x00007ffef5c7ecc3:  imul   %rdx,%rax
   0x00007ffef5c7ecc7:  jmpq   0x7ffef5c7eb8f
   0x00007ffef5c7eccc:  mov    %rsi,-0x30(%rbp)
   0x00007ffef5c7ecd0:  callq  0x7ffef5c7e9a0
   0x00007ffef5c7ecd5:  mov    -0x30(%rbp),%rsi
   0x00007ffef5c7ecd9:  jmp    0x7ffef5c7ecaf
   0x00007ffef5c7ecdb:  mov    %rsi,-0x30(%rbp)
   0x00007ffef5c7ecdf:  callq  0x7ffef5c7e9a0
   0x00007ffef5c7ece4:  mov    -0x30(%rbp),%rsi
   0x00007ffef5c7ece8:  jmp    0x7ffef5c7ec8f
   0x00007ffef5c7ecea:  xor    %edx,%edx
   0x00007ffef5c7ecec:  jmpq   0x7ffef5c7ebc3
   0x00007ffef5c7ecf1:  mov    %r13,%rdi
   0x00007ffef5c7ecf4:  mov    %rsi,-0x30(%rbp)
   0x00007ffef5c7ecf8:  callq  0x7ffef5c7e9d0
   0x00007ffef5c7ecfd:  mov    -0x30(%rbp),%rsi
   0x00007ffef5c7ed01:  jmp    0x7ffef5c7ecaf
   0x00007ffef5c7ed03:  mov    %r13,%rdi
   0x00007ffef5c7ed06:  mov    %rsi,-0x30(%rbp)
   0x00007ffef5c7ed0a:  callq  0x7ffef5c7e9d0
   0x00007ffef5c7ed0f:  mov    -0x30(%rbp),%rsi
   0x00007ffef5c7ed13:  jmpq   0x7ffef5c7ec8f
   0x00007ffef5c7ed18:  pause
   0x00007ffef5c7ed1a:  jmpq   0x7ffef5c7ebf4
   0x00007ffef5c7ed1f:  pause
   0x00007ffef5c7ed21:  jmpq   0x7ffef5c7eade
   0x00007ffef5c7ed26:  nopw   %cs:0x0(%rax,%rax,1)
   0x00007ffef5c7ed30:  mov    $0x60,%eax
   0x00007ffef5c7ed35:  syscall
=> 0x00007ffef5c7ed37:  nop
   0x00007ffef5c7ed38:  nop
   0x00007ffef5c7ed39:  nop
   0x00007ffef5c7ed3a:  retq
   0x00007ffef5c7ed3b:  sub    $0x10,%rsp
   0x00007ffef5c7ed3f:  test   %rdi,%rdi
   0x00007ffef5c7ed42:  je     0x7ffef5c7ee0d
   0x00007ffef5c7ed48:  lea    -0x24(%rbp),%r13
   0x00007ffef5c7ed4c:  mov    %rdi,%rbx
   0x00007ffef5c7ed4f:  mov    -0x2cd6(%rip),%r12d        # 0x7ffef5c7c080
   0x00007ffef5c7ed56:  test   $0x1,%r12b
   0x00007ffef5c7ed5a:  jne    0x7ffef5c7ee65
   0x00007ffef5c7ed60:  mov    -0x2ce2(%rip),%eax        # 0x7ffef5c7c084
   0x00007ffef5c7ed66:  mov    %eax,-0x24(%rbp)
   0x00007ffef5c7ed69:  mov    -0x2cc8(%rip),%rax        # 0x7ffef5c7c0a8
   0x00007ffef5c7ed70:  mov    %rax,(%rbx)
   0x00007ffef5c7ed73:  mov    -0x2cf5(%rip),%edx        # 0x7ffef5c7c084
   0x00007ffef5c7ed79:  mov    -0x2ce0(%rip),%r14        # 0x7ffef5c7c0a0
   0x00007ffef5c7ed80:  cmp    $0x1,%edx
   0x00007ffef5c7ed83:  je     0x7ffef5c7ee56
   0x00007ffef5c7ed89:  cmp    $0x2,%edx
   0x00007ffef5c7ed8c:  je     0x7ffef5c7ee21
   0x00007ffef5c7ed92:  xor    %eax,%eax
   0x00007ffef5c7ed94:  cmp    $0x3,%edx
   0x00007ffef5c7ed97:  je     0x7ffef5c7ee44
   0x00007ffef5c7ed9d:  mov    -0x2d07(%rip),%ecx        # 0x7ffef5c7c09c
   0x00007ffef5c7eda3:  cmp    -0x2d2a(%rip),%r12d        # 0x7ffef5c7c080
   0x00007ffef5c7edaa:  jne    0x7ffef5c7ed4f
   0x00007ffef5c7edac:  add    %r14,%rax
   0x00007ffef5c7edaf:  shr    %cl,%rax
   0x00007ffef5c7edb2:  cmp    $0x3b9ac9ff,%rax
End of assembler dump.
(gdb) info register
rax            0xffffffffffffffda       -38
rbx            0x7efccb1f7748   139624204695368
rcx            0xffffffffffffffff       -1
rdx            0x3b     59
rsi            0x0      0
rdi            0x7ffef5c13c30   140733021502512
rbp            0x32     0x32
rsp            0x7ffef5c13c28   0x7ffef5c13c28
r8             0x7ffef5c14220   140733021504032
r9             0x0      0
r10            0x3      3
r11            0x246    582
r12            0x1      1
r13            0x7efc9e681000   139623454478336
r14            0x3      3
r15            0x7ffef5c14110   140733021503760
rip            0x7ffef5c7ed37   0x7ffef5c7ed37
eflags         0x246    [ CF=0 PF=1 AF=0 ZF=1 SF=0 TF=0 IF=1 DF=0 OF=0 NT=0 RF=0 VM=0 AC=0 VIF=0 VIP=0 ID=0 ]
cs             0x33     51
ss             0x2b     43
ds             0x0      0
es             0x0      0
fs             0x0      0
gs             0x0      0

**Comment by rocallahan** [comment]
Another thing that might be helpful is `rr dump -b -m -p|grep map_file` and pasting the result somewhere.

**Comment by rocallahan** [comment]
Can you install debuginfo for glibc if you haven't already?

**Comment by rocallahan** [comment]
And if you could verify that 0x00007ffef5c7ed35 is actually in glibc by consulting /proc/<pid>/maps, that would be good.

**Comment by rocallahan** [comment]
Oh wait, no, that'll be in [vdso]. Never mind about the last two comments.

**Comment by CervantesYu** [comment]
#10 0x00000000006dc715 in rr::ReplaySession::enter_syscall (this=0x184b970, t=0x1851500, constraints=...) at /home/cervantes/git/rr/rr/src/ReplaySession.cc:414
414           ASSERT(t, !syscall_bp_vm);
(gdb) p t->wait_status
$1 = {
  status = 34175
}
(gdb) p syscall_bp_addr
$2 = {
  ptr = 139624580378245
}
(gdb) p t->tick_count()
$4 = 11104563129

**Comment by rocallahan** [comment]
Thanks for doing all this but unfortunately so far it doesn't show what the problem might be :-(.

`rr dump -b -m -p|grep map_file` would still be useful.

**Comment by rocallahan** [comment]
I'm getting tired so I'll have to think about this more tomorrow.

It's even more work but you might be able to narrow it down by selectively enabling extensions and/or loaded tabs.

**Comment by CervantesYu** [comment]
[rr dump -b -m -p|grep map_file](https://github.com/mozilla/rr/files/334686/map_file.txt)

**Comment by rocallahan** [comment]
Thanks!

My best guess at the moment is something dconf related, since the munmap the replay is trying to reach and failing is a map of /run/user/1000/dconf/user, and I know dconf uses shared memory in a way that confuses rr if settings change while Firefox is running. If you shut down dconf-service, or just kill it, and then record, does that make the problem go away?

Also you could run `dconf watch /` and see what's changing, if anything. If nothing changes during a recording and you still see this bug then it's probably not dconf.

**Comment by CervantesYu** [comment]
I think dconf triggered this bug and the fix for #1562 fixed this bug.

**Comment by lars-t-hansen** [comment]
This bug is not fixed, I had a !syscall_bp_vm crash today.  Also during/following compacting GC in the spidermonkey shell.

I'm pretty sure the crash happened almost exactly at midnight local time (we're at UTC+1 now) but I didn't realize that until this morning, so I didn't attempt to verify it at the time.  But I made some noise about it on IRC at 00:01.

This is RR from a few weeks ago, Fedora 28, x86_64 with Xeons.

[rr-backtrace.txt](https://github.com/mozilla/rr/files/2564903/rr-backtrace.txt)

**Comment by lars-t-hansen** [comment]
And this morning, I can step through compacting GC repeatedly without experiencing any problems.

**Comment by khuey** [comment]
Please file a new issue.
