### ISSUE TITLE
setuid test fails on Ubuntu 16.04

### ISSUE THREAD

**Issue by Keno** [mozilla/rr#1751]
```
root@rr-test-2:~/rr-build# ctest -I 369,369 --output-on-failure
Test project /root/rr-build
    Start 369: setuid
1/1 Test #369: setuid ...........................***Failed  Error regular expression found in output. Regex=[FAILED]  0.74 sec
/root/rr/src/test/util.sh: line 193:  1758 Aborted                 _RR_TRACE_DIR="$workdir" rr $GLOBAL_OPTIONS record $LIB_ARG $RECORD_ARGS $exe $exeargs > record.out 2> record.err
Test 'setuid' FAILED: : error during recording:
--------------------------------------------------
setuid-VXBArDQ8t: /root/rr/src/test/setuid.c:32: main: Assertion `"FAILED: !" && check_cond(0)' failed.
setuid-VXBArDQ8t: /root/rr/src/test/setuid.c:35: main: Assertion `"FAILED: !" && check_cond(((((__extension__ (((union { __typeof(status) __in; int __i; }) { .__in = (status) }).__i))) & 0x7f) == 0) && ((((__extension__ (((union { __typeof(status) __in; int __i; }) { .__in = (status) }).__i))) & 0xff00) >> 8) == 77)' failed.
--------------------------------------------------
record.out:
--------------------------------------------------
FAILED: errno=13 (Permission denied)
FAILED: errno=0 (Success)
--------------------------------------------------
Test setuid failed, leaving behind /tmp/rr-test-setuid-VXBArDQ8t
To replay the failed test, run
  _RR_TRACE_DIR=/tmp/rr-test-setuid-VXBArDQ8t rr replay


0% tests passed, 1 tests failed out of 1

Total Test time (real) =   0.83 sec

The following tests FAILED:
	369 - setuid (Failed)
Errors while running CTest
```

**Comment by rocallahan** [comment]
Odd. Looks like the execve failed. What does strace -f say?

**Comment by Keno** [comment]
I think the problem may be that I am root on this machine:
```
./bin/rr record ./bin/setuid
rr: Saving execution to trace directory `/root/.local/share/rr/setuid-2'.
[FATAL /root/rr/src/AutoRemoteSyscalls.cc:526:check_syscall_result() errno: SUCCESS]
 (task 8037 (rec:8037) at time 186)
 -> Assertion `false' failed to hold. Syscall openat failed with errno EACCES opening root/rr-build/bin/../bin/rr_page_64
Launch gdb with
  gdb '-l' '-1' '-ex' 'target extended-remote :8037' /root/rr-build/bin/setuid
```

**Comment by rocallahan** [comment]
Aha! To be precise, the problem must be that you built rr as root so `rr_page_64` and the `setuid` executable itself are not accessible after we've changed to another uid.

**Comment by rocallahan** [comment]
We could add something to the build step to make those files world-readable/executable, but that's probably not enough since your `rr_build` and `bin` directories would not be accessible, and we can't fix that without potentially creating security issues. So I think we should just modify the `setuid` test to handle these errors and bail out.

**Comment by Keno** [comment]
Well, for the rr_page64 problem, we could probably solve that by sending the fd from the tracer.

**Comment by rocallahan** [comment]
That would add overhead for a case I don't really care about. rr should be installed so its files are world-readable.

**Comment by Keno** [comment]
Fair enough.

**Comment by rocallahan** [comment]
Oddly enough, `setuid` run as root passes for me and I can't figure out why. Even when I fix the test to ensure we `setuid` and `setgid` to `nobody`, `openat` succeeds when it should fail.

**Comment by Keno** [comment]
I've run tests as root before without this one failing so something else is still in play. FWIW this is mainline 4.7rc6 kernel with Ubuntu 16.04 userland.

**Comment by rocallahan** [comment]
If I make `/root/rr` non-world-readable/executable, the test fails. If `/root/rr` is world-readable/executable but `/root` is not, the test passes. Weird.

**Comment by Keno** [comment]
`rr-build` is `drwxr-xr-x` for me, and `rr-build/bin/rr_page_64` is `-rw-r--r--`.

**Comment by rocallahan** [comment]
Ah, I need to call `setgroups` to drop "supplementary groups" as well as `setgid` and `setuid`. That's a bit a security nightmare...

**Comment by rocallahan** [comment]
Handling the case when `setuid` is not executable by `nobody` is easy, the test bails out when `execve` returns `EACCES`.

Handling the case where `setuid` is executable by `nobody` but `rr_page_64` is not ... I have no idea how to do this, actually. We can't make the `execve` fail because it's already succeeded and the old address space is gone. I guess we could add code to fake it by poking the contents of `rr_page_64` into the right place (or by passing the fd into the tracee) but that adds complexity just to get this test to pass...

**Comment by Keno** [comment]
I'm not sure why `bin/rr_page_64` is not executable by nobody though, `bin/rr` is. Maybe the only action item is to change the build system accordingly?

**Comment by rocallahan** [comment]
Actually I guess just writing the contents into the correct place is not a big deal. I'll try that.

**Comment by rocallahan** [comment]
> I'm not sure why bin/rr_page_64 is not executable by nobody though, bin/rr is. Maybe the only action item is to change the build system accordingly?

This won't work in general, right? If root installs rr somewhere that `nobody` can't get to, then recording processes that setuid to `nobody` won't work.

**Comment by Keno** [comment]
Isn't the reference to `RR_RESERVED_ROOT_DIR_FD` enough? Not sure how permissions work in this case i.e. when access is enforced.

**Comment by rocallahan** [comment]
`RR_RESERVED_ROOT_DIR_FD` is only there to ensure that the system root directory (as seen by rr) is accessible to chrooted tracees. It doesn't give them any special privileges as they traverse from that starting point.

**Comment by Keno** [comment]
ah, right. Sorry, for some reason I thought it was pointing to the bin directory that had rr_page_64 in it.

**Comment by Keno** [comment]
Many thanks!
