### ISSUE TITLE
mingw rr binaries

### ISSUE THREAD

**Issue by techtonik** [mozilla/rr#1782]
`gdb` is available in Windows as part of MinGW bundle. Is it possible that `rr` can be compiled for it as well?

**Comment by rocallahan** [comment]
No. rr is completely dependent on Linux kernel semantics. Windows now has a Linux kernel personality, actually, but it's nowhere near complete or accurate enough for rr to work.

**Comment by techtonik** [comment]
I see. Thanks for clarification.
