### ISSUE TITLE
Assertion `t->regs().syscall_result_signed() == -syscall_state.expect_errno' failed to hold

### ISSUE THREAD

**Issue by ehsan** [mozilla/rr#1783]
This is on the current rr master:

```
$ ./mach crashtest --debugger=rr
REFTEST INFO | Checking for orphan ssltunnel processes...
REFTEST INFO | Checking for orphan xpcshell processes...
REFTEST INFO | Running with e10s: True
### XPCOM_MEM_BLOAT_LOG defined -- logging bloat/leaks to /tmp/tmpx06aI9.mozrunner/runreftest_leaks.log
[FATAL /home/ehsan/src/rr/src/record_syscall.cc:4024:rec_process_syscall_arch() errno: SUCCESS]
 (task 3247 (rec:3247) at time 1919)
 -> Assertion `t->regs().syscall_result_signed() == -syscall_state.expect_errno' failed to hold. Expected EINVAL for 'ioctl' but got result 0 (errno SUCCESS); Unknown ioctl(0x80046484): type:0x64 nr:0x84 dir:0x2 size:4 addr:0x7ffd8c39732c
[FATAL /home/ehsan/src/rr/src/log.cc:270:emergency_debug() errno: SUCCESS] (session doesn't look interactive, aborting emergency debugging)
```

**Comment by ehsan** [comment]
Googling around for the ioctl number, it seems like it's an AMD GPU specific thing.  I ran `sudo apt-get remove fglrx-updates-core fglrx-updates fglrx-amdcccle-updates` to remove the AMD drivers I had recently installed, and after a reboot, rr works again!

**Comment by ehsan** [comment]
(This is on Ubuntu 15.10, FWIW.)

**Comment by rocallahan** [comment]
rr tries to block use of DRI GPU drivers. Apparently this didn't work in your case. `strace -f` of Firefox might show us why, if you had those drivers installed.

**Comment by ehsan** [comment]
I tried reinstalling those drivers, but unfortunately I can't reproduce this any mode.  :(

**Comment by rocallahan** [comment]
Thanks for trying!

**Comment by ehsan** [comment]
Actually it seems like I _can_ reproduce if I run `rr ./mach mochitest...` as opposed to passing `--debugger=rr` to mach.  [Here](https://gist.github.com/anonymous/306501ef62a9403b5028ec37888e946d) is an ftrace log.

**Comment by rocallahan** [comment]
That sounds odd.

Unfortunately the trace you provided only shows the mach python process. I need `strace -f` to get all the processes, though I expect that file will be enormous... Maybe if you create a wrapper script around `strace -f` and then `./mach mochitest --debugger=<script> ...` that would be a little smaller... You can kill the run after the browser has successfully started.
