### ISSUE TITLE
Help recording mq_open and friends.

### ISSUE THREAD

**Issue by pogrady668** [mozilla/rr#1790]
Hello--

I'm trying to add the recording of message queue calls to rr, and I could use a bit of help.  Given the changes [here](https://github.com/pogrady668/rr/commit/25352ba828f5334dc81e69e2dfd463ae36958305), my test runs to the point of calling mq_timedreceive, but fails there, with `Assertion ticks_now == trace_ticks failed to hold` and `src/Registers.cc:297:maybe_print_reg_mismatch() errno: SUCCESS] edx 0x1a != 0xd (replaying vs. recorded)`.  Can anyone provide some tips to help teach rr how to record the data returned by mq_timedreceive?  THANKS, in advance!

**Comment by khuey** [comment]
At a bare minimum, you need to record the outparameters of `mq_timedreceive`.  Because `msg_ptr` is a variable length parameter, you'll need to make this an `IrregularEmulatedSyscall` and add some logic to `rec_prepare_syscall_arch`.  `getcwd` is a nice simple example to crib from here.

**Comment by pogrady668** [comment]
Awesome, that was very helpful; I've committed an update which works well  [here](https://github.com/pogrady668/rr/commit/3ebe784b0f3f09fb2b5e359d8c268463335aef10).  If the call fails due to timeout, do I need to do anything to ensure that rr doesn't record undefined data?  Also, I've noticed that in many blocking calls, when rr replay is used, the program doesn't bother to wait for the actual timeout period but instead returns with the timeout error quickly (which is /super useful/).  Can you steer me toward how I can add that feature with my mq_timedreceive?  Again, THANKS for your help.

**Comment by khuey** [comment]
You get both of those for free.  Recording "undefined" data is fine, if the syscall fails it won't have been modified so it doesn't matter.  And skipping idle periods is an artifact of how rr works.  During replay we just emulate the syscalls, so we can apply register and memory updates immediately without having to actually execute the syscall and wait.

**Comment by rocallahan** [comment]
In fact, if the syscall fails, we automatically don't record any data. Your changes look good!

**Comment by pogrady668** [comment]
Thanks, gents--I've been using this and it works great--and your timely support is outstanding.  I'm planning on submitting a pull request for this once I can figure out how to squash both of those commits...  but I've got a bit more learning to do WRT git.

**Comment by khuey** [comment]
Try using `git rebase -i`
