### ISSUE TITLE
Assertion `emufs().size() == 0' failed.` (regression due to cd8dd9c)

### ISSUE THREAD

**Issue by sidkshatriya** [mozilla/rr#1803]
```
ReplaySession.cc:150: virtual rr::ReplaySession::~ReplaySession(): 
Assertion `emufs().size() == 0' failed.
```

I've just compiled 9264b12c78 and am receiving the above assertion error reliably while doing a reverse continue. The problem did not exist as recently as 3db52cd598 (August 4th 2016)

**Comment by sidkshatriya** [comment]
@khuey I did a `git bisect` and it seems that commit 5fc811a5ab is the culprit

**Comment by sidkshatriya** [comment]
@rocallahan Any idea what might be happening in commit  5fc811a to cause this problem? Any help would be very welcome ! :-)

**Comment by khuey** [comment]
The result of your bisection is slightly surprising.  Are you sure it's not cd8dd9cb8047796702a8035012246118785cb238?

**Comment by sidkshatriya** [comment]
Sorry for the "off by one" error. 

I rechecked this and you are correct. The regression first appears in cd8dd9cb8047. Its parent, ac4ad65ea works fine.

**Comment by rocallahan** [comment]
I'm working on some other issues right now...

**Comment by rocallahan** [comment]
Sounds like we're leaking an emufile somewhere, presumably through a MappedFileMonitor. Which is weird since we've torn down all Tasks, so all FdTables should be destroyed by this point, hence all MappedFileMonitors.

We can fix this particular issue by removing the EmuFile reference from MappedFileMonitor and just looking it up when we need it. That simplifies the invariants of this code, so I think we should do that. However, there is probably still a bug where the MappedFileMonitor is being leaked. To fix that, we probably need some way to reproduce the bug, or else for you @sidkshatriya to debug the leak. @sidkshatriya, can you give us a way to reproduce the bug, or investigate the leak yourself?

**Comment by khuey** [comment]
Yeah, steps to reproduce would be great here.

**Comment by sidkshatriya** [comment]
While this is easily reproducible at my end, a test case that you can setup easily and debug is difficult to send as this is part of an application under development.

Let me see if I can whittle this down to a smaller test case you can debug. That too might require some setup at your end I'm afraid. Let me see what I can do...

**Comment by khuey** [comment]
Try seeing if you can reproduce it on one of rr's tests.  I'd start with the test that cd8dd9c added.

**Comment by sidkshatriya** [comment]
Good idea. Let me run the whole test suite and also the specific test introduced by that commit and report back shortly. BTW how does one run a specific test on the command line via the test runner?

**Comment by khuey** [comment]
You don't need to run it via the test runner.  Just `./bin/rr ./bin/mmap_shared_write` to make a recording of it and then see if you can trigger the bug by reverse-continuing somehow in the replay.

**Comment by sidkshatriya** [comment]
@khuey 
That did the trick. Here is a replay session that can repeat this error.

First I did a record session `./bin/rr ./bin/mmap_shared_write` as suggested. Then I did a replay session with reverse-continue. 

Here is a transcript of the replay session (I'm on Ubuntu 16.04 + gdb 7.11.1)
```
0x00007fe37c29ecc0 in _start () from /lib64/ld-linux-x86-64.so.2
(rr) b mmap_shared_write.c:10 
Breakpoint 1 at 0x400c96: file rr/rr/src/test/mmap_shared_write.c, line 10.
(rr) c
Continuing.
rpage:0x7fe37c4c0000

Breakpoint 1, check_mapping (page=0x7fe37c4c0000, magic=-1515870811, nr_ints=1024)
    at rr/rr/src/test/mmap_shared_write.c:10
10	  atomic_printf("  %p has the correct values\n", page);
(rr) c
Continuing.
  0x7fe37c4c0000 has the correct values

Breakpoint 1, check_mapping (page=0x7fe37c4c0000, magic=1515870810, nr_ints=1024)
    at rr/rr/src/test/mmap_shared_write.c:10
10	  atomic_printf("  %p has the correct values\n", page);
(rr) rc
Continuing.
rr: rr/rr/src/ReplaySession.cc:150: virtual rr::ReplaySession::~ReplaySession(): 
Assertion `emufs().size() == 0' failed.
Remote connection closed
(rr) 
```

**Comment by sidkshatriya** [comment]
Any luck in solving this issue? I'm not able to use bleeding edge anymore as a result of this (even though it has a 100% pass rate) :-(

**Comment by sidkshatriya** [comment]
I can confirm that this is fixed at my end too. @khuey Thanks!

**Comment by khuey** [comment]
Thanks for the steps to reproduce.  It made figuring this out a lot easier.
