### ISSUE TITLE
Unable to abort multi-page backtrace dumps in rr

### ISSUE THREAD

**Issue by staktrace** [mozilla/rr#1804]
Just a minor polish issue: In regular gdb, if you run `bt` and get a backtrace that spans multiple pages, gdb will display one page at a time, with the option to press `q <return>` to "quit" (i.e. stop displaying the rest of the backtrace). This doesn't seem to work in rr, even though I enter `q <return>` it continues displaying the rest of the backtrace.

**Comment by sidkshatriya** [comment]
Is this possible? How are you running rr interactively without gdb? `rr replay` brings up gdb... perhaps I am misunderstanding what you're saying?

**Comment by staktrace** [comment]
Hm, I tried to reproduce this with a small standalone program and I couldn't. I've only seen it when debugging gecko (which I only do with rr these days) so maybe gdb does the same thing there. Maybe I was mistaken and this isn't an rr bug, sorry.

**Comment by bgirard** [comment]
Shot in the dark but are you running it from inside mach (mozilla' python utility wrapper)? mach is using python to wrap the TTY and perhaps causes GDB to behave differently.

It's likely some difference that might cause GDB to think it's not running under an interactive shell and it disables paging.

**Comment by staktrace** [comment]
In this case I wasn't running it via mach. I ran the record through mach, but then the reply was outside mach. So I doubt that's it. Might be something else in my environment though that triggers paging to be disabled. It's honestly not a big enough issue to really worry about, but I'll keep an eye out for potential causes/patterns.
