### ISSUE TITLE
Q: Do binaries need to be compiled "-g" for rr

### ISSUE THREAD

**Issue by sidkshatriya** [mozilla/rr#1808]
Do binaries need to be be compiled with debugging information i.e. `-g` for rr to work properly? 

I have a binary which is stripped of all symbols and is behaving strangely in rr. My thought is that `-g` should not matter but asking just in case...

Additionally does rr have issues with `-O2` ?

**Comment by sidkshatriya** [comment]
I compiled another program, stripped it via `strip -s` and it works so I guess the answer is _no_.

Will leave the ticket open for now in case there are any caveats...

**Comment by rocallahan** [comment]
Presence of debugging information is not relevant to the basic record and replay functionality. Obviously, gdb isn't going to work well if debugging information is not present.

**Comment by sidkshatriya** [comment]
Sure. My use case is an executable which has symbols stripped out and a shared object (loaded by the executable) which _did_ have symbols. I was only interested in debugging the shared object.

But this works and thanks for your clarification too...
