### ISSUE TITLE
Test failures

### ISSUE THREAD

**Issue by rocallahan** [mozilla/rr#1823]
@legnaleurc had some test failures: http://pastebin.com/ABNHKRjp

@legnaleurc: if you run the `clone_newflags` test program outside of rr, does it succeed without an assertion failure?

**Comment by legnaleurc** [comment]
```
FAILED: errno=10 (No child processes)
clone_newflags: /home/wcpan/local/src/rr/src/test/clone_newflags.c:34: main: Assertion `"FAILED: !" && check_cond((((status) & 0x7f) == 0) && 77 == (((status) & 0xff00) >> 8))' failed.
Aborted

```

**Comment by rocallahan** [comment]
Can you check with strace or whatever whether clone is failing with EPERM?

**Comment by legnaleurc** [comment]
clone_newflags
https://pastebin.mozilla.org/8913987

proc_fds
https://pastebin.mozilla.org/8913988

**Comment by rocallahan** [comment]
OK, `clone_newflags` should be fixed for you on master now.

For the `proc_fds` test, can you try running the test under gdb? When the assertion fails, find the failing value of `fd` and look it up via `lsof` to see what it corresponds to. This is a mysterious one...

**Comment by legnaleurc** [comment]
`clone_newflags` has been fixed.

`fd` is 29, which is a pipe.

**Comment by rocallahan** [comment]
If you set a breakpoint to stop at the beginning of `main`, are those four pipes already present?

It sounds like something in your environment is causing those four pipes to be inherited into rr test runs, which is possible but strange. If you run `lsof` can you find the other ends of those pipes?

**Comment by legnaleurc** [comment]
> If you set a breakpoint to stop at the beginning of main, are those four pipes already present?

Yes.

> It sounds like something in your environment is causing those four pipes to be inherited into rr test runs, which is possible but strange. If you run lsof can you find the other ends of those pipes?

29 <-> 30, 31 <-> 32.

**Comment by rocallahan** [comment]
So those pipes are not present in any other process, e.g. the rr process?

**Comment by legnaleurc** [comment]
Uhh ... I'm quite confused.
I got this in lsof
```
COMMAND    PID  USER   FD   TYPE DEVICE SIZE/OFF     NODE NAME
proc_fds 15434 wcpan  cwd    DIR  254,0     4096 50988287 /home/wcpan/local/src/rr/build
proc_fds 15434 wcpan  rtd    DIR  254,0     4096        2 /
proc_fds 15434 wcpan  txt    REG  254,0   545032 50992996 /home/wcpan/local/src/rr/build/bin/proc_fds
proc_fds 15434 wcpan  mem    REG  254,0  1685264 48497011 /lib/x86_64-linux-gnu/libc-2.24.so
proc_fds 15434 wcpan  mem    REG  254,0   135448 48497076 /lib/x86_64-linux-gnu/libpthread-2.24.so
proc_fds 15434 wcpan  mem    REG  254,0    14640 48497030 /lib/x86_64-linux-gnu/libdl-2.24.so
proc_fds 15434 wcpan  mem    REG  254,0    31744 48497082 /lib/x86_64-linux-gnu/librt-2.24.so
proc_fds 15434 wcpan  mem    REG  254,0   149192 48496970 /lib/x86_64-linux-gnu/ld-2.24.so
proc_fds 15434 wcpan    0u   CHR  136,1      0t0        4 /dev/pts/1
proc_fds 15434 wcpan    1u   CHR  136,1      0t0        4 /dev/pts/1
proc_fds 15434 wcpan    2u   CHR  136,1      0t0        4 /dev/pts/1
proc_fds 15434 wcpan   29r  FIFO   0,10      0t0    29936 pipe
proc_fds 15434 wcpan   30w  FIFO   0,10      0t0    29936 pipe
proc_fds 15434 wcpan   31r  FIFO   0,10      0t0    29937 pipe
proc_fds 15434 wcpan   32w  FIFO   0,10      0t0    29937 pipe
```

But when I find the node ID in /proc (29936, 29937), I found lot's of them.
For now I guess they are coming from bash.

**Comment by legnaleurc** [comment]
Processes from another tty do not have those pipes.

**Comment by legnaleurc** [comment]
I think the four pipes were inherited from `krunner`.
And if I don't use `krunner` to launch program, it still inherit a domain socket which connects to plasmashell.

**Comment by rocallahan** [comment]
OK. I pushed a change to the `proc_fds` test to master that should fix that problem by closing inherited fds before proceeding with the test.

I also pushed a change to `post_exec_fpu_regs` that should fix that test for you. That leaves `mutex_pi_stress`.

**Comment by rocallahan** [comment]
Can you confirm that `mutex_pi_stress` fails when run outside of rr? That would suggest your kernel does not support priority inheritance...

**Comment by legnaleurc** [comment]
`proc_fds` has been fixed.

`mutex_pi_stress` succeed by running outside of `rr`.

**Comment by rocallahan** [comment]
OK. It looks like if your glibc was built with `__ASSUME_FUTEX_LOCK_PI` not defined, you could hit this because we force `FUTEX_UNLOCK_PI` to return `ENOSYS` which would cause `pthread_mutex_init` to return `ENOTSUP`. So, I fixed the test to fall back to non-PI locks if we get that error. Please test again. Thanks!!!

**Comment by legnaleurc** [comment]
```
/home/wcpan/local/src/rr/src/test/util.sh: line 193: 31045 Aborted                 _RR_TRACE_DIR="$workdir" rr $GLOBAL_OPTIONS record $LIB_ARG $RECORD_ARGS $exe $exeargs > record.out 2> record.err
Test 'mutex_pi_stress' FAILED: : error during recording:
--------------------------------------------------
mutex_pi_stress-cbTYAlJnR: /home/wcpan/local/src/rr/src/test/mutex_pi_stress.c:32: main: Assertion `"FAILED: !" && check_cond(95 == (*__errno_location ()))' failed.
--------------------------------------------------
record.out:
--------------------------------------------------
FAILED: errno=0 (Success)
--------------------------------------------------
Test mutex_pi_stress failed, leaving behind /tmp/rr-test-mutex_pi_stress-cbTYAlJnR
To replay the failed test, run
  _RR_TRACE_DIR=/tmp/rr-test-mutex_pi_stress-cbTYAlJnR rr replay
```

**Comment by rocallahan** [comment]
Can you modify the test, or just record and replay it, to dump the value of errno where that fails?

**Comment by legnaleurc** [comment]
Cannot believe I forgot this.
Now all tests passed after I pulled the master, so I think this issue could be closed.
Thank you very much!

**Comment by rocallahan** [comment]
Thank *you* very much!
