### ISSUE TITLE
Recording chromium on my system asserts in `init_thread`

### ISSUE THREAD

**Issue by rocallahan** [mozilla/rr#1826]
We're in `sandbox::(anonymous namespace)::ChrootToSafeEmptyDir()`:
https://cs.chromium.org/chromium/src/sandbox/linux/services/credentials.cc?q=ChrootToSafeEmptyDir&sq=package:chromium&l=87&dr=CSs

This function allocates some stack space and some TLS space as local variables of the function. It assumes that all TLS accesses are at positive offsets to the TLS pointer (and that they don't exceed `PTHREAD_STACK_MIN`). Unfortunately, on my system, `preload.c`'s thread-locals are at negative offsets to the TLS pointer (-8 for `buffer` and -16 for `thread_inited`). So, after the fork we send the synthetic `SIGPWR` to the new child. That sets up a signal-handling frame at the top of the stack, and then we call into `init_thread`, which reads `buffer` and `thread_inited` and gets whatever the sigframe happened to put there, which in this case is something nonzero for `buffer` and zero for `thread_inited` so we assert.

**Comment by rocallahan** [comment]
The Chromium code is making incorrect assumptions about `ld.so`'s TLS usage. No doubt we're breaking it because we're using the `initial-exec` TLS model, which is unusual.

**Comment by rocallahan** [comment]
It might be possible to fix this by reverting to the default TLS model, but that sounds risky because `__get_tls_addr` will get called at weird times (e.g. in the synthetic signal sent after `clone`).

We already have TLS issues that we had to work around with `thread_locals_initialized`. I'm tempted to generalize that approach to completely remove `preload`'s dependence on `ld.so`'s TLS. Instead, we'd make those "thread locals" just be members of a global struct in `preload`. Every time we switch to a new Task, we save the current values to the old Task and copy the new Task's values into the globals.

@khuey, @Keno: Any thoughts?

**Comment by rocallahan** [comment]
I'm working on this approach. It has a nice feature: we can make these thread-locals not be propagated by fork(). That means instead of delivering a signal to force them to be reset, we can just lazily re-initialize the syscallbuf at the next hooked syscall.

**Comment by khuey** [comment]
Ouch.  Lame that it worked on my system ...

**Comment by rocallahan** [comment]
I've just about got this working. Cleaned up all known test failures, rerunning tests now. It ends up being quite nice actually.

**Comment by rocallahan** [comment]
Now I can record chromium-browser fine ... replaying it diverges :-(. I'll try to look into it sometime next week, though I'm supposed to be on holiday...

**Comment by khuey** [comment]
Hmm, it works here, even after these changes.  My first guess would be that RDRAND isn't being disabled properly somehow.

**Comment by rocallahan** [comment]
The issue turned out to be wireless-interface ioctls. Tracking in https://github.com/mozilla/rr/issues/1827. I fixed the two needed by chromium.
