### ISSUE TITLE
`info proc` doesn't work

### ISSUE THREAD

**Issue by glandium** [mozilla/rr#1834]
```
(rr) info proc
process 24554
warning: unable to open /proc file '/proc/24554/cmdline'
warning: unable to read link '/proc/24554/cwd'
warning: unable to read link '/proc/24554/exe'
```

In normal gdb, this would print out something like:

```
process 24554
cmdline = '...'
cwd = '...'
exe = '...'
```

It's not very interesting in itself, but what is is:

```
(gdb) info proc mappings
```

which prints out info about the address space, from /proc/$pid/maps.

The problem here is that 24554 is the pid of the recorded process (as appears in rr ps), not the actual process rr is running, so the underlying gdb is confused.

**Comment by rocallahan** [comment]
I do not see anything in the remote protocol that would allow us to fix this.

**Comment by glandium** [comment]
How does gdb knows the original pid?

**Comment by rocallahan** [comment]
Lots of traffic between gdb and rr uses pids and tids. We use the recorded pid because nothing else makes sense. The real pids change constantly when you're doing reverse execution and checkpoints.
