### ISSUE TITLE
Find a way to replay syscallbuf flushes more efficiently

### ISSUE THREAD

**Issue by cgjones** [mozilla/rr#184]
While trying to reproduce another bug in a test case what looks like

    for (i = 0; i < 1 <<20; ++i) {
      clock_gettime(...);
      gettimeofday(...);
   }

, I recorded it with the syscallbuf enabled.  Recording is quite quick, 2.5s of clock time or so.  Replay took foooorreeeeever though, and I thought I'd caught another bug.  However, ratcheting down the iterations showed that replay was just taking a long time.

Recording the same test *without* the syscallbuf *just* finished (I was about to interrupt it out of inpatience ;) ), and it took 395 seconds.  This is obviously the ideal case for syscallbuf, but this is 150x faster.

Problem is *replaying* a syscallbuf trace seems to be just as slow as recording without the syscallbuf (which makes sense, since we drive them about the same way).  It would suck if it took 150x longer to debug something in gdb than it took to record it, but not the end of the world.

There's got to be a cleverer way to drive replay.  One thing we could do is mprotect the next-to-last page that has syscall records on it, and then drive until we hit a SEGFAULT there.  Then unprotect and drive the slow way.

**Comment by cgjones** [comment]
@rocallahan and I brought this up again.  In the context of reverse-replay, this 100x overhead becomes a lot more important because we'll be replaying a lot more.  It also simplifies the future replay-execution-time-accounting somewhat.

The sticky wicket here is what do for futex calls and writes to sdio.

**Comment by rocallahan** [comment]
I fixed this on master.
