### ISSUE TITLE
Q: Does rr support any AMD architectures?

### ISSUE THREAD

**Issue by sidkshatriya** [mozilla/rr#1847]
In the rr "building and installing instructions" it says:

> Supported microarchitectures are Intel architectures newer than Merom and Penryn, i.e. Nehalem and beyond.

A search for AMD brings up open tickets #1552 (Support AMD Piledriver) #1423 (Support Opteron).

So does this mean only (newish) Intel architectures are supported currently and AMD is not supported? 

If so, I think we should change the build instructions to state "AMD microarchitectures are not currently supported" for clarity. People might just download the x86_64 binary on their AMD machines and expect that to work...

**Comment by pipcet** [comment]
I think the answer is currently "no", and likely to remain no for most AMD CPUs; the exception is family 15h CPUs, which have something called Light-Weight Profiling that is good enough to support rr, with some limitations; see the Piledriver thread.

Unfortunately, something appears to have broken when the kernel ptrace interface changed, so I'm a bit stuck. Hopefully I'll have some free time starting next week to look into things again.
