### ISSUE TITLE
src/util.cc:626:should_copy_mmap_region() Unhandled mmap

### ISSUE THREAD

**Issue by sidkshatriya** [mozilla/rr#1849]
The following error was posted today on the [sidkshatriya/dontbug](https://github.com/sidkshatriya/dontbug) project. (dontbug depends on rr).

The error is:
```
[FATAL /home/roc/rr/rr/src/util.cc:626:should_copy_mmap_region() errno: EACCES] 
Unhandled mmap /home/xxx/yyy/yyy-api/storage/framework/views/eb787bc5b0d00e38b5b2c5b312898d82c9820e4b.php
(prot:0x1;SHARED); uid:33 mode:33188
```

I've asked the poster some questions on ticket https://github.com/sidkshatriya/dontbug/issues/2

While I wait for his answers... would anybody able to wager what might be going on? Would be grateful for any help.

**Comment by sidkshatriya** [comment]
The user also gets

```
rr: Warning: Your CPU frequency governor is 'powersave'.  rr strongly
    recommends that you use the 'performance' governor.  Not using the
    'performance' governor can cause rr to be at least 2x slower
    on laptops.

    On Fedora-based systems, you can enable the 'performance' governor
    by running the following commands:

    $ sudo dnf install kernel-tools
    $ sudo cpupower frequency-set -g performance
```

I have recommended the appropriate fix of 

```
sudo apt-get install cpufrequtils
sudo cpufreq-set -g performance
```

But this warning shouldn't be the cause of a later error...right?

**Comment by khuey** [comment]
Right.  That warning is about performance, not correctness.

It would be useful to know if `xxx` is a different user than the user running rr.

**Comment by sidkshatriya** [comment]
Closing ticket as no more info was given by user.
