### ISSUE TITLE
checkpoint_async_signal_syscalls takes overly long

### ISSUE THREAD

**Issue by Keno** [mozilla/rr#1856]
That test is slow enough that it determines the overall length of the test suite. Is there any way we can speed it up without losing (too much) of it's testing power?

```
1863/1864 Test #1740: checkpoint_async_signal_syscalls_1000-32-no-syscallbuf ....   Passed  276.35 sec
1864/1864 Test #808: checkpoint_async_signal_syscalls_1000-no-syscallbuf .......   Passed  284.08 sec

99% tests passed, 2 tests failed out of 1864

Total Test time (real) = 284.36 sec
```

**Comment by rocallahan** [comment]
That test is really supposed to test syscallbuf being interrupted by signals. So I think we should just skip them for no-syscallbuf.

**Comment by rocallahan** [comment]
I'll do it.

**Comment by Keno** [comment]
While we're at it, maybe do the same for daemon_read, which seems to be taking quite a long time on one of my machines when syscallbuf is disabled (but as far as I understand is a test for something that only happens when syscallbuf is enabled):
```
ctest -R daemon_read
Test project /data/keno/rr-build
    Start  71: daemon_read
1/4 Test  #71: daemon_read ......................   Passed    0.60 sec
    Start  72: daemon_read-no-syscallbuf
2/4 Test  #72: daemon_read-no-syscallbuf ........   Passed   78.27 sec
    Start 1003: daemon_read-32
3/4 Test #1003: daemon_read-32 ...................   Passed    0.67 sec
    Start 1004: daemon_read-32-no-syscallbuf
4/4 Test #1004: daemon_read-32-no-syscallbuf .....   Passed   28.23 sec
```

**Comment by Keno** [comment]
Although it may be worth figuring out why `daemon_read` takes so much longer. Just looking at the trace, on the machine where it takes that long, there's a few tens of thousands of reads from `/dev/zero` in the trace, while on my main development machine there's hardly any.

**Comment by rocallahan** [comment]
It just so happens I'm working on that too.

**Comment by Keno** [comment]
Much better: `Total Test time (real) = 137.87 sec`

**Comment by Keno** [comment]
I'm quite happy with this now. There's still one test that dominates the time (`mutex_pi_stress-no-syscallbuf`), but it's much closer to the combined duration of the rest of the test suite.
