### ISSUE TITLE
Intermittent `step_thread` failure on ci.rr-project.org

### ISSUE THREAD

**Issue by rocallahan** [mozilla/rr#1862]
`step_thread` failed and left behind a trace that shows a reproducible divergence if you run the test script:
````
[ERROR /home/rr-worker/worker/worker/rr/build/rr/src/Registers.cc:297:maybe_print_reg_mismatch() errno: SUCCESS] rdx 0xcc != 0x6 (replaying vs. recorded)
[ERROR /home/rr-worker/worker/worker/rr/build/rr/src/Registers.cc:297:maybe_print_reg_mismatch() errno: SUCCESS] r8 0xcd != 0x7 (replaying vs. recorded)
[ERROR /home/rr-worker/worker/worker/rr/build/rr/src/Registers.cc:297:maybe_print_reg_mismatch() errno: SUCCESS] r15 0x7f8101306dc0 != 0x7f8101306db0 (replaying vs. recorded)
[FATAL /home/rr-worker/worker/worker/rr/build/rr/src/Registers.cc:417:compare_register_files() errno: SUCCESS] 
 (task 31470 (rec:4816) at time 273)
 -> Assertion `!bail_error || match' failed to hold. Fatal register mismatch (ticks/rec:509/513)
````

**Comment by rocallahan** [comment]
Here `rdx` is the `val` parameter to a `futex_wait`. The divergence does not show up if you just `continue` instead of doing the last `step`. My current theory is that the `step` sets breakpoints and somehow one of the breakpoints is being picked up as the `val` (since 0xcc is the value for the `int3` breakpoint instruction).

**Comment by rocallahan** [comment]
Yeah, so just before we get into trouble, gdb does this:
````
[GdbConnection] raw request Z0,6020a0,1
[GdbConnection] gdb requests setbreakpoint (addr=0x6020a0, len=1)
[GdbConnection] write_flush: '$OK#9a'
````
`0x6020a0` is the address of `bar`, i.e. our `pthread_barrier_t`. Setting a breakpoint in our data structure is bad.

**Comment by rocallahan** [comment]
OK, so what's happening is that in `__pthread_barrier_wait` there's an inlined futex syscall which gets patched with a jump to our syscallbuf stub code. To execute a `step` gdb does a series of `stepi`s which eventually step into that stub code. At that point gdb discovers it doesn't know about the function we just stepped into, so it tries to step out of it by determining the return address and setting a breakpoint there. However, we didn't execute a call so the value at the top of the stack is not the return address, it's just an arbitrary value, in this case a pointer to `bar` (which happens to have been left there by some `dl_runtime_resolve` stuff, but it could be anything). I'm not sure what checks if any gdb applies to validate this value, but `bar` passes them and so it tries to set a breakpoint there.

**Comment by Keno** [comment]
> At that point gdb discovers it doesn't know about the function we just stepped into

Is there anything in the GDB remote interface that would allow us to teach GDB about that?

**Comment by rocallahan** [comment]
Conclusion: gdb's `step`, `next` and maybe other commands are unreliable if you can't guarantee perfect stack traces at every instruction. I think to do that we'd need to supply unwinding information for our dynamically-generated stubs. There is an interface for that but it's complicated: https://sourceware.org/gdb/onlinedocs/gdb/JIT-Interface.html
I don't know how well it would work with reverse execution. It seems to assume the tracee will call into `__jit_debug_register_code` to register and unregister code which would be tricky to arrange. I'm not very excited about trying to implement this.

We could try to hack around this by detecting gdb trying to read the return address when `rip` is at a stub entry point, and faking a return value of zero. That should avoid any issues.

**Comment by Keno** [comment]
> There is an interface for that but it's complicated: https://sourceware.org/gdb/onlinedocs/gdb/JIT-Interface.html
> I don't know how well it would work with reverse execution. It seems to assume the tracee will call into __jit_debug_register_code to register and unregister code which would be tricky to arrange. I'm not very excited about trying to implement this.

Well familiar with that. It's quite horrible. I was hoping for something slightly nicer in the remote interface.

> We could try to hack around this by detecting gdb trying to read the return address when rip is at a stub entry point, and faking a return value of zero. That should avoid any issues.

Ugh, but yeah, that seems like it would work.

**Comment by rocallahan** [comment]
Need to write a reliable test for this first.

**Comment by pipcet** [comment]
> I think to do that we'd need to supply unwinding information for our dynamically-generated stubs.
Does gdb honor DWARF/CFI information determining the return address? That would be easier to add than messing with the JIT interface, I think.

I'm not sure precisely where the code is when gdb tries to set the breakpoint. syscall_hook.S appears to have the CFI magic, but it seems raw_syscall.S doesn't.

**Comment by Keno** [comment]
> I'm not sure precisely where the code is when gdb tries to set the breakpoint. syscall_hook.S appears to have the CFI magic, but it seems raw_syscall.S doesn't.

In order for GDB to find the CFI, it would have to know what function it's in, which it doesn't know for the stubs (because we just poke a bunch of instructions into memory without telling gdb about it).
