### ISSUE TITLE
Pick a reasonable maximum for the number of data compression threads

### ISSUE THREAD

**Issue by Keno** [mozilla/rr#1865]
Right now rr will start as many threads as the system has cores, which can be quite large (up 100s). It would seem better (and faster) to pick a reasonable maximum (say 4 for 8).

**Comment by rocallahan** [comment]
Sure. Nice problem to have :-).

**Comment by Keno** [comment]
Indeed! Mostly a problem if a crazy person (*cough* @yuyichao *cough*) comes along, and tries to do a bunch of recordings in parallel ;):
```
ps -eLF | grep rr | grep yuyichao | wc -l
2833
```
