### ISSUE TITLE
Best way to terminate rr recording non-interactively?

### ISSUE THREAD

**Issue by sidkshatriya** [mozilla/rr#1868]
If I start a `rr record php -S ...` session in a pseudo-tty and when I'm done, I send a ASCII 3 (Control+C) to the pty, it will terminate php and bring the rr recording to a close. All is good so far.

However when I try doing the same thing with `rr record xyz ...` (where xzy is another program), Writing an ASCII 3 to the pty does _not_ have the desired effect of only terminating xyz. Rather it ends up terminating the whole program itself. It also results in a bad recording. Its not clear why the behaviour is different for the two programs vis-a-vis Ctrl+C at this point.

The exact details are probably not so important. What I'd like to know is: what is an idiomatic way to terminate the program under recording so that rr record can also end. This needs to be done in a non-interactive way i.e. by a program and not a user. For some reason Ctrl+C interactively (i.e by a user) always seems to work properly but the same thing via wrting ASCII 3 to the pty causes problems. Not using a pty comes with its own problems. The best solution would involve me keeping the pty around but being able to terminate the tracee easily.

Its of course important for the termination to happen properly. If rr itself is terminated improperly, it results in a corrupt recording. Maybe I'm missing something obvious here. Any help/suggestions will greatly appreciated.

**Comment by rocallahan** [comment]
Basically you need to kill the tracee in a way that doesn't instantly kill rr as well. Sending SIGTERM to the tracee should work well.

**Comment by sidkshatriya** [comment]
Thanks. How will I know the PID of the tracee so I can send that process a SIGTERM? rr starts the tracee itself...

**Comment by khuey** [comment]
`/proc/<rr-pid>/task/<rr-pid>/children` should work.

**Comment by sidkshatriya** [comment]
Once all the children are dead -- rr will exit automatically itself?  

Also I suppose SIGINT (Ctrl+C) instead of SIGTERM to the children should also do the job. But we prefer SIGTERM to SIGINT?

**Comment by sidkshatriya** [comment]
Thanks @khuey! Also, do I have to be careful while killing the `/proc/<rr-pid>/task/<rr-pid>/children` children or can I SIGTERM them indiscriminately? Cause rr may have started non-tracee related "helper" processes (e.g. maybe a process related to the emufs -- I don't know, just guessing) and I probably want to avoid killing them?

**Comment by khuey** [comment]
@rocallahan will know for sure but I don't think we start any children other than the tracee.

**Comment by Keno** [comment]
Perhaps we should detach the rr recorder from its controlling terminal so ^C doesn't kill it?

**Comment by sidkshatriya** [comment]
The approach suggested by @khuey which is to obtain the child pid from `/proc` works.

But I have reverted to the old way of sending ASCII code 3 (Ctrl+C) to the psuedo-terminal (outlined on the initial comment on this ticket). This actually works fine. The problem was with my error handling related to a process wait I was doing.

So it was something like this:

```golang
err :=  rrProcess.Wait()
if err != nil {
    log.Fatal(err)
}
```

So when I delivered a Ctrl+C by writing ASCII code 3 to the psuedo-terminal, the program `xyz` would terminate and the signal would propagate to the parent process, which is rr. Then rr would terminate. (Here rr terminates cleanly).

This would cause `rrProcess.Wait()` to exit with an error code (something like `signal: interrupted` ).

The solution is to simply not exit fatally if `err` is non-nil.

```golang
err = rrProcess.Wait()
if err != nil {
	fmt.Println(err)
}
```

**Comment by rocallahan** [comment]
> I don't think we start any children other than the tracee.

That is currently true but I wouldn't want anyone to depend on it remaining true. At some point I'd like to rework trace management so that trace compression and flushing is handled by a child process; then if someone sends SIGKILL to rr itself, the child process can finish writing a complete trace.

> Perhaps we should detach the rr recorder from its controlling terminal so ^C doesn't kill it?

rr already catches SIGINT and ignores it. From @sidkshatriya's last comment here, it seems rr was getting killed somehow during shutdown of his Python supervisor wrapper. I don't think we need to change anything here.

**Comment by sidkshatriya** [comment]
BTW this was golang and not python... not that it matters at all :-)
