### ISSUE TITLE
PerfCounters.cc:138:get_cpu_microarch() errno: ENOTTY CPU 0xf40 unknown.

### ISSUE THREAD

**Issue by thyseus** [mozilla/rr#1872]
Installing rr-4.4.0-Linux-x86_64.deb and trying to do 

`rr record ls`

i get:

> rr: Saving execution to trace directory `/home/thyseus/.local/share/rr/ls-0'.
> [FATAL /home/roc/rr/rr/src/PerfCounters.cc:138:get_cpu_microarch() errno: ENOTTY] CPU 0xf40 unknown.
> Aborted

I am using Linux Mint 17.3 on Linux:

> Linux rechengnom 3.16.0-38-generic #52~14.04.1-Ubuntu SMP Fri May 8 09:43:57 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

And my CPU is this: AMD Phenom(tm) II X4 955 Processor

Any ideas? Thanks a lot !

**Comment by rocallahan** [comment]
AMD Phenom is not supported. It's pretty old.

**Comment by thyseus** [comment]
Ok. Thanks for the information. Just out of curiosity: is any non-intel CPU supported? The list of CPU´s at the line in the source code only lists intel CPU types.

**Comment by khuey** [comment]
There is ongoing work to support Piledriver in #1552, but for the moment only relatively modern Intel CPUs are supported.

**Comment by thyseus** [comment]
Thanks a lot. I just saw that there is a line

"requires a reasonably modern x86 CPU. It depends on certain performance counter features that are not available in older CPUs"

in the "limitations" section of the RR home page. Could be improved to "only intel CPUs".
