### ISSUE TITLE
SIGSYS fired when replaying Firefox recordings

### ISSUE THREAD

**Issue by mystor** [mozilla/rr#1887]
When I attempt to record and replay firefox on my machine, using the master branch of rr, I get a SIGSYS signal when debugging the process. The process appears to be recorded fine.

## STR
(My machine is running Ubuntu 16.04 LTS)
- Clone mozilla-central, and build with the following mozconfig
```
ac_add_options --enable-optimize="-Og"
ac_add_options --enable-debug
ac_add_options --enable-warnings-as-errors
ac_add_options --enable-rust

mk_add_options MOZ_OBJDIR=@TOPSRCDIR@/obj-debug-@CONFIG_GUESS@
mk_add_options AUTOCLOBBER=1
```

- Run firefox with `mach run --debugger=rr`
- `rr ps` to discover the pid of the content process
- `rr replay -p $pid` on that process
- `c` to start running the process once it has loaded
- "Thread 1 received signal SIGSYS, Bad system call."

**Comment by khuey** [comment]
#1875

**Comment by rocallahan** [comment]
I wonder if we should add `handle SIGSYS noprint nostop` to the standard prelude...

**Comment by khuey** [comment]
I've suggested adding it to Gecko's gdbinit to multiple people at Mozilla
but it seems nothing has come of that.

**Comment by rocallahan** [comment]
OK that's probably the best idea.

**Comment by froydnj** [comment]
> I've suggested adding it to Gecko's gdbinit to multiple people at Mozilla but it seems nothing has come of that.

I can do this, but the existing `.gdbinit` has `noprint nostop pass` for most signals; does the presence or absence of `pass` matter?

**Comment by rocallahan** [comment]
You need `pass`, the signal has to be passed to the tracee for the sandbox to work.

**Comment by ehsan** [comment]
At least in my case, the underlying issue is gdb defaulting to refuse loading .gdbinit from our source directory.

**Comment by mystor** [comment]
I added an explicit exception for the directory where I store my working directories such that GDB would load scripts from them. (`add-auto-load-safe-path /path/to/working/dirs` in `~/.gdbinit`)

**Comment by PaulBone** [comment]
Urgh it took about 2 hours to try and get rr working with multiprocess firefox.  This caused confusion for at least 40 minutes.

(Some other mistakes were using the wrong mozconfig, that's totally on me.)

Is this a Firefox thing or an rr thing?

**Comment by rocallahan** [comment]
Definitely a gdb thing. If you had configured mozilla-central `.gdbinit` to load automatically, that contains `handle SIGSYS noprint nostop pass` which should have avoided your problem (see above comments).

**Comment by PaulBone** [comment]
Okay, that's a firefox thing. it's because of firefox that it's getting that signal. Bug #1875 explained.
