### ISSUE TITLE
Intermittent failure due to record_async_signal firing too soon

### ISSUE THREAD

**Issue by Keno** [mozilla/rr#1896]
I'm seeing intermittent failures, e.g. in `async_segv`, because the program didn't make it all the way through setting up the signal handler before the kill fired (the machine was under high load, and is a little slow at scheduling in general). I see a couple potential solutions (e.g. small wrapper that sets the sigprocmask, so the signal remains pending or just allow being killed by the signal as one of the expected outcomes).

**Comment by rocallahan** [comment]
Another option that some of the tests use is to have the test binary print "ready" when it's ready and have the wrapper script wait for that before sending the signal.

**Comment by Keno** [comment]
Also seen on the new buildbots, I believe: https://ci.rr-project.org/#/builders/3/builds/25/steps/9/logs/stdio. Will submit a patch
