### ISSUE TITLE
Check target kernel version in CMakeLists.txt?

### ISSUE THREAD

**Issue by Smattr** [mozilla/rr#1920]
When building rr from source, I ran into unexpected issues due to missing seccomp headers because the host I was on was Linux 3.0. I didn't realise there was a seccomp dependency until C++ compilation failed. Does it make sense to have CMake check your kernel version during setup? I think seccomp was added around 3.17, though unfortunately it doesn't look like `CMAKE_SYSTEM_VERSION` comes in pleasant format for checking this.

**Comment by khuey** [comment]
`seccomp` was added in 3.5.  You could just `uname -r` to get the kernel version.

**Comment by Smattr** [comment]
Yes, that is true, but I was assuming it was slightly cleaner to do it in the CMake approved way. Are you saying you'd consider a pull request that checks `uname -r`?

**Comment by rocallahan** [comment]
A couple of issues make this murky:
* In theory, you could build rr on a system with a pre-3.5 kernel if you had the right headers installed somewhere. It just wouldn't run...
* In theory, the kernel version alone doesn't tell you what features are present because the kernel could have backported features.

**Comment by rocallahan** [comment]
Rather than a kernel version check, I think it would make more sense to do some kind of configure check to see if the header file symbols we need are present, to give a clean and early error instead of an error later during compilation.

**Comment by Smattr** [comment]
That would also retain support for cross compilation in a way that `uname -r` wouldn't.

**Comment by rocallahan** [comment]
So yeah, in general I'd take PRs that turn compile failures into configure checks.
