### ISSUE TITLE
"CPU 0x806e0 unknown" on Kaby Lake

### ISSUE THREAD

**Issue by glandium** [mozilla/rr#1921]
model name	: Intel(R) Core(TM) i7-7500U CPU @ 2.70GHz

**Comment by khuey** [comment]
Needs an addition to `get_cpu_microarch` and related code.

**Comment by glandium** [comment]
Considering running with -A "Intel Skylake" seems to work, I guess copying Skylake to Kabylake would work... although I'm clueless as to whether the pmu values are actually valid for Kabylake.

**Comment by khuey** [comment]
If Intel has updated the SDM for Kaby Lake it'll be in there, in volume 3.

**Comment by glandium** [comment]
http://www.intel.com/content/dam/www/public/us/en/documents/manuals/64-ia-32-architectures-software-developers-manual.pdf has been updated for Kaby Lake, and table 19-3 is shared between Skylake and Kabylake, so it would seem everything is the same. In an hypothetical future where there is a different microarchitecture, I don't know how one would get the pmu config values from those tables. Maybe it would be worth documenting somewhere?

**Comment by khuey** [comment]
They're the retired conditional branches counter, the retired instructions counter, and hardware interrupt counter values in the form accepted by `perf`, with additional higher bits set for counting only userspace values and interrupting on overflow.  That last bit, the 51 prefixes, might be removable (the kernel should set those internally, I think).
