### ISSUE TITLE
Tests fail on master with fresh build

### ISSUE THREAD

**Issue by fitzgen** [mozilla/rr#1923]
Fresh build + tests fails on master

```
$ git log -1
commit 134ca6fee8bf732325a38a9ec08bac10b557e6df
Merge: 729d433 fa9cab0
Author: Kyle Huey <khuey@kylehuey.com>
Date:   Thu Dec 15 19:50:52 2016 -0800

    Merge pull request #1922 from glandium/master
    
    Add support for Kabylake micro-architecture
```

My system (Fedora 24):

```
$ uname -a
Linux localhost.localdomain 4.6.5-300.fc24.x86_64 #1 SMP Thu Jul 28 01:10:12 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
```

Built with `cmake -G Ninja; ninja-build`, then ran tests with `ninja-build test` and got a handful of failures.

Summary of tests:

```
99% tests passed, 12 tests failed out of 1956

Total Test time (real) = 4062.16 sec

The following tests FAILED:
	939 - signal_stop (Failed)
	940 - signal_stop-no-syscallbuf (Failed)
	941 - signal_checkpoint (Failed)
	942 - signal_checkpoint-no-syscallbuf (Failed)
	955 - step_signal (Failed)
	956 - step_signal-no-syscallbuf (Failed)
	1917 - signal_stop-32 (Failed)
	1918 - signal_stop-32-no-syscallbuf (Failed)
	1919 - signal_checkpoint-32 (Failed)
	1920 - signal_checkpoint-32-no-syscallbuf (Failed)
	1933 - step_signal-32 (Failed)
	1934 - step_signal-32-no-syscallbuf (Failed)
Errors while running CTest
FAILED: cd /home/fitzgen/src/rr/obj && /usr/bin/ctest --force-new-ctest-process
ninja: build stopped: subcommand failed.
```

Full log: https://gist.github.com/fitzgen/b2023334ecd17ddc38556fa972255d0c

**Comment by rocallahan** [comment]
Can you run with `ninja-build check` and dump that output? That output will contain references to temporary test directories; we'll want the `gdb_rr.log` from one of those tests (`signal_stop` preferably). Also your `gdb --version` would be helpful. Thanks!

**Comment by fitzgen** [comment]
`ninja-build check` output: https://gist.github.com/fitzgen/4ce68f26ec159052ba52924389a9cff5

**Comment by fitzgen** [comment]
Can't find anything named `gdb_rr.log` in my object directory:

```
bash-4.3$ find . -type f -name gdb_rr.log
bash-4.3$ 
```

**Comment by fitzgen** [comment]
Aha! Found it in `/tmp`. Here is the `gdb_rr.log` for the `signal_stop` test: https://gist.github.com/fitzgen/9a8074e73de43a84b99ac42efe161759

**Comment by rocallahan** [comment]
rr expects to see something like
````
main () at ../src/test/sigill.c:15
15	  __asm__("ud2");
````
but you have
````
main () at ../src/test/sigill.c:15
/home/fitzgen/src/rr/src/test/sigill.c:15:334:beg:0x400bd6
````
Any idea why that might be? Does your gdb autoload something that changes its output that way?

**Comment by fitzgen** [comment]
Ah, I have `set annotate 1` in my gdbinit so it plays nice with Emacs's `M-x gud-gdb` which means spitting out some escape character garbage that Emacs can interpret.

Maybe the tests should avoid loading custom gdbinit files?

**Comment by rocallahan** [comment]
Quite right.
