### ISSUE TITLE
Failure in `clone_interruption`

### ISSUE THREAD

**Issue by rocallahan** [mozilla/rr#1929]
Recording `clone_interruption` failed with
````
[FATAL /home/rr-worker/worker/worker/rr-pr/build/rr/src/RecordTask.cc:1126:verify_signal_states() errno: SUCCESS] 
 (task 25557 (rec:25557) at time 253)
 -> Assertion `!!(blocked & mask) == is_sig_blocked(sig)' failed to hold. SIGCHLD is not blocked
[FATAL /home/rr-worker/worker/worker/rr-pr/build/rr/src/log.cc:284:emergency_debug() errno: SUCCESS] (session doesn't look interactive, aborting emergency debugging)
````

The final event in the trace is
````
  real_time:1655245.596741 global_time:252, event:`PATCH_SYSCALL' tid:25557, ticks:43448
 rax:0xe rbx:0x0 rcx:0xffffffffffffffff rdx:0x0 rsi:0x7ffd94417080 rdi:0x2 rbp:0x7ffd94417110 rsp:0x7ffd94417058 r8:0x0 r9:0x7f44ac351700 r10:0x8 r11:0x246 r12:0x400bc0 r13:0x7ffd944171f0 r14:0x0 r15:0x0 rip:0x7f44ac92d4ed eflags:0x246 cs:0x33 ss:0x2b ds:0x0 es:0x0 fs:0x0 gs:0x0 orig_rax:0xffffffffffffffff fs_base:0x7f44acf7d700 gs_base:0x0
  { tid:25557, addr:0x7f44acd900ed, length:0x4f }
  { tid:25557, addr:0x7f44ac92d4ed, length:0x5 }
  { tid:25557, addr:0x7f44ac92d4f2, length:0x1 }
````
which is the syscall-buffered `rt_sigprocmask` that blocks `SIGCHLD`. So it looks like rr picked up the change to `blocked_sigs` by syscallbuf, but the signal was not actually blocked (yet?).

**Comment by rocallahan** [comment]
This may have something to do with `-c100` being used by `clone_interruption`.

**Comment by rocallahan** [comment]
I can reproduce this locally with a test program without the patches in #1927.

**Comment by rocallahan** [comment]
The issue is just that there's nothing to us reaching `verify_signal_states` in `RecordSession::record_step` after the syscallbuf has updated `block_sigs` but before it does the system call. A signal (`TIME_SLICE_SIGNAL` in this case) can interrupt the process there; it will be stashed and not delivered, but we're still stopped in that region.

**Comment by rocallahan** [comment]
It would be easy enough to paper over this assertion, but that would mean in some cases code that uses `blocked_sigs` returns incorrect results, which is not good, but maybe we don't have any choice...

**Comment by Keno** [comment]
Is there a way we can detect whether or not we've done the syscall yet?

**Comment by rocallahan** [comment]
I can think of a few crazy complicated ways, but the only reasonable way I can think of would be to set a flag in the syscallbuf header to indicate that `blocked_sigs` is in an indeterminate state, and in that case don't use it but read the mask from the proc filesystem instead.

I just realized there's another problem with the `blocked_sigs` setup, which is that we don't replay those values *and* `sys_rt_sigprocmask` could be loading them into registers and/or copying them into spill slots which could theoretically cause divergences depending on codegen decisions...

**Comment by rocallahan** [comment]
So maybe we should eliminate `blocked_sigs` altogether and use two flags instead:
* `in_rt_sigprocmask` indicates that preload is in a critical section around `rt_sigprocmask`. Set and cleared only by preload.
* `blocked_sigs_dirty` indicates that rr's copy of the signal mask may be dirty and needs to be reloaded from `/proc`. Set to true in `sys_rt_sigprocmask` after entering the `in_rt_sigprocmask` region. In `did_waitpid`, reload the cached signal mask whenever `blocked_sigs_dirty` is true. Say that the cached signal mask is valid only when `Task::is_stopped`, and assert that (just like `Task::regs()`). Clear it in `did_waitpid` *only if* we're outside the `in_rt_sigprocmask` region.

**Comment by rocallahan** [comment]
Unfortunately this interacts poorly with `restore_signal_state`. When the application has blocked a signal but then the kernel issues a deterministic `SIGSEGV`, it unblocks the signal, and with the above approach we may detect that change and determine incorrectly that the application unblocked the signal, which means we don't do the `restore_signal_state` work when we need to.

**Comment by rocallahan** [comment]
> I just realized there's another problem with the blocked_sigs setup, which is that we don't replay those values and sys_rt_sigprocmask could be loading them into registers and/or copying them into spill slots which could theoretically cause divergences depending on codegen decisions...

The fix I checked in here did not address this.
