### ISSUE TITLE
Struggling with "Assertion `ticks_now == trace_ticks' failed to hold."

### ISSUE THREAD

**Issue by pjogrady** [mozilla/rr#1940]
I've been unable to "rr" my program for some time due to a recurrent ticks_now failing to match trace_ticks; today I poked through the testing fixture and I'm able to reliably reproduce the problem using the "record_replay" test.  I'm working with the [current rev from today](https://github.com/mozilla/rr/commit/f80d1d2115af8f7f6a524a9270b7df6f8207155a).

Here's the problem:
```
/home/linuxdev/workspace/rr/build-rr$ make test ARGS="-VV -I 921,921"
Running tests...
UpdateCTestConfiguration  from :/home/linuxdev/workspace/rr/build-rr/DartConfiguration.tcl
UpdateCTestConfiguration  from :/home/linuxdev/workspace/rr/build-rr/DartConfiguration.tcl
Test project /home/linuxdev/workspace/rr/build-rr
Constructing a list of tests
Done constructing a list of tests
Checking test dependency graph...
Checking test dependency graph end
test 921
    Start 921: record_replay

921: Test command: /bin/bash "/home/linuxdev/workspace/rr/rr/src/test/record_replay.run" "-b" "/home/linuxdev/workspace/rr/rr" "/home/linuxdev/workspace/rr/build-rr" "record_replay"
921: Test timeout computed to be: 120
921: /home/linuxdev/workspace/rr/rr/src/test/util.sh: line 219: 27489 Aborted                 (core dumped) _RR_TRACE_DIR="$workdir" rr $GLOBAL_OPTIONS replay -a $replayflags > replay.out 2> replay.err
921: Test 'record_replay' FAILED: : error during replay:
921: --------------------------------------------------
921: [FATAL /home/linuxdev/workspace/rr/rr/src/ReplaySession.cc:864:check_ticks_consistency() errno: SUCCESS]
921:  (task 27490 (rec:27487) at time 376)
921:  -> Assertion `ticks_now == trace_ticks' failed to hold. ticks mismatch for 'SYSCALL: futex'; expected 274433, got 274431
921: [FATAL /home/linuxdev/workspace/rr/rr/src/log.cc:284:emergency_debug() errno: SUCCESS] (session doesn't look interactive, aborting emergency debugging)
921: --------------------------------------------------
921: replay.out:
921: --------------------------------------------------
921: --------------------------------------------------
921: Test record_replay failed, leaving behind /tmp/rr-test-record_replay-rQyCv2rZp
921: To replay the failed test, run
921:   _RR_TRACE_DIR=/tmp/rr-test-record_replay-rQyCv2rZp rr replay
1/1 Test #921: record_replay ....................***Failed  Error regular expression found in output. Regex=[FAILED]  9.78 sec

0% tests passed, 1 tests failed out of 1

Total Test time (real) =   9.91 sec

The following tests FAILED:
        921 - record_replay (Failed)
Errors while running CTest
make: *** [test] Error 8
```

Dump shows this:
```
{
  real_time:12601.005488 global_time:374, event:`SYSCALL: getrlimit' (state:ENTERING_SYSCALL) tid:27487, ticks:271541
 rax:0xffffffffffffffda rbx:0x7ffcd41efc18 rcx:0xffffffffffffffff rdx:0x3f rsi:0x7ffcd41efc00 rdi:0x3 rbp:0x2ab695a6f060 rsp:0x7ffcd41efbe8 r8:0x0 r9:0x7ffcd41efb40 r10:0x7ffcd41ef9b0 r11:0x246 r12:0x7ffcd41efc10 r13:0x7ffcd41efd88 r14:0x2ab695a701c8 r15:0x0 rip:0x2ab696df1c07 eflags:0x246 cs:0x33 ss:0x2b ds:0x0 es:0x0 fs:0x0 gs:0x0 orig_rax:0x61 fs_base:0x2ab695891780 gs_base:0x0
}
{
  real_time:12601.006618 global_time:375, event:`SYSCALL: getrlimit' (state:EXITING_SYSCALL) tid:27487, ticks:271541
 rax:0x0 rbx:0x7ffcd41efc18 rcx:0xffffffffffffffff rdx:0x3f rsi:0x7ffcd41efc00 rdi:0x3 rbp:0x2ab695a6f060 rsp:0x7ffcd41efbe8 r8:0x0 r9:0x7ffcd41efb40 r10:0x7ffcd41ef9b0 r11:0x246 r12:0x7ffcd41efc10 r13:0x7ffcd41efd88 r14:0x2ab695a701c8 r15:0x0 rip:0x2ab696df1c07 eflags:0x246 cs:0x33 ss:0x2b ds:0x0 es:0x0 fs:0x0 gs:0x0 orig_rax:0x61 fs_base:0x2ab695891780 gs_base:0x0
  { tid:27487, addr:0x7ffcd41efc00, length:0x10 }
}
{
  real_time:12601.007904 global_time:376, event:`SYSCALL: futex' (state:ENTERING_SYSCALL) tid:27487, ticks:274433
 rax:0xffffffffffffffda rbx:0x2ab695a6f060 rcx:0xffffffffffffffff rdx:0x7fffffff rsi:0x81 rdi:0x2ab695ea10d0 rbp:0x2ab695c9f130 rsp:0x7ffcd41efbb0 r8:0x1 r9:0xf r10:0x7ffcd41ef950 r11:0x246 r12:0x7ffcd41efbe0 r13:0x7ffcd41efd88 r14:0x2ab695c96dd8 r15:0x0 rip:0x2ab696af0a99 eflags:0x246 cs:0x33 ss:0x2b ds:0x0 es:0x0 fs:0x0 gs:0x0 orig_rax:0xca fs_base:0x2ab695891780 gs_base:0x0
}
{
  real_time:12601.009111 global_time:377, event:`SYSCALL: futex' (state:EXITING_SYSCALL) tid:27487, ticks:274433
 rax:0x0 rbx:0x2ab695a6f060 rcx:0xffffffffffffffff rdx:0x7fffffff rsi:0x81 rdi:0x2ab695ea10d0 rbp:0x2ab695c9f130 rsp:0x7ffcd41efbb0 r8:0x1 r9:0xf r10:0x7ffcd41ef950 r11:0x246 r12:0x7ffcd41efbe0 r13:0x7ffcd41efd88 r14:0x2ab695c96dd8 r15:0x0 rip:0x2ab696af0a99 eflags:0x246 cs:0x33 ss:0x2b ds:0x0 es:0x0 fs:0x0 gs:0x0 orig_rax:0xca fs_base:0x2ab695891780 gs_base:0x0
}
{
  real_time:12601.010133 global_time:378, event:`SYSCALL: brk' (state:ENTERING_SYSCALL) tid:27487, ticks:288401
 rax:0xffffffffffffffda rbx:0x0 rcx:0xffffffffffffffff rdx:0x20050 rsi:0x0 rdi:0x0 rbp:0x21000 rsp:0x7ffcd41efa48 r8:0x0 r9:0x3 r10:0xc r11:0x246 r12:0x2ab6970c24f0 r13:0x2ab6970bf7b8 r14:0x21000 r15:0x2ab6970bf7b8 rip:0x2ab696df20cc eflags:0x246 cs:0x33 ss:0x2b ds:0x0 es:0x0 fs:0x0 gs:0x0 orig_rax:0xc fs_base:0x2ab695891780 gs_base:0x0
}
```

Here's the complete dump of the program: [record_replay_dump.zip](https://github.com/mozilla/rr/files/720685/record_replay_dump.zip).

I'm running as a vmware guest, Ubuntu Trusty configuration:
```
/home/linuxdev/workspace/rr/build-rr$ uname -a
Linux ubuntu 3.16.0-77-generic #99~14.04.1-Ubuntu SMP Tue Jun 28 19:17:10 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
/home/linuxdev/workspace/rr/build-rr$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 14.04.5 LTS
Release:        14.04
Codename:       trusty
/home/linuxdev/workspace/rr/build-rr$
```
In order to make rr compile, I had to comment out a few lines due to nonexistent identifiers--any tips on how to make those work are also appreciated.  Here's a patch of the changes I had to make.    [rr-patches-ubuntu-trusty.patch.txt](https://github.com/mozilla/rr/files/720694/rr-patches-ubuntu-trusty.patch.txt)

In my real program, I seem to get this specific assert across a random list of system calls.  This doesn't seem related to similar issues described earlier... this test program doesn't appear to be using HLE or anything like that.  Any tips on how to debug this?  Much appreciated!

**Comment by rocallahan** [comment]
By "reliably reproduce" do you mean it happens every time?

This sort of bug is not easy to debug at arms length :-(.

Can you try running the same test in the same configuration except with the 4.4 kernel that Ubuntu 14.04 apparently offers? There are perfcounter bugs in kernels older than that that we never really were able to characterize. Those bugs produced intermittent test failures for me, but YMMV...

**Comment by rocallahan** [comment]
I pushed a fix for most of your build issues:
https://github.com/mozilla/rr/commit/8e5bfcf17112bf6307e0e9cd9db9738ea3780fc2
I couldn't figure out your issue in `personality.c`. `UNAME26` has been around forever and I can't conditionally define it since it's an enum value, not a `#define`. Other than that they should all be fixed.

**Comment by rocallahan** [comment]
Another thing you could try is configuring your VMware guest to mask off support for RTM (but don't bother if your CPU doesn't have that), in case our hacks to block RTM aren't working.

**Comment by pjogrady** [comment]
Thanks so much for your input; it's gonna take some work to get the 4.4 kernel test; but in the meantime, I don't think I'm running with either HLE or RTM:

```
processor       : 0
vendor_id       : GenuineIntel
cpu family      : 6
model           : 63
model name      : Intel(R) Xeon(R) CPU E5-1630 v3 @ 3.70GHz
stepping        : 2
microcode       : 0x38
cpu MHz         : 3691.529
cache size      : 10240 KB
(snip)
flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush
 dts mmx fxsr sse sse2 ss syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon pebs bts nopl xt
opology tsc_reliable nonstop_tsc aperfmperf eagerfpu pni pclmulqdq vmx ssse3 fma cx16 pcid sse4_1
 sse4_2 x2apic movbe popcnt aes xsave avx f16c rdrand hypervisor lahf_lm ida arat epb xsaveopt pl
n pts dtherm tpr_shadow vnmi ept vpid fsgsbase smep
```

[cpuinfo.zip](https://github.com/mozilla/rr/files/725108/cpuinfo.zip) has the full output from /proc/cpuinfo showing the same flags for 4 CPUs.

**Comment by pjogrady** [comment]
Whatever I have in my configuration isn't fixed by going to either a 4.2 or 4.4 kernel--they both produce the same message (with different tick values) when running this test.  Here's the output from both tests; kernel 4.2: [42.txt](https://github.com/mozilla/rr/files/725209/42.txt) and kernel 4.4: [44.txt](https://github.com/mozilla/rr/files/725210/44.txt).

Given how rr updates the ticks number on return from the system call, perhaps you can help me with a quick overview of how that works?  I know that replayed system calls don't operate in real time.  In other words, the replay clock is adjusted by the recorded time it took, rather than actually waiting that long.  Given that the assert fails always with replay ticks being less than the recorded ticks, it seems like something in that area would want to be looked at-- but I really don't know enough to know if that is a sensible place to look.

**Comment by rocallahan** [comment]
Those ticks count conditional branches. No ticks elapse during system calls. A ticks mismatch means that somehow the program took a different path during replay vs recording ("divergence"). That can have any number of causes.

**Comment by rocallahan** [comment]
Thanks for trying those things. Probably the best next step is for me to try to replicate the bug. But before I do that: what's your host OS?

**Comment by pjogrady** [comment]
Windows 7 SP 1; VMWare player 6.0.6 build-2700073.

**Comment by rocallahan** [comment]
Did you configure your VMWare guest as described here: http://robert.ocallahan.org/2015/11/rr-in-vmware-solved.html ?

**Comment by rocallahan** [comment]
Also, Player 6.0.6 seems kind of old. It might be worth trying the latest release.

**Comment by pjogrady** [comment]
THANKS SO MUCH, that rr-in-vmware-solved.html was my problem.  For those too impatient to read your brief node, add
`monitor_control.disable_hvsim_clusters = true`
to your virtual machine's .vmx file.

**Comment by rocallahan** [comment]
Hmm, rr should have warned you about that every time you ran it: https://github.com/mozilla/rr/blob/master/src/CPUIDBugDetector.cc#L24

**Comment by pjogrady** [comment]
Looks like this might be why I didn't see that message: 
[https://github.com/mozilla/rr/blob/master/src/test/util.sh#L87](https://github.com/mozilla/rr/blob/master/src/test/util.sh#L87)

**Comment by rocallahan** [comment]
Sure, but that message should have been printed when you ran rr on your program, outside the tests.
