### ISSUE TITLE
`Task::did_waitpid` does not normalize registers when it should

### ISSUE THREAD

**Issue by rocallahan** [mozilla/rr#1941]
@Keno commit 70de61ab24985b465d4c530ed3043bf87cd255ca changed `Task::did_waitpid` so that `fixup_syscall_registers` is only called for syscalls through the rr-page. This is incorrect because under some conditions (which I haven't puzzled out) RCX is not set to -1 during replay while it is during recording. I consistently get divergence due to this issue ... while replaying a recording of rr doing a replay using some rather complicated binary instrumentation stuff, so it's not easy to reduce the testcase.

**Comment by rocallahan** [comment]
I guess the reason @Keno changed this was because outside of the rr-page we don't immediately know what architecture the syscall was, which made the existing logic in `is_in_non_sigreturn_exit_syscall` etc more complicated.

**Comment by Keno** [comment]
I think if the syscall is traced, the register fixup should still be happening during replay. There shouldn't be any untraced syscalls outside the rr page, should there?

**Comment by rocallahan** [comment]
What would cause the fixup to happen during replay for traced syscalls? It needs to happen for traced syscalls as well as untraced.

**Comment by Keno** [comment]
`ReplaySession::enter_syscall` canonicalizes registers for traced syscalls.

**Comment by rocallahan** [comment]
You're quite right. Sorry for the noise. The bug was something else.
