### ISSUE TITLE
rr replay on firefox recordings sometimes get stuck

### ISSUE THREAD

**Issue by bholley** [mozilla/rr#1942]
Using rr 4.4.0, ubuntu 16.10.

It tends to happen repeatedly, but I haven't nailed down whether it's a property of the replay, the recording, the workload, or system state.

Attaching a debugger seems to hang.

bholley@station:~ $ sudo cat /proc/3864/stack 
[<ffffffffffffffff>] 0xffffffffffffffff
bholley@station:~ $

**Comment by bholley** [comment]
[rrlog.zip](https://github.com/mozilla/rr/files/728675/rrlog.zip)

**Comment by bholley** [comment]
CC @rocallahan

**Comment by bholley** [comment]
Reproduces on master.

I ran the tests on my build of master, and all of them passed except one. How do I rerun just one test?

99% tests passed, 1 tests failed out of 2004

Total Test time (real) = 3172.19 sec

The following tests FAILED:
	1754 - rr_ps_ns-32-no-syscallbuf (Failed)
Errors while running CTest
Makefile:149: recipe for target 'test' failed
make: *** [test] Error 8

**Comment by bholley** [comment]
Ah: ctest -R rr_ps_ns-32-no-syscallbuf

Seems to pass when run standalone.

**Comment by bholley** [comment]
Actually, fails intermittently: https://pastebin.mozilla.org/8968991

**Comment by rocallahan** [comment]
That is probably not related to your issue.
I thought this might have been the bug addressed in https://github.com/mozilla/rr/pull/1935 but if you see this problem on master, then not.

**Comment by rocallahan** [comment]
Can you run rr under gdb and then press ctrl-C when things get stuck?

**Comment by rocallahan** [comment]
Also, can you `rr dump -b -m -p` around event 3865?

**Comment by rocallahan** [comment]
And does replay always hang at that event?

**Comment by Keno** [comment]
Those symptoms certainly do look like #1935.

**Comment by Keno** [comment]
In other news though, my patch for that kernel bug was just merged into the kernel, so if you're willing to build a mainline kernel, that would easily confirm if that's the issue.

**Comment by bholley** [comment]
I think I deleted the original trace for the log I attached, but I reproduced with master and I appear to hang in about the same spot. The event number is different on the new recording, but it happens right after mmapping startupCache.8.little (which only appears once in the log) in both the old and the new recording.

Here's the tail end of the logs for two replays of my nightly recording:
https://pastebin.mozilla.org/8969244
https://pastebin.mozilla.org/8969245

**Comment by bholley** [comment]
Here's the stack trace when I do |gdb --args rr-nightly replay| and ctrl-c when it gets stuck: https://pastebin.mozilla.org/8969247

Looks like we're stuck polling on a 6-level-deep call of linux_ptrace_test_ret_to_nx_instr.

**Comment by bholley** [comment]
> Also, can you rr dump -b -m -p around event 3865?

I don't grok this. IIUC 3865 is the tid, which will vary between replay executions. If it's supposed to be consistent across replays, then the two pastebins in https://github.com/mozilla/rr/issues/1942#issuecomment-275179441 indicate divergent replays!

If you're interested in the last event being logged (3093 in the attached log, 3072 in the new recording), here's the dump:

https://pastebin.mozilla.org/8969267

**Comment by bholley** [comment]
> so if you're willing to build a mainline kernel

I'm hesitant to, since this is an off-the-shelf ubuntu system that I need to be functional to get work down today. But it's an option if we really need it.

**Comment by Keno** [comment]
Happy to build you one and send you a .deb

**Comment by bholley** [comment]
> Happy to build you one and send you a .deb

Appreciate the offer! I'm probably a bit too paranoid for that, but I could build it myself with instructions. A few questions though:
* How likely is it that a new kernel would solve this given that I'm using rr master with the workaround?
* How easy is it to build and boot into a custom kernel while retaining the ability to boot into my original one? I'm running the proprietary nvidia drivers, which may complicate things.

I've got a lot on my plate this week, so I'd really rather avoid messing around with my kernel unless we're very sure that it's the right thing to try.

**Comment by rocallahan** [comment]
> Here's the stack trace when I do |gdb --args rr-nightly replay| and ctrl-c when it gets stuck: https://pastebin.mozilla.org/8969247

That's the stack trace of the gdb swapped in by rr. Try again passing the `-s` option to `rr replay` and attach gdb externally so your rr-under-gdb doesn't exec gdb.

**Comment by bholley** [comment]
Nuking my profile seems to do the trick, which provides additional evidence that this is related to the startup cache.

Note to self: The trace for the pastebins above is firefox-3.

**Comment by bholley** [comment]
If I do:

> RR_LOG=all gdb --args rr-nightly replay -s 8484 ~/.local/share/rr/firefox-3/

It tells me to launch gdb with:

> gdb '-l' '10000' '-ex' 'target extended-remote :8484' /home/bholley/.local/share/rr/firefox-3//mmap_hardlink_3_firefox

If I do that, and then hit 'c' in the gdb window, the process starts, and gets hung. Back in the first window (gdb --args rr-nightly replay ....) I can't seem to control-C:

[AutoRemoteSyscalls] syscall mmap
[Task] resuming execution of 25125 with PTRACE_SYSCALL
[Task] going into blocking waitpid(25125) ...
[Task]   waitpid(25125) returns 25125; status 0x857f (SYSCALL)
[Task]   (refreshing register cache)
[Task] resuming execution of 25125 with PTRACE_SYSCALL
[Task] going into blocking waitpid(25125) ...
[Task]   waitpid(25125) returns 25125; status 0x857f (SYSCALL)
[Task]   (refreshing register cache)
[AutoRemoteSyscalls] done, result=140210987569152


^C
^C
^C
^C
^C
^C^C^C^C^C^C^C^C

**Comment by mrbkap** [comment]
I'm also seeing basically the same thing as bholley. I was just chatting with khuey about it and he said he'd try to repro soon.

**Comment by khuey** [comment]
@mrbkap what m-c cset did you see this on?

**Comment by mrbkap** [comment]
@khuey https://hg.mozilla.org/mozilla-central/rev/5a4412474c63e1d9e66036d603ac42e9cb2b9150

**Comment by bholley** [comment]
For me https://hg.mozilla.org/mozilla-central/rev/8ff550409e1d

**Comment by bholley** [comment]
And to be clear, I'm pretty sure this only happens when there's an existing profile, presumably because the issue is related to reading the startup cache or something nearby.

**Comment by rocallahan** [comment]
Try running rr replay -a under strace to see where it gets stuck.

**Comment by bholley** [comment]
This is the strace output: https://pastebin.mozilla.org/8969378

**Comment by rocallahan** [comment]
So hanging in a large pwrite. Sure look similar to Keno's kernel bug...

**Comment by rocallahan** [comment]
Try dumping /proc/.../maps for the tracee when rr gets stuck to confirm
that Keno's workaround is kicking in. Maybe it is, but it doesn't prevent
the bug in this case?

**Comment by bholley** [comment]
https://pastebin.mozilla.org/8969407

**Comment by rocallahan** [comment]
No, the /proc/.../maps for the tracee. That's the maps for rr itself.

**Comment by bholley** [comment]
Oh I see. Here you go: https://pastebin.mozilla.org/8969439

**Comment by rocallahan** [comment]
````
7f856a1b9000-7f856a600000 r--p 00000000 00:00 0
````
So Keno's workaround did not kick in!

**Comment by rocallahan** [comment]
Are you sure you build master from a changeset that includes ccc9ed087a82388d99b5a1e47692ac0992977ab3?

**Comment by rocallahan** [comment]
If you did, then try inserting some logging to `safe_pwrite64` to log when we add a mapping to `mappings_to_fix` ... and if possible determine whether we add the mapping with start address `0x7f856a1b9000` to `mappings_to_fix`, and if not, why not.

**Comment by rocallahan** [comment]
I think I've found the problem.

**Comment by rocallahan** [comment]
OK, I think https://github.com/mozilla/rr/commit/5157b4ad3871de5ea2d76df7629e3cea54cad35a should fix this!

**Comment by rocallahan** [comment]
And if it does, we should do an rr 4.5.0 release.

**Comment by Keno** [comment]
Good catch.

**Comment by bholley** [comment]
> OK, I think 5157b4a should fix this!

It does. Thanks!
