### ISSUE TITLE
rr fails to build on Debian Jessie

### ISSUE THREAD

**Issue by phulin** [mozilla/rr#1943]
Debian kernel version 3.16.36-1+deb8u2.

Undefined identifier UNAME26. It looks like it's because src/test/personality.c includes sys/personality.h, not linux/personality.h. The first comes from glibc on my system, the second from linux-libc-dev, which I believe comes directly from the kernel? src/record_syscall.cc includes linux/personality.h, so it compiles successfully.

**Comment by phulin** [comment]
Changing the include doesn't work because linux/personality.h doesn't define the personality syscall (obviously). Not sure why the glibc header doesn't define UNAME26.

**Comment by phulin** [comment]
Looks like this commit fixed that problem as of 10 months ago, but versions of glibc older than that will not work:

https://github.com/bminor/glibc/commit/9ff9351d028d43af1cc2eaf432004ada0996bbf0

**Comment by rocallahan** [comment]
Aha! Thanks for tracking that down. Should be fixed now.
