### ISSUE TITLE
Assertion `!!(blocked & mask) == is_sig_blocked(sig)' failed to hold. SIGSTKFLT is blocked

### ISSUE THREAD

**Issue by staktrace** [mozilla/rr#1946]
Probably related to #1914 but I figured it's safer to file a new issue.

On a linux debug build of Firefox, with latest rr (cset a76eabbfb9), I'm running into this error. I've posted the command I was running with its output, the firefox and rr backtraces, as well as the `rr dump` output at https://gist.github.com/staktrace/fdce2e76840db0a7d1fefb444bca8d78.

Seems to be easily reproducible, let me know if you need anything else.

**Comment by rocallahan** [comment]
Probably something to do with how sigmasks are tracked when we reenter the syscallbuf in a signal handler to call sigprocmask and find that the sycallbuf is locked. I'll try writing a simplified testcase.

**Comment by rocallahan** [comment]
Hooray, I can reproduce this with a small testcase.

**Comment by rocallahan** [comment]
The problem is actually that `rt_sigaction`'s `sa_mask` can block the signals we care about during the signal handler. Not only can this cause the assertion above, it can actually cause hangs if the signal handler does a syscallbuf-ed blocking syscall, because our desched signal won't be raised.

**Comment by rocallahan** [comment]
That should have fixed it. Reopen if not.

**Comment by staktrace** [comment]
Thanks! Verified that latest rr fixes the problem.
