### ISSUE TITLE
Dumb x86 vs x86_64 build issue on Fedora

### ISSUE THREAD

**Issue by fitzgen** [mozilla/rr#1949]
I think I have hit this every time I tried to build `rr` from source on a new machine. The wiki page with build instruction for Fedora ask you to install a bunch of packages for i686, and I don't think that is right. Instead, I think they should let `dnf` choose the correct version of the package.

Anyways, following those instructions, I end up with cmake configuration errors like this:

```
-- The C compiler identification is GNU 6.3.1
-- The CXX compiler identification is GNU 6.3.1
-- The ASM compiler identification is GNU
-- Found assembler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
/usr/bin/ld: cannot find crt1.o: No such file or directory
/usr/bin/ld: cannot find crti.o: No such file or directory
/usr/bin/ld: skipping incompatible /usr/lib/gcc/x86_64-redhat-linux/6.3.1/libgcc_s.so when searching for -lgcc_s
/usr/bin/ld: cannot find -lgcc_s
/usr/bin/ld: cannot find -lc
/usr/bin/ld: skipping incompatible /usr/lib/gcc/x86_64-redhat-linux/6.3.1/libgcc_s.so when searching for -lgcc_s
/usr/bin/ld: cannot find -lgcc_s
/usr/bin/ld: cannot find crtn.o: No such file or directory
collect2: error: ld returned 1 exit status
CMake Error at CMakeLists.txt:76 (message):
  Your toolchain doesn't support 32-bit cross-compilation.  Install the
  required packages or pass -Ddisable32bit=ON to cmake.


-- Configuring incomplete, errors occurred!
See also "/home/fitzgen/rr/obj/CMakeFiles/CMakeOutput.log".
```

And if I continue with `-Ddisable32bit=ON` then I can build but all the tests fail. On my other machines where I already have `rr` building OK, I didn't have to disable any 32 bit things, so I think the issue is even earlier in the process and with the prereqs installation. But I don't know how to fix this! I tried installing without the `.i686` postfix, but I'm not getting any further in my builds.

Help please!

**Comment by khuey** [comment]
Sounds like you're missing `libgcc.i686`.

**Comment by rocallahan** [comment]
> The wiki page with build instruction for Fedora ask you to install a bunch of packages for i686, and I don't think that is right.

We need those i686 packages so we can build the code that lets 64-bit rr record 32-bit binaries.

> Sounds like you're missing libgcc.i686.

I thought that'd be pulled in by the other packages but I added `libgcc` and `libgcc.i686` to the wiki instructions just in case.

**Comment by fitzgen** [comment]
Ok, you were right, works now. Thanks!
