### ISSUE TITLE
Calls to functions sometimes break 'when'.

### ISSUE THREAD

**Issue by phulin** [mozilla/rr#1968]
e.g.

```
Thread 2 hit Breakpoint 2, cpu_loop_exec_tb (cpu=0x55de7e933960, tb=0x7fa4afba00b0, last_tb=0x7fa4af9ba670, tb_exit=0x7fa4af9ba65c, sc=0x7fa4af9ba6
    at /home/phulin/lava/panda/cpu-exec.c:621
621         if (unlikely(atomic_read(&cpu->exit_request))) {
(rr) when
Current event: 3072
(rr) call memory_region_find(system_memory, 0x2000000, 1)
$2 = {mr = 0x55de7e99fc10, address_space = 0x55de7dbe06a0 <address_space_memory>, offset_within_region = 33554432, 
  size = 0x00000000000000000000000000000001, offset_within_address_space = 33554432, readonly = false}
(rr) when
Current event not known (diversion?)
```

A quick perusal of rr code indicates this is because the Session is no longer a ReplaySession. But I don't understand the code well enough to really track it further.

**Comment by rocallahan** [comment]
I guess we need to add metadata to GdbCommands to indicate if they  should bust out of a DiversionSession or not, like we discussed a while back.

**Comment by phulin** [comment]
Oh, so the default behavior is that after you call a function you stay in the forked-off process? Is there any way to get visibility into that from gdb?

**Comment by rocallahan** [comment]
No, this is an area where the interface between gdb and rr is murky. rr has this concept of a temporary diversion state, but gdb knows nothing about it and rr has to use heuristics to decide when to enter and exit a diversion.
