### ISSUE TITLE
rr asserts under VMWare Fusion when running executable stored on host's file system 

### ISSUE THREAD

**Issue by lars-t-hansen** [mozilla/rr#1970]
Below, ~/mozilla-inbound is a symlink into /mnt/hgfs, ie the Mac's host file system.

Symptom:
```
$ rr record ~/mozilla-inbound/js/src/b-debug/dist/bin/js ...elided... 
rr: Saving execution to trace directory `/home/lhansen/.local/share/rr/js-2'.
rr: /home/lhansen/rr/rr/src/record_syscall.cc:4084: 
  bool rr::is_privileged_executable(const string&):
  Assertion `errno == ENODATA' failed.
Aborted (core dumped)
```

Copying the executable and its libraries to a directory on the virtual disk works around the issue.

**Comment by Keno** [comment]
What kind of file system does the guest see here? Can you attach gdb and see what errno you're actually getting?

**Comment by rocallahan** [comment]
Presumably he's getting `ENOTSUP`. We should probably just handle that.

**Comment by rocallahan** [comment]
I'll do it.

**Comment by rocallahan** [comment]
Done: https://github.com/mozilla/rr/commit/3741bf0e1de760fed116425a0a59b50d23683bc4

**Comment by rocallahan** [comment]
Lars, please retry and let us know :-)

**Comment by lars-t-hansen** [comment]
Yes, works now.  Thanks!
