### ISSUE TITLE
[FATAL /src/rr/src/Session.cc:486:create_shared_mmap() errno: ENOMEM] Failed to mmap shmem region

### ISSUE THREAD

**Issue by tbsaunde** [mozilla/rr#1992]
the rr process has a total of 65532 maps open of which more than 65000 appear to be /tmp/rr-shared-preload_thread_local_X_y  I haven't checked, but as a guess rr isn't cleaning 
[rr-maps.txt](https://github.com/mozilla/rr/files/801665/rr-maps.txt)
up these mappings when processes exit?

**Comment by rocallahan** [comment]
Yes, it looks like we're leaking. Investigating...
