### ISSUE TITLE
[FATAL /home/juraj/rr/src/Task.cc:2192:write_bytes_helper() errno: EINVAL] 

### ISSUE THREAD

**Issue by ojura** [mozilla/rr#1993]
I am trying to replay a trace recorded with 4.5.0 using the master (aabe65d at the time of writing). I get the following:

```
$ ./rr replay -a
[FATAL /home/juraj/rr/src/Task.cc:2192:write_bytes_helper() errno: EINVAL] 
 (task 21275 (rec:26132) at time 3531)
 -> Assertion `nwritten == buf_size' failed to hold. Should have written 1 bytes to 0xfffff0003d480600, but only wrote -1
Launch gdb with 
  gdb '-l' '10000' '-ex' 'target extended-remote :21275' /home/juraj/.local/share/rr/latest-trace/mmap_hardlink_3_cartographer_offline_node
```

I did a git bisect and have nailed it down to two commits. At 6d6452b2ccf440, running replay started hanging rr, with no output. At f87cc0ac, it doesn't hang anymore, but rather prints the above message.

**Comment by ojura** [comment]
As far as I can see, this is an incompatibility between the new version of rr and the trace recorded by the old version. In principle, you're not guaranteeing compatibility between traces made with an old version and a new version? If this can't be properly fixed, maybe you could just warn the user that they have to use the same version of rr to replay the recording.

**Comment by rocallahan** [comment]
This is my fault for not updating `TRACE_VERSION` when I should have. Fixed: https://github.com/mozilla/rr/commit/1e561cef427443f39c027aaba7acb9fb1f5ebfd4
Sorry about that.
