### ISSUE TITLE
FOLL_COW kernel bug workaround causes slowdown setting breakpoints

### ISSUE THREAD

**Issue by rocallahan** [mozilla/rr#2005]
Commit ccc9ed087a82388d99b5a1e47692ac0992977ab3 modified `safe_pwrite64` to trigger the `mprotect(PROT_WRITE)` workaround for any read-only mapping >= 2MB. Unfortunately this triggers when setting a breakpoint in any reasonably large binary, meaning that setting such a breakpoint requires 8 (!) context switches (two `AutoRemoteSyscall`s, each doing two `resume_execution`s with waits).

Perhaps, given that the fix for that kernel bug has been widely backported to the same stable kernels that regressed in the first place, we can just remove the workaround.

The only alternative I can see is to check in @Keno's test in http://marc.info/?l=linux-kernel&m=148359462917379&w=2 and run it in rr to detect the kernel bug. Well, apart from the alternative of just ignoring this issue. But that grates.

**Comment by Keno** [comment]
I think it's fine to disable the workaround since the patch is being picked up by stable kernels.

**Comment by rocallahan** [comment]
Thanks. I guess we'll do that.

**Comment by rocallahan** [comment]
We had to reland the workaround because not all Linux kernel stable branches had Keno's fix.

Here's the current status of the stable branches advertised on the linux-kernel list, as of April 11:
````
3.2   FIXED March 17
3.12  in progress as of April 11
3.16  FIXED March 17
4.4   in progress as of April 11 (according to Keno; I can't find any corresponding patch-review email)
4.7   EOL Oct 21 2016 (affected, unfixed)
4.8   EOL Jan 7 (affected, unfixed)
4.9   FIXED Feb 2
4.10+ FIXED Jan 30
````
So I think we'll be covered after the next releases of 3.12 and 4.4 ... after users have updated, of course.

Anyone stuck on 4.7 or 4.8 is still going to be affected, but we can hope that's not too many users. They should update kernels anyway unless someone out there is maintaining those kernels off-list.

**Comment by rocallahan** [comment]
So 4.4.64 just came out and it appears @Keno's fix has not yet made it in :-(. Maybe it got lost?

OTOH 3.12.73 came out on April 10 with @Keno's fix.

**Comment by rocallahan** [comment]
4.4 and 3.18 were released a few days ago with @Keno's fix.

**Comment by rocallahan** [comment]
> requires 8 (!) context switches

Right now I can't see why I said that. It looks like 4.
