### ISSUE TITLE
Stuck with "Attempt to take address of value not located in memory."

### ISSUE THREAD

**Issue by hotsphink** [mozilla/rr#2007]
I am replaying a firefox recording with rr. I foolishly stepped into something and ended up at

      _GLIBCXX_ALWAYS_INLINE __int_type
      load(memory_order __m = memory_order_seq_cst) const noexcept
      {
       memory_order __b = __m & __memory_order_mask;
	__glibcxx_assert(__b != memory_order_release);
	__glibcxx_assert(__b != memory_order_acq_rel);

	return __atomic_load_n(&_M_i, __m);
      }

in /usr/include/c++/6.3.1/bits/atomic_base.h

I can't execute any code. Continue, reverse-continue, step, si, etc all say

Attempt to take address of value not located in memory.
Command aborted.
(rr) 

I can do backtraces and things just fine.

**Comment by rocallahan** [comment]
Is this reproducible? Can you reproduce it in gdb without rr?

**Comment by hotsphink** [comment]
I can reproduce it on the same recording, but not trivially. (I repeated most of the same gdb commands.) I will attempt to simplify what is required to reproduce it, but at the moment I won't be able to reproduce without rr because my procedure involves setting a hw breakpoint and backstepping in various ways.

**Comment by hotsphink** [comment]
Reduced quite a bit. Current STR: run until seg fault. Set a hw watchpoint on some valid address. It doesn't matter which. Set a breakpoint on a line that calls a function that'll end up in that __atomic_load_n call. Reverse-continue to hit the seg fault again. Reverse-continue to that breakpoint. Step, finish, singlestep several times until reaching the __atomic_load_n call. Finish. It gets stuck in the described state.

The hw watchpoint is required to reproduce, even though it is never hit in this trace. The watched address does *not* matter; I tried watching a totally different address, and it reproduced.

The "finish" in the step, finish, step, step, step, step, step in the STR is because the line with the breakpoint is jsgc.cpp:6305:

    gcstats::AutoGCSlice agc(stats(), scanZonesBeforeGC(), invocationKind, budget, reason);

So the first step goes into scanZonesBeforeGC, the finish runs to the end of that, and the next steps step through the stats() call.

Attempting to simplify further, including removing all backwards stuff...

**Comment by hotsphink** [comment]
Unable to reproduce when only running forward.

(It could still be a gdb-only bug, of course. I just can't figure out how to trigger it without running backwards.)

I can't get it to happen if I don't hit the seg fault either.

Here are actual instructions that will reproduce with my binary. But my binary gives a handy seg fault midway through:

(rr) c
hits seg fault
(rr) up
(rr) p (void**)cx
(rr) watch -l *$
(rr) b jsgc.cpp:6305
(rr) rc
hits seg fault
(rr) rc
stops at jsgc.cpp:6305
(rr) s
(rr) fin
(rr) s
(rr) s
(rr) s
(rr) s
(rr) s
(rr) fin
gets stuck

**Comment by hotsphink** [comment]
Aha! Should have realized this as soon as I knew the hw watchpoint was necessary.

If I delete the watchpoint, I am able to run code again.

This is smelling like a gdb bug, unless there's something tricky going on here that I don't know about. The watched memory is still valid at the time of the problem, btw.

**Comment by rocallahan** [comment]
`RR_LOG=GdbConnection` might show us something useful. Though if it's a gdb bug we may not be able to work around it.

**Comment by hotsphink** [comment]
Unable to reproduce with baed600f618597085e0fc09d5ac52f0f0db04c68. I really wish I had recorded the git rev of what I was running before; I can't remember if it was the same one or not. But the recording that I *thought* it was is from an earlier rr version, so it looks like I'm newer.

I'll close this for now, but keep trying it when I have a similar situation.
