### ISSUE TITLE
What is rr's behavior when a program calls fork()?

### ISSUE THREAD

**Issue by pjogrady** [mozilla/rr#2008]
Hi, all--
I have a program that calls fork(); and I'm curious to know if there's a way to replay and debug the child process that fork creates?  This particular program forks several times, so it's important to be able to indicate exactly which PID should be followed.  Any ideas?

**Comment by khuey** [comment]
rr records the entire process tree.  You can use `rr ps` on a completed recording to view the process tree, and `replay -f`/`replay -p` to attach to a process when it is forked or execed, respectively.

**Comment by pjogrady** [comment]
OUTSTANDING, That does exactly what I'm looking for.  Thank you!
