### ISSUE TITLE
Recording Firefox mochitest under rr causes final result tally to show all zeros

### ISSUE THREAD

**Issue by mjfroman** [mozilla/rr#2011]
For example:
./mach mochitest dom/media/tests/mochitest/test_peerConnection_basicAudio.html --keep-open=false
Ends with:
```
0 INFO TEST-START | Shutdown
1 INFO Passed:  284
2 INFO Failed:  0
3 INFO Todo:    10
4 INFO Mode:    e10s
5 INFO SimpleTest FINISHED
Buffered messages finished
SUITE-END | took 6s
```

./mach mochitest dom/media/tests/mochitest/test_peerConnection_basicAudio.html --keep-open=false --debugger=rr
Ends with:
```
0 INFO TEST-START | Shutdown
1 INFO Passed:  0
2 INFO Failed:  0
3 INFO Todo:    0
4 INFO Mode:    e10s
5 INFO SimpleTest FINISHED
Buffered messages finished
SUITE-END | took 16s

```
However, both versions show something like the following a bit earlier in the output:
(non-rr)
```
508 INFO TEST-START | Shutdown
509 INFO Passed:  284
510 INFO Failed:  0
511 INFO Todo:    10
512 INFO Mode:    e10s
513 INFO Slowest: 2317ms - /tests/dom/media/tests/mochitest/test_peerConnection_basicAudio.html
514 INFO SimpleTest FINISHED
515 INFO TEST-INFO | Ran 1 Loops
516 INFO SimpleTest FINISHED
```

(with-rr)
```
GECKO(20878) | TEST-START | Shutdown
GECKO(20878) | Passed:  247
GECKO(20878) | Failed:  0
GECKO(20878) | Todo:    10
GECKO(20878) | Mode:    e10s
GECKO(20878) | Slowest: 4148ms - /tests/dom/media/tests/mochitest/test_peerConnection_basicAudio.html
GECKO(20878) | SimpleTest FINISHED
GECKO(20878) | TEST-INFO | Ran 1 Loops
GECKO(20878) | SimpleTest FINISHED

```
I don't remember this (the zero values at the end under rr) happening in the past, but I can't say with any certainty what version of rr I was using at the time.
[log-with-rr.txt](https://github.com/mozilla/rr/files/886979/log-with-rr.txt)
[log-without-rr.txt](https://github.com/mozilla/rr/files/886980/log-without-rr.txt)

**Comment by mjfroman** [comment]
uname -a
Linux moz 4.8.0-45-generic #48~16.04.1-Ubuntu SMP Fri Mar 24 12:46:56 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

mozilla-central changeset: 3364cc17988c

**Comment by khuey** [comment]
This happens with `--debugger=gdb`, so it is a bug in the mach harness (probably related to file descriptor redirection with `--debugger` if I had to guess.
