### ISSUE TITLE
Test failures due to improper handling of $TMPDIR

### ISSUE THREAD

**Issue by jhector** [mozilla/rr#2016]
My /tmp directory is mounted with 'noexec'. In order to make `make test` work it is necessary to specify `$TMPDIR` which points to a directory mounted with exec permissions, like this:
```
TMPDIR=/home/user/tmp make test
```
However, the following test are still failing:

> 749 - mprotect_growsdown (Failed)                                              
> 750 - mprotect_growsdown-no-syscallbuf (Failed)     
> 803 - string_instructions_async_signals_shared (Failed)
> 804 - string_instructions_async_signals_shared-no-syscallbuf (Failed)
> 869 - break_mmap_private (Failed)                   
> 870 - break_mmap_private-no-syscallbuf (Failed)     
> 1773 - mprotect_growsdown-32 (Failed)               
> 1774 - mprotect_growsdown-32-no-syscallbuf (Failed) 
> 1827 - string_instructions_async_signals_shared-32 (Failed)
> 1828 - string_instructions_async_signals_shared-32-no-syscallbuf (Failed)
> 1893 - break_mmap_private-32 (Failed)               
> 1894 - break_mmap_private-32-no-syscallbuf (Failed) 

I discussed this with roc on IRC and it seems rr internally drops a file to /tmp (hardcoded) and tries to mmap it back to memory with PROT_EXEC resulting in a EPERM failure because /tmp is mounted as noexec. This should account for the mprotect/mmap test failing. The error log is pasted here:
[mprotect/mmap failure log](https://pastebin.mozilla.org/9018242)

Unrelated to the mmap/mprotect seems this test:
> string_instructions_async_signals_shared

The underlying issue for this is still unkown, my error log is pasted here:
[string_instructions_async_signals_shared log](https://pastebin.mozilla.org/9018139)

**Comment by rocallahan** [comment]
I fixed all the hardcoding of /tmp I could find. That's on master.

**Comment by rocallahan** [comment]
For string_instructions_async_signals_shared, can you try
````
rr record -K .../string_instructions_async_signals_shared
rr replay -K -a
````
?

**Comment by jhector** [comment]
I did a `git pull`, and ran `make` again, running `make test` with `TMPDIR` set now fails all the tests.
Also, what path is this: `.../string_instructions_async_signals_shared` relative to (are the 3 dots intended?)?

**Comment by rocallahan** [comment]
> I did a git pull, and ran make again, running make test with TMPDIR set now fails all the tests.

Works for me.

> Also, what path is this: .../string_instructions_async_signals_shared

Wherever that file is on your system.

**Comment by jhector** [comment]
I did a `make clean` and a new `make` and now the tests are passing again.

For the output of the replay:
[https://pastebin.mozilla.org/9018628](https://pastebin.mozilla.org/9018628)

**Comment by rocallahan** [comment]
Hmm, so you have `/dev/shm` mounted noexec as well?

**Comment by rocallahan** [comment]
Did you run this with `TMPDIR` set to something other than `/tmp`? Was `/tmp` mounted noexec?

**Comment by rocallahan** [comment]
Fixed I think

**Comment by jhector** [comment]
Yes my /dev/shm is mounted noexec as well.
I can confirm that the mentioned tests now all pass with latest master. Thank you very much.
