### ISSUE TITLE
Error when recording new recording while replaying the latest-trace

### ISSUE THREAD

**Issue by Keno** [mozilla/rr#2027]
I was replaying a rather long running failure in the background and in the meantime decided to investigate something else by recording a different execution. Of course this caused the latest-trace directory to now point to my new recording. As a result the original replay failed with:
```
[FATAL /data/keno/rr/src/AutoRemoteSyscalls.cc:554:check_syscall_result() errno: SUCCESS]
 (task 22679 (rec:22576) at time 8507)
 -> Assertion `false' failed to hold. Syscall open failed with errno ENOENT opening /home/keno/.local/share/rr/latest-trace/mmap_clone_549_libgmp.so.10.3.2
```
I think it would be a good idea to resolve symlinks in the trace directory first, or even using openat on the resolved directory such that creating a new recording while replaying another doesn't mess up the replay.

**Comment by rocallahan** [comment]
> using openat on the resolved directory

`TraceWriter::make_latest_trace` needs to be able to create a symlink to the trace, which we can't do unless we have an actual path name, not just a file descriptor to the directory. So this doesn't work during recording. I guess we could use openat during replay by separating more of the code but that's more work, so for now I'll just use `realpath`.

**Comment by Keno** [comment]
Sounds good. Thanks!
