### ISSUE TITLE
RR assertion on reverse-continue

### ISSUE THREAD

**Issue by jrmuizel** [mozilla/rr#2029]
I got rr: /home/jrmuizel/src/rr/src/fast_forward.cc:109: bool rr::mem_intersect(rr::remote_ptr<void>, int, rr::remote_ptr<void>, int): Assertion `a2 + s2 > a2' failed.

I don't think I'll be able to reproduce it.

**Comment by rocallahan** [comment]
I assume this is a 64-bit rr build.

But I think I know how to reproduce this... Looks like you had a watchpoint at address -1 or something like that.

**Comment by rocallahan** [comment]
Actually I'm not sure the bug I'm looking at is the same as this, since we should have asserted earlier I think if there's a watchpoint at address -1. But I'll fix what I can see.

**Comment by rocallahan** [comment]
I guess the other possibility is that gdb somehow configured a zero-sized watchpoint, which would also trigger the above assertion in some cases, without asserting anywhere else. That commit fixes that too.

**Comment by rocallahan** [comment]
On reflection, also landed https://github.com/mozilla/rr/commit/3640251c9b3ee0949e69954cf6e7ff549132e5f7 to explicitly ignore zero-sized watches in fast_forward. We don't want to spuriously bound the iterations.

**Comment by jrmuizel** [comment]
It's very possible that there was something fishy with the watchpoint. i.e I may have set it on a rust zero sized type.
