### ISSUE TITLE
Provide a way to detect rr within .gdbinit

### ISSUE THREAD

**Issue by hotsphink** [mozilla/rr#2035]
There may be some clever way of doing this already. In my .gdbinit, I load a python init script .gdbinit.py. From that script, I want to detect whether I am running gdb directly, or gdb via rr. I want to be able to detect this during the initial script execution so I can choose whether or not to install some additional rr-specific commands.

I was using

    try:
        gdb.execute("when", False, True)
        RUNNING_RR = True
    except gdb.error:
        RUNNING_RR = False

but that fails during the initial script execution because the 'when' command has not yet been defined.

Even an environment variable would be fine.

**Comment by rocallahan** [comment]
OK, https://github.com/mozilla/rr/commit/e4b266451489dceb7ffd74e4bce538dbbaeca0f4 sets `GDB_UNDER_RR` when launching gdb. Note that if you launch a shell from gdb using `!` that inherits that variable and then running gdb-without-rr will get confused, but the chances of that are remote and I couldn't find any other way to make the information accessible to `~/.gdbinit`.

**Comment by hotsphink** [comment]
Perfect, thanks!
