### ISSUE TITLE
adjtimex.c:18:15: error: absolute value function 'abs' given an argument of type 'long' but has parameter of type 'int' which may cause truncation of value [-Werror,-Wabsolute-value]

### ISSUE THREAD

**Issue by dholbert** [mozilla/rr#2038]
I just tried to build rr with yesterday's clang trunk (clang version 5.0.0 from svn revision 304217).

The build failed at this build warning treated as an error:
````
/scratch/work/tools/rr/src/test/adjtimex.c:18:15: error: absolute value function 'abs' given an argument of type 'long' but has parameter of type 'int' which may cause truncation of value [-Werror,-Wabsolute-value]
  test_assert(abs(tx.time.tv_sec - ts.tv_sec) <= 1);
              ^
/scratch/work/tools/rr/rr/src/test/adjtimex.c:18:15: note: use function 'labs' instead
  test_assert(abs(tx.time.tv_sec - ts.tv_sec) <= 1);
              ^~~
              labs
/scratch/work/tools/rr/rr/src/test/rrutil.h:163:60: note: expanded from macro 'test_assert'
#define test_assert(cond) assert("FAILED: !" && check_cond(cond))
                                                           ^
/usr/include/assert.h:89:5: note: expanded from macro 'assert'
  ((expr)                                                               \
    ^
1 error generated.
````

**Comment by dholbert** [comment]
I'm not sure if clang's suggested fix (s/abs/labs/ in adjtimex.c) is good or correct, but it does fix the issue and allows my build to complete.

**Comment by rocallahan** [comment]
can you send us the PR?

**Comment by dholbert** [comment]
Sure, though I'm not yet 100% sure it's correct/sufficient for other platforms.

The variable that matters here is `tv_sec` (or rather, the result of subtracting two `tv_sec` values).  `tv_sec` has type `time_t` whose representation is up to the compiler, it seems.

In any case, labs() seems more capable than abs(), so even if clang's suggested fix isn't 100% sufficient, it's at least a step in the right direction.
