### ISSUE TITLE
Strange long lags when using rr on a frankenstein environment

### ISSUE THREAD

**Issue by thomasdullien** [mozilla/rr#2040]
Hey there,

I am using rr in a rather Frankenstein environment: I am debugging the windows library mpengine.dll using a shim for loading Windows DLLs into linux environments (https://github.com/taviso/loadlibrary).

Recording a trace works fine, but when I start single-stepping, I have strange high-variance in the times it takes to do a step - sometimes it is fast, and sometimes it takes minutes to perform a single forward "ni".

How would I best go about debugging this? :)

Cheers,
Thomas

**Comment by rocallahan** [comment]
Run rr with `RR_LOG=GdbConnection,ReplayTimeline` and show us the results for a fast and slow `ni`.

Is `stepi` always fast?

**Comment by thomasdullien** [comment]
Hey there,

after some more messing around: The issue appears to manifest itself only when debugging in the TUI GDB mode (Ctrl-X-A). I have attached a screenlog.0 of what is happening.

As far as I can tell, when "nexti" is performed normally (without TUI), the following happens:

(rr) ni
[GdbConnection] raw request Z0,8051580,1
[GdbConnection] gdb requests setbreakpoint (addr=0x8051580, len=1)
[GdbConnection] write_flush: '$OK#9a'
[GdbConnection] raw request Z0,f74c97d0,1
[GdbConnection] gdb requests setbreakpoint (addr=0xf74c97d0, len=1)
[GdbConnection] write_flush: '$OK#9a'
[GdbConnection] raw request Z0,f750c490,1
[GdbConnection] gdb requests setbreakpoint (addr=0xf750c490, len=1)
[GdbConnection] write_flush: '$OK#9a'
[GdbConnection] raw request Z0,f76f2560,1
[GdbConnection] gdb requests setbreakpoint (addr=0xf76f2560, len=1)
[GdbConnection] write_flush: '$OK#9a'
[GdbConnection] raw request vCont;s:p16a3.16a3;c:p16a3.-1
[GdbConnection] forcing query/resume thread to ANY
[GdbConnection] write_flush: '$T05thread:p16a3.16a3;#3a'
[GdbConnection] raw request g
[GdbConnection] gdb requests registers
[GdbConnection] write_flush: '$0100000006290cbb78a0beff684cba0970a0beff7ca0beff18c30b09000000003acb27f602020000230000002b0000002b0000002b0000000700000063000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000008002400000000000000080ff3f7f0300010001000000000000000000009b9929f6000000000000000000009b990000000000ff00000000000000000000696e7075740035095d1454f7987f350900000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000074656c696e652028272273656172636820626172223d90002e77726974656c696e652028272273656172636820706167801f0000ffffffff00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000#22'
[GdbConnection] raw request mf627cb3a,1
[GdbConnection] gdb requests memory (addr=0xf627cb3a, len=1)
[GdbConnection] write_flush: '$78#6f'
[GdbConnection] raw request mf627cac0,40
[GdbConnection] gdb requests memory (addr=0xf627cac0, len=64)
[GdbConnection] write_flush: '$e55dc204008bcee845831900ebe2cccccccccccccccccccc558bec51568bf1578b7d0c3bbeb400000077778b4d0872083b8eb0000000736a837d100074648b45#22'
[GdbConnection] raw request qfThreadInfo
[GdbConnection] gdb asks for thread list
[GdbConnection] write_flush: '$mp16a3.16a3#01'
[GdbConnection] raw request qsThreadInfo
[GdbConnection] write_flush: '$l#6c'
[GdbConnection] raw request z0,8051580,1
[GdbConnection] gdb requests removebreakpoint (addr=0x8051580, len=1)
[GdbConnection] write_flush: '$OK#9a'
[GdbConnection] raw request z0,f74c97d0,1
[GdbConnection] gdb requests removebreakpoint (addr=0xf74c97d0, len=1)
[GdbConnection] write_flush: '$OK#9a'
[GdbConnection] raw request z0,f750c490,1
[GdbConnection] gdb requests removebreakpoint (addr=0xf750c490, len=1)
[GdbConnection] write_flush: '$OK#9a'
[GdbConnection] raw request z0,f76f2560,1
[GdbConnection] gdb requests removebreakpoint (addr=0xf76f2560, len=1)
[GdbConnection] write_flush: '$OK#9a'
0xf627cb3a	64274	in {standard input}
(rr) x/20i $eip

On the other hand, when I issue an ni with TUI enabled a few instructions later, I end up with the following:

(rr) ni
[GdbConnection] raw request Z0,8051580,1
[GdbConnection] gdb requests setbreakpoint (addr=0x8051580, len=1)
[GdbConnection] write_flush: '$OK#9a'
[GdbConnection] raw request Z0,f74c97d0,1
[GdbConnection] gdb requests setbreakpoint (addr=0xf74c97d0, len=1)
[GdbConnection] write_flush: '$OK#9a'
[GdbConnection] raw request Z0,f750c490,1
[GdbConnection] gdb requests setbreakpoint (addr=0xf750c490, len=1)
[GdbConnection] write_flush: '$OK#9a'
[GdbConnection] raw request Z0,f76f2560,1
[GdbConnection] gdb requests setbreakpoint (addr=0xf76f2560, len=1)
[GdbConnection] write_flush: '$OK#9a'
M[GdbConnection] raw request mf6281900,40
[GdbConnection] gdb requests memory (addr=0xf6281900, len=64)
[GdbConnection] write_flush: '$00008bcee8c52f00005e8be55dc3cccccccccccccccccccc558bec538b5d0c565785db0f840eff13008bfb33c0ababab8b7d0885ff0f84fcfe1300f607040f84#d0'
[GdbConnection] raw request mf6281940,40
[GdbConnection] gdb requests memory (addr=0xf6281940, len=64)
[GdbConnection] write_flush: '$fbfe13006a0c6a085e56ff1504d396f650ff1500d396f689430485c0745f6a0c56ff1504d396f650ff1500d396f689430885c0744833c9c7000100000041e845#fd'
[GdbConnection] raw request mf6281980,40
[GdbConnection] gdb requests memory (addr=0xf6281980, len=64)
[GdbConnection] write_flush: '$0000008b4b046a025a89018bca8b4308895004e8300000008b4b046a035e8941048bce8b4308897008e81a0000008b4b04894108893333c05f5e5b5dc353e8d5#2d'
[GdbConnection] raw request mf62819c0,40
[GdbConnection] gdb requests memory (addr=0xf62819c0, len=64)
[GdbConnection] write_flush: '$d70a00598bc6ebf0a1f0ad96f685c0751868fe170000ba18080ff6b9d0240ff6e8ae4433005933c0c383e901741c83e901741183e9017406b80c250ff6c30540#d3'
[GdbConnection] raw request mf6281a00,40
(.... megabytes of sequential memory reads of size 0x40...)

Does this help?

More information:
1) This does not happen on all instructions, in my case, the first ~20 or so instructions
after a breakpoint work fine, and things only go crazy after a retn 0x14.
2) Stepi seems to not change much.

Cheers,
Thomas

**Comment by rocallahan** [comment]
This looks like it's probably not caused by rr, though rr may make the problem worse in some way. You could try running without rr to see how that goes. You could also try using gdb+gdbserver to see if the problem appears with a remote client that's not rr.

These reads look like the real problem here. What's at address 0xf6281900 in the tracee? We might need to attach gdb to gdb to see why it's issuing all those memory requests.

Are you using exactly the same gdb init scripts with TUI? I don't really know anything about TUI.

**Comment by Smattr** [comment]
This is probably just noise, but a few of the reported symptoms triggered something in my recent memory. Is it possible you're hitting one of less observable start up delays in mp* as discussed in https://github.com/taviso/loadlibrary/issues/5? My immediate intuition is no, but your environment sounds pretty unorthodox, so who knows.

With regards to TUI, I have had several scenarios I could successfully debug in GDB's REPL, but not in TUI. IME reverse stepping compounds these problems. E.g. I had something I could repro and step forward and back over in the REPL and doing the same in TUI would cause GDB to segfault. I generally treat the REPL as the gold standard.

Anyway, HTH.

**Comment by rocallahan** [comment]
Probably not an rr bug.
