### ISSUE TITLE
visiting https://rr-project.org/ gives errors about insecure connections

### ISSUE THREAD

**Issue by froydnj** [mozilla/rr#2041]
Firefox says:

```
rr-project.org uses an invalid security certificate.

The certificate is only valid for the following names: *.github.com, github.com, *.github.io, github.io

Error code: SSL_ERROR_BAD_CERT_DOMAIN
```

It'd be nice if we could link to https://rr-project.org/

**Comment by rocallahan** [comment]
Unfortunately there is no easy way to use HTTPS with github.io pages on a custom domain. We might be able to use Cloudflare to front it...

**Comment by sidkshatriya** [comment]
You may have already seen this, but now its possible to have custom domain names on github.io:

https://blog.github.com/2018-05-01-github-pages-custom-domains-https/

**Comment by khuey** [comment]
Yup, and we're already using it!
