### ISSUE TITLE
Unable to run rr on Intel i7-7700HQ

### ISSUE THREAD

**Issue by kinnison** [mozilla/rr#2043]
Hi,

I am unable to run rr on my Thinkpad T470p with an i7-7700HQ processor:

[FATAL /home/roc/rr/rr/src/PerfCounters.cc:162:get_cpu_microarch() errno: EOPNOTSUPP] CPU 0x906e0 unknown.

What do I need to supply to help you support this chip?

D.

**Comment by rocallahan** [comment]
Try rr master? That CPU should be supported on rr master.

**Comment by kinnison** [comment]
Does the CI produce debs for that sort of thing?  I've never built rr before myself.

**Comment by rocallahan** [comment]
No, we only produce packages when we do releases, and we should do one soon. But rr is pretty easy to build.

**Comment by kinnison** [comment]
I can confirm that master builds and passes its tests on my machine, thank you.  I look forward to the release.
