### ISSUE TITLE
Assertion `current->trace_reader().time() == mark.ptr->proto.key.trace_time'

### ISSUE THREAD

**Issue by hotsphink** [mozilla/rr#2049]
Similar reproduction steps to the previous issue I filed, issue 2048.

1. run to a seg fault in jit code
2. set a hardware watchpoint on a write to the (aligned) jitcode pointer
3. reverse-continue

It crashes with the above assert. See the attached 
[rr-log.txt](https://github.com/mozilla/rr/files/1098447/rr-log.txt), where the crashing $pc was 0x59c937d2041 and I did a watchpoint on 0x59c937d2040.

**Comment by rocallahan** [comment]
Maybe retry with this additional logging:
https://github.com/mozilla/rr/commit/fd478815ca4cade176ce06163ec0c8603e9b4575
Also, make sure your kernel is not affected by this regression: http://robert.ocallahan.org/2017/06/patch-on-linux-kernel-stable-branches.html
That could potentially manifest as a bug like this.

**Comment by rocallahan** [comment]
We discovered today that the bug seems to occur when a write-watchpoint is set on some instruction bytes in which rr sets a temporary breakpoint in `ReplayTimeline::replay_step_to_mark`. Setting the breakpoint and then running to it appears to trigger the write-watchpoint ... which is surprising, since rr's writes shouldn't trigger tracee watchpoints.

**Comment by hotsphink** [comment]
Thanks!

Somehow your patch has a strange s/changes/changwrite_memes/ in it.

I also don't understand the test -- it sets a watchpoint on $pc, but it never modifies that location. I assume it gets 'stopped' when it runs off the beginning of the program? Does that test the change? I guess it will, since it will avoid the assert.

It'd be nice to test that the watchpoints are hit, though maybe that overlaps with existing non-pc tests. I'll submit a PR and see what you think.

**Comment by rocallahan** [comment]
> it sets a watchpoint on $pc, but it never modifies that location

The test sets a breakpoint on the location, and rr adding and removing that breakpoint during internal machinations is what triggers the spurious watchpoint firing.
