### ISSUE TITLE
rr and gdb graphical front-end

### ISSUE THREAD

**Issue by mychele** [mozilla/rr#2051]
Hi all, 
I was wondering if it is possible to use rr together with one of the many gdb graphical front-ends (nemiver, ddd, etc).
Thanks,
Michele

**Comment by rocallahan** [comment]
Yes, it is. `rr replay -d` lets you set the debugger name. You can also do more complicated things with `rr replay -s` to start rr replay without launching the debugger, then launch your own debugger and connect it to rr.

**Comment by mychele** [comment]
Thanks a lot!

**Comment by mychele** [comment]
Hi,
sorry for re-opening this issue, but I get an error when trying to use rr and nemiver..

$ rr replay -d nemiver

error: Unknown option -l
Usage:
  nemiver [OPTION...]  [<prog-to-debug> [prog-args]]

A C/C++ debugger for GNOME

Help Options:
  -h, --help                                      Show help options
  --help-all                                      Show all help options
  --help-gtk                                      Show GTK+ Options

Application Options:
  --env=<"var0=val0 var1=val1 var2=val2 ...">     Set the environment of the program to debug
  --attach=<pid|process name>                     Attach to a process
  --load-core=</path/to/core/file>                Load a core file
  --list-sessions                                 List the saved debugging sessions
  --purge-sessions                                Erase the saved debugging sessions
  --session=<N>                                   Debug the program that was of session number N
  --last                                          Execute the last session
  --log-domains=<DOMAINS>                         Enable logging domains DOMAINS
  --log-debugger-output                           Log the debugger output
  --use-launch-terminal                           Use this terminal as the debugee's terminal
  --remote=<HOST:PORT|serial-line-path>           Connect to remote target specified by HOST:PORT
  --solib-prefix=</path/to/prefix>                Where to look for shared libraries loaded by the inferior. Use in conjunction with --remote
  --gdb-binary=</path/to/gdb>                     Set the path of the GDB binary to use to debug the inferior
  --just-load                                     Do not set a breakpoint in 'main' and do not run the inferior either
  --version                                       Show the version number of Nemiver
  --display=DISPLAY                               X display to use

**Comment by rocallahan** [comment]
That's happening because nemiver doesn't take the same options as gdb, i.e. it's not a drop-in replacement for gdb.

You probably want to start rr with `rr replay -s 9999` or something like that and then launch nemiver separtely with --remote=localhost:9999.

Of course, nemiver might not support the reverse-execution commands. I don't know much about it.

**Comment by ojura** [comment]
You can use it in an IDE which has a graphical frontend for gdb. Check out the guide [on the rr wiki](https://github.com/mozilla/rr/wiki/Using-rr-in-an-IDE) or [here](http://larics.fer.hr/farm/laricswiki/doku.php?id=software:debugging#reversible_debugging_with_rr). It's not foolproof, but it can be useful.

**Comment by rocallahan** [comment]
I'm going to close this; there isn't an rr issue here.
