### ISSUE TITLE
Assertion `false' failed to hold. overshot target ticks=31438659 by 21210

### ISSUE THREAD

**Issue by rlhunt** [mozilla/rr#2052]
I was attempting to replay a recording of gecko recently and ran into this:

```
[rhunt@rhunt-thinkpad firefox]$ rr replay -p 1121 -g 230222 ~/.local/share/rr/firefox-8/
[ERROR /home/rhunt/bin/rr/src/rr-4.5.0/src/ReplaySession.cc:545:guard_overshoot() errno: SUCCESS] Replay diverged; target registers mismatched: 
[FATAL /home/rhunt/bin/rr/src/rr-4.5.0/src/ReplaySession.cc:549:guard_overshoot() errno: SUCCESS] 
 (task 2287 (rec:1132) at time 2343)
 -> Assertion `false' failed to hold. overshot target ticks=31438659 by 21210
Launch gdb with 
  gdb '-l' '10000' '-ex' 'target extended-remote :2287' /home/rhunt/.local/share/rr/firefox-8//mmap_hardlink_3_firefox
```
Not sure exactly what that means.

The process and event number is from using `-M` option when recording.

I'm normally able to record and replay fine, and I can replay another recording I did from the same build.

**Comment by khuey** [comment]
You're probably running into https://mail.mozilla.org/pipermail/rr-dev/2017-June/000500.html and need to downgrade your kernel.

**Comment by rlhunt** [comment]
Ah, I even read that in the mailing list. That is probably what is happening. Thanks!
