### ISSUE TITLE
recording firefox: Assertion `!counting_period || measure_val <= adjusted_counting_period' failed to hold

### ISSUE THREAD

**Issue by mozkeeler** [mozilla/rr#2054]
Built firefox and then ran with ./mach run --debugger=rr:

keeler@p710 ~/mozilla-unified $ ./mach run --debugger=rr
 0:00.19 /usr/local/bin/rr /home/keeler/mozilla-unified/obj-x86_64-pc-linux-gnu/dist/bin/firefox -no-remote -profile /home/keeler/mozilla-unified/obj-x86_64-pc-linux-gnu/tmp/scratch_user
rr: Saving execution to trace directory `/home/keeler/.local/share/rr/firefox-15'.
[FATAL /home/keeler/src/rr/rr/src/PerfCounters.cc:617:read_ticks() errno: SUCCESS] 
 (task 21187 (rec:21187) at time 1136)
 -> Assertion `!counting_period || measure_val <= adjusted_counting_period' failed to hold. Detected 493095 ticks, expected no more than 247037
=== Start rr backtrace:
/usr/local/bin/rr(_ZN2rr13dump_rr_stackEv+0x3e)[0x77830e]
/usr/local/bin/rr(_ZN2rr9GdbServer15emergency_debugEPNS_4TaskE+0x1c9)[0x626eb9]
/usr/local/bin/rr[0x64d544]
/usr/local/bin/rr(_ZN2rr21EmergencyDebugOstreamD2Ev+0x72)[0x64d3a2]
/usr/local/bin/rr(_ZN2rr12PerfCounters10read_ticksEPNS_4TaskE+0x459)[0x673979]
/usr/local/bin/rr(_ZN2rr4Task11did_waitpidENS_10WaitStatusE+0x47a)[0x75492a]
/usr/local/bin/rr(_ZN2rr4Task4waitEd+0x8f2)[0x7538e2]
/usr/local/bin/rr(_ZN2rr9Scheduler10rescheduleENS_10SwitchableE+0x278)[0x72db58]
/usr/local/bin/rr(_ZN2rr13RecordSession11record_stepEv+0x11f)[0x687b9f]
/usr/local/bin/rr[0x67de76]
/usr/local/bin/rr(_ZN2rr13RecordCommand3runERSt6vectorINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEESaIS7_EE+0x1e7)[0x67ce37]
/usr/local/bin/rr(main+0x288)[0x789618]
/lib64/libc.so.6(__libc_start_main+0xf1)[0x7f94c3e9b401]
/usr/local/bin/rr(_start+0x2a)[0x597bfa]
=== End rr backtrace
Launch gdb with
  gdb '-l' '10000' '-ex' 'target extended-remote :21187' /home/keeler/mozilla-unified/obj-x86_64-pc-linux-gnu/dist/bin/firefox

**Comment by mozkeeler** [comment]
Looks like 828f3f60acf5df252e41f36f1c4a968839e812fa introduced this, so... I need a newer kernel?

**Comment by khuey** [comment]
For the moment you need an *older* kernel.  See https://mail.mozilla.org/pipermail/rr-dev/2017-June/000500.html

**Comment by mozkeeler** [comment]
Oh, I see. Nuts. I guess this isn't an rr bug then.
