### ISSUE TITLE
Debbuging services like nginx

### ISSUE THREAD

**Issue by machadovilaca** [mozilla/rr#2058]
> rr record /usr/sbin/nginx 
rr: Saving execution to trace directory `/root/.local/share/rr/nginx-10'.
>
---------------------------------------------------------------------
RR runs the whole nginx  program and then stops while if I use gdb the program keeps running waiting for requests.
----------------------------------------------------------------------------
>gdb
(gdb) file /usr/sbin/nginx
Reading symbols from /usr/sbin/nginx...Reading symbols from /usr/lib/debug/usr/sbin/nginx.debug...done.
done.
(gdb) attach 25842
...
(gdb) c
Continuing.
-----------------------------------------------------------------
Am I missing something? How can I replicate gdb usage on rr?
Thanks

**Comment by rocallahan** [comment]
`nginx` automatically daemonizes and goes to the background. When the main program exits, rr by default also exits and shuts down all the daemon processes. You can fix that by passing the `-w` option to `rr record`.

However, doing that, I see that `nginx` is using an ioctl rr doesn't support, so I'd better fix that...

**Comment by rocallahan** [comment]
OK, https://github.com/mozilla/rr/commit/ca07326a7886cef304b284c8d538a53fae077722 works for me with nginx, so hopefully it will work for you!

**Comment by machadovilaca** [comment]
Yes, it now keeps track of daemon process as intended but I wasn't able to quit the program successfully and, as a result, I can't replay that recording.  
I have tried Ctrl+Z, use kill to terminate rr process and to terminate nginx processes too.
----------------------------------------------------------
>rr record -w nginx
rr: Saving execution to trace directory `/root/.local/share/rr/nginx-21'.
^Z
[1]+  Stopped                 rr record -w nginx

>rr replay
rr: /rr/rr/src/TraceStream.cc:568: void rr::TraceReader::read_generic(std::vector<unsigned char>&): Assertion `time == global_time' failed.
>

**Comment by machadovilaca** [comment]
it works!
>rr record -w /usr/sbin/nginx 
rr: Saving execution to trace directory `/root/.local/share/rr/nginx-17'.
(I make a request to nginx and then "killall nginx")

>rr ps
PID	PPID	EXIT	CMD
31459	--	0	/usr/sbin/nginx
31460	31459	0	(forked without exec)
31461	31460	-11	(forked without exec)
31462	31460	0	(forked without exec)
31463	31460	0	(forked without exec)
31480	31460	0	(forked without exec)

>rr replay -f 31461
...
Program received signal SIGSEGV, Segmentation fault.
....
Detaching from program: /root/.local/share/rr/nginx-17/mmap_hardlink_6_nginx, process 31461

>

Worked as expected! Thanks
