### ISSUE TITLE
Assertion `time == global_time' failed.

### ISSUE THREAD

**Issue by machadovilaca** [mozilla/rr#2059]
Following my last report about nginx using an ioctl rr doesn't support, it now keeps track of daemon process as intended.
But i have the following issue right now:

> #rr record -w /usr/sbin/nginx
rr:Saving execution to trace directory `/root/.local/share/rr/nginx-21'.
^Z
[1]+  Stopped                 rr record -w /usr/sbin/nginx
#  

> #rr replay
rr: /rr/rr/src/TraceStream.cc:568: void rr::TraceReader::read_generic(std::vector<unsigned char>&): Assertion `time == global_time' failed.

>

**Comment by rocallahan** [comment]
I'm not sure why ctrl-C doesn't work. But you should be able to kill nginx from another terminal (e.g. using `killall nginx`) and things should work.
