### ISSUE TITLE
apparent fd resource leak

### ISSUE THREAD

**Issue by vtjnash** [mozilla/rr#2060]
I am getting the following error
```
[FATAL /data/software/rr/src/AutoRemoteSyscalls.cc:455:retrieve_fd_arch() errno: EMFILE] Failed to create parent socket
Aborted
```
Triggered by running the following code to just launch and terminate a large number of subprocesses, until rr runs up to the ulimit for `fd` handles:
```
julia> for i in 1:1000
              run(`echo`, (DevNull, DevNull, DevNull))
              end
```
Reproducable on the current release version of Julia (0.6.1) available at https://julialang.org/downloads/
```
$ rr --version
rr version 4.4.0
```

**Comment by rocallahan** [comment]
I just tried that on master and it worked fine. Can you try it on rr master? 4.4.0 is pretty old.

**Comment by vtjnash** [comment]
Yes, thanks. rr 4.5.0 seems to run this test fine.
