### ISSUE TITLE
Build error: ar: two different operation options specified

### ISSUE THREAD

**Issue by Jesin** [mozilla/rr#2068]
The version I am trying to build is 164d3b0348a666abdd58a05ea3260a93a6017e8a. The build fails with this error:
```
[ 30%] Linking C static library libbrotli.a
/usr/bin/ar: two different operation options specified
make[2]: *** [CMakeFiles/brotli.dir/build.make:642: libbrotli.a] Error 1
make[1]: *** [CMakeFiles/Makefile2:11195: CMakeFiles/brotli.dir/all] Error 2
make: *** [Makefile:163: all] Error 2
```

**Comment by rocallahan** [comment]
Can you run `make -n` or in some other way determine the exact `ar` command line that is being used?

**Comment by Jesin** [comment]
I used `cmake -DCMAKE_VERBOSE_MAKEFILE=ON` with 6d90fc5ca7ba6b4f020c49a947bf68040be6a933 and got this output: [rr-2017-08-05-6d90fc5c.log.gz](https://github.com/mozilla/rr/files/1202800/rr-2017-08-05-6d90fc5c.log.gz)

**Comment by Jesin** [comment]
I used `cmake -DCMAKE_VERBOSE_MAKEFILE=ON` with 6d90fc5ca7ba6b4f020c49a947bf68040be6a933 and got this output:
[rr-2017-08-05-6d90fc5c.log.gz](https://github.com/mozilla/rr/files/1202800/rr-2017-08-05-6d90fc5c.log.gz)

**Comment by Jesin** [comment]
The problem might be that I was using `-DCMAKE_STATIC_LINKER_FLAGS` by mistake. I will try changing that option.

**Comment by Jesin** [comment]
That fixed it.
