### ISSUE TITLE
"CPU frequency governor" warning should provide steps for Debian-based systems as well

### ISSUE THREAD

**Issue by theres-waldo** [mozilla/rr#2069]
When I run rr, I often see this message:

> rr: Warning: Your CPU frequency governor is 'powersave'.  rr strongly
>     recommends that you use the 'performance' governor.  Not using the
>     'performance' governor can cause rr to be at least 2x slower
>     on laptops.
> 
>     On Fedora-based systems, you can enable the 'performance' governor
>     by running the following commands:
> 
>     $ sudo dnf install kernel-tools
>     $ sudo cpupower frequency-set -g performance

I'm running a Debian-based system, where the required commands are slightly different:

>     $ sudo apt-get install cpufrequtils
>     $ sudo cpufreq-set -g performance

It would be nice if the warning message displayed those as well.

**Comment by rocallahan** [comment]
If you install the linux-cpupower package does the `cpupower` command line work?

Actually I'm considering getting rid of that message since I personally ignore it :-). I should do some testing to see if it actually matters anymore.

**Comment by theres-waldo** [comment]
> If you install the linux-cpupower package does the cpupower command line work?

Yes (so in that case it would be sufficient to mention the alternate package name).

> Actually I'm considering getting rid of that message since I personally ignore it :-)

Ok, that's good to know :)
