### ISSUE TITLE
 -> Assertion `1 == t->vm()->task_set().size()' failed to hold. TODO: monkeypatch multithreaded process

### ISSUE THREAD

**Issue by jrmuizel** [mozilla/rr#2072]
I get this running renderdoccmd capture glxinfo. With https://github.com/baldurk/renderdoc
I believe renderdoccmd LD_PRELOADS a library that starts a thread before init or something like that.

**Comment by rocallahan** [comment]
This is kind of a pain to fix :-(.

The problem is that those pre-rrpreload-init threads could be in syscalls that post-rrpreload-init threads then patch. The pre-rrpreload-init threads can then return into patch code and crash.

**Comment by rocallahan** [comment]
Running rr *inside* renderdoc instead of outside it should work around this (if that's possible).

**Comment by rocallahan** [comment]
`rr record -n` would also work, but of course that's slow.

**Comment by rocallahan** [comment]
Trying to build renderdoc itself I get the charming message
````
CMake Error at /usr/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find PythonInterp: Found unsuitable version "1.4", but required
  is at least "3" (found /home/roc/bin/python3)
````

**Comment by rocallahan** [comment]
From reading source, it looks like the renderdoc pre-rrpreload-init thread blocks in an `accept` call during startup.

FWIW renderdoc should probably put its library last in LD_PRELOAD on the assumption that pre-main LD_PRELOAD code isn't likely to do interesting GL-related work. Going first in LD_PRELOAD probably breaks ASAN.

**Comment by rocallahan** [comment]
The pre-rrpreload-init thread could even be in a signal handler with the post-syscall return address on the stack...

**Comment by rocallahan** [comment]
Let me know if that fails to fix it.
