### ISSUE TITLE
ioctl(TUNGETFEATURES = 0x800454cf) not handled

### ISSUE THREAD

**Issue by pmhahn** [mozilla/rr#2074]
[FATAL /root/rr/src/record_syscall.cc:4180:rec_process_syscall_arch() errno: SUCCESS] 
 (task 15818 (rec:15818) at time 131118)
 -> Assertion `t->regs().syscall_result_signed() == -syscall_state.expect_errno' failed to hold. Expected EINVAL for 'ioctl' but got result 0 (errno SUCCESS); Unknown ioctl(0x800454cf): type:0x54 nr:0xcf dir:0x2 size:4 addr:0x7ffe4f992580

qemu-bridge-helper.c:146
```
static bool has_vnet_hdr(int fd)
{
    unsigned int features = 0;

    if (ioctl(fd, TUNGETFEATURES, &features) == -1) {
        return false;
    }

    if (!(features & IFF_VNET_HDR)) {
        return false;
    }

    return true;
}
```
Described here: torvalds/linux@07240fd0902c872f044f523893364a1a24c9f278

**Comment by rocallahan** [comment]
looks like an easy one

**Comment by rocallahan** [comment]
oops
