### ISSUE TITLE
Assertion `!!(caught & mask) == (disposition == SIGNAL_HANDLER)' failed to hold. SIGTRAP is not caught

### ISSUE THREAD

**Issue by CervantesYu** [mozilla/rr#2075]
I had the following errors in launching Firefox nightly with rr:
% rr ./firefox -P devel --no-remote
rr: Saving execution to trace directory `/home/cervantes/.rr/firefox-6'.
[FATAL /home/cervantes/git/rr/rr/src/RecordTask.cc:1187:verify_signal_states() errno: SUCCESS] 
 (task 22835 (rec:22835) at time 1860)
 -> Assertion `!!(caught & mask) == (disposition == SIGNAL_HANDLER)' failed to hold. SIGTRAP is not caught
=== Start rr backtrace:
rr(_ZN2rr13dump_rr_stackEv+0x45)[0x8077f9]
rr(_ZN2rr9GdbServer15emergency_debugEPNS_4TaskE+0x189)[0x6c50f7]
rr[0x6e75b2]
rr(_ZN2rr21EmergencyDebugOstreamD1Ev+0x5a)[0x6e77f0]
rr(_ZN2rr10RecordTask20verify_signal_statesEv+0x69b)[0x76b02d]
rr(_ZN2rr13RecordSession11record_stepEv+0x4be)[0x71d672]
rr[0x7142c7]
rr(_ZN2rr13RecordCommand3runERSt6vectorINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEESaIS7_EE+0x17b)[0x714c01]
rr(main+0x1ce)[0x81c0fb]
/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf0)[0x7f8293203830]
rr(_start+0x29)[0x6430d9]
=== End rr backtrace
Launch gdb with
  gdb '-l' '10000' '-ex' 'target extended-remote 127.0.0.1:22835' /mnt/SSD/data/hg/mozilla-central/obj-x86_64-pc-linux-gnu/dist/bin/firefox

gdb attaching to the debugee shows some random stack.
This is reproduced with rr revision e92770bf38ecf18fcabc6e8b248bb7ec5baf2396
gdb version (Ubuntu 7.11.1-0ubuntu1~16.5) 7.11.1
Firefox revision: b95b1638db48

**Comment by rocallahan** [comment]
Fixed by https://github.com/mozilla/rr/commit/ed45cd6aa6b0a7eb894e1161e6176191e554328c

**Comment by CervantesYu** [comment]
Verified with today's build. Thanks for the quick fix.
