### ISSUE TITLE
pass arguments to debugger.

### ISSUE THREAD

**Issue by amosbird** [mozilla/rr#2076]
Hi, I'm trying to using rr with tmux and cgdb via this command,
`tmux send-keys "rr replay -d cgdb -- $1 -tty $tty2 -ex \"dashboard -output $tty1\" -ex \"dashboard expression -output $tty3\"" C-m` . How can I pass the arguments correctly? I've tried prepending `-o` to each of the argument, however it doesn't work out.

**Comment by rocallahan** [comment]
Multiple `-o` options are supposed to work.

`rr replay` doesn't support a `--` option to pass all remaining arguments to the debugger. I suppose we could add that.

**Comment by amosbird** [comment]
the "--" argument is for cgdb. The original command is 
`tmux send-keys "cgdb -- $1 -tty $tty2 -ex \"dashboard -output $tty1\" -ex \"dashboard expression -output $tty3\"" C-m`

I tried `-o--` but that doesn't work

**Comment by rocallahan** [comment]
Try `-o --`

**Comment by amosbird** [comment]
so i prepend `-o` to all the args like this `tmux send-keys "rr replay -d cgdb -o -- -o -tty -o $tty2 -o -ex -o \"dashboard -output $tty1\" -o -ex -o \"dashboard expression -output $tty3\"" C-m` 

It still doesn't work. `-tty: No such file or directory.`

**Comment by rocallahan** [comment]
I don't know...

**Comment by rocallahan** [comment]
I added a `--` option to `rr replay` that makes it easy to pass any number of arguments to gdb.
