### ISSUE TITLE
Replay diverged when replaying chromium content_shell recording.

### ISSUE THREAD

**Issue by flackr** [mozilla/rr#2077]
I've seen frequent recording divergence when trying to record and replay chromium and content_shell runs. Here's one particular failure I just ran into.

(Build chromium content_shell with the following args.gn)
clang_use_chrome_plugins = true
is_component_build = true
is_debug = true
use_debug_fission = false

Then:
rr record ./out_linux/Debug/content_shell --user-data-dir=/home/flackr/.config/chrome-sessions/testing/projects/chromium/src --enable-devtools-experiments --ignore-gpu-blacklist --password-st
ore=basic --disable-hang-monitor --no-sandbox --disable-seccomp-sandbox --disable-setuid-sandbox --single-process --use-gl=osmesa http://output.jsbin.com/wuqotub/quiet

After the page loads, scroll or not, then close it.

rr replay
(rr) c
Continuing.
[New Thread 15709.15739]
...
[ERROR /home/roc/rr/rr/src/ReplaySession.cc:545:guard_overshoot() errno: SUCCESS] Replay diverged; target registers mismatched:
[FATAL /home/roc/rr/rr/src/ReplaySession.cc:549:guard_overshoot() errno: SUCCESS]
 (task 15859 (rec:15739) at time 11583)
 -> Assertion `false' failed to hold. overshot target ticks=2287294 by 590991
Launch gdb with
  gdb '-l' '10000' '-ex' 'target extended-remote :15859' /home/flackr/.local/share/rr/latest-trace/mmap_hardlink_3_content_shell

Do you have any advice or is there anything I could provide to help debug this?

**Comment by rocallahan** [comment]
First check your kernel version and make sure you're not hitting this: http://robert.ocallahan.org/2017/06/patch-on-linux-kernel-stable-branches.html

**Comment by flackr** [comment]
Ah yes, looks like Ubuntu 14.04.5 LTS kernel 4.4.0-87-generic has the patch listed in the kernel changelog :(.
http://changelogs.ubuntu.com/changelogs/pool/main/l/linux-lts-xenial/linux-lts-xenial_4.4.0-92.115~14.04.1/changelog

**Comment by rocallahan** [comment]
It looks like xenial 4.4.0-93 fixes the problem:
http://changelogs.ubuntu.com/changelogs/pool/main/l/linux-lts-xenial/linux-lts-xenial_4.4.0-93.116~14.04.1/changelog
so maybe an update will fix things for you?

**Comment by rocallahan** [comment]
No, looks like that kernel is not released for 14.04 yet :-(

**Comment by rocallahan** [comment]
The new kernel has been released.
