### ISSUE TITLE
rr does not support LLDB as a client

### ISSUE THREAD

**Issue by vadimcn** [mozilla/rr#2078]
I hoped I could use LLDB to connect to rr in server mode, but this was not to be... Looks like rr's emulation of gdbserver is not complete.   

A couple of problems I found during initial investigation:
- rr reports process id=0, which LLDB considers invalid.
- rr uses ['multiprocess' thread id format](https://sourceware.org/gdb/onlinedocs/gdb/Packets.html#thread_002did-syntax) even though LLDB did not indicate 'multiprocess' extension support in qSupported request.

**Comment by rocallahan** [comment]
I don't plan to work on LLDB support but I'd be happy to review PRs for it.

**Comment by luser** [comment]
FYI I don't know if you'd be interested in using Rust code in rr itself, but I started [a crate](https://github.com/luser/rust-gdb-remote-protocol) to implement the GDB remote protocol in Rust, and @tromey and @froydnj are hacking away at actually implementing it. I figured if nothing else, seeing if we could swap out rr's existing protocol handler code for this crate would be a good way to prove that it works.

**Comment by rocallahan** [comment]
Interesting. What are you planning to use it for?

Converting rr to Rust would be nice in the abstract but I don't think introducing a Rust dependency makes sense at this time. People still build rr on old systems and a Rust dependency would make that difficult. Also, given rr's maturity I don't think it would benefit that much from moving to Rust. At some point in the future when Rust build environments are more ubiquitous, and if someone wants to make rr enhancements that benefit from Rust features like safe threading, or we decide that we want rr to be more secure, then we could revisit this.

**Comment by lorienhu** [comment]
I was able to connect with lldb with no problems. This was with lldb 6.0.0 (others may work, I didn't try). However, lldb doesn't have the reverse-continue, reverse-step, and reverse-next commands.

**Comment by vadimcn** [comment]
Closed via #2367
