### ISSUE TITLE
rr does not build on Ubuntu 14.04

### ISSUE THREAD

**Issue by vadimcn** [mozilla/rr#2079]
TUNSETVNETLE, TUNGETVNETBE, TUNGETVNETLE, TUNGETVNETBE macros are not defined on Ubuntu 14.04.
Not sure what these ioctls do.   Is it safe to comment out those cases in record_syscall.cc?

**Comment by rocallahan** [comment]
We should add them to kernel_supplement.h protected by #ifdefs
