### ISSUE TITLE
cmake doesn't check for the capnp tool

### ISSUE THREAD

**Issue by glandium** [mozilla/rr#2085]
After updating my rr tree (finally), I started a build, and cmake complained that capnp was missing, so I installed the libcapnp developement package. Turns out, that was not enough, but cmake didn't say anything, and the build had to went through up to the point where the capnp tool was required to fail.

**Comment by rocallahan** [comment]
In what way wasn't it enough? Can you show me the build failure?

**Comment by glandium** [comment]
```
[ 96%] Generating rr_trace.capnp.c++, rr_trace.capnp.h
make[2]: capnp: Command not found
CMakeFiles/rr.dir/build.make:61: recipe for target 'rr_trace.capnp.c++' failed
make[2]: *** [rr_trace.capnp.c++] Error 127
CMakeFiles/Makefile2:17228: recipe for target 'CMakeFiles/rr.dir/all' failed
```
(note: the error messages might not be totally what you'd get, because I translated them from japanese)
