### ISSUE TITLE
rr fails to debug FF by simply using "rr record ./mach run" then "rr reply"

### ISSUE THREAD

**Issue by ghoo1125** [mozilla/rr#2087]
STR:
1. rr record ./mach run
2. rr reply
3. (rr) continue

Result:
It will stop instantly, and show the messasge: Program stopped. 0x00007fbe0cbb0c30 in _start () from /lib64/ld-linux-x86-64.so.2

But if reocrd with "rr record -M" then rr reply -g \<nnnn\> it works fine.
Guess the problem is due to rr records the mach python script.

**Comment by rocallahan** [comment]
That's right. That's not a bug. Use `rr ps` to get a list of processes and `rr replay -p <pid>` to debug one of them. You'll still stop at `_start`, but at that point, you can just `continue`.

**Comment by chenpighead** [comment]
So, I guess, for developers who would like to debug Firefox by rr, and would like to use rr along with `./mach run` command, they should use `./mach run —debugger=rr`. Not sure if this is something worth to be documented in the wiki or project page though.

**Comment by rocallahan** [comment]
`./mach run —debugger=rr` is more efficient, but either should work.
