### ISSUE TITLE
GdbConnection.cc:778:5: warning: variable 'ret' is used uninitialized whenever switch default is taken [-Wsometimes-uninitialized]

### ISSUE THREAD

**Issue by dholbert** [mozilla/rr#2093]
Building rr with clang version 6.0.0 (trunk 312809), I get the following build warning:
````
GdbConnection.cc.o
/rr/src/GdbConnection.cc:778:5: warning: variable 'ret' is used uninitialized
                                whenever switch default is taken [-Wsometimes-uninitialized]
    default:
    ^~~~~~~
/rr/src/GdbConnection.cc:795:10: note: uninitialized use occurs here
  return ret;
         ^~~
/rr/src/GdbConnection.cc:767:10: note: initialize the variable 'ret' to silence this warning
  int ret;
         ^
          = 0
1 warning generated.
````

**Comment by dholbert** [comment]
Looks like the default switch statement is an error-handling case and is assumed to be unreachable (it has "parser_assert(false)" which I assume is fatal in debug builds):
https://github.com/mozilla/rr/blob/6b272d5a27a73c071ed492db0e4a2ccfcb04536f/src/GdbConnection.cc#L767-L781

Perhaps |ret| should be set to some dummy value there, to appease the compiler, since it can't tell that the code is unreachable, and we do go on to use `ret` afterwards?

**Comment by rocallahan** [comment]
Yeah

**Comment by dholbert** [comment]
Seems to have been fixed via early-return, in https://github.com/mozilla/rr/commit/7875085863e2bac129baab3374625a84c9a2a328 . Thanks!

I can confirm that the repo's current tip builds with no warnings displayed anymore, using the same clang version.
