### ISSUE TITLE
error messages for installing capnp could be improved

### ISSUE THREAD

**Issue by dbaron** [mozilla/rr#2094]
When running cmake to build rr master (6b272d5a27a73c071ed492db0e4a2ccfcb04536f) on Ubuntu 17.04, I hit this error message:

```
CMake Error at CMakeLists.txt:125 (message):
  Can't find 'capnp' command; install 'capnproto' package?
```

I ran `sudo apt install capnproto`, but then I got the error:

```
-- Checking for module 'capnp'
--   No package 'capnp' found
CMake Error at /usr/share/cmake-3.7/Modules/FindPkgConfig.cmake:415 (message):
  A required package was not found
Call Stack (most recent call first):
  /usr/share/cmake-3.7/Modules/FindPkgConfig.cmake:588 (_pkg_check_modules_internal)
  CMakeLists.txt:134 (pkg_check_modules)
```

the solution is that I *also* needed to `sudo apt install libcapnp-dev`.

Note that both are needed; if I install *only* libcapnp-dev, then I get the first error again.

**Comment by rocallahan** [comment]
Unfortunately the correct package name for the library is distro-dependent. So I changed the message to just link to https://github.com/mozilla/rr/wiki/Building-And-Installing#tldr.
