### ISSUE TITLE
How to automatically start replay and go directly to main instead of _start?

### ISSUE THREAD

**Issue by cirosantilli** [mozilla/rr#2098]
I've tried:

```
rr replay -o -q -o -ex -o 'start' "$@"
```

but it segfaults after I continue and:

```
rr replay -o -q -o -ex -o 'b main' -o -ex -o 'c' "$@"
```

says that the program is not yet started, so we can't continue.

**Comment by rocallahan** [comment]
We would need to add another rr replay command-line option that adds a gdb option to be inserted *after* the `-ex target ...` option.

**Comment by rocallahan** [comment]
> `rr replay -o -q -o -ex -o 'b main' -o -ex -o 'c' "$@"`

This should work now.

**Comment by cirosantilli** [comment]
Awesome! Putting all commands after `target` does seen like a better default.

Now I can do:

```
  rrc() ( rr record "$@" )
  rrp() ( rr replay -o -q -o -ex -o 'b main' -o -ex -o 'c' "$@" )
  rrr() ( rrc "$@" && rrp )
```

for the win :birthday:

**Comment by rocallahan** [comment]
It's a bit smarter than that. We only put `continue` commands (and following commands) after the target.
