### ISSUE TITLE
Long pause when starting Firefox with webrender under rr

### ISSUE THREAD

**Issue by staktrace** [mozilla/rr#2102]
When running Firefox with webrender enabled under rr, I see a long pause (around 20 seconds) when the window first opens. This doesn't happen without rr. The pause appears to be detected as a possible process hang by Ubuntu since the window does that thing where it fades to a darker color. However after a bit it resumes and continues as normal.

My mozconfig is at https://github.com/staktrace/moz-scripts/blob/master/mozconfig.Linux-host-debug (there's nothing really important in there) and the command line I'm using is:

`MOZ_ACCELERATED=1 MOZ_WEBRENDER=1 ./mach run --debugger=rr`

**Comment by rocallahan** [comment]
I don't see the pause, but I also don't get Webrender. Maybe that's because I get `Failed GL context creation for WebRender: 0`?

**Comment by rocallahan** [comment]
This is in a fresh build of mozilla-central, pulled today.

**Comment by rocallahan** [comment]
You could do `rr dump -b -m -p` on your rr recording and upload that somewhere and it would probably help.

You could even run `rr pack` and upload the entire trace somewhere and I should be able to replay it for analysis...

**Comment by staktrace** [comment]
Yeah, the GL context error is probably preventing you from getting WR enabled. You might need a newer GL library to get it working.

I put the output from `rr dump -b -m -p` at https://staktrace.com/pub/recording-dump.txt.gz (~5 MB). If you still want the packed trace let me know; I made a tarball but it's ~620 MB and not as convenient to upload.

**Comment by rocallahan** [comment]
Thanks.

It's hard to be sure but there's a region of the trace around event 25243 where things look quite slow. We get stuff like this:
````
{
  real_time:1042823.023820 global_time:25245, event:`SYSCALL: futex' (state:ENTERING_SYSCALL) tid:5882, ticks:2242193
rax:0xffffffffffffffda rbx:0xfe987 rcx:0xffffffffffffffff rdx:0x1 rsi:0x89 rdi:0x7fa7624c6b24 rbp:0x7fa7624c6aa0 rsp:0x7fa7624c69e0 r8:0x7fa7624c6af0 r9:0xffffffff r10:0x7fa7624c6a30 r11:0x246 r12:0x1 r13:0x7fa7624c6a30 r14:0xffffffffffffff92 r15:0x7fa7624c6b00 rip:0x7fa78d981709 eflags:0x246 cs:0x33 ss:0x2b ds:0x0 es:0x0 fs:0x0 gs:0x0 orig_rax:0xca fs_base:0x7fa7624c7700 gs_base:0x0
}
{
  real_time:1042823.023821 global_time:25246, event:`SYSCALLBUF_RESET' tid:5882, ticks:2242193
}
{
  real_time:1042823.041025 global_time:25247, event:`SCHED' tid:5885, ticks:5953081980
rax:0x7fa7619b95ac rbx:0x7fa7579954d0 rcx:0x0 rdx:0x7c rsi:0x7fa754bb9638 rdi:0x7fa7619b9590 rbp:0x7fa74305d600 rsp:0x7fa7619b9468 r8:0x7fa7619b91f0 r9:0x42e9e07000007fa7 r10:0x0 r11:0x7fa78cc99f50 r12:0x7fa7619b9590 r13:0x7fa7619b94c8 r14:0x7fa7579955e0 r15:0x7fa754bb9638 rip:0x7fa7634b2b32 eflags:0x202 cs:0x33 ss:0x2b ds:0x0 es:0x0 fs:0x0 gs:0x0 orig_rax:0xffffffffffffff09 fs_base:0x7fa7619c6700 gs_base:0x0
}
{
  real_time:1042823.041032 global_time:25248, event:`SYSCALL: futex' (state:EXITING_SYSCALL) tid:5882, ticks:2242193
rax:0xffffffffffffff92 rbx:0xfe987 rcx:0xffffffffffffffff rdx:0x1 rsi:0x89 rdi:0x7fa7624c6b24 rbp:0x7fa7624c6aa0 rsp:0x7fa7624c69e0 r8:0x7fa7624c6af0 r9:0xffffffff r10:0x7fa7624c6a30 r11:0x246 r12:0x1 r13:0x7fa7624c6a30 r14:0xffffffffffffff92 r15:0x7fa7624c6b00 rip:0x7fa78d981709 eflags:0x246 cs:0x33 ss:0x2b ds:0x0 es:0x0 fs:0x0 gs:0x0 orig_rax:0xca fs_base:0x7fa7624c7700 gs_base:0x0
}
````
So thread 5882 blocks on a futex, then thread 5885 runs for 20ms without doing any system calls, then thread 5882's futex times out and it does some more work. And that pattern repeats for a while.

Using `rr replay -g` to stop around there and find out what those two threads are doing would probably be very helpful.

**Comment by staktrace** [comment]
I looked at a few backtraces around there - at [event 25243](https://gist.github.com/staktrace/f8faf5b790864d64f3a2f3a6a59d9b00#file-at-event-25243), [event 25754](https://gist.github.com/staktrace/f8faf5b790864d64f3a2f3a6a59d9b00#file-at-event-25754) and [event 28424](https://gist.github.com/staktrace/f8faf5b790864d64f3a2f3a6a59d9b00#file-at-event-28424). It looks like 5882 isn't really doing a whole lot, but thread 5885 looks like it's running a bunch of llvmpipe stuff for software rasterization. I guess it's doing initialization or something else that's expensive. It could be that running under rr is making us go down a different path than we would otherwise (I recall now that happened to dholbert in https://bugzilla.mozilla.org/show_bug.cgi?id=1343102) or maybe this is just slower under rr?

**Comment by rocallahan** [comment]
rr forces use of the software rasterizer. Maybe that's all this is? I you could try forcing that outside of rr and then see how that compares to running under rr.

The only other alternative at this time is to try using GLX but that might not be better.

**Comment by staktrace** [comment]
I ran into unrelated problems trying to verify this, but yeah it seems likely that it's just the software rasterizer. I'll close this for now.
