### ISSUE TITLE
detect AMD CPUs and emit intelligible error message

### ISSUE THREAD

**Issue by froydnj** [mozilla/rr#2107]
...telling people AMD CPUs are not supported, rather than something cryptic about `errno` values.  Bonus points for pointing them to the appropriate Github issues, etc. etc.

**Comment by rocallahan** [comment]
On Ryzen we print a warning: https://github.com/mozilla/rr/blob/master/src/PerfCounters.cc#L171
On non-Ryzen we fail with "CPU unknown".

Was this about Ryzen and if so, is the warning inadequate?

**Comment by froydnj** [comment]
This issue was inspired by #2106, which wasn't about Ryzen.  I feel like I've seen a couple of other issues about non-Ryzen AMD CPUs go by, too.  For non-Ryzen CPUS, folks could be pointed at the AMD support github issue, or just informed that their CPU won't work because of inadequate hardware support.

**Comment by rocallahan** [comment]
Ah, so flesh out the CPU list with additional AMD processors and print something other than "unknown CPU". OK...

**Comment by froydnj** [comment]
Right, or just check the CPUID manufacturer name for `AuthenticAMD` in the unknown case and print information based on that.
