### ISSUE TITLE
23% of tests fail on Ubuntu 16.04

### ISSUE THREAD

**Issue by senjitsu** [mozilla/rr#2115]
Working on getting RR up and running and am seeing many test failures. I havent dug through all of them, but they all seem to generate the same / similar output. 

I am seeing 77% tests passing, but it took some additional work to even get that far from the normal install instructions. I had to get the perf tools setup and set the perf_event_paranoid flag to 1 from 3, prior to this.

I am running Ubuntu 16.04 in VMware Workstation 14. 

```
Start testing: Oct 23 06:58 PDT
----------------------------------------------------------
669/2141 Testing: block_clone_checkpoint-no-syscallbuf
669/2141 Test: block_clone_checkpoint-no-syscallbuf
Command: "/bin/bash" "/home/hive/rr/rr/src/test/block_clone_checkpoint.run" "block_clone_checkpoint" "-n" "/home/hive/rr/obj" "120"
Directory: /home/hive/rr/obj
"block_clone_checkpoint-no-syscallbuf" start time: Oct 23 06:58 PDT
Output:
----------------------------------------------------------
FAILED: sending "b breakpoint
"
exception: a float is required
Test 'block_clone_checkpoint' FAILED: debug script failed
--------------------------------------------------
gdb_rr.log:
GNU gdb (Ubuntu 7.11.1-0ubuntu1~16.5) 7.11.1
Copyright (C) 2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from /tmp/rr-test-block_clone_checkpoint-LgmRWzRup/block_clone_checkpoint-LgmRWzRup-0/mmap_hardlink_3_block_clone_checkpoint-LgmRWzRup...done.
Really redefine built-in command "restart"? (y or n) [answered Y; input not from terminal]
Remote debugging using 127.0.0.1:8458
Reading symbols from /lib64/ld-linux-x86-64.so.2...Reading symbols from /usr/lib/debug//lib/x86_64-linux-gnu/ld-2.23.so...done.
done.
0x00007fcdbc703c30 in _start () from /lib64/ld-linux-x86-64.so.2
(rr) --------------------------------------------------
debug.err:
cat: debug.err: No such file or directory
```

When I go to rerun the /tmp/ test binary, I am not getting anything interesting as far as I can tell, however, I have never used anything of these tools. 

```
Starting program: /tmp/rr-test-block_clone_checkpoint-LgmRWzRup/block_clone_checkpoint-LgmRWzRup 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
EXIT-SUCCESS
[Inferior 1 (process 23208) exited normally]
```
I am currently trying to run the test as a replay, but wanted to get the issue started up here incase I am just missing something in the setup.

EDIT: After running the replay, it looks as if the test is not running at all, and is just exiting / returning from ld64.

**Comment by khuey** [comment]
On my machine this started with e6f3f03ebdec.  Haven't gotten around to figuring it out yet.

**Comment by khuey** [comment]
(Which means you can probably ignore this if you just want to solve your panda bug. If you want to dive in here that would be appreciated though! :) )

**Comment by senjitsu** [comment]
I will play with it once I am in my baremetal environment. I am really new to both panda / rr so I am not sure I will be of any use, but will do what I can!

**Comment by senjitsu** [comment]
So by removing the line that was changed in [https://github.com/mozilla/rr/commit/e6f3f03ebdec408e577f7d2213eb4e61ceb77a0e](url) solved the issue. I am not familiar enough with the entire environment to help beyond that at this time.

**Comment by rocallahan** [comment]
Fixed on master by https://github.com/mozilla/rr/commit/8257bdee0558b72f49d946f1619b47d568794369 ?

**Comment by sidkshatriya** [comment]
[This ticket has not been updated in a long time but I want to add my 2 cents for people who may see this (still open) ticket. A lot of people use 16.04 and I want to report my success with ubuntu version.]

I run 16.04 and for a long time now, I've been receiving 100% test pass. So its possible that the test failures you saw were a temporary phenomenon which is now fixed or something specific to your local setup.

**Comment by rocallahan** [comment]
Thanks. I'll just close this.
