### ISSUE TITLE
Get time since execution

### ISSUE THREAD

**Issue by WesleyYue** [mozilla/rr#2126]
I would like to be able to query the elapsed time (during the recording) when I am stopped at a breakpoint. Would this be a difficult feature to implement? Do you have any hints on how one might approach implementing this?

**Comment by khuey** [comment]
When you say elapsed time do you mean in real time?  rr stores the real time at each trace event (syscall, async signal, etc).  We could give back the real time of the most recent trace event pretty easily.  Giving you something more accurate than that would be much harder, if not impossible.

**Comment by WesleyYue** [comment]
I think we're talking about the same thing? 

Few things:
1) Does rr replay do any work to attempt to preserve time? Or does it only try to preserve the order of inputs?
2) What exactly is a trace event? I dug around in the wiki but couldn't find a good definition.
3) Besides being able to see the elapsed time in the time scale during the recording at breakpoints, I would also like to be able to log the value at a memory location over the recording time scale. Would it make more sense to write this as a gdb plugin on a watchpoint and use rr only for replay without hooking anything with rr's time stamps on trace events?

**Comment by rocallahan** [comment]
1. No. We just replay as fast as possible, which is almost always what users want.
2. See `rr dump`.
3. I'm not sure exactly what you're asking for but logging the value of a memory location plus a timestamp at each rr event could be implemented by modifying rr or using it as a library if you're willing to write some C++ code. `RerunCommand.cc` would be a good starting point.

**Comment by khuey** [comment]
Trace events are points at which state changes from something other than the execution of a deterministic instruction.  Things like syscalls, signals, RDTSC, thread scheduling, etc.

**Comment by WesleyYue** [comment]
Ok, thanks! I think this is enough information to get me started in the right direction.

**Comment by cs01** [comment]
> We could give back the real time of the most recent trace event pretty easily. Giving you something more accurate than that would be much harder, if not impossible.

+1 for this. How would/should the timestamps be provided back to the user when replaying in gdb or gdb-mi?

**Comment by khuey** [comment]
You would need to add a custom gdb command (e.g. a `when-realtime`) patterned after the other `SimpleGdbCommand`s in src/GdbCommand.cc
