### ISSUE TITLE
no in-gdb documentation for the "when" command

### ISSUE THREAD

**Issue by pm215** [mozilla/rr#2134]
```
(rr) help when
This command is not documented.

List of when subcommands:


Type "help when" followed by when subcommand name for full documentation.
Type "apropos word" to search for commands related to "word".
Command name abbreviations are allowed if unambiguous.
```

Not very significant, but it would be nice to have some documentation text available here.

**Comment by rocallahan** [comment]
I'm not sure how to implement this.

**Comment by froydnj** [comment]
You can document commands in gdb with [the appropriately-named `document` command](https://sourceware.org/gdb/current/onlinedocs/gdb/Define.html#index-document).

See [an example in Firefox's `.gdbinit`](http://dxr.mozilla.org/mozilla-central/source/.gdbinit#172).
