### ISSUE TITLE
"when" is insufficiently granular to usefully tell you where you are in an execution playback

### ISSUE THREAD

**Issue by pm215** [mozilla/rr#2135]
I'd like to be able to use 'when' to identify where I am in an execution playback. Unfortunately it seems to be insufficiently granular for this. For instance I have a log from gdb of forward execution where I hit a breakpoint 4000 times, and each time 'when' reports "Current event 243325". That means that if I'm subsequently reverse-executing through that section of code, "when" is no good for identifying where I am...

**Comment by rocallahan** [comment]
`when-ticks` should help; paired with the event number and lexicographically ordered, it gives you an increasing process metric. In some pathological situations `when-ticks` is also insufficiently granular but you probably won't encounter that.

**Comment by pm215** [comment]
That seems like the kind of helpful detail that a "help when" documentation text could mention :-)
