### ISSUE TITLE
can't print TLS variable in rr replay: "Remote target failed to process qGetTLSAddr request"

### ISSUE THREAD

**Issue by pm215** [mozilla/rr#2136]
I tried to print the value of a variable in my program which happens to be a TLS variable, but gdb complains:

```
(rr) print current_cpu
Cannot find thread-local storage for Thread 4139.4151, executable file /home/petmay01/.rr/qemu-system-aarch64-72/mmap_hardlink_3_qemu-system-aarch64:
Remote target failed to process qGetTLSAddr request
```

**Comment by khuey** [comment]
Hrm, we should support that ... https://github.com/mozilla/rr/blob/master/src/GdbConnection.cc#L616

Can you figure out where we're going wrong inside `ThreadDb::get_tls_address`?

**Comment by pm215** [comment]
I'm not sure if it's the same situation I was in when I encountered this bug, but I've repro'd at least one case where I get this message. We successfully parse the request in get_tls_address (the packet from gdb is "$qGetTLSAddr:p102b.102b,0,0#79"), but then in GdbServer::dispatch_debugger_request() the call to target->get_tls_address() returns false and we return an "E01" response, which causes gdb to print its message.

This happens because rr::ThreadDb::initialize() fails, which in turn sees to be because when we call td_ta_new_fn() it fails, because ps_pglobal_lookup() of "nptl_version" failed.

That all may be because this is what happens if you try this as the very first thing you do when you get into an rr gdb prompt, before it's actually tried executing anything. If I tell it to continue to some breakpoint then it works. That said, this wasn't the situation I was in when I first ran into the error (I have a feeling it was something involving reverse-executing to a breakpoint.) I can't now reproduce that situation, though, because a rebuild of the binary I'm debugging has invalidated the rr session...

**Comment by rocallahan** [comment]
I can repro something like this when I try to print a TLS variable before `main`. That's because TLS data structures have not been set up by ld.so yet. Later on I get a different issue `Cannot access memory at address 0x0`, and then later still (still before `main`) TLS works.

Are you checking TLS values before `main`?

**Comment by rocallahan** [comment]
Maybe it's not so much that TLS hasn't been set up yet, but because dynamic-library stuff hasn't been set up enough to allow gdb to resolve the symbols needed by libthreaddb.

**Comment by pm215** [comment]
As I say, my repro case was checking before main, but I'm pretty sure my original bug report wasn't. (But I can't repro that one now, because rr sessions evaporate when the program under debug is rebuilt.)

**Comment by pm215** [comment]
I found another instance of this. This is definitely during execution, I'm inside a signal handler in the thing I'm debugging. rr::ThreadDb::initialize() fails because ps_pglobal_lookup() of "nptl_version" returns PS_NOSYM.

**Comment by rocallahan** [comment]
Can you get a log of this failure with `RR_LOG=GdbSession,GdbConnection`?

**Comment by pm215** [comment]
Attached is the result of RR_LOG_FILE=/tmp/rr.log RR_LOG=GdbSession,GdbConnection ~/src/rr-obj64/bin/rr replay /home/petmay01/.rr/qemu-aarch64-10
[rr.log](https://github.com/mozilla/rr/files/1510177/rr.log)

(Incidentally RR_LOG_FILE seems to be undocumented -- I had to look through the source code to figure out how to direct tracing to a file.)

Abbreviated transcript of the user session:
```
$ RR_LOG_FILE=/tmp/rr.log RR_LOG=GdbSession,GdbConnection ~/src/rr-obj64/bin/rr replay /home/petmay01/.rr/qemu-aarch64-10
GNU gdb (Ubuntu 7.11.1-0ubuntu1~16.5) 7.11.1
[etc]
Reading symbols from /home/petmay01/.rr/qemu-aarch64-10/mmap_pack_30_qemu-aarch64...done.
Really redefine built-in command "restart"? (y or n) [answered Y; input not from terminal]
Remote debugging using 127.0.0.1:7719
Reading symbols from /lib64/ld-linux-x86-64.so.2...Reading symbols from /usr/lib/debug//lib/x86_64-linux-gnu/ld-2.23.so...done.
done.
0x00007f6e3124ec30 in _start () from /lib64/ld-linux-x86-64.so.2
(rr) handle SIGSEGV pass noprint nostop
Signal        Stop      Print   Pass to program Description
SIGSEGV       No        No      Yes             Segmentation fault
(rr) handle SIGBUS pass noprint nostop
Signal        Stop      Print   Pass to program Description
SIGBUS        No        No      Yes             Bus error
(rr) c
Continuing.
ERROR: ld.so: object '/home/petmay01/src/rr-obj64/bin/../lib/rr/librrpreload.so' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
OpenJDK 64-Bit Server VM warning: Cannot open file hotspot_pid30232.log due to Permission denied

Warning:  Cannot open log file: hotspot_%p.log
Warning:  Forcing option -XX:LogFile=/tmp/hotspot_pid30232.log
[New Thread 30232.30241]
[New Thread 30232.30393]
  14736    1       3       java.lang.StringUTF16::getChar (60 bytes)
  15876    2       3       java.lang.StringLatin1::hashCode (42 bytes)
[snip lots of output from javac]
 167158  336       3       java.lang.String::regionMatches (187 bytes)   made not entrant
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x0000004000fca3f0, pid=30232, tid=30241
#
# JRE version: OpenJDK Runtime Environment (9.0) (slowdebug build 9-internal+0-adhoc.stuart.jdk9dev)
# Java VM: OpenJDK 64-Bit Server VM (slowdebug 9-internal+0-adhoc.stuart.jdk9dev, mixed mode, tiered, compressed oops, serial gc, linux-aarch64)
# Problematic frame:
# V  [libjvm.so+0x5c03f0]  Atomic::add(int, int volatile*)+0x34
#
# Core dump will be written. Default location: Core dumps may be processed with "/usr/share/apport/apport %p %s %c %d %P" (or dumping to /srv/chroot/xenial-aarch64/core.30232)
#
# An error report file with more information is saved as:
# /tmp/hs_err_pid30232.log
Compiled method (c2)  167732  456       4       java.nio.Buffer::position (55 bytes)
 total in heap  [0x000000401314c790,0x000000401314cb70] = 992
 relocation     [0x000000401314c910,0x000000401314c928] = 24
 main code      [0x000000401314c940,0x000000401314ca00] = 192
 stub code      [0x000000401314ca00,0x000000401314ca10] = 16
 metadata       [0x000000401314ca10,0x000000401314ca18] = 8
 scopes data    [0x000000401314ca18,0x000000401314ca78] = 96
 scopes pcs     [0x000000401314ca78,0x000000401314cb68] = 240
 dependencies   [0x000000401314cb68,0x000000401314cb70] = 8
#
# If you would like to submit a bug report, please visit:
#   http://bugreport.java.com/bugreport/crash.jsp
#
Current thread is 30241
Dumping core ...
[New Thread 30232.30238]
[New Thread 30232.30375]
[New Thread 30232.30470]
[New Thread 30232.30479]
[New Thread 30232.30529]
[New Thread 30232.30616]
[New Thread 30232.30620]

Thread 2 received signal SIGABRT, Aborted.
[Switching to Thread 30232.30241]
safe_syscall_base () at /home/petmay01/linaro/qemu-from-laptop/qemu/linux-user/host/x86_64/safe-syscall.inc.S:75
75              pop     %rbp
(rr) break handle_cpu_signal
Breakpoint 1 at 0x555ea6ef4f8e: file /home/petmay01/linaro/qemu-from-laptop/qemu/accel/tcg/user-exec.c, line 63.
(rr) rc
Continuing.

Thread 2 received signal SIGABRT, Aborted.
safe_syscall_base () at /home/petmay01/linaro/qemu-from-laptop/qemu/linux-user/host/x86_64/safe-syscall.inc.S:72
72              syscall
(rr) rc
Continuing.

Thread 2 hit Breakpoint 1, handle_cpu_signal (pc=93865015992631, address=275198036212, is_write=1, 
    old_set=0x53e872845328) at /home/petmay01/linaro/qemu-from-laptop/qemu/accel/tcg/user-exec.c:63
warning: Source file is more recent than executable.
63          CPUState *cpu = current_cpu;
(rr) n
82           */
(rr) n
83          if (helper_retaddr) {
(rr) print helper_retaddr
Cannot find thread-local storage for Thread 30232.30241, executable file /home/petmay01/.rr/qemu-aarch64-10/mmap_pack_30_qemu-aarch64:
Remote target failed to process qGetTLSAddr request
(rr) q
A debugging session is active.

        Inferior 1 [process 30232] will be detached.

Quit anyway? (y or n) y
Detaching from program: /home/petmay01/.rr/qemu-aarch64-10/mmap_pack_30_qemu-aarch64, process 30232
```

**Comment by rocallahan** [comment]
Is that log truncated? It doesn't seem to mention qGetTLSAddr...

**Comment by pm215** [comment]
It looked truncated to me too, but it's all that rr wrote, and as you can see from the transcript I exited the debugger cleanly so rr should have got a chance to clean up. So if it's truncated that would be an rr bug :-)

**Comment by pm215** [comment]
I tried looking at the logfile while interactively controlling the gdb session, and though rr adds more info to the log when I type 'c' in gdb (for the vCont packet, etc), there's nothing relating to the qGetTLSAddr, even though gdb is sending that packet:
```
(rr) print helper_retaddr
Sending packet: $qGetTLSAddr:p7618.7621,20,7f6e31475168#12...Packet received: E01
Cannot find thread-local storage for Thread 30232.30241, executable file /home/petmay01/.rr/qemu-aarch64-10/mmap_pack_30_qemu-aarch64:
Remote target failed to process qGetTLSAddr request
```
So presumably the log arguments you suggest aren't sufficient to capture it. (Aside: did you really mean GdbSession? That string doesn't appear anywhere in the rr sources.)

**Comment by pm215** [comment]
OK, so some of this seems to be that rr doesn't flush its log to disk when it's just sitting there waiting for a command from gdb, so you have to tell gdb to do something more to get rr to do enough more to write the log to disk where you can see it. And as far as I can see typing 'q' to gdb to quit the rr session doesn't make rr flush any outstanding buffered log data on exit...

in gdb:
```
Sending packet: $z0,555ea6ec5b37,1#97...Packet received: OK
Sending packet: $z0,555ea6ef4f8e,1#d0...Packet received: OK
Sending packet: $z0,7f6e31251f3b,1#62...Packet received: OK
Sending packet: $z0,7f6e312638c9,1#3e...Packet received: OK
Sending packet: $z0,7f6e312647e6,1#3d...Packet received: OK
82          if (helper_retaddr) {
(rr) print helper_retaddr
Sending packet: $qGetTLSAddr:p7618.7621,20,7f6e31475168#12...Packet received: E01
Packet qGetTLSAddr (get-thread-local-storage-address) is supported
Cannot find thread-local storage for Thread 30232.30241, executable file /home/petmay01/.rr/qemu-aarch64-10/mmap_pack_30_qemu-aarch64:
Remote target failed to process qGetTLSAddr request
(rr) n
Sending packet: $Z0,555ea6ec5b37,1#77...Packet received: OK
Sending packet: $Z0,555ea6ef4f8e,1#b0...Packet received: OK
Sending packet: $Z0,7f6e31251f3b,1#42...Packet received: OK
Sending packet: $Z0,7f6e312638c9,1#1e...Packet received: OK
Sending packet: $Z0,7f6e312647e6,1#1d...Packet received: OK
```

corresponding segment of the rr log from a run with RR_LOG_FILE=/tmp/rr.4.log RR_LOG=GdbServer,GdbConnection,GdbSession,ThreadDb:
```
[GdbConnection] raw request z0,555ea6ec5b37,1
[GdbConnection] gdb requests removebreakpoint (addr=0x555ea6ec5b37, len=1)
[GdbConnection] write_flush: '$OK#9a'
[GdbConnection] raw request z0,555ea6ef4f8e,1
[GdbConnection] gdb requests removebreakpoint (addr=0x555ea6ef4f8e, len=1)
[GdbConnection] write_flush: '$OK#9a'
[GdbConnection] raw request z0,7f6e31251f3b,1
[GdbConnection] gdb requests removebreakpoint (addr=0x7f6e31251f3b, len=1)
[GdbConnection] write_flush: '$OK#9a'
[GdbConnection] raw request z0,7f6e312638c9,1
[GdbConnection] gdb requests removebreakpoint (addr=0x7f6e312638c9, len=1)
[GdbConnection] write_flush: '$OK#9a'
[GdbConnection] raw request z0,7f6e312647e6,1
[GdbConnection] gdb requests removebreakpoint (addr=0x7f6e312647e6, len=1)
[GdbConnection] write_flush: '$OK#9a'
[GdbConnection] raw request qGetTLSAddr:p7618.7621,20,7f6e31475168
[GdbConnection] gdb asks for TLS addr
[ThreadDb] load_library OK
[ThreadDb] ps_pglobal_lookup nptl_version failed
[ThreadDb] initialize td_ta_new_fn failed
[GdbConnection] write_flush: '$E01#a6'
[GdbConnection] raw request Z0,555ea6ec5b37,1
[GdbConnection] gdb requests setbreakpoint (addr=0x555ea6ec5b37, len=1)
[GdbConnection] write_flush: '$OK#9a'
[GdbConnection] raw request Z0,555ea6ef4f8e,1
[GdbConnection] gdb requests setbreakpoint (addr=0x555ea6ef4f8e, len=1)
[GdbConnection] write_flush: '$OK#9a'
[GdbConnection] raw request Z0,7f6e31251f3b,1
[GdbConnection] gdb requests setbreakpoint (addr=0x7f6e31251f3b, len=1)
[GdbConnection] write_flush: '$OK#9a'
[GdbConnection] raw request Z0,7f6e312638c9,1
[GdbConnection] gdb requests setbreakpoint (addr=0x7f6e312638c9, len=1)
[GdbConnection] write_flush: '$OK#9a'
[GdbConnection] raw request Z0,7f6e312647e6,1
[GdbConnection] gdb requests setbreakpoint (addr=0x7f6e312647e6, len=1)
[GdbConnection] write_flush: '$OK#9a'
```

As you can see it fails to find the nptl_version symbol.

Full log attached.
[rr.4.log](https://github.com/mozilla/rr/files/1513956/rr.4.log)

**Comment by rocallahan** [comment]
I think the problem is that when we clone a TaskGroup we don't clone it's thread_db.

**Comment by rocallahan** [comment]
Yeah, I can reproduce. File this in the "how did this ever work" category.

**Comment by rocallahan** [comment]
Actually this is quite hard to fix :-(.

A simple case is when we replay forward to a breakpoint, then reverse-step, then print a TLS variable. This doesn't work because the reverse-step restarts from a cloned checkpoint at the beginning of the trace, and the cloned checkpoint has no ThreadDb. We can easily make checkpointing clone the existing ThreadDb if there is one, but it doesn't fix this case.

The problem is that a ThreadDb is not created and initialized until a gdb internal breakpoint is hit to indicate that gdb can resolve the symbols needed to initialize the ThreadDb. So when we create the cloned checkpoint at the beginning of the trace, the ThreadDb hasn't been created yet. When we resume the checkpoint we replay forward to the reverse-singlestep destination, but during this replay we ignore all breakpoints, including gdb's internal breakpoints. So when execution reaches the reverse-singlestep destination no ThreadDb has been created and accessing TLS doesn't work.

**Comment by rocallahan** [comment]
Instead of associating the ThreadDb with a ThreadGroup, we could associate it with a GdbServer (we're not likely to ever support multi-process debugging in a single GdbServer, or if we care we could give the GdbServer a hashmap from TaskUid to ThreadDb), and when you reverse-execute just assume that the ThreadDb remains valid. In theory the addresses of the symbols resolved for ThreadDb could change during execution, which would invalidate that assumption, but in practice hopefully we won't hit this during reverse execution. Everything related to gdb's internal breakpoints is kinda broken when you reverse-execute through them...

**Comment by rocallahan** [comment]
I should think about this a little more in case there are some hidden issues...

**Comment by pm215** [comment]
Thanks for the quick bugfix. Would you like me to open a separate issue for "logs not flushed to RR_LOG_FILE when you quit the rr gdb session", or is that expected behaviour ?

**Comment by rocallahan** [comment]
Thanks for reminding me. I just fixed it with https://github.com/mozilla/rr/commit/ed91e251d4840f54add6a2cb4f2b784171301bdc
