### ISSUE TITLE
Bug Bounty program

### ISSUE THREAD

**Issue by Chokoabigail** [mozilla/rr#2150]
Is there a Bug Bounty program at RR?
If so where can I find more details about her?
(More details = what bugs are accepted, what is the minimum payment, what form of submission accepted , who to submit my founding, etc.)

**Comment by rocallahan** [comment]
There is no bug bounty program for rr.

rr is not designed to handle malicious code safely (see https://github.com/mozilla/rr/wiki/Usage#malicious-code) and we do not claim any particular security properties for it.
