### ISSUE TITLE
spidermonkey ion compilation bug hard to reproduce under rr

### ISSUE THREAD

**Issue by hotsphink** [mozilla/rr#2153]
I recently had a bug that reproduced in 23 out of 100 runs without rr, 0 out of 100 with rr --chaos. I eventually found a tuning parameter (--ion-warmup-threshold=200) that raised the non-rr frequency to about 75%, and that was enough to catch it under rr (I didn't run enough times to know the frequency, but it seems like it was at around 50% of half a dozen runs or so as I flailed around.) Note that it would never reproduce without --chaos, because it depended on offthread jit compilation and by default rr reports a single core, causing everything to run on the main thread.

This was a tricky one, because setting the ion threshold too low (eg with --ion-eager) or too high (the default 1000) would make it go away. I *think* the relevant actions are: (1) run in the interpreter or maybe baseline, (2) switch to ion, (3) GC. And somewhere in there the relevant event happens, which is having ion construct an unboxed object with a nursery-allocated string property. I still don't know why making ion more eager made it go away, but I don't know much about when objects are unboxed or where that string came from.

As I understand it, scripts run in the interpreter up to 10 iterations, then baseline, then when they reach the ion warmup threshold they are queued for compiling off-thread. I *think* there's some entry point that checks whether the script is compiled yet and switches to it if so? Or it might be some fancier on-stack replacement thing. At any rate, the exact switchover point is determined by thread scheduling, if I'm not mistaken.

Filing this issue in case it's useful for tweaking chaos mode. I've fixed the bug, so I don't need anything here and you can close it if it's not actionable.

**Comment by rocallahan** [comment]
Thanks for the report, this sort of report is valuable.

It's possible that increasing the number runs by a couple of orders of magnitude would have produced a result for rr --chaos, so I would have recommended trying that if those runs would complete within, say, a day.

Can you describe the thread schedule required to exhibit the bug in more detail? I'm not quite sure what runs on what thread from your description.

**Comment by hotsphink** [comment]
The runs take about 60 seconds if they're going to fail, 3 minutes if they succeed. So I could bump it up by one order of magnitude, maybe, but no more than that. (The duration of the run depends on the input size, but I never observed a failure using smaller input.)

I'm kind of fuzzy about what runs on what thread, and also about the required sequence of events for this bug. But I'll try to describe what I know or think I know.

First, the bug is a missing case for JSVAL_TYPE_STRING at https://searchfox.org/mozilla-central/source/js/src/vm/UnboxedObject.cpp#140 with my current patch stack, which allocates strings in the nursery for generational GC. The problem occurs when you construct an unboxed object, store a nursery string in a property but do not store nursery objects in any other properties. If you had stored a nursery object, then the entire unboxed object would be flagged as containing nursery pointers and fixed up when the nursery objects get tenured. So in the problematic case, you have a nursery string, at some later point you do a minor GC which moves the string to the tenured heap and leaves the unboxed object's property pointing to stale (thankfully poisoned) nursery space. I was then getting a crash when a verifier runs over the whole heap and tries to traverse into that supposed string.

So the sequence of actions here is simply constructing the relevant unboxed object with ion jit code, then doing a minor GC, then doing a verification pass (I'm not sure if that's triggered after the minor GC, or at the next major GC.)

It was easy to know what the basic problem was without rr, by the way. I caught the crash under gdb and saw the poison pattern, and knew I wasn't barriering a write into an unboxed object's string property. But after manually checking writes to unboxed objects, they all looked good. I didn't know there was this separate construction thing. The rr recording, via a watchpoint on the PC that writes into the string property, immediately pointed me to the code that generated the machine code with the missing barrier. It was the sort of bug that is easy to find and fix with rr, extremely hard without.

Anyway, now that I've spelled that out, I'm more confused than ever what the ion compilation timing has to do with anything. I'll try to pull in jandem to describe how this stuff works.

But what I do know is what I described in the earlier comment, where we start running in the interpreter, then move to the baseline JIT, then to ionmonkey. Ionmonkey compilation can happen on the main thread, or it can happen on a helper thread and after the compilation is complete, a notification gets posted to the main thread (not really, but it ends up doing the same thing). The main thread then switches to the faster ion-compiled code at the earliest opportunity. I *think* it can do it at any loop head, but I'm not sure about that.

--ion-eager is a flag that triggers ion compilation immediately. Come to think of it, I bet I know why the bug didn't happen then. If you trigger ion compilation too soon, you won't have the type data, and I bet the type data is necessary to decide to use unboxed objects? Ooh, looking at the code, it's pretty direct: until you've seen some number of objects constructed, you won't attempt to optimize them with an unboxed layout. So I guess if the ion code is generated before the decision to used an unboxed layout has been made, then none of this will happen.

As for why the default warmup threshold of 1000 iterations was less likely to trigger the bug, I can only speculate that either (1) we don't hit the threshold and never ion compile, or (2) by the time we hit the threshold and wait for the compile to finish, we're no longer constructing any of these objects. Either that, or it's close enough to being done that we never do a minor GC before the relevant object is dead anyway. (Or there are phases of constructing these objects and using them, then discarding them.)

Sorry, I'm not sure if this rambling helps. It seems like if that compilation thread were given all the time it needed to finish compiling quickly, it would make this more likely to trigger? I should've tried with more values of the warmup threshold, in case the situation isn't quite as simple as "too small bad, too big bad". The test runs are a bit slow to do a lot of, but doing 10 runs at a time might be enough. I'll build a version without my fix and try out a couple of values. And also verify whether the offthread compilation is really as relevant as I'm saying here.

**Comment by rocallahan** [comment]
Currently chaos mode works by choosing a victim thread and refusing to schedule it over some time interval. From what you've said it sounds like that should have worked if we chose to starve the main thread after the compilation thread has started...

**Comment by hotsphink** [comment]
For whatever it's worth:

Without rr, if you turn off either unboxed objects or off main thread compilation, 0/20.

The crashes out of 20 attempts for warmup thresholds of 1,10,20,50,100,200,400,800,1000,2000,4000 are 0,0,0,0,0,11,0,15,4,18,0.

The same thing with rr: 0,0,6,6,3,7,0,10,7,19,4

Uh... so that's all over the map, but generally speaking, I'm getting *more* crashes with rr than without. Erm. I kinda skimmed back through history to pick a version, maybe this one is different? Because that 7/20 is a far cry from the 0/100 I saw originally.

At any rate, I'm closing this bug. It doesn't seem like there's anything worth chasing down here.

**Comment by hotsphink** [comment]
Oh, one significant difference I just thought of. My original attempts were with a much older version of rr. I'm not sure how to tell what version it was. I've heard git has a reflog, so I did 'git reflog', and it told me I previously was on 380526d. So maybe that?

**Comment by rocallahan** [comment]
I find it hard to believe that a 2.5-year-old rr would work at all with modern Firefox...

**Comment by hotsphink** [comment]
Bah, it couldn't have been more than half a year old. Every time I see that git can do something and try it out, it never ends up doing what I expect. Unfortunately, I have no record of what version I was using. I even deleted the trace, so I can't check what version trace file format it was (it was pre-capnproto).
