### ISSUE TITLE
Weird behavior of stat64 under rr when running a Firefox test

### ISSUE THREAD

**Issue by bzbarsky** [mozilla/rr#2156]
STEPS TO REPRODUCE:

1)  Install rr 5.0.0
2) Check out Firefox revision 58ab683a6b02
3) Compile Firefox.
4) Run `mach mochitest --debugger=rr --debugger-args="-M record" dom/bindings/test/test_exceptionSanitization.html`

EXPECTED RESULTS: Record the test and let me debug it

ACTUAL RESULTS: Failing assertion in necko.

I tracked back to why the assertion fires and the issue is that Firefox is trying to read a file:// url (`file:///home/bzbarsky/mozilla/vanilla/obj-firefox/dist/bin/modules/reader/Readability.js` in my case), gets to nsLocalFile::FillStatCache, does:

    if (STAT(mPath.get(), &mCachedStat) == -1) {

and gets a return value that is not -1.  At the same time, mCachedStat is not written to; it still has the 0xe4 jemalloc uninitialized memory markers all over its members.  Then later we try to get the file size, get a very large negative number (`-1953184666628070172` because it's getting `0xe4e4e4e4e4e4e4e4` as a `long long`) and things break.  Running this same test not under rr works fine.

**Comment by bzbarsky** [comment]
Running with MOZ_DISABLE_CONTENT_SANDBOX=1 makes things work, so this is something about the interaction of rr's syscall interception and sandboxing....

**Comment by khuey** [comment]
Can you try rr master?  Or at least a build with b8821907e0ed?

**Comment by bzbarsky** [comment]
Ah.  On master things work fine.
