### ISSUE TITLE
After a (not so long) debugging sesssion, rc stops working, and it's impossible to recover

### ISSUE THREAD

**Issue by emilio** [mozilla/rr#2160]
In particular, `rc` hangs, and pressing ctrl + C only results in `Invalid remote reply` messages.

**Comment by khuey** [comment]
Can you `rr record` the replay?  It will be easier if you `rr replay -s <port>` and manually launch a gdb connected to that port. Log at least `GdbConnection`, `GdbServer`, and `ReplayTimeline`.

**Comment by emilio** [comment]
Sure, will try to do that tomorrow.

**Comment by emilio** [comment]
This was on 244151f05a0a0c9315675c6278580a98cb97db69, fwiw. Tomorrow I'll try on master.

**Comment by emilio** [comment]
I haven't been able to repro it on master after a while, so I'm going to close as WFM, but I'll reopen if it happens again.

Thanks for all the awesome btw :)
