### ISSUE TITLE
Running an individual <test>.run inside src/test doesn't load proper $OBJDIR

### ISSUE THREAD

**Issue by WesleyYue** [mozilla/rr#2167]
When we run `bash <test>.run` to run an individual test inside `src/test`, the default OBJDIR is set to OBJDIR=`realpath $SRCDIR/../obj` in src/test/util.sh:129. However, if $SRCDIR is supposed to be the root `rr` directory, this would try to find the `obj` directory as a sibling of `rr`. Shouldn't it be OBJDIR=`realpath $SRCDIR/obj` instead?

**Comment by rocallahan** [comment]
Yes, the current code assumes you put `obj` as a sibling of `rr` instead of a child. That's where I have it. Is that a problem?

**Comment by WesleyYue** [comment]
I see. Following the build instructions from the wiki would produce `obj` as a child of `rr` which is why I got confused. Maybe either the wiki or the script should be changed for consistency?

**Comment by rocallahan** [comment]
Good point. Wiki updated.
