### ISSUE TITLE
rr replay -p PID attaches to the root of the process tree

### ISSUE THREAD

**Issue by hsivonen** [mozilla/rr#2168]
# Steps to reproduce

1. Install rr 5.1.0 on Ubuntu 16.04 x86_64 with rolling hardware enablement stack (currently kernel 4.13.0-36-generic #40~16.04.1-Ubuntu SMP)
2. Add `printf("CONTENT PROCESS PID: %d\n", getpid());` somewhere in Gecko in code that never runs in the chrome process. (I used `PaymentRequest.cpp`.)
3. Build Firefox
4. Launch Firefox with ` ./mach run --debug --debugger=rr --setpref dom.payments.request.enabled=true`
5. Do something that provokes the `printf` from a content process.
6. Quit Firefox.
7. Run `rr ps` and note the pid of the process that has no parent.
8. Per [instructions on the wiki](https://github.com/mozilla/rr/wiki/Recording-Firefox#recording-firefox-in-e10s-mode), launch `rr` with `rr replay -p 1234` where 1234 is the PID taken from the `printf` output.
9. Shortly after `rr` starts, press ctrl-C.
10. Once the `(rr)` prompt shows up, run the command `p getpid()`.
11. Set a break point on the line where you added the `printf` in step 2.
12. Run the command `continue`.

# Actual results

Step 10 prints the pid of the root process noted in step 7. The debuggee terminates without ever stopping at the break point.

# Expected results

Expected step 10 to print the same pid that was passed as the argument to the `-p` switch to `rr`. Expected the execution to reach the `printf` and the debugger to break there.

**Comment by rocallahan** [comment]
If you interrupt rr with ctrl-C before your desired process has execed, we just attach the process that was running when you hit ctrl-C. I don't understand your expectation; when you hit ctrl-C, your target process does not exist (or at least hasn't execed yet), so how do you expect us to attach to it?

**Comment by hsivonen** [comment]
> If you interrupt rr with ctrl-C before your desired process  has execed, we just attach the process that was running when you hit  ctrl-C. I don't understand your expectation; when you hit ctrl-C, your  target process does not exist (or at least hasn't execed yet), so how do  you expect us to attach to it?

Ah, good point. I expected to be able to set breakpoints for future library loads as usual and didn't think carefully enough to realize that I need to wait until the target process exists to do that.

I guess this could be considered a request to make ctrl-C combined with `-p PID` less of a footgun. At the very least it shouldn't _silently_ attach do a different process than originally requested.

**Comment by rocallahan** [comment]
Yes, I agree there should be some kind of warning.

**Comment by rocallahan** [comment]
We now print something like
```
--------------------------------------------------
 ---> Interrupted; attached to NON-TARGET process 11880 at event 898.
--------------------------------------------------
```
... immediately followed by tons of gdb symbol-loading spew which pushes it out of view. But that's probably the best we can do for now.

**Comment by hsivonen** [comment]
Thank you.
