### ISSUE TITLE
Errors for prerequisites installation of build procedure

### ISSUE THREAD

**Issue by kevin-coder** [mozilla/rr#2172]
When I tried to install the prerequisites according to "Building And Installing" sections, following error message pop up:

Package realpath is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source
However the following packages replace it:
  manpages-pl manpages-fr-extra

System info:
Distributor ID:	Ubuntu
Description:	Ubuntu Bionic Beaver (development branch)
Release:	18.04
Codename:	bionic

So, for Ubuntu 18.04, is it necessary for updating the instruments of prerequisites installation?

**Comment by rocallahan** [comment]
Thanks. I replaced `realpath` with `coreutils` in the wiki page.

**Comment by kevin-coder** [comment]
Got you, thank you so much!
