### ISSUE TITLE
rr fatal error: CPUID faulting required to disable CPUID features

### ISSUE THREAD

**Issue by staktrace** [mozilla/rr#2179]
Running `rr` on even simple commands like `ls` now makes rr crash with a fatal error:

```
[FATAL /home/kats/zspace/rr/rr/src/RecordSession.cc:1892:set_disable_cpuid_features()] CPUID faulting required to disable CPUID features
=== Start rr backtrace:
rr(_ZN2rr13dump_rr_stackEv+0x45)[0x835291]
rr(_ZN2rr15notifying_abortEv+0x51)[0x835247]
rr(_ZN2rr12FatalOstreamD1Ev+0x28)[0x70a996]
rr(_ZN2rr13RecordSession26set_disable_cpuid_featuresERKNS_20DisableCPUIDFeaturesE+0xb1)[0x74292b]
rr[0x7383c9]
rr[0x738506]
rr(_ZN2rr13RecordCommand3runERSt6vectorINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEESaIS7_EE+0x17b)[0x738f35]
rr(main+0x203)[0x84a911]
/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf0)[0x7f2906289830]
rr(_start+0x29)[0x65d159]
=== End rr backtrace
```

My /proc/cpuinfo is at https://gist.github.com/staktrace/3b0cb1e90fef52e7afba91cfcce6f7bd and `uname -a` shows:

```
Linux kgupta-pc 4.4.0-119-generic #143-Ubuntu SMP Mon Apr 2 16:08:24 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
```

rr used to work fine on this same hardware, and building the revision prior to 8b0538907 also works fine.

**Comment by khuey** [comment]
You see this on tip?

**Comment by staktrace** [comment]
Yup, where tip for me is 2140c9bafc (I pulled a few days ago)

**Comment by khuey** [comment]
That's not tip ...

**Comment by staktrace** [comment]
Oh it looks like a fix landed more recently than that... let me retest. Sorry!

**Comment by staktrace** [comment]
Yeah it works now. For some reason I thought I had pulled just a day or two ago, so when I looked at the "recent" changes there was nothing related. But it was like a week ago... time flies!

**Comment by khuey** [comment]
np, glad it works :)
