### ISSUE TITLE
Task.cc:188 [-Werror=restrict] aliasing trouble

### ISSUE THREAD

**Issue by jreiser** [mozilla/rr#2183]
```
rr/src/Task.cc:188:35: error: passing argument 2 to restrict-qualified parameter aliases with argument 1 [-Werror=restrict]
   ssize_t nbytes = readlink(path, path, sizeof(path) - 1);
                             ~~~~  ^~~~

commit 1e8f531c4dcd83ebb01d4f6e4aa318eb57d2a543 (HEAD -> master, origin/master, origin/HEAD)
Date:   Fri Apr 20 22:58:04 2018 +1200

glibc-headers-2.27-8.fc28.x86_64   /usr/include/unistd.h:
extern ssize_t readlink (const char *__restrict __path,
                         char *__restrict __buf, size_t __len)
     __THROW __nonnull ((1, 2)) __wur;

gcc (GCC) 8.0.1 20180324 (Red Hat 8.0.1-0.20)

```

**Comment by jreiser** [comment]
```diff --git a/src/Task.cc b/src/Task.cc
index 8d9d2903..08e0116b 100644
--- a/src/Task.cc
+++ b/src/Task.cc
@@ -184,8 +184,9 @@ ScopedFd Task::open_fd(int fd, int flags) {
 
 string Task::file_name_of_fd(int fd) {
   char path[PATH_MAX];
-  snprintf(path, sizeof(path) - 1, "/proc/%d/fd/%d", tid, fd);
-  ssize_t nbytes = readlink(path, path, sizeof(path) - 1);
+  char procfd[40];
+  snprintf(procfd, sizeof(procfd) - 1, "/proc/%d/fd/%d", tid, fd);
+  ssize_t nbytes = readlink(procfd, path, sizeof(path) - 1);
   if (nbytes < 0) {
     path[0] = 0;
   } else {
```
11 tests failed, perhaps due to kernel from Fedora 28 (4.16.2-300.fc28.x86_64 #1 SMP Thu Apr 12 14:58:07 UTC 2018)

**Comment by rocallahan** [comment]
Thanks for the patch. Guess I'll install F28 Beta and look at those failures.

**Comment by rocallahan** [comment]
I pushed your patch as https://github.com/mozilla/rr/commit/89610ffc38ee5676b0415cac479707bc624a7f2e.

**Comment by rocallahan** [comment]
I installed F28 in a VM and reproduced some test failures. The following rr commits fix all of them:
https://github.com/mozilla/rr/commit/48617d9a9e86ccc0b5b270900ee82a58c0ce6c93
https://github.com/mozilla/rr/commit/284aa21358b0d560a0ad544a8039c0af473568b9
https://github.com/mozilla/rr/commit/e646be9f239826a386da567a43ccd8a1429623a6
https://github.com/mozilla/rr/commit/fe84b09806f543271cd8f2df41d5eb1f40349481
The first three are a change in gdb behavior; it seems to now require casting to a return type when calling C functions. The last one works around a kernel regression, which I filed as https://bugzilla.kernel.org/show_bug.cgi?id=199469.

**Comment by rocallahan** [comment]
All those were test-only issues, rr itself works fine.
