### ISSUE TITLE
Support for Celeron architecture on QEMU hypervisor?

### ISSUE THREAD

**Issue by ex0dus-0x** [mozilla/rr#2196]
Running Lubuntu on QEMU with the following command (as specified in the installation guide):

```
qemu-system-i386 -enable-kvm -boot d -m 512 -cpu host -hda guest.img  
```

`lscpu` on my host returns the following model:

```
Model name:          Intel(R) Celeron(R) CPU  N2840  @ 2.16GHz
```

After successful compilation and installation of `rr`, and proper configuration of `/proc/sys/kernel/perf_event_paranoid`,  this result occurs, when attempting to record a simple process:

```
$ rr record ls .
[FATAL /home/testbed/isolate/rr/src/PerfCounters.cc:201:get_cpu_microarch()] Intel CPU type 0x30670 unknown
```

I have changed the `-cpu` flag of QEMU to run `SandyBridge`, which is supposedly a support architecture for `rr`. The following result occurs:

```
[FATAL /home/testbed/isolate/rr/src/PerfCounters.cc:262:start_counter() errno: ENOENT] Unable to open performance counter with 'perf_event_open'; are perf events enabled? Try 'perf record'.
```

Any thoughts?

**Comment by khuey** [comment]
In order to use rr in QEMU your virtual cpu must be `host-passthrough`.

That doesn't actually help you because rr does not support your physical CPU though. I don't think Silvermont has the necessary performance counters. @rocallahan can confirm.

**Comment by rocallahan** [comment]
I believe Silvermont does have the necessary counters, but in some versions at least there are bugs stopping rr from working. See https://github.com/mozilla/rr/issues/1642.

We definitely can't support Celeron so I'm going to close this issue. People need to use `host-passthrough` with QEMU; any Silvermont issues should be followed up in https://github.com/mozilla/rr/issues/1642.

**Comment by khuey** [comment]
Maybe I'm just confused by Intel's byzantine naming conventions but https://ark.intel.com/products/82103/Intel-Celeron-Processor-N2840-1M-Cache-up-to-2_58-GHz says the Celeron N2840 is "Bay Trail" which I believe is a subset of the Silvermont microarchitecture.

**Comment by rocallahan** [comment]
OK, I stand corrected. Followup should still happen in the Silvermont issue.
