### ISSUE TITLE
Replay Assertion when using mmap with PROT_WRITE|PROT_READ|PROT_EXEC and MAP_SHARED

### ISSUE THREAD

**Issue by roquo** [mozilla/rr#2199]
I got an assertion when replaying an mmap()-syscall with these attributes:

`
        int main(){

	int fd = open("text.txt", O_RDWR);
	void* addr = mmap(NULL, 1, PROT_WRITE|PROT_READ|PROT_EXEC, MAP_SHARED, fd, 0);

	if (addr == MAP_FAILED){
        	perror("mmap");
		return 1;
	}

	printf("%s, at %p\n",addr, &addr);

	return 0;}
`

Recording doesn't show any problems, the assertion in replay is

`[FATAL /home/kevin/rr/rr-5.1.0/src/AutoRemoteSyscalls.cc:631:infallible_mmap_syscall()] 
 (task 68581 (rec:68571) at time 183)
 -> Assertion `addr == ret' failed to hold. MAP_FIXED at 0xf76f8000 but got 0xfffffff3
`

I am using rr-5.1.0 and RedHat Enterprise 7.4 with kernel version 3.10.0 
GDB backend is 7.12.1
Program is compiled with gcc-version 4.8.5 
Is this a known bug, or am I facing a problem cause of my OS? 

The assertion only accures when all the 3 the Protocols are enabled and when I want to use MAP_SHARED, any other combination I tested didn't trigger the assertion.

Would rr-5.2.0 solve this problem? I don't use the newest version, because my kernel doesn't support it.

Thanks for your help :)

**Comment by khuey** [comment]
When I try to run this I get an EACCES during replay.

**Comment by rocallahan** [comment]
The problem probably is that the EmuFs replay file is non-executable so we're not allowed to map it PROT_EXEC.

**Comment by roquo** [comment]
![grafik](https://user-images.githubusercontent.com/35525625/41272262-bdf484c0-6e14-11e8-8c49-c71a61cc4944.png)
I think you mean the `mmap_copy_xxx` File? I even tried to change rights, that everyone can execute it, but nothing worked

**Comment by roquo** [comment]
![grafik](https://user-images.githubusercontent.com/35525625/41299317-76f3e256-6e63-11e8-92e8-dd34997acbc3.png)
I looked at the file table of my running process and I saw that the mapped file is only mapped with read and executable rights. I think this is the cause of the error

**Comment by rocallahan** [comment]
I can reproduce the bug.
