### ISSUE TITLE
Assertion `false' failed to hold. 2147483647 IN_TX ticks detected while HLE not supported due to KVM PMU virtualization bug

### ISSUE THREAD

**Issue by posidron** [mozilla/rr#2202]
[FATAL /tmp/rr.build.GZO95iA65T/rr/src/PerfCounters.cc:740:read_ticks()] 
 (task 29190 (rec:29190) at time 511430)
 -> Assertion `false' failed to hold. 2147483647 IN_TX ticks detected while HLE not supported due to KVM PMU
virtualization bug. See http://marc.info/?l=linux-kernel&m=148582794808419&w=2
Aborting. Retry with -F to override, but it will probably
fail.
[FATAL /tmp/rr.build.GZO95iA65T/rr/src/log.cc:364:emergency_debug()] (session doesn't look interactive, aborting emergency debugging)
=== Start rr backtrace:
rr(_ZN2rr13dump_rr_stackEv+0x37)[0x7df2a7]
rr(_ZN2rr15notifying_abortEv+0x5e)[0x7de8fe]
rr(_ZN2rr12FatalOstreamD1Ev+0x42)[0x68eb92]
rr[0x68f051]
rr(_ZN2rr21EmergencyDebugOstreamD2Ev+0x72)[0x68eee2]
rr(_ZN2rr12PerfCounters10read_ticksEPNS_4TaskE+0x183)[0x6b9633]
rr(_ZN2rr4Task11did_waitpidENS_10WaitStatusE+0x579)[0x7a9619]
rr(_ZN2rr4Task4waitEd+0x84b)[0x7a812b]
rr(_ZN2rr9Scheduler10rescheduleENS_10SwitchableE+0x278)[0x780668]
rr(_ZN2rr13RecordSession11record_stepEv+0x119)[0x6cf6a9]
rr[0x6c45cb]
rr(_ZN2rr13RecordCommand3runERSt6vectorINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEESaIS7_EE+0x3d1)[0x6c32d1]
rr(main+0x2ee)[0x7f514e]
/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf1)[0x7f501b2881c1]
rr(_start+0x2a)[0x5cd65a]
=== End rr backtrace

**Comment by surki** [comment]
@posidron If it is of any use, I have had success running it in Amzon Linux (2017.??), both in c5.9xlarge and i3.metal

**Comment by khuey** [comment]
This is a known KVM bug and there's not really anything we can do to get Amazon to upgrade their hypervisor. They seem to be switching everything to Nitro anyways, which does work. So I'm going to close this.
