### ISSUE TITLE
Failing recording because signals sent to rr

### ISSUE THREAD

**Issue by roquo** [mozilla/rr#2210]
I built a little test framework with rr, which starts recording automatically with our application. Sometimes i got the feeling, when our disks are low on space, the recording fails, and i get the "incomplete" message. 
Does rr build (a lot) of tmp files, and can i redirect where they get build? I think, while recording my personal disk runs out of space, rr terminates and deletes all the tmp-files. My personal disk is not really big and only a virtual disk from a bigger server.

**Comment by rocallahan** [comment]
You can set the `_RR_TRACE_DIR` environment variable to have the traces stored wherever you want. Does that solve your problem?

**Comment by roquo** [comment]
Memory usage was not the fault. We have an inherent bug in our test framework, which kills every process with SIGKILL created in one test case, when an error occures for example. When running rr with our application it was kind of magic which process got first killed, sometimes rr could record the kill of the application, sometimes not. 

I started tracing now signals while running rr in our test framework, sometimes we get a SIGHUP and this signal terminates then rr. Are there any signal handlers installed in rr, that we can ignore (every) signal?
I know that we can't block SIGKILL and SIGSTOP, so I have to look in our test framework, that this doesn't occure, but it would be a big effort, to look for every signal for every application there, so it would be cool, if we could ignore them.
