### ISSUE TITLE
Actual master branch: replay is not working anymore!

### ISSUE THREAD

**Issue by roquo** [mozilla/rr#2213]
I cloned the actual git repository and replay does not work any more.
![grafik](https://user-images.githubusercontent.com/35525625/42265472-f0abdd8a-7f73-11e8-855a-25c31e275bb9.png)
I can't kill the started rr process with kill -9 <pid>, only reboot helps.  `make test` stops running after first test. 
RR is running under Red Hat 7 built with gcc 4.8.5

I went back to commit `8f8adb6` and everything works fine. So the newest commit `a4a7ff1` has to be the reason for the failing replay

It seems that the issue appears only on Red Hat, I tried it with Ubuntu 14 and everything worked fine.
Is this a kernel bug in Red Hat 7? 
`pwrite64()` in `Task.cc`line 2181 never returns, when to write at /proc/<pid>/mem at some point.

**Comment by rocallahan** [comment]
Weird. What kernel version?

Try recording rr's `bin/simple` and then replaying it?

Try replaying with `RR_LOG=all`?

**Comment by roquo** [comment]
Record.log of bin/simple
[record.log](https://github.com/mozilla/rr/files/2165576/record.log)

Replay.log 
[replay.log](https://github.com/mozilla/rr/files/2165579/replay.log)

Kernel Version is:
3.10.0-693.el7.x86_64

**Comment by rocallahan** [comment]
Try reverting cdbc02d77155ae65e0c5ed3b5948c67155ca9713 ?

**Comment by roquo** [comment]
Reverting solved the issue. Is this going to be in the master branch?

**Comment by rocallahan** [comment]
I guess Red Hat did not backport the regression fix 8310d48b125d19fcd9521d83b8293e63eb1646aa to their stable branch. That is sad.

If you have a support contract with Red Hat maybe you can ask them to unbreak their kernel? If you don't, I suggest switching to a system with a newer kernel. I really don't want to reintroduce this performance-hurting workaround.

**Comment by rocallahan** [comment]
That's https://github.com/torvalds/linux/commit/8310d48b125d19fcd9521d83b8293e63eb1646aa I mean
