### ISSUE TITLE
Buffer `epoll_wait` syscalls

### ISSUE THREAD

**Issue by rocallahan** [mozilla/rr#2241]
This is hard because of the kernel bug mentioned here: https://varnish-cache.org/lists/pipermail/varnish-commit/2016-January/014928.html

**Comment by rocallahan** [comment]
Most `epoll_wait` syscalls end up blocking, but a lot don't and could usefully be buffered.

**Comment by rocallahan** [comment]
The problem is that a call to `epoll_wait` that blocks and would trigger our desched signal, returns with `EINTR` so it's not blocked.

**Comment by zairil** [comment]
Tq for your information
