### ISSUE TITLE
Is window display possible in rr replay?

### ISSUE THREAD

**Issue by xlicz** [mozilla/rr#2242]
I'm debugging an OpenCV application which would show an image in a window named "test"  with a simple function
```cpp
void ShowColorDebugMap2(const cv::Mat &map)
{
    std::string window_name = "test";
    cv::namedWindow(window_name, 0);
    cv::imshow(window_name, map);
    cv::waitKey(1);
}
```

When I do rr record, it works nicely. However, when I do rr replay, it doesn't show anything. Is this a known limitition of rr? Thanks!

**Comment by rocallahan** [comment]
That's just the way rr works. rr doesn't replay the window contents. That could be done but it would be a significant amount of work.

**Comment by xlicz** [comment]
Thanks for your reply. I further try to display the image with a customized display function and call it explicitly with gdb, rr complain a IO related error, which is as follow:

```bash
(rr) call ShowColorDebugMap(mapBuilder->maps.mergedMap.m_color_debug_map)
mapbuilder_dual_layer: Fatal IO error 9 (Bad file descriptor) on X server :0.

Thread 1 hit Breakpoint 1, main (argc=1, argv=0x7ffdfacbb848) at /home/xianggen/fast_ssd/Dev/ml_team/map_server_node/src/pita_slam/src/apps/mapbuilder_dual_layer/main.cpp:206
206	                            ShowColorDebugMap(mapBuilder->maps.mergedMap.m_color_debug_map);
The program being debugged stopped while in a function called from GDB.
Evaluation of the expression containing the function
(ShowColorDebugMap(cv::Mat const&)) will be abandoned.
When the function is done executing, GDB will silently stop.
```
Is this an expected behavior? Since I'm debugging an image related bug, I need to visualize it, is any way to work around this?

**Comment by rocallahan** [comment]
It looks like your dump function tried to contact the X server. That isn't possible during replay; none of the file descriptors open during recording are open during replay. If your image is in memory somewhere, you could find it and dump it from memory.

**Comment by xlicz** [comment]
This way works, thank you!
