### ISSUE TITLE
Cannot find 'realpath' on Ubuntu 18.10 for the build prerequisites

### ISSUE THREAD

**Issue by huzq85** [mozilla/rr#2265]
In the "Building And Installing" section, the following prerequisites should be installed on the Ubuntu before building.

sudo apt-get install ccache cmake make g++-multilib gdb \
  pkg-config coreutils python-pexpect manpages-dev git \
  ninja-build capnproto libcapnp-dev **realpath**

However, on Ubuntu 18.10, binary "**realpath**" cannot be found. Below is the Error Message.

Package realpath is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source
However the following packages replace it:
  manpages-pl manpages-fr-extra

**Comment by rocallahan** [comment]
I'll take that out. thanks.

**Comment by huzq85** [comment]
@rocallahan , thank you for quick update, by take this issue out, you mean rr cannot support Ubuntu 18.10?

**Comment by rocallahan** [comment]
No, it should build and work fine on Ubuntu 18.10 without that package.

**Comment by huzq85** [comment]
Got you, I will have a try. Thank you so much for the quick update!
