### ISSUE TITLE
rr on non-x86 platforms

### ISSUE THREAD

**Issue by lu-zero** [mozilla/rr#2274]
Would be possible to document what's needed to have rr working on a non-x86 platform?

**Comment by rocallahan** [comment]
Have you read https://arxiv.org/abs/1705.05937 ? What would you want to know that's not in there?

**Comment by rocallahan** [comment]
I'll close this issue. If you have specific questions about porting rr to a specific architecture (a large project, but a welcome one!) email rr-dev or me personally.

**Comment by lu-zero** [comment]
Thank you :)
