### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by SeanHeelan** [mozilla/rr#2280]
In this zip file ([rr_issue.zip](https://github.com/mozilla/rr/files/2501704/rr_issue.zip)) there's a CTF challenge binary and a Python script to run it and interact with it. The Python script requires pwntools (http://docs.pwntools.com/en/stable/install.html). When I try to record the execution using `rr record ./x.py` I get a segmentation fault in rr. I am using the latest version of rr from git master, on Fedora 28 with kernel 4.18.13-200.fc28.x86_64, and running that inside VMWare Workstation.

**Comment by rocallahan** [comment]
It's an unknown ioctl:
```
Assertion `t->regs().syscall_result_signed() == -syscall_state.expect_errno' failed to hold. Expected EINVAL for 'ioctl' but got result 4 (errno errno(-4)); Unknown ioctl(0x5441): type:0x54 nr:0x41 dir:0 size:0 addr:0x102
```

**Comment by rocallahan** [comment]
`TIOCGPTPEER` apparently, added in Linux 4.13.
