### ISSUE TITLE
can't record multi-threaded mono programs due to SIGPWR conflict

### ISSUE THREAD

**Issue by cwitty** [mozilla/rr#2294]
I was trying to "rr record" a program implemented with mono, and it failed with:
 -> Assertion `SYSCALLBUF_DESCHED_SIGNAL == si->si_signo && si->si_code == POLL_IN' failed to hold. Tracee is using SIGPWR??? (siginfo={signo:SIGPWR,errno:SUCCESS,code:SI_TKILL})

And indeed, according to https://github.com/mono/mono/blob/master/libgc/doc/README.linux,
"The garbage collector uses SIGPWR and SIGXCPU if it is used with
Linux threads."

I think the details are probably unimportant, because it looks like any version of rr would fail on any multi-threaded program implemented with any version of mono, as long as the program does at least one garbage collection.  But just in case: 

I was trying to record the game "Magnetic by Nature" (which uses mono because it was developed with Unity).  I'm using the Debian package of rr (package version 5.2.0-2) for amd64, on a fairly up-to-date installation of Debian testing.  I'm on a laptop with Intel integrated graphics, and I'm using the Debian kernel package version 4.18.10-2+b1.  The game is bundled with its own copy of mono, and I don't know what version it is.  (It's pretty old, though; the bundled libmono.so is dated August 8, 2014.)

**Comment by rocallahan** [comment]
If you build from master, you should be able to change `#define SYSCALLBUF_DESCHED_SIGNAL SIGPWR` in `src/preload/preload_interface.h` to a different unused signal, say `SIGURG` and re-record.

I suppose it would be good to have a command-line option to set the signal number, though it would be a little tricky to implement. Or we can try to tolerate applications using the same signal as rr...

**Comment by khuey** [comment]
Resolved by cd145d1e904c8b7ddd85725b8bf1240a087a429e. There's now a `--syscall-buffer-sig` argument that allows replacing rr's internal usage of `SIGPWR` with another signal.
