### ISSUE TITLE
Moving whole documentation from github wiki to repo

### ISSUE THREAD

**Issue by mkmodrzew** [mozilla/rr#2297]
I found it quite troublesome to inform about changes I made in https://github.com/mozilla/rr/wiki/Building-And-Installing. Due to that no one saw them there was no chance to correct me before adding them, and in consequence I changed one thing to much and text was wrong about building test suite. Now I fixed that, but wouldn't it be better to move all the texts in wiki to the repo under `doc` directory? This way those text would be checked in code review as the any other file in the project. If you would find it helpful I could do that.

**Comment by rocallahan** [comment]
I prefer the lower-touch wiki process. If I was really worried about edits to the wiki I would set up something to notify when the wiki changed, but in the history of rr I can't remember ever being annoyed by a wiki edit, so it's probably not worth it. Thanks for the heads up and for the documentation update though!
