### ISSUE TITLE
gdbgui --rr crashes if there is no previous recording

### ISSUE THREAD

**Issue by bergercookie** [mozilla/rr#2298]
Without having recorded something in advance (`rr record`) gdbgui just crashes on startup:

```
set breakpoint pending on
The underlying gdb process has been killed. This tab will no longer function as expected.
Error occurred on server when running gdb command: gdb is not running
```

Obviously such usage is not advised and that's something an experienced `gdb`, `rr` user wouldn't do, but may discourage new users who would like to use this functionality.

P.S. Thanks for this amazing tool.

**Comment by rocallahan** [comment]
What exactly are you doing to start gdbgui with rr, and are you sure this is an rr bug not a gdbgui bug?

**Comment by bergercookie** [comment]
> What exactly are you doing to start gdbgui with rr

I'm just using `gdbgui --rr`

**Comment by rocallahan** [comment]
If gdbgui is crashing then I'd suspect this is a bug in gdbgui first :-)

**Comment by bergercookie** [comment]
Apologies, wrong project.
