### ISSUE TITLE
Potential incompatibility with new io_uring kernel AIO API

### ISSUE THREAD

**Issue by hotsphink** [mozilla/rr#2324]
I was just reading https://lwn.net/Articles/776703/ and it struck me that this would probably break rr, at least with the no-syscall variants. Not an issue right now, just a heads up. (And I may be wrong.)

**Comment by rocallahan** [comment]
You're right, all kernel<->user shared-mem ringbuffers are incompatible with rr. Forcing the syscall to return ENOSYS would be one option for blocking it.

**Comment by khuey** [comment]
Lets dupe this forward to #2613.
