### ISSUE TITLE
Unable to launch asan firefox

### ISSUE THREAD

**Issue by jschwartzentruber** [mozilla/rr#2329]
I'm not able to launch firefox nightly asan builds under rr (fde5e5e0)

The process is created, but no window ever appears. It seems to be hung up in mutex acquisition:

    #0 0x7f5e6ec3f11f  (/usr/bin/../lib64/rr/librrpreload.so+0x2511f)
    #1 0x7f5e6b287325 in sqlite3_mutex_enter /builds/worker/workspace/build/src/db/sqlite3/src/sqlite3.c:25105:5
    #2 0x7f5e6b287325 in sqlite3_initialize /builds/worker/workspace/build/src/db/sqlite3/src/sqlite3.c:153884
    #3 0x7f5e60ff3f7d in AutoSQLiteLifetime /builds/worker/workspace/build/src/toolkit/xre/AutoSQLiteLifetime.cpp:141:15
    #4 0x7f5e60ff3f7d in BootstrapImpl /builds/worker/workspace/build/src/toolkit/xre/Bootstrap.cpp:20
    #5 0x7f5e60ff3f7d in XRE_GetBootstrap /builds/worker/workspace/build/src/toolkit/xre/Bootstrap.cpp:99
    #6 0x557f3c94ec28 in mozilla::GetBootstrap(char const*) /builds/worker/workspace/build/src/xpcom/glue/standalone/nsXPCOMGlue.cpp:369:3
    #7 0x557f3c94da34 in InitXPCOMGlue() /builds/worker/workspace/build/src/browser/app/nsBrowserApp.cpp:224:16
    #8 0x557f3c94cf0e in main /builds/worker/workspace/build/src/browser/app/nsBrowserApp.cpp:282:17

When I try an --enable-fuzzing asan build, I get a different backtrace in another mutex:

    #0 0x7f0b51ff111f  (/usr/bin/../lib64/rr/librrpreload.so+0x2511f)
    #1 0x7f0b4edd07bd in PR_Lock /builds/worker/workspace/build/src/nsprpub/pr/src/pthreads/ptsynch.c:171:10
    #2 0x7f0b4eda67ed in PR_GetEnv /builds/worker/workspace/build/src/nsprpub/pr/src/misc/prenv.c:67:5
    #3 0x7f0b4ed75122 in _PR_InitFdCache /builds/worker/workspace/build/src/nsprpub/pr/src/io/prfdcach.c:179:23
    #4 0x7f0b4edc00c1 in _PR_InitIO /builds/worker/workspace/build/src/nsprpub/pr/src/pthreads/ptio.c:1138:5
    #5 0x7f0b4eda7ec9 in _PR_InitStuff /builds/worker/workspace/build/src/nsprpub/pr/src/misc/prinit.c:202:5
    #6 0x7f0b4eda7ec9 in _PR_ImplicitInitialization /builds/worker/workspace/build/src/nsprpub/pr/src/misc/prinit.c:219
    #7 0x7f0b4eda8fdc in PR_IntervalNow /builds/worker/workspace/build/src/nsprpub/pr/src/misc/prinrval.c:37:27
    #8 0x7f0b332c4acb in __cxx_global_var_init /builds/worker/workspace/build/src/tools/fuzzing/common/FuzzingTraits.cpp:31:36
    #9 0x7f0b332c4acb in _GLOBAL__sub_I_FuzzingTraits.cpp /builds/worker/workspace/build/src/tools/fuzzing/common/FuzzingTraits.cpp
    #10 0x7f0b5200e549 in call_init.part.0 (/lib64/ld-linux-x86-64.so.2+0x10549)
    #11 0x7f0b5200e649 in _dl_init (/lib64/ld-linux-x86-64.so.2+0x10649)
    #12 0x7f0b52012532 in dl_open_worker (/lib64/ld-linux-x86-64.so.2+0x14532)
    #13 0x7f0b51baff56 in __GI__dl_catch_exception (/usr/lib/libc.so.6+0x137f56)
    #14 0x7f0b52011dfe in _dl_open (/lib64/ld-linux-x86-64.so.2+0x13dfe)
    #15 0x7f0b51c59159 in __asprintf (/usr/lib/libdl.so.2+0x1159)
    #16 0x7f0b51baff56 in __GI__dl_catch_exception (/usr/lib/libc.so.6+0x137f56)
    #17 0x7f0b51bafff2 in __GI__dl_catch_error (/usr/lib/libc.so.6+0x137ff2)
    #18 0x7f0b51c598be  (/usr/lib/libdl.so.2+0x18be)
    #19 0x7f0b51c591f9 in dlopen (/usr/lib/libdl.so.2+0x11f9)
    #20 0x55d6ed32f9b7 in __interceptor_dlopen /builds/worker/workspace/moz-toolchain/src/llvm/projects/compiler-rt/lib/asan/../sanitizer_common/sanitizer_common_interceptors.inc:5919:15
    #21 0x55d6ed394f43 in GetLibHandle /builds/worker/workspace/build/src/xpcom/glue/standalone/nsXPCOMGlue.cpp:85:29
    #22 0x55d6ed394f43 in ReadDependentCB /builds/worker/workspace/build/src/xpcom/glue/standalone/nsXPCOMGlue.cpp:130
    #23 0x55d6ed394f43 in XPCOMGlueLoad /builds/worker/workspace/build/src/xpcom/glue/standalone/nsXPCOMGlue.cpp:291
    #24 0x55d6ed394f43 in mozilla::GetBootstrap(char const*) /builds/worker/workspace/build/src/xpcom/glue/standalone/nsXPCOMGlue.cpp:358
    #25 0x55d6ed393ef4 in InitXPCOMGlue() /builds/worker/workspace/build/src/browser/app/nsBrowserApp.cpp:224:16
    #26 0x55d6ed393365 in main /builds/worker/workspace/build/src/browser/app/nsBrowserApp.cpp:282:17

I'm using [ffpuppet --rr](https://github.com/MozillaSecurity/ffpuppet) to launch. Arch linux 4.20.5
```
ASAN_OPTIONS=abort_on_error=false:\
allocator_may_return_null=true:\
check_initialization_order=true:\
detect_invalid_pointer_pairs=1:\
detect_leaks=false:\
disable_coredump=true:\
handle_abort=true:\
handle_sigbus=true:\
handle_sigfpe=true:\
handle_sigill=true:\
log_path='/tmp/ffplogs_pvzmbrgk/ffp_asan_28306.log':\
malloc_context_size=20:\
sleep_before_dying=0:\
strict_init_order=true:\
symbolize=true
```

**Comment by rocallahan** [comment]
This shouldn't be too hard to debug. Is the thread stopped in a futex call? If so, what is the value at the futex, and where was that value set? (Use a hardware watchpoint to find out.)

**Comment by emilio** [comment]
I'm hitting this. Backtrace:

<details>

```
(rr) bt full
#0  0x000055cd82039050 in pthread_mutex_lock ()
#1  0x00007efeed38abcd in PR_Lock (lock=0x60f000000c70) at /home/emilio/src/moz/gecko-static-analysis/nsprpub/pr/src/pthreads/ptsynch.c:171
        rv = 32765
#2  0x00007efeed37f758 in PR_GetEnv (var=0x7efeed31d520 <str> "NSPR_FD_CACHE_SIZE_LOW") at /home/emilio/src/moz/gecko-static-analysis/nsprpub/pr/src/misc/prenv.c:67
        ev = 0x7ffd22b730a0 "\365P\267\"\375\177"
#3  0x00007efeed338644 in _PR_InitFdCache () at /home/emilio/src/moz/gecko-static-analysis/nsprpub/pr/src/io/prfdcach.c:179
        low = 0x18a0 <error: Cannot access memory at address 0x18a0>
        high = 0x60f000001990 ""
#4  0x00007efeed3b86f8 in _PR_InitIO () at /home/emilio/src/moz/gecko-static-analysis/nsprpub/pr/src/pthreads/ptio.c:1138
#5  0x00007efeed381b28 in _PR_InitStuff () at /home/emilio/src/moz/gecko-static-analysis/nsprpub/pr/src/misc/prinit.c:202
#6  0x00007efeed370119 in _PR_ImplicitInitialization () at /home/emilio/src/moz/gecko-static-analysis/nsprpub/pr/src/misc/prinit.c:219
#7  0x00007efeed387fcf in PR_IntervalNow () at /home/emilio/src/moz/gecko-static-analysis/nsprpub/pr/src/misc/prinrval.c:37
#8  0x00007efee01c47d9 in __cxx_global_var_init() () at /home/emilio/src/moz/gecko-static-analysis/tools/fuzzing/common/FuzzingTraits.cpp:31
#9  0x00007efee01c4805 in _GLOBAL__sub_I__ () at /usr/bin/../lib/gcc/x86_64-redhat-linux/9/../../../../include/c++/9/bits/uniform_int_dist.h:173
#10 0x00007efef08aa14a in call_init.part () at /lib64/ld-linux-x86-64.so.2
#11 0x00007efef08aa251 in _dl_init () at /lib64/ld-linux-x86-64.so.2
#12 0x00007efef08ae19f in dl_open_worker () at /lib64/ld-linux-x86-64.so.2
#13 0x00007efef0421ce9 in _dl_catch_exception () at /lib64/libc.so.6
#14 0x00007efef08ada0e in _dl_open () at /lib64/ld-linux-x86-64.so.2
#15 0x00007efef081539a in dlopen_doit () at /lib64/libdl.so.2
#16 0x00007efef0421ce9 in _dl_catch_exception () at /lib64/libc.so.6
#17 0x00007efef0421d83 in _dl_catch_error () at /lib64/libc.so.6
#18 0x00007efef0815b09 in _dlerror_run () at /lib64/libdl.so.2
#19 0x00007efef081543a in dlopen@@GLIBC_2.2.5 () at /lib64/libdl.so.2
#20 0x000055cd82054704 in __interceptor_dlopen.part.0 ()
#21 0x000055cd821418fa in GetLibHandle(char const*) (aDependentLib=0x7ffd22b70880 "/home/emilio/src/moz/gecko-static-analysis/obj-x86_64-pc-linux-gnu/dist/bin/libxul.so")
    at /home/emilio/src/moz/gecko-static-analysis/xpcom/glue/standalone/nsXPCOMGlue.cpp:86
        libHandle = 0x61a00001b680
#22 0x000055cd8214174e in ReadDependentCB(char const*) (aDependentLib=0x7ffd22b70880 "/home/emilio/src/moz/gecko-static-analysis/obj-x86_64-pc-linux-gnu/dist/bin/libxul.so")
    at /home/emilio/src/moz/gecko-static-analysis/xpcom/glue/standalone/nsXPCOMGlue.cpp:131
        libHandle = 0x0
#23 0x000055cd821415dc in XPCOMGlueLoad(char const*) (aXPCOMFile=0x6080000000a0 "/home/emilio/src/moz/gecko-static-analysis/obj-x86_64-pc-linux-gnu/dist/bin/libxul.so")
    at /home/emilio/src/moz/gecko-static-analysis/xpcom/glue/standalone/nsXPCOMGlue.cpp:299
        l = 10
        xpcomDir = "/home/emilio/src/moz/gecko-static-analysis/obj-x86_64-pc-linux-gnu/dist/bin/libxul.so\000and.so\000t", '\000' <repeats 1890 times>...
        flist = {mValue = 0x616000000080, _mCheckNotUsedAsTemporary = {mStatementDone = true}}
        buffer = "libxul.so\000\000nd.so\000\000td\006\000\000\000@\032\267\"\375\177\000\000\320\031\267\"\375\177\000\000r\371\023\202\315U\000\000\000\000\000\000\000\000\000\000`\032\267\"\375\177\000\000\360\031\267\"\375\177\000\000r\371\023\202\315U\000\000\340+\267\"\375\177\000\000 \000\000\000\200`\000\000`\032\267\"\375\177\000\000\340+\267\"\375\177\000\000\340,\267\"\375\177\000\000\340+\267\"\375\177\000\000`\032\267\"\375\177\000\000\340,\267\"\375\177\000\000\060\032\267\"\375\177\000\000\"\371\023\202\315U\000\000@\032\267\"\375\177\000\000`\032\267\"\375\177\000\000\340,\267\"\375\177\000\000\340+\267\"\375\177\000\000`\032\267\"\375\177\000\000"...
        lastSlash = 0x6080000000eb "/libxul.so"
        cursor = 0x7ffd22b708cc "libxul.so"
#24 0x000055cd82140df4 in mozilla::GetBootstrap(char const*) (aXPCOMFile=0x608000000020 "/home/emilio/src/moz/gecko-static-analysis/obj-x86_64-pc-linux-gnu/dist/bin/firefox")
    at /home/emilio/src/moz/gecko-static-analysis/xpcom/glue/standalone/nsXPCOMGlue.cpp:366
        file = [(char *) 0x6080000000a0 "/home/emilio/src/moz/gecko-static-analysis/obj-x86_64-pc-linux-gnu/dist/bin/libxul.so"]
        b = [(mozilla::Bootstrap *) 0x7ffd22b72a40]
        lastSlash = 0x60800000006b "/firefox"
        base_len = 76
        func = 0xb65afd525fc
#25 0x000055cd8213d757 in InitXPCOMGlue() () at /home/emilio/src/moz/gecko-static-analysis/browser/app/nsBrowserApp.cpp:224
        exePath = [(char *) 0x608000000020 "/home/emilio/src/moz/gecko-static-analysis/obj-x86_64-pc-linux-gnu/dist/bin/firefox"]
#26 0x000055cd8213d27a in main(int, char**, char**) (argc=4, argv=0x7ffd22b73078, envp=0x7ffd22b730a0) at /home/emilio/src/moz/gecko-static-analysis/browser/app/nsBrowserApp.cpp:282
        start = {mValue = {mUsedCanonicalNow = 0, mTimeStamp = 6265684847615}}
        rv = 582430544
        result = 0
```

</details>

This is the only thread alive. Mutex looks like:

```
$1 = {__data = {__lock = 0, __count = 0, __owner = 0, __nusers = 0, __kind = 3, __spins = 0, __elision = 0, __list = {__prev = 0x0, __next = 0x0}},
  __size = '\000' <repeats 16 times>, "\003", '\000' <repeats 22 times>, __align = 0}
```

Reverse-continuing seems stuck there. But seems like it's the static FuzzingTraits initialization which is causing this to go badly, so I can probably workaround this for now.

**Comment by emilio** [comment]
The lock right after being created looks like the same:

```
(rr) p lock->mutex
                  $4 = {__data = {__lock = 0, __count = 0, __owner = 0, __nusers = 0, __kind = 3, __spins = 0, __elision = 0, __list = {__prev = 0x0, __next = 0x0}},
  __size = '\000' <repeats 16 times>, "\003", '\000' <repeats 22 times>, __align = 0}
```

**Comment by emilio** [comment]
Yeah, I thought I could workaround it by removing the static initializers that end up calling into pthreads, but nope, next hang is at:

```
(rr) bt
#0  0x00007fadb0ec8e34 in pthread_mutex_lock (mutex=0x7fadad48f620 <pthreadMutexAlloc.staticMutexes>) at /home/emilio/src/moz/rr/src/preload/overrides.c:49
#1  0x00007fadad105ef7 in pthreadMutexEnter (p=0x7fadad48f620 <pthreadMutexAlloc.staticMutexes>) at /home/emilio/src/moz/gecko-static-analysis/db/sqlite3/src/sqlite3.c:25649
#2  0x00007fadad0a940b in sqlite3_mutex_enter (p=0x7fadad48f620 <pthreadMutexAlloc.staticMutexes>) at /home/emilio/src/moz/gecko-static-analysis/db/sqlite3/src/sqlite3.c:25104
#3  0x00007fadad0ac7a4 in sqlite3_initialize () at /home/emilio/src/moz/gecko-static-analysis/db/sqlite3/src/sqlite3.c:153872
#4  0x00007fada06439e9 in mozilla::AutoSQLiteLifetime::AutoSQLiteLifetime() (this=0x602000000ed8) at /home/emilio/src/moz/gecko-static-analysis/toolkit/xre/AutoSQLiteLifetime.cpp:141
#5  0x00007fada0643f07 in mozilla::BootstrapImpl::BootstrapImpl() (this=0x602000000ed0) at /home/emilio/src/moz/gecko-static-analysis/toolkit/xre/Bootstrap.cpp:20
#6  0x00007fada0643d0e in XRE_GetBootstrap(mozilla::Bootstrap::UniquePtr&) (b=[(class mozilla::Bootstrap *) 0x0]) at /home/emilio/src/moz/gecko-static-analysis/toolkit/xre/Bootstrap.cpp:99
#7  0x0000556dbf453ebc in mozilla::GetBootstrap(char const*) (aXPCOMFile=0x608000000020 "/home/emilio/src/moz/gecko-static-analysis/obj-x86_64-pc-linux-gnu/dist/bin/firefox")
    at /home/emilio/src/moz/gecko-static-analysis/xpcom/glue/standalone/nsXPCOMGlue.cpp:377
#8  0x0000556dbf450757 in InitXPCOMGlue() () at /home/emilio/src/moz/gecko-static-analysis/browser/app/nsBrowserApp.cpp:224
#9  0x0000556dbf45027a in main(int, char**, char**) (argc=4, argv=0x7ffe478f3068, envp=0x7ffe478f3090) at /home/emilio/src/moz/gecko-static-analysis/browser/app/nsBrowserApp.cpp:282
```

And I'm out of ideas then :)

**Comment by emilio** [comment]
That mutex's `kind` looks a bit different:

```
(rr) p mutex
$2 = (pthread_mutex_t *) 0x7fadad48f620 <pthreadMutexAlloc.staticMutexes>
(rr) p *mutex
$3 = {__data = {__lock = 0, __count = 0, __owner = 0, __nusers = 0, __kind = 0, __spins = 0, __elision = 0, __list = {__prev = 0x0, __next = 0x0}}, __size = '\000' <repeats 39 times>, 
  __align = 0}
```

**Comment by emilio** [comment]
Looks like ASAN also hooks into pthread_mutex_lock, but they don't seem to be doing anything particularly worrysome.

**Comment by emilio** [comment]
Here's the output of rr dump. I stopped firefox by Ctrl+C-ing it (so SIGINT): [dump.txt](https://github.com/mozilla/rr/files/2972225/dump.txt)

Not quite sure what's going on there, there's a single futex syscall as expected, but there's a whole lot of stuff going on afterwards that I don't really understand...

**Comment by rocallahan** [comment]
Recording and replaying a simple pthreads example with ASAN works fine.

Can you give me a link to a build that's failing?

**Comment by emilio** [comment]
The following (taken from taskcluster) reproduces the issue for me:

  https://queue.taskcluster.net/v1/task/CRB5IrmMQ5KRIE63eYBMrQ/runs/0/artifacts/public/build/target.tar.bz2

If you need a mozconfig, this is mine:

```
ac_add_options --disable-optimize
ac_add_options --enable-debug
ac_add_options --enable-fuzzing

# ASan
ac_add_options --enable-address-sanitizer
ac_add_options --disable-jemalloc
ac_add_options --disable-crashreporter
ac_add_options --disable-elf-hack
export CFLAGS="-fsanitize=address -Dxmalloc=myxmalloc -fPIC"
export CXXFLAGS="-fsanitize=address -Dxmalloc=myxmalloc -fPIC"
export LDFLAGS="-fsanitize=address"
```

**Comment by rocallahan** [comment]
Thanks.

This is rr's interception of `pthread_mutex_lock` interacting badly with ASAN's interception of `pthread_mutex_lock`.

`librrpreload.so` overrides `pthread_mutex_lock` to call `fix_mutex_kind` and then tail-call to `__pthread_mutex_lock`, normally defined by `libpthread`. However ASAN has intercepted `__pthread_mutex_lock` like so:
```
#if SANITIZER_INTERCEPT___PTHREAD_MUTEX
INTERCEPTOR(int, __pthread_mutex_lock, void *m) {
  return WRAP(pthread_mutex_lock)(m);
}
```
(as of LLVM commit https://github.com/llvm-project/llvm-project-20170507/commit/0a6efb6b61cba4040646e634c89c81ce38512d4d)

As you can see ASAN's wrapper delegates to the real `pthread_mutex_lock` (no leading `__`), which is our function. So there's an infinite loop of tail calls; no stack blowout, but the app effectively hangs.

**Comment by rocallahan** [comment]
I'm not 100% sure but I think ASAN's interceptor should be calling `WRAP(__pthread_mutex_lock)` there.

**Comment by rocallahan** [comment]
Filed https://bugs.llvm.org/show_bug.cgi?id=41095 though we probably need to figure out a better approach that is robust to this kind of behaviour.
