### ISSUE TITLE
Starting/stopping tracing from the application

### ISSUE THREAD

**Issue by pwaller** [mozilla/rr#2341]
Hi There! First off, thanks for bringing this awe-inspiring tool to the world.

I've done my best to scan the issue tracker, wiki and technical report to see if my question is answered there, but I didn't find a straightforward answer.

#### My high level use case is this:

I want to look at execution traces leading up to stack corruption. What I think I'd like to be able to get is the output of `rr rerun --singlestep=ip | sed 's/rip://' | addr2line -afp -e <binary>` so I can just see the log of executed instructions/functions/line numbers for a bit, to help me understand what my application is doing.

I can do this today just fine, but unfortunately the logs leading up to the crash can be quite large, so `rr rerun` can take a while before it gets to the section of interest. In particular, my program does a lot of "startup" that I would like to skip over.

#### My ask:

Is it possible to have the debuggee signal the start point of a record or region of interest, and signal when to finish the trace? 

Another possibility would be to say "I'd like to just dump the trace with rerun from when this instruction is hit, and then stop once this other instruction is hit". And for the performance of this to scale as a function of the instructions in the window of interest (and not as a function of the amount of execution happening in the startup).

If either of these things are possible, it seems like it would make my current workflow easier. Of course, my current workflow might be non-optimal and I'd appreciate any hints you can give at improving it.

#### Other thoughts

* [There is a section "Dump a trace event or range of events"](https://github.com/mozilla/rr/wiki/Debugging-protips#dump-a-trace-event-or-range-of-events) on the Wiki, but I can't figure out how it relates to what I'm asking. One thought I have is that maybe I can generate an event, and then use that event to achieve the desired effect, perhaps.

* There are the options to `rr rerun`: `--trace-start=` and `--trace-end=EVENT` which obviously sound like what I want, but I can't figure out how to specify an `<EVENT>` - same problem as the above bullet point.

* Restricting the trace with `rr rerun` would be fine - but presumably there is an overhead to recording the instructions outside the window of interest. Is it possible to avoid recording them?

Thanks for reading :)

**Comment by rocallahan** [comment]
`rr replay -a -M` will replay and dump event numbers alongside all output to stdout/stderr. That should help you choose an event range for tracing.

**Comment by pwaller** [comment]
That is a useful trick, thanks!

Now that I know what I'm looking for, I found it mentioned under ["debugging a recording"](https://github.com/mozilla/rr/wiki/Usage#debugging-a-recording), and I did read this before but didn't quite catch its significance for my use-case.

The `-M,--mark-stdio` flag has very little "pointing at it" in the documentation which would make you realize that you should use it to make an event number to start from, if you're looking at "events".

I note also that there fairly little documentation on `rerun` (it's not mentioned on the usage page) and `rerun --function` is a opaque to me from the doc string. It sounds interesting but I don't follow what it does or when would be an appropriate time to use it.

I would still like to be able to specify a function or address to break on, since I don't want to put stdio at each point that I might trace. Fair enough if I have to make do with the preceding event as a trace start point.

I found my way to [the "when" command](https://github.com/mozilla/rr/wiki/Usage#the-when-command), which sounds like I ought to be able to use it to choose a trace point according to a function name, but if I try to use it programmatically with `rr replay -o -ex`, I get:

```
$ rr replay -o -batch -o -ex="break myfunction" -o -ex="r" -o -ex="when"
Really redefine built-in command "restart"? (y or n) [answered Y; input not from terminal]
Breakpoint 1 at 0x40b79b: file src/myfunction.c, line 801.

Breakpoint 1, myfunction () at src/myfunction.c:801

Traceback (most recent call last):
  File "<string>", line 51, in invoke
  File "<string>", line 60, in rr_cmd
gdb.error: command can only be used with remote target
Error occurred in Python command: command can only be used with remote target
0x0000000000400a40 in _start ()
```

I also get this error when doing `--gdb-x` on a file containing those three commands (break; run; when).

**Comment by rocallahan** [comment]
> rr replay -o -batch -o -ex="break myfunction" -o -ex="r" -o -ex="when"

Don't use "run" here. When rr starts the target is already running. Use "continue" instead.

**Comment by pwaller** [comment]
I still get the same error ("gdb.error: command can only be used with remote target") with continue rather than run.

**Comment by rocallahan** [comment]
ok. I think you might just have to pipe those commands into gdb rather than run them on the command line.

**Comment by pwaller** [comment]
Piping does work, and I was able to solve my problem. Happy to close the issue unless you want to keep it open as a reminder for some minor documentation improvements.

**Comment by rocallahan** [comment]
You're welcome!
