### ISSUE TITLE
Build system: avoid overriding external flags

### ISSUE THREAD

**Issue by daurnimator** [mozilla/rr#2344]
Currently CMakeLists specifies the optimisation level and debug level, overriding a user's own settings.

Patch available [here](https://aur.archlinux.org/cgit/aur.git/tree/0001-avoid-overriding-external-opt-debug-flags.patch?h=rr)

**Comment by rocallahan** [comment]
Won't this patch regress users who won't set their own settings?

**Comment by daurnimator** [comment]
A better solution might be to only set them for particular build types, e.g.
```
set(CMAKE_CXX_FLAGS_RELEASE "${CMAKE_CXX_FLAGS_RELEASE} -O2")
```

**Comment by rocallahan** [comment]
How come that isn't a problem for you but the existing code is?

**Comment by daurnimator** [comment]
> How come that isn't a problem for you but the existing code is?

Arch uses the "plain" or "none" build type and provides all its own flags. See https://wiki.archlinux.org/index.php/Makepkg#CFLAGS.2FCXXFLAGS.2FLDFLAGS_in_makepkg.conf_do_not_work_for_CMake_based_packages for the packaging advice.

**Comment by rocallahan** [comment]
I see. Hmm.

**Comment by rocallahan** [comment]
It's a little bit tricky because we really need to build librrpreload with debuginfo no matter what. And you kind of want to build it with optimizations usually too.

**Comment by rocallahan** [comment]
One specific problem with your patch is that it means librrpreload's .c and .S files don't necessarily build with debuginfo. If they're built without debuginfo then users won't be able to get backtraces in rr when the application is stopped at a system call, which is very common. So I think we actually do need -g3 in CMAKE_ASM_FLAGS, and somewhere else too.

**Comment by rocallahan** [comment]
Tell me what you think of this patch.
[patch.txt](https://github.com/mozilla/rr/files/3130052/patch.txt)

**Comment by daurnimator** [comment]
If the user selects e.g. Release, then doesn't cmake add the relevant optimisation flags *for* you?

**Comment by rocallahan** [comment]
Yes, that simplifies things a bit.
[patch.txt](https://github.com/mozilla/rr/files/3130103/patch.txt)

**Comment by daurnimator** [comment]
Seems sensible for now I think. I haven't tested it myself though.

**Comment by rocallahan** [comment]
OK, I checked it in.
