### ISSUE TITLE
Failure to read from AFS when file is not cached

### ISSUE THREAD

**Issue by zhidvegi** [mozilla/rr#2353]
I have a rather obscure bug, when recording an program that reads a file from AFS that is not yet cached, the read will return EOF as if the file had 0 length. This happens on RHEL7.4, kernel:
Linux version 3.10.0-693.2.2.el7.x86_64 (mockbuild@x86-039.build.eng.bos.redhat.com) (gcc version 4.8.5 20150623 (Red Hat 4.8.5-16) (GCC) ) #1 SMP Sat Sep 9 03:55:24 EDT 2017
kernel-module-openafs-1.6.22.1-1_3.10.0_693.2.2.el7.x86_64
The code I'm running that shows the issue:

~~~~
#include <stdio.h>

int main(int argc, char *argv[])
{
    unsigned long nl = 0;
    long ch;
    FILE *fp = argc > 1 ? fopen(argv[1], "r") : stdin;
    if (!fp) {
        fprintf(stderr, "Cannor open file\n");
        return 0;
    }
    while ((ch = getc(fp)) != EOF)
        nl += ch == '\n';
    printf("Num lines: %lu\n", nl);
    return 0;
}
~~~~
And when I run it looks like this, showing two consecutive runs, the second works since the file is cached:
~~~~
-bash-4.2$ rr record ~/c/getctest ~/c/newnd.log
rr: Saving execution to trace directory `<redacted>/.local/share/rr/getctest-2'.
Num lines: 0
-bash-4.2$ rr record ~/c/getctest ~/c/newnd.log
rr: Saving execution to trace directory `<redacted>/.local/share/rr/getctest-3'.
Num lines: 14002
-bash-4.2$ ls -al ~/c/newnd.log
-rw-r--r-- 1 30304 bin 663226 Nov 14  2005 <redacted>/c/newnd.log
~~~~

**Comment by rocallahan** [comment]
Does the problem reproduce if you do `rr record -n ...`?

**Comment by zhidvegi** [comment]
No, it does not happen with rr record -n

**Comment by rocallahan** [comment]
The problem is most likely related to signal handling in AFS. Without `-n`, I assume `read()` of a non-cached file blocks in our syscallbuf code. rr configures things so that when a syscall blocks in syscallbuf, a signal is raised immediately (so that rr can schedule another thread) and then the syscall is restarted. It wouldn't surprise me at all if AFS doesn't handle this correctly.

**Comment by rocallahan** [comment]
One way to test this would be to modify your example program so that while you open and read the file, another process bombards the main process with signals (e.g. SIGCHLD) that have a no-op signal handler.

**Comment by zhidvegi** [comment]
Indeed, I've been able to trigger that doing what you've suggested. So I guess this is really a bug in AFS.
