### ISSUE TITLE
Execution difference

### ISSUE THREAD

**Issue by Hi-Angel** [mozilla/rr#2375]
Would be great if `rr` was able to give a human-readable difference of 2 execution traces *(e.g. in terms of assembly commands, or whatever — doesn't matter. If `rr` internally just store machine commands, that would be useful nevertheless — one could use e.g. radare2 to convert that to assembly)*.

The upshot is that some bugs are triggered sporadically, and comparing differences between a "problem run" and "good run" would speed up debugging by a lot.

**Comment by khuey** [comment]
Going to dupe this to #2366
