### ISSUE TITLE
rr receives app's SIGABRT and crashes without writing log

### ISSUE THREAD

**Issue by harjoc** [mozilla/rr#2377]
I am trying to record an app which crashes using SIGABRT, and rr replay reports that the log is incomplete.

abort() is actually kill(0, SIGABRT) which delivers the signal to all processes in the process group including rr. And 'rr record' results in a core file containing:

#0  ptrace (request=PTRACE_SYSCALL)
#1  in rr::Task::fallible_ptrace at rr/src/Task.cc:1980
...

Adding setpgid(0,0) right before run_initial_child() seems to work, i.e. the complete log is written. Should there be a rr flag that enables this ? Although it might prevent the recorded app from receiving CTRL-C and such.

**Comment by rocallahan** [comment]
This works fine for me. rr catches the SIGABRT, completes writing the trace file, and then sends SIGABRT to itself so any parent process sees the child exiting as expected.

What version of rr are you using?

**Comment by harjoc** [comment]
I'm testing with rr-master as of yesterday. Rr works fine for kill(getpid(), SIGABRT) but catches the signal if sent using kill(0, SIGABRT), resulting in an incomplete trace. My mistake earlier for stating that abort() from libc results in kill(0, SIGABRT). I'm using a custom abort() macro.

**Comment by rocallahan** [comment]
Ah OK.

**Comment by rocallahan** [comment]
I chose not to put the recorded child in its own process group, because it's common to use rr as a wrapper, in which case we want the child's SIGABRT to abort the process that invoked rr. Ignoring the signal lets us terminate the recording cleanly while still allowing the signal to affect the whole process group.
