### ISSUE TITLE
rr catches assert/sigabrt twice on reverse-continue

### ISSUE THREAD

**Issue by milianw** [mozilla/rr#2380]
the below shows unexpected behavior that is confusing for novices:

```
$ cat test.c 
#include <assert.h>

int main()
{
    assert(0);
    return 0;
}
$ gcc -g -O0 test.c
$ rr record ./a.out
...
$ rr replay
...
(rr) c
Continuing.
a.out: test.c:5: main: Assertion `0' failed.

Program received signal SIGABRT, Aborted.
0x00007f945337d755 in raise () from /usr/lib/libc.so.6
```

As expected, we got to the assert. But continuing in reverse triggers SIGABRT again, which is unexpected:

```
(rr) reverse-continue 
Continuing.

Program received signal SIGABRT, Aborted.
0x00007f945337d755 in raise () from /usr/lib/libc.so.6
```

continuing once more goes to the start as expected:

```
(rr) 
Continuing.

Program stopped.
0x00007f9453587100 in _start () from /lib64/ld-linux-x86-64.so.2
```

**Comment by rocallahan** [comment]
Unfortunately this is the only reasonable way to do it. gdb reports a signal after it has been delivered. Therefore during reverse execution we have to go back through the signal delivery and report it again.
