### ISSUE TITLE
rr trace is incomplete after SIGABRT

### ISSUE THREAD

**Issue by earthling** [mozilla/rr#2382]
On the surface, this looks similar to [2377](https://github.com/mozilla/rr/issues/2377), but in this case our application aborts with a plain old call to abort in the stdlib.
```
rr version: 5.2.0
kernel: 4.15.0-55-generic #60-Ubuntu SMP
distro: ubuntu 18.04
```
I'm using a python (3.6) script to repeatedly drive rr on a workload that sometimes exits after tripping an assert. The application in this case is the openjdk running the dacapo benchmark suite. It sometimes takes days for the assert to trip so it's quite sad to find an incomplete rr trace. When the application exits normally a usable trace is produced. If it exits with an abort (for example, using the development flag -XX:+CrashGCForDumpingJavaThread), it produces a usable trace. But in cases where the workload has been run repeatedly and ultimately asserts out, the trace is incomplete (although a core file is still produced).

At first, I thought the incomplete trace may have been caused by a [known issue](https://bugs.python.org/issue25942) with the [subprocess module](https://docs.python.org/3.6/library/subprocess.html), but I'm running rr with a function that does _not_ SIGKILL anything, ever. Does rr need to run in a shell? Does rr have an internal log somewhere? What can I do to help trouble shoot this? I need my traces!

Thanks.

**Comment by khuey** [comment]
Does it happen on master?

**Comment by earthling** [comment]
Let me get back to you on that...

**Comment by khuey** [comment]
Another thing that would be useful to know is whether it is the thing rr is recording that calls `abort(3)` or something else.

**Comment by earthling** [comment]
I'm certain the thing being recorded calls abort - it produces a core file that confirms this.

**Comment by rocallahan** [comment]
If rr is being killed by a signal then the exit status of rr itself should tell you what that signal is, so check that.

You should definitely check if the fix for #2377 helps you. There might be some weird reason why the abort() call ends up targeting the process group.

You can enable rr logging with `RR_LOG=debug` or more fine-grained stuff like `RR_LOG=RecordCommand:debug` but I don't think that's going to help you if rr is just being killed by some signal.

**Comment by rocallahan** [comment]
If it is a stray signal then there are tools like https://manpages.ubuntu.com/manpages/disco/man8/killsnoop-bpfcc.8.html that might help you identify the signal and who's sending it.

**Comment by earthling** [comment]
In either case (incomplete trace or usable trace), the exit status of rr is 6 - which is consistent with SIGABRT. Are you expecting the traced process to have an exit status of 6, and rr itself to have an exit status of 0?

That killsnoop command looks great - thanks for that tip.

**Comment by rocallahan** [comment]
rr takes care to exit with the status of the tracee. So here, 6 isn't telling you anything.

**Comment by rocallahan** [comment]
(If it had exited with SIGKILL or something like that then that would have told us something.)

**Comment by earthling** [comment]
I was able to get a usable trace running the tip of master. Thanks!

**Comment by khuey** [comment]
Great! I'll go ahead and close this.
