### ISSUE TITLE
Clang installation instructions - minor instruction error (in wiki)

### ISSUE THREAD

**Issue by marcrepo** [mozilla/rr#2385]
### Wiki - First line of Clang build instructions are missing the "/rr" after the .. 

Wiki Page: https://github.com/mozilla/rr/wiki/Building-And-Installing

***Section: Project Building***

First line of Clang compilation instructions:
CC=clang CXX=clang++ cmake -G Ninja ..

I believe it should be:
CC=clang CXX=clang++ cmake -G Ninja ../rr

This is needed as the first set of build instructions create the _obj_ directory and then make it the default directory - so the clang compilation instructions are issued inside the _obj_ directory.

**Comment by rocallahan** [comment]
Yep thanks
