### ISSUE TITLE
delve randomly detaches from process

### ISSUE THREAD

**Issue by dasl-** [mozilla/rr#2388]
I am attaching delve to a process inside a docker container. Example: https://gist.github.com/dasl-/0752fc02e655ec4c342ea7da69c4b948

I am using the Goland IDE to connect to delve. 

Firstly, it is often very slow to load local variables / call stack: 
![delve1](https://user-images.githubusercontent.com/1332576/65465397-3030ad80-de2a-11e9-8f07-9797088dd6ad.png)

Secondly, sometimes delve randomly disconnects when it is in the process of loading a local variables at a given frame in the call stack. The delve process dies and I have to reattach it and start over.

**Comment by khuey** [comment]
Is this somehow specific to using delve with rr?

**Comment by dasl-** [comment]
sorry, opened the issue on the wrong project.
