### ISSUE TITLE
New release with python2 removed

### ISSUE THREAD

**Issue by bryteise** [mozilla/rr#2390]
Hello, it has been a bit since the last release and I was wondering if we could get another now that the python3 switch is completed?

**Comment by khuey** [comment]
Yeah we should do a new release. The bohem gc stack stuff is out of scope for now, and I'm not aware of any other rr issues outstanding. @rocallahan?

**Comment by khuey** [comment]
We might want to do a cursory investigation of #2389 first.

**Comment by jubalh** [comment]
A new release with Python 3 would be highly appreciated. So we can include rr to the openSUSE repositories.

**Comment by rocallahan** [comment]
Done, finally!
https://github.com/mozilla/rr/releases/tag/5.3.0
