### ISSUE TITLE
Make rr's gdbinit hooks generate code depending on language

### ISSUE THREAD

**Issue by alehander92** [mozilla/rr#2399]
Currently this can lead to warnings and errors in `pascal` mode of gdb because it expects `:=` instead of `=` : i can make a PR , but my idea would be to somehow test what `show language` is and generate different hooks based on that, not sure if this is the best approach .. on the other hand i wonder if its possible to have different lang source files in the same binary: it feels like yes, and then maybe a more granular approach would be needed (but probably doing it in each hook would be slow)

**Comment by rocallahan** [comment]
Can we have code (maybe in Python) that gets the current language, does `set lang c`, executes the expression, and then `set lang <old-language>`?

**Comment by alehander92** [comment]
i thought about that, but this needs to happen on each call to the hook: wouldn't this be a bit slow

**Comment by rocallahan** [comment]
Probably not.

**Comment by alehander92** [comment]
Ok, we can define hooks which call a python command to do it, I'll try to make a PR to `gdb_rr_macros` when i have time soon
