### ISSUE TITLE
Crash on replay from within gdb

### ISSUE THREAD

**Issue by bkin** [mozilla/rr#2409]
Using rr 5.2.0 from Ubuntu 18.04.2 LTS.

I am recording a successful run of an application with 'rr record X'. When I replay with 'rr replay' and then 'continue' from within gdb, I am getting a crash within a proprietary library for which I have neither source nor debug information.

I am not seeing the crash when I either replay with 'rr replay -a' or record with 'rr record -n'. In both cases, the replay is true to the original recording.

Given the proprietary nature of said library, I'm willing to fix the issue on my machine but I'd be glad for hints on where to start.

**Comment by rocallahan** [comment]
Let's start by looking at the console output you get when the crash happens?

**Comment by bkin** [comment]
Here is my gdb session

    (rr) c
    Continuing.
    found 'DEVELOPMENT' to be set to '1'
    found 'DATABASE' to be set to 'kbase/kbase@siph.dbhost-tps-01'
    found 'DB_CACHE' to be set to '1'
    found 'DB_CACHE_SERVERS' to be set to 'ws-tps-cbc-01'
    QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-bki'
    [New Thread 8245.8254]

    Thread 1 received signal SIGSEGV, Segmentation fault.
    0x00007fa58b7f82d5 in ?? () from /b/work/tps/cmake_builds/release/lib/libclntsh.so.11.1
    (rr) x/i 0x00007fa58b7f82d5
    => 0x7fa58b7f82d5:      movzbl (%rbx),%esi
    (rr) p $rbx
    $1 = 0
    (rr) when
    Current event: 39828
    (rr)

Curiously, I can 'rr replay -g 400000' (so way beyond where I am getting the crash) and if I do that, the session in gdb is also true to my original recording.

**Comment by rocallahan** [comment]
what happens if you continue after the segfault?

**Comment by rocallahan** [comment]
And, if you run with gdb without rr, do you encounter the same segfault?

**Comment by rocallahan** [comment]
Also if you run `when` after the segfault, and then inspect the rr trace with `rr dump -b -m -p`, looking for `time:<when>`, can you copy here the dump around that event?

**Comment by bkin** [comment]
I cannot continue after the segfault
If I run with 'gdb -args' instead of 'rr record', I don't see the same

**Comment by rocallahan** [comment]
What happens when you continue after the segfault?

**Comment by bkin** [comment]
Segfaults again

**Comment by bkin** [comment]
About the `rr dump`:

    {
      real_time:5533674.052694 global_time:39825, event:`SYSCALL: rt_sigaction' (state:EXITING_SYSCALL) tid:8245, ticks:507789700
    rax:0x0 rbx:0x681fffa0 rcx:0xffffffffffffffff rdx:0x0 rsi:0x7ffd2d8d3250 rdi:0xb rbp:0xd rsp:0x681ffe00 r8:0x0 r9:0x7ffd2d8d3590 r10:0x8 r11:0x246 r12:0x0 r13:0x17 r14:0x7ffd2d8d4fa0 r15:0x7ffd2d8d4ff0 rip:0x70000002 eflags:0x246 cs:0x33
     ss:0x2b ds:0x0 es:0x0 fs:0x0 gs:0x0 orig_rax:0xd fs_base:0x7fa594ae6780 gs_base:0x0
      { tid:8245, addr:0x7ffd2d8d3250, length:0x20 }
    }
    {
      real_time:5533674.052726 global_time:39826, event:`SYSCALLBUF_FLUSH' tid:8245, ticks:507789734
      { syscall:'rt_sigprocmask', ret:0x0, size:0x18 }
    }
    {
      real_time:5533674.052728 global_time:39827, event:`SIGNAL: SIGSEGV(det)' tid:8245, ticks:507789734
    rax:0x7fa58b7f82b5 rbx:0x0 rcx:0x0 rdx:0x7fa58bfff368 rsi:0x1 rdi:0x0 rbp:0x7ffd2d8d36b0 rsp:0x7ffd2d8d33a0 r8:0x0 r9:0x7ffd2d8d3590 r10:0x8 r11:0xe r12:0x0 r13:0x17 r14:0x7ffd2d8d4fa0 r15:0x7ffd2d8d4ff0 rip:0x7fa58b7f82d5 eflags:0x10246
     cs:0x33 ss:0x2b ds:0x0 es:0x0 fs:0x0 gs:0x0 orig_rax:0xffffffffffffffff fs_base:0x7fa594ae6780 gs_base:0x0
    }
    {
      real_time:5533674.052729 global_time:39828, event:`SYSCALLBUF_RESET' tid:8245, ticks:507789734
    }
    {
      real_time:5533674.052755 global_time:39829, event:`SIGNAL_HANDLER: SIGSEGV(det)' tid:8245, ticks:507789734
    rax:0x0 rbx:0x0 rcx:0x0 rdx:0x7ffd2d8d2d00 rsi:0x7ffd2d8d2e30 rdi:0xb rbp:0x7ffd2d8d36b0 rsp:0x7ffd2d8d2cf8 r8:0x0 r9:0x7ffd2d8d3590 r10:0x8 r11:0xe r12:0x0 r13:0x17 r14:0x7ffd2d8d4fa0 r15:0x7ffd2d8d4ff0 rip:0x7fa58b1d63f0 eflags:0x246 cs:0x33 ss:0x2b ds:0x0 es:0x0 fs:0x0 gs:0x0 orig_rax:0xffffffffffffffff fs_base:0x7fa594ae6780 gs_base:0x0 st0:0x0 st1:0x0 st2:0x0 st3:0x0 st4:0x0 st5:0x0 st6:0x0 st7:0x0 ymm0:0x0 ymm1:0x0 ymm2:0x0 ymm3:0x0 ymm4:0x0 ymm5:0x0 ymm6:0x0 ymm7:0x0 ymm8:0x0 ymm9:0x0 ymm10:0x0 ymm11:0x0 ymm12:0x0 ymm13:0x0 ymm14:0x0 ymm15:0x0
      { tid:8245, addr:0x7ffd2d8d2cf8, length:0x940 }
    }
    {
      real_time:5533674.052790 global_time:39830, event:`SYSCALLBUF_FLUSH' tid:8245, ticks:507792594
      { syscall:'rt_sigprocmask', ret:0x0, size:0x18 }
    }
    {
      real_time:5533674.052794 global_time:39831, event:`SYSCALL: rt_sigaction' (state:ENTERING_SYSCALL) tid:8245, ticks:507792594
    rax:0xffffffffffffffda rbx:0x681fffa0 rcx:0xffffffffffffffff rdx:0x0 rsi:0x7ffd2d8d3250 rdi:0x7 rbp:0xd rsp:0x681ffe00 r8:0x0 r9:0x7ffd2d8d36b0 r10:0x8 r11:0x246 r12:0x0 r13:0x17 r14:0x7ffd2d8d4fa0 r15:0x7ffd2d8d4ff0 rip:0x70000002 eflags:0x246 cs:0x33 ss:0x2b ds:0x0 es:0x0 fs:0x0 gs:0x0 orig_rax:0xd fs_base:0x7fa594ae6780 gs_base:0x0
    }
    {
      real_time:5533674.052795 global_time:39832, event:`SYSCALLBUF_RESET' tid:8245, ticks:507792594
    }

**Comment by rocallahan** [comment]
Does it segfault again at the same place? If you do `when` there, what's the new value? And if you keep continuing (possibly setting `handle SIGSEGV nostop`), do you get through them all?

**Comment by bkin** [comment]
I think I can also share the backtrace from when I see the crash:

    #0  0xXXX in slaac_int () from libclntsh.so.11.1
    #1  0xXXX in slrac () from libclntsh.so.11.1
    #2  0xXXX in unw_step () from libclntsh.so.11.1
    #3  0xXXX in skgdsgframe () from libclntsh.so.11.1
    #4  0xXXX in kgdsdsts_extra () from libclntsh.so.11.1
    #5  0xXXX in kgdsdsts () from libclntsh.so.11.1
    #6  0xXXX in dbgemdGetCallStackWFlag () from libclntsh.so.11.1
    #7  0xXXX in dbgemdGetCallStack () from libclntsh.so.11.1
    #8  0xXXX in dbgemdFillCompFunNames () from libclntsh.so.11.1
    #9  0xXXX in dbgemdFillIncCtx () from libclntsh.so.11.1
    #10 0xXXX in dbgexPopulateIncCtx () from libclntsh.so.11.1
    #11 0xXXX in dbgexProcessError () from libclntsh.so.11.1
    #12 0xXXX in dbgeExecuteForError () from libclntsh.so.11.1
    #13 0xXXX in dbgePostErrorKGE () from libclntsh.so.11.1
    #14 0xXXX in dbgc_dde () from libclntsh.so.11.1
    #15 0xXXX in kgeadse () from libclntsh.so.11.1
    #16 0xXXX in kgerinv_internal () from libclntsh.so.11.1
    #17 0xXXX in kgesoftnmierr () from libclntsh.so.11.1
    #18 0xXXX in dbgrfrbf_read_block_file () from libclntsh.so.11.1
    #19 0xXXX in dbgrmflrp_read_page () from libclntsh.so.11.1
    #20 0xXXX in dbgrmblgmp_get_many_pages () from libclntsh.so.11.1
    #21 0xXXX in dbgrmmdrrmd_read_relation_meta_data () from libclntsh.so.11.1
    #22 0xXXX in dbgrmmdora_open_record_access_full () from libclntsh.so.11.1
    #23 0xXXX in dbgriporc_openrel_wcreate () from libclntsh.so.11.1
    #24 0xXXX in dbgrip_open_relation_access () from libclntsh.so.11.1
    #25 0xXXX in dbgrip_start_iterator () from libclntsh.so.11.1
    #26 0xXXX in dbgrip_relation_iterator () from libclntsh.so.11.1
    #27 0xXXX in dbgruprac_read_adrctl () from libclntsh.so.11.1
    #28 0xXXX in dbgrsc_set_createid () from libclntsh.so.11.1
    #29 0xXXX in dbgrcas_create_adr_schema () from libclntsh.so.11.1
    #30 0xXXX in dbgraid_adr_init_disk () from libclntsh.so.11.1
    #31 0xXXX in dbgrcaod_check_adr_ondisk () from libclntsh.so.11.1
    #32 0xXXX in dbgrlWriteAlertDetail_int () from libclntsh.so.11.1
    #33 0xXXX in dbgrlWriteAlertDetail () from libclntsh.so.11.1
    #34 0xXXX in dbgrlWriteAlertText () from libclntsh.so.11.1
    #35 0xXXX in nlddwrtlog () from libclntsh.so.11.1
    #36 0xXXX in nldsadrvfp () from libclntsh.so.11.1
    #37 0xXXX in nldsfprintf () from libclntsh.so.11.1
    #38 0xXXX in kpeDbgInitError () from libclntsh.so.11.1
    #39 0xXXX in kpeDbgGetNPDGlobal () from libclntsh.so.11.1
    #40 0xXXX in kpeDbgTLSInit () from libclntsh.so.11.1
    #41 0xXXX in kpummTLSGET1 () from libclntsh.so.11.1
    #42 0xXXX in kpeDbgProcessInit () from libclntsh.so.11.1
    #43 0xXXX in kpummpin () from libclntsh.so.11.1
    #44 0xXXX in kpuenvcr () from libclntsh.so.11.1
    #45 0xXXX in OCIEnvCreate () from libclntsh.so.11.1

I believe most of this may be some sort of error handling due to something being wrong with TLSInit?!

**Comment by bkin** [comment]
Yes, segfaults are at the same place, but actually the event number given by `when` increases.

And yes, it eventually ends after I set handle SIGSEGV nostop and continue

**Comment by rocallahan** [comment]
OK! Sounds like rr is working fine.

**Comment by bkin** [comment]
So a gdb issue then?

**Comment by rocallahan** [comment]
You've recorded an execution which, for some reason, triggers SIGSEGV a number of times, but there is a signal handler set up that catches the signal and handles it somehow in a way that lets the execution continue. It certainly looks like `rr replay -a` and `rr replay` are correctly replaying what was recorded.

You just got confused because gdb, by default, stops at SIGSEGV and reports it, whether or not the signal is fatal. (You're not alone; Firefox uses a lot of SIGSYS signals with handlers, which gdb also stops for, and this confuses Mozilla developers using gdb with or without rr.)

The only thing that bothers me is that you say this doesn't happen with `rr record -n` or just running under gdb. That suggests that `rr record` with syscallbuf enabled is somehow triggering these segfaults, and that is worrying.

**Comment by rocallahan** [comment]
Since replay works, you could potentially use rr with reverse execution to debug the cause of the segfault, especially if you have the source code to that library, but possibly even if you don't.

OTOH, if the recording actually does what you want --- runs the right test, reproduces the right bug, etc --- then maybe you don't need to worry about it.

**Comment by bkin** [comment]
Oh, a custom signal handler, ok, that makes sense to me. And I did not know about `handle SIGSEGV nostop` before, so thanks about that as well.

Would it be helpful to compare 'rr dump' for recordings with and without '-n' in order to find out about the triggering of Segfaults?

**Comment by rocallahan** [comment]
gdb is full of useful features no-one knows about, which is why discoverability was a big goal for Pernosco :-).

Comparing `rr dump`s is not likely to be helpful.

One thing that would be interesting is figuring out how far down that stack an `rr record -n` run gets. E.g. does `kpeDbgInitError` get called with `rr record -n`?

**Comment by bkin** [comment]
I'll check what part of the stack `rr record -n` will touch. This might take a few minutes.

**Comment by bkin** [comment]
Where can I learn a bit more about how sycall buffering works in rr?

**Comment by rocallahan** [comment]
https://arxiv.org/pdf/1705.05937.pdf section 3

**Comment by bkin** [comment]
According to the output of `rr dump`, there are 51 different types of syscalls made before the SIGSEGV occurs. Could it be interesting to bisect on these? I could try to remove some of them from the library that rr injects to see which one causes the issue.

If I can obtain the library where the call to the stub is patched in from within rr, I could also try to blacklist my proprietary one and see if that helps.

**Comment by rocallahan** [comment]
You need to use `rr dump -b -m -p` and the syscallbuf'ed syscalls are the ones listed under the `SYSCALLBUF_FLUSH` events. Yes, I guess it might be interesting to know which syscall(s) cause problems, although that's labor-intensive enough I think
> One thing that would be interesting is figuring out how far down that stack an rr record -n run gets. E.g. does kpeDbgInitError get called with rr record -n?
Is more important.

**Comment by bkin** [comment]
Ok, I'll check that next.

**Comment by bkin** [comment]
It's getting up until `kpummTLSGET1` but not `kpeDbgTLSInit`

**Comment by rocallahan** [comment]
Is `kpeDbgTLSInit` called at all anywhere in the trace? especially, is it called earlier in the `rr record -n` trace?

If not ... I guess you could step through `kpummTLSGET1` in parallel in the two traces and figure out where the control flow is diverging.

**Comment by bkin** [comment]
I don't think it's called there, but I'll doublecheck. Thanks for now Rob, you've been super helpful, but the kids are coming home right now, all hope it lost for more debugging in the next few hours :-)
I'll get back to you

**Comment by rocallahan** [comment]
No problem. It's long past my bed-time here on the other side of the world so I'll leave you to it.

**Comment by bkin** [comment]
Just a quick status: The traces have more of that aforementioned stack in common than I though initially. Both reach `dbgrfrbf_read_block_file` before they diverge. I have then found a libc call to `__libc_pread64` of 16k bytes that returns -1 for the trace with the segfault and 16384 for the other one.
This is coming from an actual syscall instruction, not one intercepted by syscall buffering.

I'll continue along this route.

**Comment by bkin** [comment]
Sorry, __libc_pread64 was actually intercepted. I got a bit lost. So during the recording, pread64 is not giving back as many bytes as we have asked for. I am now running this:

    gdb -args rr record --disable-cpuid-faulting <my program>

And have a conditional breakpoint in libc's pread64 just after the real syscall was made to reveal when I get less than what had been asked for.

**Comment by bkin** [comment]
For the recording with --disable-cpuid-faulting, I get this during replay:

    [FATAL /home/roc/rr/rr/src/ReplaySession.cc:1023:check_ticks_consistency()]
         (task 18231 (rec:17883) at time 28354)
         -> Assertion `ticks_now == trace_ticks' failed to hold. ticks mismatch for 'SYSCALL: getrandom'; expected 304516262, got 304516260

During record, I had no instance where pread64 would be unable to return the number of bytes that had been requested (or by conditional breakpoint failed).

I will now try to reproduce the once again by running `rr record <my program>` just to see if it will stumble over `pread64` again.

**Comment by bkin** [comment]
Interestingly, there are only three calls to pread64. The very first one returns -1 for plain 'rr record'. Here is what happens when I `strace <myprog>`:

    openat(AT_FDCWD, ".../ADR_CONTROL.ams", O_RDONLY|O_DSYNC|O_DIRECT) = 9
    prlimit64(0, RLIMIT_NOFILE, NULL, {rlim_cur=1024, rlim_max=1024*1024}) = 0
    fcntl(9, F_DUPFD, 256)                  = 256
    close(9)                                = 0
    fcntl(256, F_SETFD, FD_CLOEXEC)         = 0
    fstatfs(256, {f_type=EXT2_SUPER_MAGIC, f_bsize=4096, f_blocks=122657050, f_bfree=38774306, f_bavail=32537929, f_files=31162368, f_ffree=29148893, f_fsid={val=[3901449468, 2866517587]}, f_namelen=255, f_frsize=4096, f_flags=ST_VALID|ST_RELATIME}) = 0
    times({tms_utime=51, tms_stime=10, tms_cutime=0, tms_cstime=0}) = 2307230061
    pread64(256, "\0"..., 16384, 0) = 16384
    times({tms_utime=51, tms_stime=10, tms_cutime=0, tms_cstime=0}) = 2307230062
    clock_gettime(CLOCK_PROCESS_CPUTIME_ID, {tv_sec=0, tv_nsec=625957410}) = 0
    times({tms_utime=51, tms_stime=10, tms_cutime=0, tms_cstime=0}) = 2307230062
    pread64(256, "\0"..., 4096, 20480) = 4096
    times({tms_utime=51, tms_stime=10, tms_cutime=0, tms_cstime=0}) = 2307230062
    times({tms_utime=51, tms_stime=10, tms_cutime=0, tms_cstime=0}) = 2307230062
    pread64(256, "\0"..., 4096, 45056) = 4096
    times({tms_utime=51, tms_stime=10, tms_cutime=0, tms_cstime=0}) = 2307230062
    clock_gettime(CLOCK_PROCESS_CPUTIME_ID, {tv_sec=0, tv_nsec=626066169}) = 0
    close(256)                              = 0

That ADR_CONTROL.ams there is in another file system. I am not sure what it is
good for, but it seems related to the proprietary library that I am working
with. The very first pread64 that I am getting with `rr record` will return -1
and not 16384, like here.

**Comment by bkin** [comment]
And here the same thing from the perspective of `rr dump -b -m -p`:

    {
      real_time:5533673.959839 global_time:35335, event:`SYSCALLBUF_FLUSH' tid:8245, ticks:496465610
      { syscall:'openat', ret:0x9, size:0x10 }
    }
    {
      real_time:5533673.959841 global_time:35336, event:`SYSCALL: prlimit64' (state:ENTERING_SYSCALL) tid:8245, ticks:496465610
    rax:0xffffffffffffffda rbx:0x681fffa0 rcx:0xffffffffffffffff rdx:0x0 rsi:0x7 rdi:0x0 rbp:0x12e rsp:0x681ffe00 r8:0x0 r9:0x9 r10:0x7ffd2d8db2f0 r11:0x246 r12:0x55d6536dee98 r13:0x7ffd2d8db730 r14:0x9 r15:0x55d6536dee78 rip:0x70000002 eflags:0x246 cs:0x33 ss:0x2b ds:0x0 es:0x0 fs:0x0 gs:0x0 orig_rax:0x12e fs_base:0x7fa594ae6780 gs_base:0x0
    }
    {
      real_time:5533673.959842 global_time:35337, event:`SYSCALLBUF_RESET' tid:8245, ticks:496465610
    }
    {
      real_time:5533673.959861 global_time:35338, event:`SYSCALL: prlimit64' (state:EXITING_SYSCALL) tid:8245, ticks:496465610
    rax:0x0 rbx:0x681fffa0 rcx:0xffffffffffffffff rdx:0x0 rsi:0x7 rdi:0x0 rbp:0x12e rsp:0x681ffe00 r8:0x0 r9:0x9 r10:0x7ffd2d8db2f0 r11:0x246 r12:0x55d6536dee98 r13:0x7ffd2d8db730 r14:0x9 r15:0x55d6536dee78 rip:0x70000002 eflags:0x246 cs:0x33 ss:0x2b ds:0x0 es:0x0 fs:0x0 gs:0x0 orig_rax:0x12e fs_base:0x7fa594ae6780 gs_base:0x0
      { tid:8245, addr:0x7ffd2d8db2f0, length:0x10 }
    }
    {
      real_time:5533673.959888 global_time:35339, event:`SYSCALLBUF_FLUSH' tid:8245, ticks:496465714
      { syscall:'fcntl', ret:0x100, size:0x10 }
      { syscall:'close', ret:0x0, size:0x10 }
      { syscall:'fcntl', ret:0x0, size:0x10 }
    }
    {
      real_time:5533673.959890 global_time:35340, event:`SYSCALL: fstatfs' (state:ENTERING_SYSCALL) tid:8245, ticks:496465714
    rax:0xffffffffffffffda rbx:0x681fffa0 rcx:0xffffffffffffffff rdx:0x1000 rsi:0x7ffd2d8db3a8 rdi:0x100 rbp:0x8a rsp:0x681ffe00 r8:0x0 r9:0x9 r10:0x7ffd2d8db2f0 r11:0x246 r12:0x55d6536dee98 r13:0x55d6536eb8a8 r14:0x55d6536f0340 r15:0x55d6536dee78 rip:0x70000002 eflags:0x246 cs:0x33 ss:0x2b ds:0x0 es:0x0 fs:0x0 gs:0x0 orig_rax:0x8a fs_base:0x7fa594ae6780 gs_base:0x0
    }
    {
      real_time:5533673.959891 global_time:35341, event:`SYSCALLBUF_RESET' tid:8245, ticks:496465714
    }
    {
      real_time:5533673.959910 global_time:35342, event:`SYSCALL: fstatfs' (state:EXITING_SYSCALL) tid:8245, ticks:496465714
    rax:0x0 rbx:0x681fffa0 rcx:0xffffffffffffffff rdx:0x1000 rsi:0x7ffd2d8db3a8 rdi:0x100 rbp:0x8a rsp:0x681ffe00 r8:0x0 r9:0x9 r10:0x7ffd2d8db2f0 r11:0x246 r12:0x55d6536dee98 r13:0x55d6536eb8a8 r14:0x55d6536f0340 r15:0x55d6536dee78 rip:0x70000002 eflags:0x246 cs:0x33 ss:0x2b ds:0x0 es:0x0 fs:0x0 gs:0x0 orig_rax:0x8a fs_base:0x7fa594ae6780 gs_base:0x0
      { tid:8245, addr:0x7ffd2d8db3a8, length:0x78 }
    }
    {
      real_time:5533673.959977 global_time:35343, event:`SYSCALL: times' (state:ENTERING_SYSCALL) tid:8245, ticks:496490442
    rax:0xffffffffffffffda rbx:0x681fffa0 rcx:0xffffffffffffffff rdx:0x0 rsi:0x55d6536ffe18 rdi:0x7ffd2d8da9b0 rbp:0x64 rsp:0x681ffe00 r8:0x55d653704000 r9:0x3 r10:0x452f r11:0x246 r12:0x55d653704000 r13:0x0 r14:0x55d6536ffe18 r15:0x55d6536cee10 rip:0x70000002 eflags:0x246 cs:0x33 ss:0x2b ds:0x0 es:0x0 fs:0x0 gs:0x0 orig_rax:0x64 fs_base:0x7fa594ae6780 gs_base:0x0
    }
    {
      real_time:5533673.959998 global_time:35344, event:`SYSCALL: times' (state:EXITING_SYSCALL) tid:8245, ticks:496490442
    rax:0x8761a89a rbx:0x681fffa0 rcx:0xffffffffffffffff rdx:0x0 rsi:0x55d6536ffe18 rdi:0x7ffd2d8da9b0 rbp:0x64 rsp:0x681ffe00 r8:0x55d653704000 r9:0x3 r10:0x452f r11:0x246 r12:0x55d653704000 r13:0x0 r14:0x55d6536ffe18 r15:0x55d6536cee10 rip:0x70000002 eflags:0x246 cs:0x33 ss:0x2b ds:0x0 es:0x0 fs:0x0 gs:0x0 orig_rax:0x64 fs_base:0x7fa594ae6780 gs_base:0x0
      { tid:8245, addr:0x7ffd2d8da9b0, length:0x20 }
    }
    {
      real_time:5533673.960120 global_time:35345, event:`PATCH_SYSCALL' tid:8245, ticks:496505353
    rax:0x11 rbx:0x100 rcx:0xffffffffffffffff rdx:0x4000 rsi:0x55d653704000 rdi:0x100 rbp:0x7ffd2d8d5bb0 rsp:0x7ffd2d8d5b80 r8:0x0 r9:0x55d653704000 r10:0x0 r11:0x246 r12:0x55d653704000 r13:0x4000 r14:0x0 r15:0x0 rip:0x7fa5ae9c93f2 eflags:0x246 cs:0x33 ss:0x2b ds:0x0 es:0x0 fs:0x0 gs:0x0 orig_rax:0xffffffffffffffff fs_base:0x7fa594ae6780 gs_base:0x0
      { tid:8245, addr:0x7fa5aebd967b, length:0x4f }
      { tid:8245, addr:0x7fa5ae9c93f2, length:0x5 }
      { tid:8245, addr:0x7fa5ae9c93f7, length:0x3 }
    }
    {
      real_time:5533673.960644 global_time:35346, event:`SYSCALLBUF_FLUSH' tid:8245, ticks:496739001
      { syscall:'pread64', ret:0xffffffffffffffea, size:0x10 }
      { syscall:'lstat', ret:0xfffffffffffffffe, size:0xa0 }
      { syscall:'openat', ret:0x9, size:0x10 }
      { syscall:'fcntl', ret:0x0, size:0x10 }
      { syscall:'lseek', ret:0x0, size:0x10 }
      { syscall:'write', ret:0x6d, size:0x10 }
      { syscall:'lstat', ret:0xfffffffffffffffe, size:0xa0 }
      { syscall:'openat', ret:0xa, size:0x10 }
      { syscall:'fcntl', ret:0x0, size:0x10 }
      { syscall:'lseek', ret:0x0, size:0x10 }
      { syscall:'gettimeofday', ret:0x0, size:0x20 }
      { syscall:'write', ret:0x38, size:0x10 }
      { syscall:'lseek', ret:0x6d, size:0x10 }
      { syscall:'write', ret:0x20, size:0x10 }
      { syscall:'write', ret:0x53, size:0x10 }
      { syscall:'lseek', ret:0x8d, size:0x10 }
      { syscall:'write', ret:0x2f, size:0x10 }
      { syscall:'write', ret:0xa, size:0x10 }
      { syscall:'lseek', ret:0xbc, size:0x10 }
      { syscall:'write', ret:0x49, size:0x10 }
      { syscall:'write', ret:0xa, size:0x10 }
      { syscall:'lseek', ret:0x105, size:0x10 }
      { syscall:'write', ret:0x24, size:0x10 }
      { syscall:'write', ret:0x7, size:0x10 }
    }

**Comment by bkin** [comment]
rr dump mentions no earlier `pread64` so I guess I would have to find the real call from something like `strace rr record <myprog>`?

**Comment by rocallahan** [comment]
In `syscallbuf.c` there's a block starting with 
```
  if (buf && count >= CLONE_SIZE_THRESHOLD &&
      thread_locals->cloned_file_data_fd >= 0 && is_bufferable_fd(fd) &&
      sizeof(void*) == 8 && !(count & 4095)) {
```
Try disabling that path with `if (0 && ...` ?

It's possible that O_DSYNC or O_DIRECT is interfering with things in some way.

**Comment by rocallahan** [comment]
Er no never mind.

Try just disabling the `CASE(pread64)` path in syscallbuf.c to verify that's the problem?

**Comment by bkin** [comment]
I'm on it. btw: I had to 'pip install pexpect' to build rr, this is not mentioned on https://github.com/mozilla/rr/wiki/Building-And-Installing

**Comment by bkin** [comment]
With that commented out, I am still running into the same problem. But reverse-stepping from that, I end up in `SYSCALLHOOK_END(_syscall_hook_trampoline_48_3d_00_f0_ff_ff)` for the call to `pread64`. This is odd since I would have expected that this only comes into play when the syscall buffering is in place. Maybe I wasn't compiling properly.

I'll rebuild rr with debug info to see a bit more.

**Comment by bkin** [comment]
Sorry, I was commenting `pwrite64`... Now that I commented out `pread64`, it all works!

**Comment by bkin** [comment]
I'll revert and try to find why `pread64` is giving the bad return value. I did not have any luck with `gdb rr record` or `strace rr record` yet. I'll try `rr record rr record` next, maybe that works.

**Comment by rocallahan** [comment]
I have a theory... I'll check it when I'm back at my computer

**Comment by bkin** [comment]
ok, I'll wait for that then. `rr record rr record` did not work.

**Comment by khuey** [comment]
> 
> 
> I'm on it. btw: I had to 'pip install pexpect' to build rr, this is not mentioned on https://github.com/mozilla/rr/wiki/Building-And-Installing

The instructions about required packages for both Ubuntu and Fedora include the python3-pexpect package. If your system python is still python2 then that might not work for you.

**Comment by rocallahan** [comment]
`man 2 open` says
> The O_DIRECT flag may impose alignment restrictions on the length an address of user-space buffers and the file offset of I/Os.  In Linux alignment restrictions vary by filesystem and kernel version and might be absent entirely.

Buffering `read` syscalls uses a temporary buffer that has no special alignment, so it would break with `O_DIRECT` if the filesystem requires special alignment. I think this is probably the bug.

Unfortunately I can't reproduce this locally because apparently btrfs doesn't impose alignment restrictions, or maybe it just ignores O_DIRECT.

**Comment by rocallahan** [comment]
Reopen if that fix doesn't fix things.

**Comment by bkin** [comment]
That solved my issue and I can now use `rr record` with syscall buffering again, thank you very much!!

Minor nitpick: Since I had to custom-build rr, I had it installed in `/usr/local/bin` which is early in my path. But simple running `rr record <myprog>` still tried to inject `/usr/bin/../lib/rr/librrpreload.so` (the one installed from Ubuntu) via `LD_PRELOAD`. This gave me the same bug than before. I did find the undocumented option `--resource-path` but could not feed it into `rr` successfully ("Invalid option --resource-path=/usr/local"). I ended up copying my custom `librrpreload.so`over the one from rr 5.2.0 shipped with Ubuntu. This then showed that my issue is solved with 5874aa8

Do you want me to look more into why the wrong librrpreload.so is picked up or should we leave it at that?

Another unrelated thing: I am seeing some of rr's test fail on my machine. Should I share these results with you? And how would I?

**Comment by rocallahan** [comment]
> Do you want me to look more into why the wrong librrpreload.so is picked up or should we leave it at that?

It would be great if you tracked that down, but if you don't feel like doing that, that's fine.

> Another unrelated thing: I am seeing some of rr's test fail on my machine. Should I share these results with you? And how would I?

Pasting the ctest verbose log would be a good start. Then we'd find a simple test that's failing and try getting that test's verbose log (or just `rr record`/`rr replay` and see what happens).

To be honest, if you're happily using rr, tracking down the rr test failures is probably not a good use of your time for your own sake. But I'll help you analyze them if you want.

BTW I'm going offline for a few days very soon.

**Comment by bkin** [comment]
Since I'm getting a great tool with free support here, I feel obliged to give something back. I'll open separate issues for both points and fill in some details. 
None of them are urgent in any way for me. Have fun in the real world!

**Comment by bkin** [comment]
> > Do you want me to look more into why the wrong librrpreload.so is picked up or should we leave it at that?

> It would be great if you tracked that down, but if you don't feel like doing that, that's fine.

rr is injecting the proper library, I had picked the wrong trace during replay. Sorry.
