### ISSUE TITLE
"rr replay" takes > 1 minute on program that takes ~1 second to execute

### ISSUE THREAD

**Issue by HighCommander4** [mozilla/rr#2424]
I have been using rr to debug testcases in the LLVM codebase, and generally it's super useful.

However, one annoyance is that even a testcase that takes ~1 second to execute normally will take over a minute to `rr replay`.

The time does not appear to be spent replaying the body of the testcase, since even if I put a breakpoint at the beginning of the testcase, it takes ~1 minute for it to be hit (and then replaying the rest of the testcase is fast).

In particular, when I run `rr replay`:

  * it takes a few seconds for me to get the initial debugger prompt where I can set a breakpoint
  * if I now set a breakpoint at the beginning of the testcase and `continue` to it, it takes ~1 minute for it to be reached
  * after that, continuing / stepping / reverse-continuing etc. is fast

What is happening during this long ~1 minute delay? Is there a way to make it faster?

**Comment by khuey** [comment]
My guess would be that gdb is busy loading symbols ... if you `rr replay -a` do you see these delays?

**Comment by HighCommander4** [comment]
> if you `rr replay -a` do you see these delays?

Nope! `rr replay -a` takes just a fraction of a second longer than a normal execution :)

Is there something I could do to speed up the symbol loading?

**Comment by bkin** [comment]
To improve debugger startup time, I use `set auto-solib-add off` in my `~/.gdbinit`. This avoids loading symbols from libraries (but not the executable). When you miss symbols from certain libraries during debugging, you can then run `sharedlibrary <regex>` to load them.

**Comment by rocallahan** [comment]
> Is there something I could do to speed up the symbol loading?

Build a gdb index? https://sourceware.org/gdb/onlinedocs/gdb/Index-Files.html
Or use Pernosco.

Sounds like this is really a gdb issue, not an rr issue, so I'll close this.

**Comment by HighCommander4** [comment]
> Build a gdb index? https://sourceware.org/gdb/onlinedocs/gdb/Index-Files.html

Thanks for the suggestion! I can confirm that with `set index-cache on`, subsequent replays after indexing are much faster (~5 seconds instead of ~1 minute).

One thing that could perhaps be improved (if possible) would be to make it clear that this is where the time is being spent. I noticed that if run with the `--goto` option, `rr replay` does print this when the breakpoint is reached:

```
--------------------------------------------------
 ---> Reached target process 25760 at event 3267.
--------------------------------------------------
Remote debugging using 127.0.0.1:25848
Reading symbols from /home/nr/programs/rr/bin/../lib/rr/librrpreload.so...
Reading symbols from /home/nr/dev/projects/llvm/build/lib/libLLVMX86Info.so.10git...
Reading symbols from /lib/x86_64-linux-gnu/libpthread.so.0...
(No debugging symbols found in /lib/x86_64-linux-gnu/libpthread.so.0)
Reading symbols from /home/nr/dev/projects/llvm/build/lib/libgtest_main.so.10git...
Reading symbols from /home/nr/dev/projects/llvm/build/lib/libgtest.so.10git...
Reading symbols from /home/nr/dev/projects/llvm/build/lib/libclangAST.so.10git...
Reading symbols from /home/nr/dev/projects/llvm/build/lib/libclangBasic.so.10git...
Reading symbols from /home/nr/dev/projects/llvm/build/lib/libclangFormat.so.10git...
...
```

which makes it clear that this is what's taking up the time. If `rr replay` could be made to print this "Reading symbols" output when run without `--goto` as well, that would clear things up I think.
