### ISSUE TITLE
rr_page* files should not be in /usr/bin

### ISSUE THREAD

**Issue by wcohen** [mozilla/rr#2431]
rr installs rr_page_* files in /usr/bin.   Only executable binaries and scripts should be in /usr/bin. These files are not user executable code and should go elsewhere, maybe /usr/libexec/rr.

**Comment by rocallahan** [comment]
Can you send a PR?

**Comment by wcohen** [comment]
There is a open Fedora bugzilla for reviewing the packaging and including it in Fedora.

https://bugzilla.redhat.com/show_bug.cgi?id=1793156

The srpm being reviewed can be downloaded from:
http://people.redhat.com/wcohen/rr/rr-5.3.0.9000-3.fc30.src.rpm

It has a workaround the rr.spec file has 
%undefine __brp_mangle_shebangs

Without this workaround in rr.spec the rawhide build fails when the build system checks for /usr/bin/env use because the the /usr/bin/rr_page_* files are not scripts nor are they valid elf files.

https://koji.fedoraproject.org/koji/taskinfo?taskID=40830728

The problem is reported toward the end of the build.log:

https://kojipkgs.fedoraproject.org//work/tasks/765/40830765/build.log


Note that Fedora 31 and earlier does not need this workaround.

**Comment by wcohen** [comment]
What is happening is a bit opaque from the output of the brp-mangle-shebangs in the build.log below.  However, I added a -x the to script and saw that it was dying when it attempted to process /usr/bin/rr_page_32


+ /usr/lib/rpm/redhat/brp-mangle-shebangs
*** WARNING: ./usr/share/bash-completion/completions/rr is executable but has no shebang, removing executable bit
mangling shebang in /usr/bin/rr-collect-symbols.py from /usr/bin/env python3 to #!/usr/bin/python3
error: Bad exit status from /var/tmp/rpm-tmp.1lPsA4 (%install)
    Bad exit status from /var/tmp/rpm-tmp.1lPsA4 (%install)
RPM build errors:
Child return code was: 1
EXCEPTION: [Error()]

**Comment by eclipseo** [comment]
> These files are not user executable code and should go elsewhere, maybe /usr/libexec/rr.

Libexec is for programs too, just not run by the user. /usr/share/rr seems to me the most appropriate, although it is usually not for arch dependent data, rr_page are detected as text file which is why brp-mangle-shebangs is triggered.

**Comment by rocallahan** [comment]
rr_page files are not text files. They are architecture-specific executable code and data (but not ELF files of course).

I don't really care what the right answer is, I just want people to decide and someone send a PR :-).

**Comment by wcohen** [comment]
The issue has been addressed by commit 7908feaee2ddedcee6db7619a221b24193fb5e99, so closing this issue.
