### ISSUE TITLE
rr doesn't work with SDL2

### ISSUE THREAD

**Issue by sefeng211** [mozilla/rr#2432]
```
➜  build rr ./emueGBA ../rom/Dr_mario.gb
rr: Saving execution to trace directory `/home/saber/.local/share/rr/emueGBA-3'.
X Error of failed request:  BadValue (integer parameter out of range for operation)
  Major opcode of failed request:  151 (GLX)
  Minor opcode of failed request:  3 (X_GLXCreateContext)
  Value in failed request:  0x0
  Serial number of failed request:  101
  Current serial number in output stream:  102
```

I aware #1578, however I don't get the first error. Not sure what I should do to move it forward, thanks :)

**Comment by rocallahan** [comment]
We disable direct rendering. I guess something's falling back to GLX, which your system doesn't support. Is there some way to force SDL2 to use a pure CPU, non-GLX renderer?

**Comment by sefeng211** [comment]
Not sure about that, I probably need to compile SDL2 myself....
Anyways, since it's a not a bug in rr, I am closing this off. Thanks for the help.

**Comment by rocallahan** [comment]
It kind of is a bug in rr, since if we knew how to force CPU-only non-GLX rendering in SDL2 via an environment variable or some other easy way, we could add that to rr.

**Comment by sefeng211** [comment]
ah I see...okay, Let me look that around, reopening :)

**Comment by sefeng211** [comment]
According to https://discourse.libsdl.org/t/force-cpu-only-non-glx-rendering-on-linux/27099/2, `SDL_RENDER_DRIVER=software` is the environment variable that we can use.

I've tested it and it works for me.
