### ISSUE TITLE
check_for_ioc_period_bug() returns an error

### ISSUE THREAD

**Issue by Yulmart** [mozilla/rr#2434]
I'm trying to run the testsuite on a 32-bit machine, however, almost all of the test cases fail. 

```
[root@hpe-dl120g6-01 test]# uname -r
5.4.12-100.fc30.i686
```

These test cases fail with the following error:

```
[FATAL /root/rr/src/PerfCounters.cc:331:check_for_ioc_period_bug() errno: EINVAL] ioctl(PERF_EVENT_IOC_PERIOD) failed
```

**Comment by rocallahan** [comment]
Does `perf stat` work?

You may need to write a reduced testcase that exercises `PERF_EVENT_IOC_PERIOD` to see if that works at all on your system.

**Comment by Yulmart** [comment]
`perf stat` works. I'll try making a simple testcase to see if `PERF_EVENT_IOC_PERIOD` works at all.

**Comment by wcohen** [comment]
The kernel is returning the EINVAL.  It would be helpful to know which specific kernel was used on the 32-bit platform.  Check to see if that was the same kernel version used for the successful run of the 64-bit  tests.

You might also use systemtap to track down where in the kernel the EINVAL is coming from. Look to see if arguments passed into function make sense.

The PERF_EVENT_IOC_PERIOD handled in this part of a case statement:
https://elixir.bootlin.com/linux/latest/source/kernel/events/core.c#L5256

Looks like the EINVAL coming from somewhere in the the _perf_event_period function:

https://elixir.bootlin.com/linux/latest/source/kernel/events/core.c#L5179

**Comment by marcpawl** [comment]
Strace is reporting 
perf_event_open({type=PERF_TYPE_RAW, size=PERF_ATTR_SIZE_VER5, config=0x5101c4, ...}, 0, -1, -1, PERF_FLAG_FD_CLOEXEC) = 3
ioctl(3, PERF_EVENT_IOC_PERIOD, [1])    = -1 EINVAL (Invalid argument)
[root@Lab230slot2 bin]# uname -msr
Linux 5.4.158-1.el7.elrepo.x86_64 x86_64

on Centos 7.6


[root@Lab230slot2 bin]#  rr record  /usr/bin/ls
[FATAL /builddir/build/BUILD/rr-5.4.0/src/PerfCounters.cc:232:check_for_ioc_period_bug() errno: EINVAL] ioctl(PERF_EVENT_IOC_PERIOD) failed
=== Start rr backtrace:
rr(_ZN2rr13dump_rr_stackEv+0x3b)[0x5b247b]
rr(_ZN2rr15notifying_abortEv+0x47)[0x5b2507]
rr[0x4cf7c3]
rr(_ZN2rr12PerfCounters23default_ticks_semanticsEv+0x1a)[0x4d044a]
rr(_ZN2rr7SessionC2Ev+0x1ce)[0x574c3e]
rr(_ZN2rr13RecordSessionC1ERKSsRKSt6vectorISsSaISsEES7_RKNS_20DisableCPUIDFeaturesENS0_16SyscallBufferingEiNS_7BindCPUES2_PKNS_9TraceUuidEbb+0x6b)[0x4e4c6b]
rr(_ZN2rr13RecordSession6createERKSt6vectorISsSaISsEES5_RKNS_20DisableCPUIDFeaturesENS0_16SyscallBufferingEhNS_7BindCPUERKSsPKNS_9TraceUuidEbbb+0x82b)[0x4e59cb]
rr(_ZN2rr13RecordCommand3runERSt6vectorISsSaISsEE+0xe7b)[0x4d870b]
rr(main+0x1ee)[0x44e03e]
/lib64/libc.so.6(__libc_start_main+0xf5)[0x7f27bf0ab555]
rr[0x44e19f]
=== End rr backtrace
Aborted (core dumped)
[root@Lab230slot2 t]# perf stat /usr/bin/ls

 Performance counter stats for '/usr/bin/ls':

              1.08 msec task-clock                #    0.785 CPUs utilized
                 0      context-switches          #    0.000 K/sec
                 0      cpu-migrations            #    0.000 K/sec
                95      page-faults               #    0.088 M/sec
           2360963      cycles                    #    2.190 GHz                      (18.03%)
           1599242      stalled-cycles-frontend   #   67.74% frontend cycles idle
           1116423      stalled-cycles-backend    #   47.29% backend cycles idle
           1781417      instructions              #    0.75  insn per cycle
                                                  #    0.90  stalled cycles per insn
            353099      branches                  #  327.573 M/sec
             18006      branch-misses             #    5.10% of all branches          (81.97%)

       0.001372537 seconds time elapsed

       0.000000000 seconds user
       0.001384000 seconds sys


[root@Lab230slot2 t]#
