### ISSUE TITLE
Creating an RPM subpackge for rr-testsuite

### ISSUE THREAD

**Issue by Yulmart** [mozilla/rr#2449]
I've been working on introducing an installable rr-testsuite (similar to the ones that Dyninst, Papi and SystemTap have). I would appreciate your feedback on the overall idea so far.

The testsuite binaries in `~/obj/bin` would be installed to `/usr/lib64/rr/testsuite/obj/bin'`. The rest of the testing framework would also be installed in its appropriate folders. For example, `util.sh` would be installed at `/usr/lib64/rr/testsuite/rr/src/test`. It seems that there are a lot of additional files and libraries that the testsuite depends on. This part will take some time to get right.

Additionally, as per the Linux FHS, I couldn't come to a strong conclusion as to where the testsuite should be installed, so `/usr/lib64/rr/testsuite` is subject to change.

**Comment by rocallahan** [comment]
Sounds OK to me.

**Comment by rocallahan** [comment]
The PRs were reverted.
