### ISSUE TITLE
Assertion `nread == sizeof(val)' failed.

### ISSUE THREAD

**Issue by Keno** [mozilla/rr#2451]
I'm seeing fairly frequent assertions failures of this kind:

```
rr: Saving execution to trace directory `/home/keno/.local/share/rr/julia-46'.
Test    (Worker) | Time (s) | GC (s) | GC % | Alloc (MB) | RSS (MB)
cmdlineargs  (1) |        started at 2020-03-09T16:53:05.521
rr: /home/keno/rr/src/PerfCounters.cc:275: int64_t rr::read_counter(rr::ScopedFd&): Assertion `nread == sizeof(val)' failed.
```

The thing that's probably unusual about this is that we're nesting `rr record` with `--ignore-nested`. It works fine (or rather I should say it doesn't assert) without the `--ignore-nested`. Doing this kind of thing used to work fine, a few months back, though of course both rr and the software I'm testing have changed since.

**Comment by rocallahan** [comment]
I have no idea what's causing this but I guess it wouldn't be *too* hard to track down :-)

**Comment by Keno** [comment]
Yeah, I'm working on it. I just figured I'd post it first in case you already knew about it. Interestingly it might be related to my other issue, in that it seems to have gone away after I forced `LD_PRELOAD` through all the children.

**Comment by Keno** [comment]
Indeed. Simple reproducer:
```
rr record env -i /home/keno/rr-build/bin/rr record --ignore-nested env
rr: Saving execution to trace directory `/home/keno/.local/share/rr/env-1'.
rr: /home/keno/rr/src/PerfCounters.cc:275: int64_t rr::read_counter(rr::ScopedFd&): Assertion `nread == sizeof(val)' failed.
Aborted
```
