### ISSUE TITLE
More completely fake the number of CPUs for the process

### ISSUE THREAD

**Issue by Keno** [mozilla/rr#2453]
We use LD_PRELOAD to override `sysconf` to change the number of processors that the process we're recording sees. Unfortunately, this mechanism is a bit brittle. If the process doesn't pass through LD_PRELOAD to its children, the override will cease working. I'm seeing some processes be quite confused by this. It should be possible to intercept glibc's requests to sysfs and procfs in addition to the LD_PRELOAD intercept to guarantee that processes get a consistent view of the system whether or not they see the LD_PRELOAD. The code glibc uses is here: https://github.com/bminor/glibc/blob/5f72f9800b250410cad3abfeeb09469ef12b2438/sysdeps/unix/sysv/linux/getsysstats.c#L126.
Looks like there's three places it looks:
- /sys/devices/system/cpu/*
- /proc/stat
- /proc/cpuinfo

**Comment by rocallahan** [comment]
Some processes also use `sched_getaffinity` but we handle that via `Scheduler::pretend_affinity_mask()`.

Hacking those files reasonable. I guess whatever we do should be consistent with `Scheduler::regenerate_affinity_mask()`.

**Comment by Keno** [comment]
Turns out glibc's parser for this file is broken ([I filed a glibc bug](https://sourceware.org/bugzilla/show_bug.cgi?id=25859)), so we'll need to implement the same for `/proc/stat`, otherwise this scheme fails if `rr record --num-cores` is set to something other than 1. I'll submit a patch.
