### ISSUE TITLE
std::random_device hack no longer works

### ISSUE THREAD

**Issue by Keno** [mozilla/rr#2459]
As of https://github.com/gcc-mirror/gcc/commit/b0c0d878a8b5bf39dbea4c192fed26d340524439, the internal implementation of std::random_device changed. E.g. on my platform the fallback is now using a file descriptor rather than a FILE*. That said, if linux is new enough and CPUID faulting is enabled, then libstdc++ properly autodetects the absence of the rdrand instruction. I'm not quite sure what to do about this one. I don't see a good way to auto-detect which ABI to use.

**Comment by rocallahan** [comment]
Seems like we could override  `_M_init` and `_M_init_pretr1` to modify the token pointer instead, which would work on both versions?

**Comment by Keno** [comment]
Let me try that and see if I can come up with something that works on this system.

**Comment by Keno** [comment]
I think the problem with that approach is that we'd have to detect the std::string ABI in use, which seems even more difficult than detecting the std::random_device ABI.

**Comment by rocallahan** [comment]
Yeah OK. Is this causing an actual problem for you? If not maybe we just ignore it and hope it doesn't come up.

**Comment by Keno** [comment]
Well, recording something under rr that uses random_device now crashes for me. I don't personally record anything that uses this C++ class, but the rr tests exercise this of course. Maybe the thing to do is just disable the override if CPUID faulting is enabled and hope that the combination of super-new libstdc++, old-enough linux kernel to not have CPUID faulting and use of std::random_device is rare enough that nobody stumbles into it?

**Comment by rocallahan** [comment]
There's also virtualization settings where CPUID faulting is not available. I.e. all of AWS :-(.

**Comment by rocallahan** [comment]
Maybe we should check the glibc version explicitly?
