### ISSUE TITLE
rr can't find required Python module pexpect on RHEL7

### ISSUE THREAD

**Issue by jalapenopuzzle** [mozilla/rr#2466]
I have been trying to build Mozilla/rr on RHEL7. Consider this equivalent to CENTOS7.

I started off by modifying the installation instructions.
In the dependency step, I adapted package names to equivalents provided by RHEL7.
cmake -> cmake3 (from EPEL)
python3-expect -> pexpect

Then the project building step:
mkdir obj && cd obj
cmake3 ../rr

but cmake3 fails:
$ cmake3 ../rr
-- Found PkgConfig: /usr/bin/pkg-config (found version “0.27.1”)
-- Checking for module ‘capnp’
--   Found capnp, version 0.5.3.1
-- Found PythonInterp: /usr/bin/python3 (found suitable version “3.6.8”, minimum required is “3”)
Traceback (most recent call last):
  File “\<string\>”, line 1, in <module>
ModuleNotFoundError: No module named ‘pexpect’
CMake Error at CMakeList.txt:294 (message):
  Couldn’t find required Python module pexpect

-- Configuring incomplete, errors occurred!
See also “/home/stanb/rr/obj/CMakeFiles/CMakeOutput.log”.
See also “/home/stanb/rr/obj/CMakeFiles/CMakeError.log”.
[stanb@bumblebee obj]$ 

Note that the pexpect on RHEL7 is 2.3-11.el7. I suspect that this pexpect is too old to work with python3, but I haven’t proved that. I don’t know for sure why cmake3 can’t find pexpect.
Unfortunately, RedHat does NOT support newer pexpect on RHEL7.
https://access.redhat.com/solutions/3440581

$ cmake3 ../rr
-- Found PkgConfig: /usr/bin/pkg-config (found version “0.27.1”)
-- Checking for module ‘capnp’
--   Found capnp, version 0.5.3.1
-- Found PythonInterp: /usr/bin/python3 (found suitable version “3.6.8”, minimum required is “3”)
Traceback (most recent call last):
  File “<string>”, line 1, in \<module\>
ModuleNotFoundError: No module named ‘pexpect’
CMake Error at CMakeList.txt:294 (message):
  Couldn’t find required Python module pexpect

-- Configuring incomplete, errors occurred!
See also “/home/stanb/rr/obj/CMakeFiles/CMakeOutput.log”.
See also “/home/stanb/rr/obj/CMakeFiles/CMakeError.log”.
$

Note that the pexpect on RHEL7 is 2.3-11.el7. I suspect that this pexpect is too old to work with python3, but I haven’t proved that. I don’t know for sure why cmake3 can’t find pexpect.
Unfortunately, RedHat does NOT support newer pexpect on RHEL7.
https://access.redhat.com/solutions/3440581

How can I build Mozilla/rr on RHEL7?

**Comment by rocallahan** [comment]
How about just building with tests disabled?

**Comment by jalapenopuzzle** [comment]
It turns out that there is a package 
python36-pexpect
in the EPEL repository.

Installing python36-pexpect instead of the python3-pexpect listed in the Fedora dependencies allows the cmake3 step to complete.

This is my dependency installation step for RHEL7 with EPEL available:

yum install \
  ccache cmake3 make gcc gcc-c++ gdb libgcc libgcc.i686 \
  glibc-devel glibc-devel.i686 libstdc++-devel libstdc++-devel.i686 \
  python36-pexpect man-pages ninja-build capnproto capnproto-libs capnproto-devel

The build step becomes:
mkdir obj && cd obj
cmake3 ../rr
make -j2
sudo make install

Initially I had a lot of trouble running out of memory in the make step when using make -j8 as recommended in the original instructions.

**Comment by rocallahan** [comment]
Thanks.

**Comment by pnkfelix** [comment]
I was having similar issues trying to get python3 to see an already installed pexpect which python2.7 was able to import.

I don't know the "right" way to fix this on my particular host, but after reading https://github.com/pexpect/pexpect/issues/611#issuecomment-567872285, I was able to adapt this solution:

```
python3 -m pip install pexpect
```

and then `cmake ../rr` worked. (Well, really `env PKG_CONFIG_PATH=/usr/local/lib/pkgconfig cmake3 ../rr`, but that's orthgonal.)

I'm just throwing this as a note on here so that my future attempts to search about this problem in this repo will hopefully bear fruit.
