### ISSUE TITLE
[FATAL /build/rr-kyNkfr/rr-5.2.0/src/PerfCounters.cc:202:get_cpu_microarch()] Intel CPU type 0x30660 unknown

### ISSUE THREAD

**Issue by rajeshgangam** [mozilla/rr#2477]
Hi, 

I am facing a fatal exception for x86_64 based router.  Can you please help us understand what could be the real issue here.

root@draco-leaf2:/# rr record -n `which ls`
rr: Saving execution to trace directory `/root/.local/share/rr/ls-2'.
[FATAL /build/rr-kyNkfr/rr-5.2.0/src/PerfCounters.cc:202:get_cpu_microarch()] Intel CPU type 0x30660 unknown
root@draco-leaf2:/# dmesg | grep PMU
[    0.116300] Performance Events: PEBS fmt0+, Atom events, 8-deep LBR, Intel PMU driver.
[    0.156826] NMI watchdog: Enabled. Permanently consumes one hw-PMU counter.
root@draco-leaf2:/#

**Comment by Keno** [comment]
You can try adding it here: https://github.com/mozilla/rr/blob/master/src/PerfCounters.cc#L124-L139. However, I suspect you are unlikely to be successful. That CPUID is a Cedarview chip, which is about a decade old at this point and I'm fairly sure does not have a sufficiently advanced PMU for rr's use case.

**Comment by rajeshgangam** [comment]
Hi Keno, Thanks for the diff, Will try this and update you.  Appreciate your timely help.
