### ISSUE TITLE
Record single process from a tree with shared memory dependencies

### ISSUE THREAD

**Issue by neon12345** [mozilla/rr#2486]
We have implemented selective recording of processes from a process tree.
Since this depends on code outside the scope of rr, it would be helpful to have a plugin/extension mechanism.

For example we have changed rr to work in sync with an external shared memory recorder through a custom event. Communication is done with minimal local client/server handling to inject/receive the event and have the ability to get file descriptors for memory regions during replay.

Selective recording is useful to get meaningful recordings from huge process trees with many syscalls you are not interested in and unrecorded parts can run concurrent on multiple cores.

Reverse-step needs some more work and would benefit from a plugin/extension mechanism with custom events.

**Comment by rocallahan** [comment]
Sounds interesting. I'd like to hear more details about what you need.

**Comment by neon12345** [comment]
The first part ist the selectiveness. Since we are not very familiar with the rr code, our solution does not rely on it here. It is basically a daemon mode for rr that starts new recordings for marked executables.
It takes care of the fact that you cannot simply run rr somewhere in a process tree due to proc not mounted or capabilities and make it seamless.

Since it is not very comfortable to "mark" executables upfront and there is a caveat with process parent-child relationship, this could be integrated into rr. The functionality is basically to just ignore spawned processes (or select) based on individual settings.
To make this work with shared memory recording, it is important to be able to inject and propagate LD_PRELOAD with both recorded and not recorded parts. Restrictions for executables with capabilities required additional measures.  

For the second part I will post a small patch later, showing the rr changes for a better understanding of what was needed.

**Comment by neon12345** [comment]
Here is what we do: https://github.com/neon12345/rr/commit/c25a5b8cdf122256eaa3dbff9691a8c1da3275d3
Please do not mind the style or anything. It is just a quick and dirty test with not much going on.

 rr just needs to receive messages from the external recorder and place an event during record. Then send the event with the memory region file descriptor to the recorder/replayer on replay.
A better approach would be to allow shared library plugin loading into rr with a well defined plugin API to call into rr and register callbacks or add options for the command line.

Since rr is reading memory possibly not touched by the application, there was a problem with "record_remote" we needed to quickly work around.

The client/server approach also has a race condition making us save the initial state of shared memory again. A better integration can prevent this.

**Comment by neon12345** [comment]
We can now reverse-step a custom event.
