### ISSUE TITLE
Can't start Firefox GUI when trying to record with rr

### ISSUE THREAD

**Issue by yoasif** [mozilla/rr#2494]
Using Firefox Nightly 20200407093520

uname -a
5.4.0-21-generic #25-Ubuntu SMP

lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu Focal Fossa (development branch)
Release:	20.04
Codename:	focal

Installed via:

```
cd /tmp
wget https://github.com/mozilla/rr/releases/download/5.3.0/rr-5.3.0-Linux-$(uname -m).deb
sudo dpkg -i rr-5.3.0-Linux-$(uname -m).deb
```

Log attached. I never see a Firefox GUI appear. Not sure it matters, but my profile manager is configured to appear when I launch Firefox.

[rr.log](https://github.com/mozilla/rr/files/4446575/rr.log)

**Comment by khuey** [comment]
We haven't done a release with 0a49d7a4a5f5eb121f92bae288d4983d580a1ac0 which is required for the latest glibc. You could build rr master from source.

@rocallahan maybe we should do a 5.3.1/5.4 once the dust settles on the recent changes.

**Comment by yoasif** [comment]
Building it from source works.
