### ISSUE TITLE
Very slow recording of Firefox 

### ISSUE THREAD

**Issue by yoasif** [mozilla/rr#2495]
Using Firefox Nightly 20200407093520

uname -a
5.4.0-21-generic #25-Ubuntu SMP

lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description: Ubuntu Focal Fossa (development branch)
Release: 20.04
Codename: focal

I see minutes to load a web page, constant freezing while scrolling (GNOME keeps saying the app is not responding, which makes this worse).

Log can be grabbed from https://drive.google.com/open?id=1NxPnfrB2zzIYOCf0cdo-FV-3Oqp8lqE6

**Comment by khuey** [comment]
The biggest contribution to this was likely fixed by 0f867a58a9ff03039f2a72f663d4f57ec511486a

**Comment by mjfroman** [comment]
I'm seeing this as well.  I'm on most recent head of rr, and recording a single mochitest is taking 10+ minutes.  Some of the time appears to be some type of timeout that was not present in the past.  It does eventually finish.  I have logs if anyone needs them.

**Comment by rocallahan** [comment]
If you upload the trace to Pernosco that would make it easy to look at.

**Comment by mjfroman** [comment]
I tried to upload, but got:

> ./pernosco-submit upload ~/.local/share/rr/firefox-83 ~/mozilla/moz-central
> Running 'rr pack'...
> rr: Packed trace directory `/home/mfroman/.local/share/rr/firefox-83'.
> Copying /usr/lib/x86_64-linux-gnu/libthread_db.so into trace...
> Obtaining source file list...
> Traceback (most recent call last):
>   File "./pernosco-submit", line 705, in <module>
>     repo_paths = package_source_files()
>   File "./pernosco-submit", line 553, in package_source_files
>     (repo_mount, modified_files) = analyze_repo(repo_path, files)
>   File "./pernosco-submit", line 489, in analyze_repo
>     return analyze_hg_repo(repo_path, files)
>   File "./pernosco-submit", line 467, in analyze_hg_repo
>     r = hg_find_rev(repo_path, remotes)
>   File "./pernosco-submit", line 439, in hg_find_rev
>     rev_num = int(rev_num)
> ValueError: invalid literal for int() with base 10: '@'
>

**Comment by rocallahan** [comment]
Can you put a `print(output)` before line 439 and tell us what it printed?

**Comment by mjfroman** [comment]
output before line 439 is:
> @  530908 5804c4ddb9294e524857e7186053e0fa6804006a
> ~

Which looks like the line at 436 is probably assuming that 'hg log' hasn't been aliased, which I have done.  Let me change my .hgrc setup and retry the submission.

**Comment by mjfroman** [comment]
The upload seems to be progressing now.  See https://bugzilla.mozilla.org/show_bug.cgi?id=1415922 for dealing with hg aliases, but tldr:
set this environment variable to to disable loading of aliases: HGPLAIN=1

**Comment by mjfroman** [comment]
Trace finished uploading as: s3://pernosco-upload/hgkw9lJ-aVI.tar.zst

**Comment by rocallahan** [comment]
Thanks!!! Can you try again and test this patch to pernosco-submit for me?
[patch.txt](https://github.com/mozilla/rr/files/4618665/patch.txt)

**Comment by mjfroman** [comment]
Sweet!  With my hg log alias back in place, that patch works.
