### ISSUE TITLE
Intermittent test failure in ptrace_remote_unmap

### ISSUE THREAD

**Issue by Keno** [mozilla/rr#2509]
I'm seeing an intermittent failure in the ptrace_remote_unmap test. I saw it once during the regular test suite, but after that I ran a bunch of copies in parallel and am seeing about an 0.5% failure rate. The log always looks the below. Interestingly replaying the trace from a failing test has a slightly higher change of failing, but it's not 100%, so there appears to be something racy during replay:

```
(rr) break breakpoint
break breakpoint
Breakpoint 1 at 0x565d5b9a: file 32/ptrace_remote_unmap.c, line 80.
c
(rr) c
Continuing.

Breakpoint 1, breakpoint () at 32/ptrace_remote_unmap.c:80
checkpoint
80	static __attribute__((noinline)) void breakpoint(void) {
(rr) checkpoint
Checkpoint 1 at   breakpoint () at 32/ptrace_remote_unmap.c:80
(rr) restart 1
restart 1
0x565d5b9e	80	static __attribute__((noinline)) void breakpoint(void) {

Program stopped.
rc
rc
breakpoint () at 32/ptrace_remote_unmap.c:80
80	static __attribute__((noinline)) void breakpoint(void) {
(rr) rc
Continuing.
[FATAL /home/keno/rr-clean/src/Task.cc:2569:clone_syscall_is_complete()]
 (task 3425876 (rec:3425617) at time 202)
 -> Assertion `regs().syscall_may_restart() || -ENOSYS == result || -EAGAIN == result || -ENOMEM == result' failed to hold. Unexpected task status 0x107f (STOP-SIGSTKFLT) (clone syscall errno: errno(-120))
Tail of trace dump:
```

**Comment by Keno** [comment]
Full logs: https://gist.github.com/Keno/bee26159e2523671525a62b2395bb231
I'm trying to debug it, but not having much luck so far.

**Comment by Keno** [comment]
I added some extra instrumentation and was able to capture this:
```
[PerfCounters] Resetting counters with period 928
[Task] resuming execution of 458623 with PTRACE_SYSEMU tick_period 928 wait 0
[Task] Flushing registers for tid 458623 { args:(0x57a0a000,0x57a09008,0xf7ecf000,0x57a0a000,0xf7ecf000,4159510552) orig_syscall:45syscallno: 1470144512 }
[Task] going into blocking waitid(458623) ...
[Task]   waitid(458623) returns 0; status 0x57f (STOP-SIGTRAP)
[Task]   (refreshing register cache)
[Task] Requesting registers from tracee 458623
[PerfCounters] disabling perf counters
[Task] Saw 930 ticks
[AddressSpace] Writing back 0xcd at 0xf7f24b40
[Task] resuming execution of 458623 with PTRACE_CONT tick_period -2 wait 0
[Task] Flushing registers for tid 458623 { args:(0x1000011,0,0,0,0xf7cdd768,0) orig_syscall:120syscallno: 120 }
[Task] going into blocking waitid(458623) ...
[Task]   waitid(458623) returns 0; status 0x107f (STOP-SIGSTKFLT)
[Task]   (refreshing register cache)
[Task] Requesting registers from tracee 458623
[Task] Saw 0 ticks
[FATAL /home/keno/rr-clean/src/Task.cc:2574:clone_syscall_is_complete()]
 (task 458623 (rec:3425617) at time 202)
 -> Assertion `regs().syscall_may_restart() || -ENOSYS == result || -EAGAIN == result || -ENOMEM == result' failed to hold. Unexpected task status 0x107f (STOP-SIGSTKFLT) (clone syscall errno: errno(-120))
Tail of trace dump:
```

**Comment by rocallahan** [comment]
So we skidded far too far?

**Comment by Keno** [comment]
I wouldn't say far too far. Looks like we skidded two ticks beyond what was programmed? I think the issue is that we hit the syscall, disabled the counters, but then got the SIGSTKFLT anyway because it was already pending (or rather, the skid made it fire while we were already in the kernel, so we got the syscall trace first) - (Incidentally, why is the syscall trap a plain SIGTRAP, rather than a syscall entry trap?).

**Comment by rocallahan** [comment]
> (Incidentally, why is the syscall trap a plain SIGTRAP, rather than a syscall entry trap?)

Because we speed things up by just setting a breakpoint at the next syscall instead of relying on a real SYSEMU trap.

**Comment by rocallahan** [comment]
I don't understand what we were trying to replay here. If it was the syscall, we should not have set the ticks period, but if it was a context switch, then we should have lowered the ticks value so we didn't skid into a syscall.

**Comment by Keno** [comment]
Looks like we're trying to replay towards the asynchronous event at ticks mark `55145` (98 ticks after the syscall), but then we reduce it by the skid size (100), and end up programming the counter for two ticks before the syscall and skid into it.

**Comment by Keno** [comment]
I may have a patch. Let me do some stress tests to see if I see the problematic behavior again.
