### ISSUE TITLE
ReplaySession cloning scheme fails if vm and fd table do not match

### ISSUE THREAD

**Issue by Keno** [mozilla/rr#2540]
Every once in a while I'm seeing reverse execution fail with an error message like:
```
[FATAL /home/keno/rr-clean/src/AutoRemoteSyscalls.cc:555:check_syscall_result()]
 (task 971134 (rec:923518) at time 4115775)
 -> Assertion `false' failed to hold. Syscall lseek failed with errno EBADF
```
with a backtrace like:
```
#15 0x000055a25709ab0d in rr::AutoRemoteSyscalls::check_syscall_result (this=0x7ffcd77d1550, ret=-9, syscallno=8) at /home/keno/rr-clean/src/AutoRemoteSyscalls.cc:555
#16 0x000055a25709e096 in rr::AutoRemoteSyscalls::infallible_syscall<int, long, int> (this=0x7ffcd77d1550, syscallno=8) at /home/keno/rr-clean/src/AutoRemoteSyscalls.h:160
#17 0x000055a25709a764 in rr::AutoRemoteSyscalls::infallible_lseek_syscall (this=0x7ffcd77d1550, fd=301, offset=0, whence=0) at /home/keno/rr-clean/src/AutoRemoteSyscalls.cc:539
#18 0x000055a257271c53 in rr::Task::copy_state (this=0x55a259e115a0, state=...) at /home/keno/rr-clean/src/Task.cc:2161
#19 0x000055a25724d1de in rr::Session::finish_initializing (this=0x55a25a0901d0)
```
I believe the issue is something like the following.
We select an arbitrary task in the AddressSpace to be the new group leader at clone time and then fork all other tasks that share the same address space from it. The problem with this is that we assume that all tasks within the same address space have the same file descriptor table. That is not necessarily the case (e.g. during vfork). As a result we fail to lseek the cloned data fd, because it doesn't exist in the incorrect fd table (or even if it does, it may not be the right one).

That said, the particular trace that I'm reproducing this in is quite long, so I haven't taken a very deep look yet, so my analysis may be wrong.

**Comment by Keno** [comment]
I guess the decision to make is whether or not we need tasks that shared an fd table during record to also during replay, or whether we just want to emulate the whole thing and re-set-up to corrects fds when we actually need to.

**Comment by rocallahan** [comment]
The latter certainly sounds more robust.

**Comment by Keno** [comment]
So I managed to fix this, but we have the same problem with thread groups. There's a couple of places in replay where we look at whether we're the only member of our current ThreadGroup. I'm thinking we either put each replay task into its own thread group, or we track separately the record/replay thread groups. It's probably possible to recreate thread groups more faithfully, but that would be quite an undertaking. Do you foresee any problem with putting each replay task into its own thread group?

**Comment by rocallahan** [comment]
I can't think of any problem with that off the top of my head.
