### ISSUE TITLE
Fatal error in rr record

### ISSUE THREAD

**Issue by malhanvishal** [mozilla/rr#2609]
[FATAL /home/roc/rr/rr/src/util.cc:1632:write_all() errno: EDQUOT] Can't write 60299 bytes

#0  0x00002adb5e1e01f7 in raise () from /lib64/libc.so.6
#1  0x00002adb5e1e1a28 in abort () from /lib64/libc.so.6
#2  0x00000000005f2322 in rr::notifying_abort() ()
#3  0x00000000005f2196 in rr::write_all(int, void const*, unsigned long) ()
#4  0x00000000004c6c55 in rr::CompressedWriter::compression_thread() ()
#5  0x00000000004c6cf9 in rr::CompressedWriter::compression_thread_callback(void*) ()
#6  0x00002adb5df96e25 in start_thread () from /lib64/libpthread.so.0
#7  0x00002adb5e2a334d in clone () from /lib64/libc.so.6

Version: rr version 5.3.0
unman -a: Linux linserv01 3.10.0-693.el7.x86_64 #1 SMP Thu Jul 6 19:56:57 EDT 2017 x86_64 x86_64 x86_64 GNU/Linux

**Comment by rocallahan** [comment]
```
#define	EDQUOT		122	/* Quota exceeded */
```
Is your storage full?

**Comment by malhanvishal** [comment]
Ah! that is the case... thanks! we can close this.
