### ISSUE TITLE
Make a basic effort to track the files backing STDOUT/STDERR_FILENO during replay

### ISSUE THREAD

**Issue by cgjones** [mozilla/rr#262]
A quirk I noticed in another bug (but seemed not to have filed on its own) is that during recording, there's no spew from FF's glxtest process.  But during replay, it spews.  Certainly not the end of the world, but it's misleading.  The reason is that glxtest dups all its open fds to /dev/null.  We ignore that during replay

Not a priority.

**Comment by cgjones** [comment]
Fixed, thanks kcmp!

**Comment by rocallahan** [comment]
FWIW, we don't use kcmp anymore; we track file descriptor activity ourselves via `FdTable` and `FileMonitor`.
