### ISSUE TITLE
recording chrome loading cnn.com hits EBADF when establishing shared memory between parent <-> child

### ISSUE THREAD

**Issue by pasko** [mozilla/rr#2628]
Steps to reproduce (assuming google-chrome-stable is installed (debian)):
```
zsh> rm -rf /tmp/rr-userdata && RR_LOG=all rr record /opt/google/chrome/chrome \
    --user-data-dir=/tmp/rr-userdata \
    --no-sandbox \
    --allow-sandbox-debugging \
    about:blank >! /tmp/rr.log 2>&1
```
Attached: [rr.log.gz](https://github.com/mozilla/rr/files/4997938/rr.log.gz)

Fails with (5 out of 5 runs):
```
[FATAL /path/to/src/AutoRemoteSyscalls.cc:586:check_syscall_result()]                                                                                                               
 (task 2650716 (rec:2650716) at time 84129)                                                                                                                                                                          
 -> Assertion `false' failed to hold. Syscall mmap failed with errno EBADF
```

Seems like some wrong fd is received in Session::create_shared_mmap().

Side question: The trick with single stepping the child to do an mmap there looks interesting. Is it because scheduling slices of execution in the child is harder?

**Comment by rocallahan** [comment]
> Side question: The trick with single stepping the child to do an mmap there looks interesting. Is it because scheduling slices of execution in the child is harder?

Not sure what you mean by that. We need to map some rr-specific memory into the child and the only way to do that is to get it to execute an mmap system call. So, we set up the syscall register state and use ptrace to singlestep through the syscall. That's the simplest way to get it to execute a syscall on our behalf.

**Comment by rocallahan** [comment]
So the problem here is this:
```
[INFO log()] SYSCALL: futex
[INFO log()] (none)
[Task] Falling back to the remote fd dance
[AutoRemoteSyscalls] Sending fd 168 via socket fd 11
[AutoRemoteSyscalls] syscall recvmsg { args:(0x3e9,0x30,0,0,0,0) orig_syscall: 202 syscallno: -512 }
[AutoRemoteSyscalls] Task is dying, don't try anything.
[AutoRemoteSyscalls] syscall openat { args:(0xffffffffffffffff,0x1,0x2,0,0,0) orig_syscall: 202 syscallno: -512 }
[AutoRemoteSyscalls] Task is dying, don't try anything.
[AutoRemoteSyscalls] syscall sendmsg { args:(0x3e9,0x30,0,0,0,0) orig_syscall: 202 syscallno: -512 }
[AutoRemoteSyscalls] Task is dying, don't try anything.
[AutoRemoteSyscalls] syscall close { args:(0xfffffffffffffffd,0x80,0,0,0,0) orig_syscall: 202 syscallno: -512 }
[AutoRemoteSyscalls] Task is dying, don't try anything.
[AutoRemoteSyscalls] syscall close { args:(0xffffffffffffffff,0x80,0,0,0,0) orig_syscall: 202 syscallno: -512 }
[AutoRemoteSyscalls] Task is dying, don't try anything.
[INFO open_mem_fd()] Can't retrieve mem fd for 1065179; process no longer exists?
```
We tried to open the memfd for a dying process. With the changes I previously made, that works OK, but we have sent a message into the special socket we use to send fds to our tracees, and the tracee has not read it, so it's still in the socket buffer! So next time we need to send a message to a different tracee, that tracee reads the old message and fails.

**Comment by rocallahan** [comment]
Easy to repro this in the `unexpected_exit` testcase.

**Comment by rocallahan** [comment]
I guess the easiest way to fix this is to read the message back out of the socket if the tracee didn't.
