### ISSUE TITLE
/etc/sysctl.conf is no longer read by systemd, so rr should not advise user to edit it

### ISSUE THREAD

**Issue by balaziks** [mozilla/rr#2638]
`rr` fails with error message like this

```
rr needs /proc/sys/kernel/perf_event_paranoid <= 1, but it is 2.
Change it to 1, or use 'rr record -n' (slow).
Consider putting 'kernel.perf_event_paranoid = 1' in /etc/sysctl.conf
```

when `perf_event_paranoid` is set to incorrect value and advises the user to edit `/etc/sysctl.conf` which is however not read on machines running [systemd 207 or newer](https://lists.freedesktop.org/archives/systemd-devel/2013-September/013189.html).

Maybe we could detect presence and version of systemd, which might be unnecessarily complicated or we could just remove the potentially misleading line. Or perhaps we could point users to `man 5 sysctl.d` and `man 5 sysctl.conf` instead.

**Comment by rocallahan** [comment]
Ubuntu 18.04 and Fedora 31 both symlink `/etc/sysctl.d/99-sysctl.conf` to `/etc/sysctl.conf` and I suspect many other distros do too.

`man 5 sysctl.conf` just mentions `/etc/sysctl.conf` so I don't think that would be an improvement. I'm not actually sure what we could say here that would be an improvement. Just add `or see "man 5 sysctl.d"`? Send a PR if you think that's better.

**Comment by balaziks** [comment]
Well, I didn't know about the symlinks in those distributions (and didn't care enough to check for them before submitting the issue, sorry about that).

I think giving more information (pointing to manual pages) would be a good addition to merely telling what is wrong and how to fix it (provided one is using a _right_ distro).

**Comment by rocallahan** [comment]
Fixed by the PR.
