### ISSUE TITLE
Is it possible to restart replay at a different when-ticks id?

### ISSUE THREAD

**Issue by vicshen** [mozilla/rr#2645]
"run <event-id>" could restart at a different event.  But event-id is insufficiently granular.  Is there any way to start based on when-ticks id?

**Comment by rocallahan** [comment]
Currently, no. That could be added pretty easily though.

**Comment by Keno** [comment]
I added `seek-ticks` in https://github.com/mozilla/rr/pull/2658. See if that fits your needs.

**Comment by vicshen** [comment]
Yes it's great!  Thanks a lot.
