### ISSUE TITLE
fails to build with ld.lld 

### ISSUE THREAD

**Issue by milianw** [mozilla/rr#2650]
Using LLD 10.0.1 as `ld` produces multiple errors of the following kind:

```
inja fxregs_32
[13/13] Linking C executable bin/fxregs_32
FAILED: bin/fxregs_32 
: && /home/milian/.bin/gcc -D__USE_LARGEFILE64 -pthread -msse2 -D__MMX__ -D__SSE__ -D__SSE2__ -Wstrict-prototypes -std=gnu11  -pthread -O3 -DNDEBUG -m32 -Wall -Wextra -DDEBUG -UNDEBUG -g3 -O0 CMakeFiles/fxregs_32.dir/32/x86/fxregs.c.o -o bin/fxregs_32  -lrt  -ldl && :
ld.lld: error: can't create dynamic relocation R_386_32 against local symbol in readonly segment; recompile object files with -fPIC or pass '-Wl,-z,notext' to allow text relocations in the output
>>> defined in CMakeFiles/fxregs_32.dir/32/x86/fxregs.c.o
>>> referenced by fxregs.c:64 (32/x86/fxregs.c:64)
>>>               CMakeFiles/fxregs_32.dir/32/x86/fxregs.c.o:(main)
```

Potentially related to https://github.com/mozilla/rr/issues/1540 - but could also be an upstream in ld.lld. Using ld.gold works fine. Could someone with more knowledge of what `fxregs.c` is doing investigate this and potentially create a bug report upstream for ld.lld, if that's to blame?

Thanks

**Comment by rocallahan** [comment]
Works fine for me with lld 9.0.

**Comment by milianw** [comment]
Hm that's odd, then it's a regression with lld 10 apparently. I'll try to report a bug upstream and see what the lld folks have to say to that.

**Comment by milianw** [comment]
Reported it there now: https://bugs.llvm.org/show_bug.cgi?id=47586

**Comment by MaskRay** [comment]
Can you share the build instruction for 32-bit on x86-64? There is unlikely a ld.lld issue. It correctly reports a text relocation which it might fail to report before. 

When neither -z notext nor -z text is specified, GNU ld is in an indefinite state where it will enable text relocations (DT_TEXTREL DF_TEXTREL) on demand. It is not considered a good practice for userspace applications to do this. binutils 2.35 can be configured to error by default (--enable-textrel-check=error) like LLD.

**Comment by MaskRay** [comment]
OK: `cmake -GNinja -H. -BRelease -DCMAKE_ASM_FLAGS=-m32 -DCMAKE_C_FLAGS='-m32 -fPIC' -DCMAKE_CXX_FLAGS='-m32 -fPIC' -DCMAKE_EXE_LINKER_FLAGS='-m32 -pie'`

```
// src/test/x86/fxregs.c
/* Push the constants in stack order so they look as
 * we expect in gdb. */
#if __i386__
      "fldl st7\n\t"
      "fldl st6\n\t"
      "fldl st5\n\t"
      "fldl st4\n\t"
      "fldl st3\n\t"
      "fldl st2\n\t"
      "fldl st1\n\t"
      "fldl st0\n\t"
```

Direct accesses (R_386_32) like these require text relocations. LLD correctly reports that the link needs -Wl,-z,notext
