### ISSUE TITLE
`PTRACE_SETREGSET` fails

### ISSUE THREAD

**Issue by rocallahan** [mozilla/rr#2655]
https://github.com/mozilla/rr/issues/2034#issuecomment-691349725
> now I'm getting Assertion !errno' failed to hold. ptrace(PTRACE_SETREGSET, 110711, addr=0x202, data=0x7ffd971a9170) failed with errno 22`

https://github.com/mozilla/rr/issues/2034#issuecomment-691350469
> Happens every time for me (even, say just `rr record ls`).

It's not happening for me (5.7.15-100.fc31.x86_64). What kernel versions are you on @glandium @Keno  ?

**Comment by rocallahan** [comment]
Or is this AMD-specific perhaps?

**Comment by Keno** [comment]
```

**Comment by rocallahan** [comment]
I assumed this was commit 5c12d5f9ab77e526f852cbca82f454a42e3a6e30. But the failing ptrace `PTRACE_SETREGSET` call (`NT_X86_XSTATE`) wasn't changed in that commit...

**Comment by Keno** [comment]
Bisected to https://github.com/mozilla/rr/commit/50a3b7bdfbb3b818db75e1e8ec3081a0e694d87b

**Comment by Keno** [comment]
Presumably the issue is that CPUID indicates support for PKRU, but the kernel doesn't actually support it. We should be computing the native xsave layout by looking in the sw reserved xsave area where the kernels stores the maximal xstate it supports.

**Comment by rocallahan** [comment]
Huh, I had no idea AMD supports PKRU now!

**Comment by Keno** [comment]
Didn't know that either, but it does appear so.
