### ISSUE TITLE
rr replay crashes when replaying a content process of Firefox

### ISSUE THREAD

**Issue by sefeng211** [mozilla/rr#2661]
When using `rr replay -p <process id>` for a content process, rr has always been crashing for me.

This is the bt for the crash.
https://pastebin.com/crQHNLYS

This is probably related to my personal setup and the bt seems to indicate that this is related to gtk and dark them, but I have no idea how to fix it.

Thanks!

**Comment by khuey** [comment]
https://firefox-source-docs.mozilla.org/contributing/debugging/debugging_firefox_with_rr.html#sigsys

**Comment by khuey** [comment]
Also see the discussion in #1887

**Comment by sefeng211** [comment]
Ah, Thanks!!
