### ISSUE TITLE
Intermittent failure in setuid

### ISSUE THREAD

**Issue by rocallahan** [mozilla/rr#2694]
See https://github.com/mozilla/rr/issues/2034#issuecomment-695806881 @bnjbvr

`setuid` calls `getgrnam`/`getpwnam`. The user/group DB stuff uses shared memory on some systems so I suspect we need to work around that harder. Just an `rr replay` of the failing trace, then dropping into the emergency debugger and getting a stack trace, with debuginfo present for glibc, would probably give us a good clue,

**Comment by bnjbvr** [comment]
I could reproduce by running `rr replay /tmp/rr-test.../latest-trace`. Here's the content of the full directory for this test failure: https://benj.me/pub/test-failure.zip

**Comment by khuey** [comment]
Please `rr pack /tmp/rr-test.../latest-trace` and upload that.

**Comment by bnjbvr** [comment]
Just did that to the same URL; I didn't know what to upload (weirdly `rr pack` doesn't tell what its output file/directory is?), so I uploaded the whole dir again. Cheers!

**Comment by khuey** [comment]
`rr pack` operates in place so that's exactly what I wanted.

Using an internal tool that roc and I have I get the following output.

```
khuey@minbar:~/dev/scratch/trace/rr-test-setuid-xqNdC40gw/latest-trace$ ~/dev/pernosco/rr/obj/bin/rr rerun -x .
Unsupported instruction at 0x7f8d2cf3103f (opcode rdrand)
```

rdrand is obviously not deterministic. We have various hacks to convince tracees not to use rdrand but apparently they're not working on your machine.

This address is in glibc but I don't have symbols for your glibc. Can you `rr replay /tmp/rr-test.../latest-trace`, do `hbreak *0x7f8d2cf3103f`, continue, and then give us a stack trace once you hit the breakpoint?

**Comment by bnjbvr** [comment]
> Can you rr replay /tmp/rr-test.../latest-trace, do hbreak *0x7f8d2cf3103f, continue, and then give us a stack trace once you hit the breakpoint?

```
#0  0x00007f8d2cf3103f in ?? () from /lib/x86_64-linux-gnu/libnss_systemd.so.2
#1  0x00007f8d2cf31273 in ?? () from /lib/x86_64-linux-gnu/libnss_systemd.so.2
#2  0x00007f8d2cf31541 in ?? () from /lib/x86_64-linux-gnu/libnss_systemd.so.2
#3  0x00007f8d2cf1fb11 in ?? () from /lib/x86_64-linux-gnu/libnss_systemd.so.2
#4  0x00007f8d2cf25b1e in ?? () from /lib/x86_64-linux-gnu/libnss_systemd.so.2
#5  0x00007f8d2cf26251 in ?? () from /lib/x86_64-linux-gnu/libnss_systemd.so.2
#6  0x00007f8d2cf33981 in _nss_systemd_getgrnam_r () from /lib/x86_64-linux-gnu/libnss_systemd.so.2
#7  0x00007f8d2d0444ed in __getgrnam_r (name=name@entry=0x561f8e70a023 "nobody", resbuf=resbuf@entry=0x7f8d2d150020 <resbuf>, buffer=0x561f90419fc0 "", 
    buflen=buflen@entry=1024, result=result@entry=0x7ffe807b32a0) at ../nss/getXXbyYY_r.c:315
#8  0x00007f8d2d04379c in getgrnam (name=0x561f8e70a023 "nobody") at ../nss/getXXbyYY.c:134
#9  0x0000561f8e709538 in main (argc=1, argv=0x7ffe807b3438) at /home/ben/code/rr/src/test/setuid.c:15
```

(Let me know if there's a chat channel I could join for faster feedback :))

**Comment by khuey** [comment]
You can join #rr on Mozilla's Matrix instance.

**Comment by khuey** [comment]
I filed an upstream issue. There's not much we can do here for the time being.
