### ISSUE TITLE
RFC: Open up the packing process to external tools

### ISSUE THREAD

**Issue by loganwendholt** [mozilla/rr#2707]
I’m currently dealing with a use case where I have a binary which I run and record multiple times with different inputs. I then call rr pack on each recording, and store the packed recordings for eventual replay. Since the binary is the same on each run, the majority of the files in each packed recording are the same, and rr pack is making lots of copies of the same files.

To cut down on these unnecessary copies, I’m interested in adding functionality to allow users to manage the packing process externally using a separate tool or script.

To do this, the following modifications to `rr` will be necessary:

- A way to acquire the list of all files that `rr pack` would have copied into the recording directory
- A way to update the file paths in the mmaps file to point to new file locations

Using these features, the external tool could collect all of the files in all the recordings, perform its own determination of which files are unique, and store these files in whatever way is desired. The tool would also be responsible for making sure all necessary files are accessible during replay, and could modify the `mmaps` file to point to the proper files, wherever they are located.

This seems like it would also provide everything needed to address the use case in #2529 without requiring `rr` itself to be aware of any additional information -- everything would be managed externally.

For getting the list of files, I’m looking at adding a new option such as  `rr pack --list-only`, which outputs a list of all files which would have been copied into the trace. Looking at the code, this looks like it should be fairly trivial.

To update the mmaps file, the user would need to provide a mapping of `old_path: new_path`. This could be provided as a file in some simple human-readable format, accessed via a new command like `rr overwrite-mmaps <file_map>` or something similar.

Thoughts?

**Comment by rocallahan** [comment]
Why doesn't the approach in https://github.com/mozilla/rr/pull/2529#issuecomment-618110543 work for you?

The overhead of making those copies reduces to nearly zero if your traces are on the same filesystem as the recorded binaries, and that filesystem supports reflinks.

**Comment by loganwendholt** [comment]
The main reason I proposed an alternative to the approach in that comment is because I want to run on a filesystem without reflinks, and want to avoid extra copies.

**Comment by rocallahan** [comment]
Then the question is whether it is easier to change rr (and support that change indefinitely) than for you and possibly other users to use a filesystem with reflinks :-)

**Comment by rocallahan** [comment]
If using a filesystem with reflinks is simply impossible for some reason then I think the next simplest approach for rr would be to add an option to `rr pack` that uses symlinks instead of reflinks. Then you can scan the results of `rr pack` and do whatever it is you need to do. I don't see that rewriting the mmaps in a trace is necessary.

**Comment by loganwendholt** [comment]
Fair enough, the symlink approach would be fine too. I'll take a look at coding something up.

**Comment by loganwendholt** [comment]
See #2709 for a proposed implementation of this symlinking behavior. Closing this issue so that any additional discussion can take place within the PR instead.
