### ISSUE TITLE
Test vsyscall_reverse_next-32 failing

### ISSUE THREAD

**Issue by bernhardu** [mozilla/rr#2722]
I ran the tests yesterday and found all tests succeed, a few just on the second attempt.
But vsyscall_reverse_next-32 continued to fail.

I could observe this on
* physicial system with AMD Ryzen 7 1700, Debian testing from a few days with kernel 5.8.0-3-amd64/5.8.14-1.
* qemu VM at i5-4210U, Debian testing from a few days with kernel 5.9.0-1-amd64/5.9.1-1 (or 5.9.0-1-686-pae/5.9.1-1 with 32bit userland, there it is the test vsyscall_reverse_next)

I tried a short bisect and wrote 4287a0c3b1c096c60621fa3bd220853ce0ba5cb0 is the first bad commit.
With that commit removed from current head the test succeeds.

<details><summary>gdb_rr.log from today, I guess that is the most relevant part?</summary>
<p>

```
2296: --------------------------------------------------
2296: gdb_rr.log:
2296: GNU gdb (Debian 9.2-1) 9.2
2296: Copyright (C) 2020 Free Software Foundation, Inc.
2296: License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
2296: This is free software: you are free to change and redistribute it.
2296: There is NO WARRANTY, to the extent permitted by law.
2296: Type "show copying" and "show warranty" for details.
2296: This GDB was configured as "x86_64-linux-gnu".
2296: Type "show configuration" for configuration details.
2296: For bug reporting instructions, please see:
2296: <http://www.gnu.org/software/gdb/bugs/>.
2296: Find the GDB manual and other documentation resources online at:
2296:     <http://www.gnu.org/software/gdb/documentation/>.
2296: 
2296: For help, type "help".
2296: Type "apropos word" to search for commands related to "word"...
2296: Reading symbols from /tmp/rr-test-vsyscall_reverse_next_32-goC1ut0Wf/vsyscall_reverse_next_32-goC1ut0Wf-0/mmap_hardlink_3_vsyscall_reverse_next_32-goC1ut0Wf...
2296: Really redefine built-in command "restart"? (y or n) [answered Y; input not from terminal]
2296: Remote debugging using 127.0.0.1:22189
2296: Reading symbols from /lib/ld-linux.so.2...
2296: Reading symbols from /usr/lib/debug/.build-id/3d/12637936898bf0a0110c35990ebc0617eed9b7.debug...
2296: 0xf7f970b0 in _start () from /lib/ld-linux.so.2
2296: (rr) break vsyscall_reverse_next.c:6
2296: break vsyscall_reverse_next.c:6
2296: Breakpoint 1 at 0x5664a2a7: file /home/bernhard/data/entwicklung/2020/rr/2020-10-28/obj_x86_64/32/vsyscall_reverse_next.c, line 6.
2296: c
2296: (rr) c
2296: Continuing.
2296: 
2296: Breakpoint 1, main () at /home/bernhard/data/entwicklung/2020/rr/2020-10-28/obj_x86_64/32/vsyscall_reverse_next.c:6
2296: 6   time(NULL);
2296: (rr) disable 1
2296: n
2296: disable 1
2296: (rr) n
2296: 7   atomic_puts("EXIT-SUCCESS");
2296: reverse-next
2296: (rr) reverse-next
2296: 
2296: Program stopped.
2296: 0xf7f970b0 in _start () from /lib/ld-linux.so.2
2296: (rr) --------------------------------------------------
```

</p>
</details>

**Comment by rocallahan** [comment]
Alright, retry with master, in particular 1e272a18696ad13187c68360dbbfe8a132b8f0b1

**Comment by bernhardu** [comment]
Thanks for the fast fix, now all tests succeed on my amd64 systems.
On i386 two other tests started now to fail (vdso_gettimeofday_stack,vdso_time_stack),
but are they supposed to run on i386 when "protected" by 'skip_if_32_bit'?

**Comment by bernhardu** [comment]
If it is not supposed to run on i386 - would this be acceptable?
```diff
diff --git a/src/test/util.sh b/src/test/util.sh
index 76e397b2..b13356f3 100644
--- a/src/test/util.sh
+++ b/src/test/util.sh
@@ -105,6 +105,7 @@ if [[ $TESTNAME =~ ([A-Za-z0-9_]+)_32$ ]]; then
     bitness=_32
     TESTNAME_NO_BITNESS=${BASH_REMATCH[1]}
 else
+    [[ "$(uname -m)" == "x86_64" ]] || bitness=_32
     TESTNAME_NO_BITNESS=$TESTNAME
 fi
 LIB_ARG=$2
```

**Comment by rocallahan** [comment]
This is going to set bitness to _32 on Aarch64.

Can you just check for i386 and set bitness in that case?

**Comment by bernhardu** [comment]
Oh sorry, did not thought on that one. Please have a look at #2725 for the skip_if_32_bit part.
I guess this issue can be closed then?

**Comment by bernhardu** [comment]
With today's git all tests succeed (a few on the second attempt) on all in my first post mentioned systems.
I hope it's ok when I am going forward and close this issue.
