### ISSUE TITLE
How about overhead(memory and disk) when long time run?

### ISSUE THREAD

**Issue by wonter** [mozilla/rr#2729]
Hello, i have been using rr for debugging for some time and it really saves me a lot of time.

And i have a new idea to run my program with benchmark tools for a long time(maybe weeks or months) in a sandbox or offline environment to reproduce some obscure bugs, but my concern is whether rr will have so much overhead that the memory and disk are full.

So there are to questions:

1. Can i play like this?
2. If i can, how much overhead will rr have?

**EDITI:  My program is a storage service like redis, so it will have a lot of bandwidth and disk usage during benchmark.**

**Comment by rocallahan** [comment]
Running for weeks or months probably won't work but you'd have to measure it. It's very workload dependent.
