### ISSUE TITLE
Passing stdin with RR_LOG=all:debug set causes OOM

### ISSUE THREAD

**Issue by pwaller** [mozilla/rr#2732]
rr 5.3.0, Ubuntu 20.04.

#### Steps to reproduce
1. `rr record echo`
2. `RR_LOG=all:debug rr replay <<<''`

Witness resident memory climb until `Killed`, dmesg shows OOM killer kicked in. It doesn't do this with logging off.

Context: I thought I'd have a go at debugging #2682 with rr-under-rr. In order to do that, I want to drive the inner rr by passing some commands via stdin. However, I'm finding that I can't.

**Comment by pwaller** [comment]
Reproduced on master@ 321a73d4

**Comment by rocallahan** [comment]
https://github.com/mozilla/rr/commit/0f72cae286dac44cf0028d72a04f488083377430 fixes this
