### ISSUE TITLE
Investigate using faster syscall interfaces

### ISSUE THREAD

**Issue by joneschrisg** [mozilla/rr#33]
Currently wrap_syscalls.c enters the kernel through an `int $0x80` instruction.  That's a full synchronous interrupt and can be hurty in syscall-heavy applications.  Intel and AMD added faster instructions to do this, `syscall` and `sysenter` (though I forget whose is whose).  We'll most likely get a speedup by using those when available.

**Comment by rocallahan** [comment]
We use `syscall` on x86-64 so this is only an issue for 32-bit, and not something we care about.
