### ISSUE TITLE
Implement ptrace API

### ISSUE THREAD

**Issue by joneschrisg** [mozilla/rr#567]
@rocallahan and I had half-joked about this, thought I'd filed, oops.  With #566 fixed, the FF plugin tests die when intentionally forcing a crash to check that the FF crash reporter is working correctly.  The minidumper requires ptrace, which obviously rr doesn't support.

To support that, the rr tracer would need to emulate the ptrace calls.  Not particularly difficult AFAICT, but a pretty big chunk of work.  Filing this to track.

**Comment by luser** [comment]
@rocallahan fixed this a few months ago: https://mail.mozilla.org/pipermail/rr-dev/2015-January/000207.html

**Comment by rocallahan** [comment]
ptrace is only partially supported. I put more information in the wiki: https://github.com/mozilla/rr/wiki/Supporting-ptrace

**Comment by Keno** [comment]
I think we can consider this one done. ptrace emulation is pretty complete now.

**Comment by rocallahan** [comment]
OK.
