### ISSUE TITLE
Prevent tracees from unsetting PR_TSC_SIGSEGV

### ISSUE THREAD

**Issue by joneschrisg** [mozilla/rr#792]
Obviously not urgent, filed in the pedantry category.

**Comment by layderv** [comment]
Hi, would you mind providing a bit more context on this? Is it necessary to run a 32-bit OS for this to work?
I'm reading without issues the counter using `rdtsc`, with an x86_64 executable though.
Is this still relevant?

**Comment by khuey** [comment]
This referred to calling `prctl(PR_SET_TSC, PR_TSC_ENABLE)` in the tracee to circumvent our rdtsc interception. The tsc_enable state is fully emulated for tracees now so this is not relevant anymore.
