### ISSUE TITLE
Remove all manual memory management

### ISSUE THREAD

**Issue by joneschrisg** [mozilla/rr#820]
We have a lot of legacy malloc/frees lying around.  Now that we're in C++, we can do much better.

**Comment by rocallahan** [comment]
I only see one `malloc` in the tree currently, wrapped in `xmalloc`, which itself only has one caller in `GdbConnection.cc` ... and that should definitely be replaced by a C++ `string`.

**Comment by rocallahan** [comment]
So, yes!

**Comment by brooksmoses** [comment]
Looks like with mkmodrzew's pull request, the actual issue here is fixed, but the now-unused "xmalloc" definition in src/util.{h,cc} needs to be removed.

(There's a lot of use of "xmalloc" in tests, but those are getting the definition from src/test/util.h, I believe.)
