### ISSUE TITLE
Reimplement SYS_fork support

### ISSUE THREAD

**Issue by joneschrisg** [mozilla/rr#871]
We support the explicit `SYS_fork` syscall, but it's not tested and I doubt it works.  glibc implements libc fork() as approximately `clone(SIGCHLD)`.

Tracees that manually invoke `syscall(SYS_fork)` are on their own for 1.0, as far as I'm concerned.  (Unlike glibc vfork(), which is actually implemented as SYS_vfork, though it could be done with clone too.)

**Comment by Keno** [comment]
@rocallahan this one's done as well, I believe

**Comment by rocallahan** [comment]
Yep.
