### ISSUE TITLE
Support queued signals (multiple pending "real" signals)

### ISSUE THREAD

**Issue by cgjones** [mozilla/rr#968]
#215 and some other issues allow rr to deal with multiple signals *becoming* pending, but the incoming rr-internal signals are just discarded, and at most one real signal is stashed.

I imagine multiple real signals arriving is pretty rare in practice, but there are certainly many legitimate reasons why it could happen.  Definitely not doing this for 1.0.

If/when this becomes worth doing, some time will need to be spent learning how linux expects ptrace tracers to deliver multiple queued signals to tracees.

**Comment by rocallahan** [comment]
Trevor Saunders says he sees this in Firefox with accessibility turned on. I'm working on it.

**Comment by cgjones** [comment]
Phew, thanks for letting me know --- this was next on my rr to-do list :).  I spent a little bit of time in the past thinking about how I would implement this, but it's not all that fantastically complicated.  The two notes I can leave are

* there can be at most 2 each queued "regular" signals, but there can be an arbitrary number of queued real-time signals
* I don't know in what order linux delivers queued signals.  I was going to write a small test program to investigate.  But it may also not matter for a first version.

**Comment by rocallahan** [comment]
I'm assuming that those don't matter much.

**Comment by rocallahan** [comment]
My current work is at https://github.com/rocallahan/rr/tree/multi-signals. It's an significant set of patches. There's a lot of refactoring of `RecordSession::record_step` (as I mentioned on rr-dev), followed by some new tests that send multiple signals, and some small changes to make them pass.

Unfortunately these multiple_pending_signal tests don't actually test multiple stashed signals in rr, because in these tests the kernel doesn't deliver a second signal until rr has dispatched the first signal. I need to think about the best way to create a simple, reliable test that lets rr collect multiple signals. Advice appreciated!

**Comment by cgjones** [comment]
> I'm assuming that those don't matter much.

They won't in the 99% case, but we should keep track of where we're cutting semantic corners.

>  I need to think about the best way to create a simple, reliable test that lets rr collect multiple signals. 

A few random things
* `signalfd()` might behave like we want
* `sigqueue()` might behave differently from `kill()` in a way that helps us, but I doubt it
* IIRC the kernel installs a default signal mask upon entering a signal handler.  That mask might be unintentionally blocking the later signals you're trying to deliver.  I think `sigaction()` lets you define that mask explicitly.  But again IIRC, only the being-delivered signal is masked out.

Also, do your patches remove the hackery we added to "upgrade" the various rr-internal signals among each other?  They certainly can queue up at least one deep during the test suite, so you could get existing semi-reliable tests for free.

**Comment by rocallahan** [comment]
My tests avoid setting a mask during signal handlers.

> Also, do your patches remove the hackery we added to "upgrade" the various rr-internal signals among each other?

No. I could try removing that and replacing it with stashing, that's a good idea.

**Comment by cgjones** [comment]
> My tests avoid setting a mask during signal handlers.

Right, I was talking about the implicit mask set up by the kernel.  I see that multiple_pending_signals doesn't set one up, so only the delivered signal would be masked.  I don't know why you wouldn't see multiple pending signals there other than bad luck in timing.  And multiple_pending_signals_sequential additionally masks SIGUSR2 on purpose.

Another thing you could try is queuing two signals for the receiving thread while the receiving thread has those signals masked.  Then the queueing thread could notify the receiver thread, and the receiver thread unblock those signals.  That could make you luckier with timing.

**Comment by rocallahan** [comment]
I don't think it's a timing issue in this case. Observing the pending signal set via /proc/<pid>/status, and the syscall log, I can see that in multiple_pending_signals both signals are pending for the task before it comes out of the read syscall. It's just that the kernel delivers the signals one at a time, so it delivers a signal, we consume it, then it delivers the other signal (if not blocked).

So to get multiple stashed signals we need to receive signals during a task continue that can't consume signals, e.g. while stepping during desched handling or go_to_a_happy_place.

**Comment by cgjones** [comment]
OK, that's pretty convenient.  If you shoot signals at a receiver thread while it's in a loop making buffered syscalls like gettimeofday(), that should trip that code pretty reliably.  I think we have a test that does that that I ended up disabling.
